### ISSUE TITLE
dials.find_spots fails on old VMXi images

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#1016]
```
$ dials.import /dls/mx/data/mx17352/mx17352-126/VMXi-AB0440/well_31/images/image_2063.nxs
$ dials.find_spots imported.expt 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.1101-g6e2af7e3c
...
Traceback (most recent call last):
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191118/build/../modules/dials/command_line/find_spots.py", line 187, in <module>
    script.run()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191118/build/../modules/dials/command_line/find_spots.py", line 128, in run
    reflections = flex.reflection_table.from_observations(experiments, params)
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191118/modules/dials/array_family/flex.py", line 198, in from_observations
    return find_spots(experiments)
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191118/modules/dials/algorithms/spot_finding/finder.py", line 759, in __call__
    table, hot_mask = self._find_spots_in_imageset(imageset)
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191118/modules/dials/algorithms/spot_finding/finder.py", line 855, in _find_spots_in_imageset
    r, h = extract_spots(imageset[j0:j1])
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191118/modules/dials/algorithms/spot_finding/finder.py", line 469, in __call__
    return self._find_spots(imageset)
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191118/modules/dials/algorithms/spot_finding/finder.py", line 577, in _find_spots
    result = function(task)
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191118/modules/dials/algorithms/spot_finding/finder.py", line 106, in __call__
    mask = self.imageset.get_mask(index)
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dxtbx Internal Error: /dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191118/modules/dxtbx/model/panel.h(355): DXTBX_ASSERT(data.accessor()[0] == image_size_[1]) failure.
```

**Comment by graeme-winter** [comment]
assert(data are wrong) => #wontfix?

if the image sizes are recorded incorrectly in the files (which I think happened from Eiger 1 => 2) then I don't think this is something for us to fix?

**Comment by rjgildea** [comment]
But it _used_ to work, and I want to reprocess these images...

**Comment by Anthchirp** [comment]
confirmed this works on 1.14
