### ISSUE TITLE
dials.merge fails for narrow wedges in P1

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#1018]
`$ xia2 image=/dls/mx/data/mx17352/mx17352-126/VMXi-AB0440/well_45/images/image_8273.nxs remove_blanks=True`
fails eventually with:
```
--------------------- Scaling DEFAULT ----------------------
Completed a round of scaling using dials.scale
Resolution for sweep NATIVE/SWEEP1: 3.11 (cc_half > 0.3)
--------------------- Scaling DEFAULT ----------------------
Completed a round of scaling using dials.scale
---------------- Systematic absences check -----------------
Most likely space group: P 1
dials.merge failed, see log file for more details:
/dls/science/users/hko55533/mx17352-126/VMXi-AB0440/well_45_image_8273/DEFAULT/scale/32_dials.merge.log
```

```
Traceback (most recent call last):
  File "/dls/science/users/hko55533/software/cctbx/build/../modules/dials/command_line/merge.py", line 177, in <module>
    run()
  File "/dls/science/users/hko55533/software/cctbx/build/../modules/dials/command_line/merge.py", line 164, in run
    mtz_file = merge_data_to_mtz(params, experiments, reflections)
  File "/dls/science/users/hko55533/software/cctbx/build/../modules/dials/command_line/merge.py", line 108, in merge_data_to_mtz
    merged_data = merge_and_truncate(params, experiments, reflections)
  File "/dls/science/users/hko55533/software/cctbx/modules/dials/algorithms/merging/merge.py", line 229, in merge_and_truncate
    scaled_array, params.merging.n_bins, params.merging.use_internal_variance
  File "/dls/science/users/hko55533/software/cctbx/modules/dials/algorithms/scaling/scaling_library.py", line 408, in merging_stats_from_scaled_array
    cc_one_half_significance_level=0.01,
  File "/dls/science/users/hko55533/software/cctbx/modules/cctbx_project/iotbx/merging_statistics.py", line 492, in __init__
    i_obs.info().label_string())
Sorry: The data in None are already merged.  Only unmerged (but scaled) data may be used in this program.
```

**Comment by jbeilstenedmands** [comment]
My commit should address this issue, although I was getting a slightly different error raise when trying to test on a different dataset, so if you could confirm that your case is fixed then this can be closed.

**Comment by rjgildea** [comment]
[1018.tar.gz](https://github.com/dials/dials/files/3859827/1018.tar.gz)
I still see the error with the attached files:
```
$ dials.merge 13_symmetrized.refl 13_symmetrized.expt
...
Traceback (most recent call last):
  File "/dls/science/users/hko55533/software/cctbx/build/../modules/dials/command_line/merge.py", line 176, in <module>
    run()
  File "/dls/science/users/hko55533/software/cctbx/build/../modules/dials/command_line/merge.py", line 163, in run
    mtz_file = merge_data_to_mtz(params, experiments, reflections)
  File "/dls/science/users/hko55533/software/cctbx/build/../modules/dials/command_line/merge.py", line 107, in merge_data_to_mtz
    merged_data = merge_and_truncate(params, experiments, reflections)
  File "/dls/science/users/hko55533/software/cctbx/modules/dials/algorithms/merging/merge.py", line 233, in merge_and_truncate
    params.merging.use_internal_variance,
  File "/dls/science/users/hko55533/software/cctbx/modules/dials/algorithms/scaling/scaling_library.py", line 408, in merging_stats_from_scaled_array
    cc_one_half_significance_level=0.01,
  File "/dls/science/users/hko55533/software/cctbx/modules/cctbx_project/iotbx/merging_statistics.py", line 492, in __init__
    i_obs.info().label_string())
Sorry: The data in None are already merged.  Only unmerged (but scaled) data may be used in this program.
```
