### ISSUE TITLE
dials.find_spots nproc=auto fails

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1019]
```
Grey-Area run :) $ dials.find_spots imported.expt nproc=auto
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.1110-g158a52241
The following parameters have been modified:

spotfinder {
  mp {
    nproc = Auto
  }
}
input {
  experiments = imported.expt
}

Setting spotfinder.filter.min_spot_size=3
Configuring spot finder from input parameters
--------------------------------------------------------------------------------
Finding strong spots in imageset 0
--------------------------------------------------------------------------------


Finding spots in image 1 to 1700...
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/find_spots.py", line 187, in <module>
    script.run()
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/find_spots.py", line 128, in run
    reflections = flex.reflection_table.from_observations(experiments, params)
  File "/Users/graeme/svn/cctbx/modules/dials/array_family/flex.py", line 198, in from_observations
    return find_spots(experiments)
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 759, in __call__
    table, hot_mask = self._find_spots_in_imageset(imageset)
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 855, in _find_spots_in_imageset
    r, h = extract_spots(imageset[j0:j1])
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 469, in __call__
    return self._find_spots(imageset)
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 505, in _find_spots
    if mp_nproc * mp_njobs > len(imageset):
TypeError: Please report this error to dials-support@lists.sourceforge.net: unsupported operand type(s) for *: 'AutoType' and 'int'
```

**Comment by graeme-winter** [comment]
Works fine with `nproc=8` on command-line

**Comment by graeme-winter** [comment]
Either should trap `nproc=auto` or make it work - swearing at users is not nice 😉

**Comment by dagewa** [comment]
`dials.find_spots=auto` seems more generally broken now - even with one imageset it fails:
```
$ dials.find_spots imported.expt nproc=auto
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 3.dev.193-g38aefdfe5
The following parameters have been modified:

spotfinder {
  mp {
    nproc = Auto
  }
}
input {
  experiments = imported.expt
}

Setting spotfinder.filter.min_spot_size=3
Configuring spot finder from input parameters
--------------------------------------------------------------------------------
Finding strong spots in imageset 0
--------------------------------------------------------------------------------


Finding spots in image 1 to 720...
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/find_spots.py", line 230, in <module>
    script.run()
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/find_spots.py", line 152, in run
    reflections = flex.reflection_table.from_observations(experiments, params)
  File "/home/fcx32934/sw/cctbx/modules/dials/array_family/flex_ext.py", line 174, in from_observations
    return find_spots(experiments)
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 761, in __call__
    table, hot_mask = self._find_spots_in_imageset(imageset)
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 873, in _find_spots_in_imageset
    r, h = extract_spots(imageset[j0:j1])
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 465, in __call__
    return self._find_spots(imageset)
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 501, in _find_spots
    if mp_nproc * mp_njobs > len(imageset):
TypeError: Please report this error to dials-support@lists.sourceforge.net: unsupported operand type(s) for *: 'AutoType' and 'int'

```
