### ISSUE TITLE
flatten_reflections fails on multiple scaled.expt

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#1032]
```
$ dials.show /dls/i04/data/2019/cm23004-5/processed/20191121/SmarGon/rotation_calibration*/lys8_*/xia2-dials/DataFiles/*scaled.expt
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = /dls/i04/data/2019/cm23004-5/processed/20191121/SmarGon/rotation_calibration1/lys8_O0_C0_P0_1_/xia2-dials/DataFiles/AUTOMATIC_DEFAULT_scaled.expt
  experiments = /dls/i04/data/2019/cm23004-5/processed/20191121/SmarGon/rotation_calibration2/lys8_O0_C0_P45_2_/xia2-dials/DataFiles/AUTOMATIC_DEFAULT_scaled.expt
  experiments = /dls/i04/data/2019/cm23004-5/processed/20191121/SmarGon/rotation_calibration3/lys8_O0_C45_P45_1_/xia2-dials/DataFiles/AUTOMATIC_DEFAULT_scaled.expt
  experiments = /dls/i04/data/2019/cm23004-5/processed/20191121/SmarGon/rotation_calibration4/lys8_O45_C45_P45_1_/xia2-dials/DataFiles/AUTOMATIC_DEFAULT_scaled.expt
}

Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v2-0-2/build/../modules/dials/command_line/show.py", line 630, in <module>
    run(sys.argv[1:])
  File "/dls_sw/apps/dials/dials-v2-0-2/build/../modules/dials/command_line/show.py", line 192, in run
    experiments = flatten_experiments(params.input.experiments)
  File "/dls_sw/apps/dials/dials-v2-0-2/modules/dials/util/options.py", line 1151, in flatten_experiments
    result.extend(o.data)
RuntimeError: dxtbx Internal Error: /dls_sw/apps/dials/dials-v2-0-2/modules/dxtbx/model/experiment_list.h(190): DXTBX_ASSERT(index < 0) failure.
```

In contrast, providing the integrated `.expt` as input succeeds:
```
$ dials.show /dls/i04/data/2019/cm23004-5/processed/20191121/SmarGon/rotation_calibration*/lys8_*/xia2-dials/DataFiles/*SWEEP1.expt
```

**Comment by rjgildea** [comment]
This is because all experiments are set with the identifier `0`, and the `Experiment.append()` method asserts that identifiers are unique:
https://github.com/dials/dxtbx/blob/a6456abcd817a344d0cdde3321536b513b89276d/model/experiment_list.h#L187-L194

```
for o in filename_object_list:
    print(o.data[0].identifier)

0
0
0
0
```

However, providing multiple separately individually-scaled `.expt` files to various dials programs seems a perfectly legitimate thing to do (e.g. providing the individual `scaled.expt` to `xia2.multiplex`), so this bug should probably be fixed.
