### ISSUE TITLE
dials.image_viewer broken for i23 detector with multi_panel=True

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#1044]
```
$ dials.image_viewer thaumatin_1_000*.cbf multi_panel=True show_mask=True
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

show_mask = True
format {
  multi_panel = True
}
input {
  experiments = <image files>
}

Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/image_viewer.py", line 195, in <module>
    runner()
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/image_viewer.py", line 133, in __call__
    self.view()
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/image_viewer.py", line 139, in view
    self.wrapper.display(experiments=self.experiments, reflections=self.reflections)
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_wrap.py", line 75, in display
    self.frame.load_image(chooser_wrapper(imagesets[0], 0))
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py", line 556, in load_image
    show_untrusted=show_untrusted,
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/slip_viewer/frame.py", line 431, in load_image
    get_raw_data=get_raw_data,
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/slip_viewer/tile_generation.py", line 286, in set_image
    self.raw_image.set_raw_data(get_raw_data(self.raw_image))
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py", line 926, in get_raw_data
    self.mask_raw_data(raw_data)
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py", line 1174, in mask_raw_data
    mask = self.get_mask(self.pyslip.tiles.raw_image)
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py", line 1163, in get_mask
    mask = image.get_mask()
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/slip_viewer/frame.py", line 45, in get_mask
    return self.image_set.get_mask(self.index)
RuntimeError: dxtbx Internal Error: /Users/rjgildea/software/cctbx/modules/dxtbx/imageset.h(877): DXTBX_ASSERT(mask.n_tiles() == data.n_tiles()) failure.
```

**Comment by graeme-winter** [comment]
I am approximately 0% surprised by this.

**Comment by graeme-winter** [comment]
I think the P12M has some special 🦍 code in image viewer anyway right?

**Comment by rjgildea** [comment]
I don't think this is an issue with the image viewer - I think there is something more fundamentally wrong with the format class. E.g. dials.find_spots also fails (this works with dials 1.14):
```
$ dials.import thaumatin_1_000*.cbf multi_panel=True
$ dials.find_spots imported.expt 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.0.33-gf3689ac4e
The following parameters have been modified:

input {
  experiments = imported.expt
}

Setting spotfinder.filter.min_spot_size=3
Configuring spot finder from input parameters
--------------------------------------------------------------------------------
Finding strong spots in imageset 0
--------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/find_spots.py", line 195, in <module>
    script.run()
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/find_spots.py", line 129, in run
    reflections = flex.reflection_table.from_observations(experiments, params)
  File "/Users/rjgildea/software/cctbx/modules/dials/array_family/flex.py", line 198, in from_observations
    return find_spots(experiments)
  File "/Users/rjgildea/software/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 759, in __call__
    table, hot_mask = self._find_spots_in_imageset(imageset)
  File "/Users/rjgildea/software/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 801, in _find_spots_in_imageset
    mask = self.mask_generator.generate(imageset)
  File "/Users/rjgildea/software/cctbx/modules/dials/util/masking.py", line 149, in generate
    assert len(detector) == len(image)
AssertionError: Please report this error to dials-support@lists.sourceforge.net:
```

**Comment by graeme-winter** [comment]
Yeh I'll buy that...

**Comment by dagewa** [comment]
I think this issue has been fixed? At least
```
dials.image_viewer $(libtbx.find_in_repositories dials_regression)/image_examples/DLS_I23/I23_P12M_alpha_0001.cbf multi_panel=True show_mask=True
```
does not fail.
