### ISSUE TITLE
dev.dials.find_bad_pixels does not work for multi panel detectors

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1045]
We need it to for I23's P12M but would also probably benefit from moving it out from dev.dials.

**Comment by dagewa** [comment]
I just tried 
```
dials.import $(dials.data get -q image_examples)/DLS_I23_P12M_thau_00001.cbf.gz
dials.find_bad_pixels imported.expt
```
There are **twelve and a half million** lines of cryptic output like this:
```
The following parameters have been modified:

input {
  experiments = imported.expt
}

mask: 0 0 16
mask: 0 1 16
mask: 0 2 16
mask: 0 3 16
mask: 0 4 16
mask: 0 5 16
...
lots more lines
...
mask: 5070 2458 16
mask: 5070 2459 16
mask: 5070 2460 16
mask: 5070 2461 16
mask: 5070 2462 16
```
then it fails with
```
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/find_bad_pixels.py", line 213, in <module>
    run()
  File "/home/fcx32934/sw/cctbx/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/find_bad_pixels.py", line 204, in run
    mask[h // nfast, h % nfast] = False
IndexError: Please report this error to dials-support@lists.sourceforge.net: Index out of range.
```
So, I agree with the issue subject - it does not work.
