### ISSUE TITLE
dials.merge writes out broken merged.mtz file

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#1047]
The `merged.mtz` file output by the following `dials.merge` command can not be read back by `iotbx.mtz.dump`:
```
$ dials.merge /dls/i23/data/2019/nr23571-22/processed/gw/thaumatin/20191127/th_2/thaumatin_37_/6f19514a-dd9a-4930-9e76-3d5e72a71672/xia2.multiplex/multiplex.{expt,refl}
```

```
$ iotbx.mtz.dump merged.mtz 
Processing: merged.mtz
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v2-0-2/build/../modules/cctbx_project/iotbx/command_line/mtz.dump.py", line 85, in <module>
    run(args=sys.argv[1:])
  File "/dls_sw/apps/dials/dials-v2-0-2/build/../modules/cctbx_project/iotbx/command_line/mtz.dump.py", line 77, in run
    show_batches=command_line.options.show_batches)
  File "/dls_sw/apps/dials/dials-v2-0-2/build/../modules/cctbx_project/iotbx/command_line/mtz.dump.py", line 17, in process
    mtz_object = mtz.object(file_name=file_name)
RuntimeError: cctbx Error: MTZ file read error: merged.mtz
```

**Comment by rjgildea** [comment]
I suspect this is somehow related to the presence of multiple wavelengths:
```
$ dials.show /dls/i23/data/2019/nr23571-22/processed/gw/thaumatin/20191127/th_2/thaumatin_36_/xia2.multiplex/multiplex.expt | grep -i wavelength
    wavelength: 1.8368
    wavelength: 1.7712
    wavelength: 1.8233
    wavelength: 1.87855
    wavelength: 1.93725
    wavelength: 1.7712
    wavelength: 1.8368
    wavelength: 1.90745
    wavelength: 1.98375
    wavelength: 2.0664
    wavelength: 2.15625
    wavelength: 2.25426
    wavelength: 2.3616
    wavelength: 2.47968
    wavelength: 2.61019
    wavelength: 2.7552
    wavelength: 3.30625
    wavelength: 4.13281
    wavelength: 3.30625
    wavelength: 3.0996
    wavelength: 2.7552
    wavelength: 2.47968
    wavelength: 2.3616
    wavelength: 2.25426
    wavelength: 2.15625
    wavelength: 2.0664
    wavelength: 1.98375
    wavelength: 1.90745
```

**Comment by graeme-winter** [comment]
Ah, you need to make sure that these are wrangled gracefully, MTZ files get quite sniffy about this. You can’t have > 1 wavelength for merged data. 

Could be reasonable to squash them all to the median for merging.

**Comment by rjgildea** [comment]
Interestingly, this works:
```
$ dials.show /dls/i23/data/2019/nr23571-22/processed/gw/thaumatin/20191127/th_2/thaumatin_10_/xia2.multiplex/multiplex.expt | grep wavelength
    wavelength: 2.0664
    wavelength: 1.7712
    wavelength: 1.8233
    wavelength: 1.87855
    wavelength: 1.93725
    wavelength: 1.7712
    wavelength: 1.8368
    wavelength: 1.90745
    wavelength: 1.98375
$ dials.merge /dls/i23/data/2019/nr23571-22/processed/gw/thaumatin/20191127/th_2/thaumatin_10_/xia2.multiplex/multiplex.{expt,refl} ; iotbx.mtz.dump merged.mtz
```
but with one more wavelength it fails:
```
$ dials.show /dls/i23/data/2019/nr23571-22/processed/gw/thaumatin/20191127/th_2/thaumatin_11_/xia2.multiplex/multiplex.expt | grep wavelength
    wavelength: 2.15625
    wavelength: 1.7712
    wavelength: 1.8233
    wavelength: 1.87855
    wavelength: 1.93725
    wavelength: 1.7712
    wavelength: 1.8368
    wavelength: 1.90745
    wavelength: 1.98375
    wavelength: 2.0664
$ dials.merge /dls/i23/data/2019/nr23571-22/processed/gw/thaumatin/20191127/th_2/thaumatin_11_/xia2.multiplex/multiplex.{expt,refl} ; iotbx.mtz.dump merged.mtz
...
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v2-0-2/build/../modules/cctbx_project/iotbx/command_line/mtz.dump.py", line 85, in <module>
    run(args=sys.argv[1:])
  File "/dls_sw/apps/dials/dials-v2-0-2/build/../modules/cctbx_project/iotbx/command_line/mtz.dump.py", line 77, in run
    show_batches=command_line.options.show_batches)
  File "/dls_sw/apps/dials/dials-v2-0-2/build/../modules/cctbx_project/iotbx/command_line/mtz.dump.py", line 17, in process
    mtz_object = mtz.object(file_name=file_name)
RuntimeError: cctbx Error: MTZ file read error: merged.mtz
```
```

**Comment by jbeilstenedmands** [comment]
I've been looking into this again, and I think we're starting to come up against limits in the mtz reading library (number of data columns perhaps?). For the 11 datasets above, turning anomalous=False for dials.merge results in many fewer columns and no crash out of mtz.dump (4 columns per dataset rather than 14):
`dials.merge /dls/i23/data/2019/nr23571-22/processed/gw/thaumatin/20191127/th_2/thaumatin_11_/xia2.multiplex/multiplex.{expt,refl} anomalous=False ; iotbx.mtz.dump merged.mtz`

This is even fine for the full thaumatin_36 dataset:
`dials.merge /dls/i23/data/2019/nr23571-22/processed/gw/thaumatin/20191127/th_2/thaumatin_36_/xia2.multiplex/multiplex.{expt,refl} anomalous=False ; iotbx.mtz.dump merged.mtz`

Closing this issue as it seems that there is no fundamental issue with the written mtz file.
