### ISSUE TITLE
Error in cyclic index -> refine -> index

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#1048]
Found an error trying to feed back refinement results into indexing. I thought this was a supported use case. It certainly sometimes works, I think some edge case of spot counts being lowish?
```
dials.import /dls/mx/data/cm20609/cm20609-5/20191127/tryp3/grid4/x3/*.cbf && \
    dials.find_spots imported.expt nproc=10 && \
    dials.index imported.expt strong.refl
```
Works:
```
dials.index indexed.expt indexed.refl
```
doesn't work
```
dials.refine indexed.expt indexed.refl
dials.index refined.expt refined.refl
```
Get:
```
Traceback (most recent call last):
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191123/build/../modules/dials/command_line/index.py", line 272, in <module>
    run()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191123/build/../modules/dials/command_line/index.py", line 256, in run
    experiments, reflections, params
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191123/build/../modules/dials/command_line/index.py", line 181, in index
    known_crystal_models=known_crystal_models,
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191123/build/../modules/dials/command_line/index.py", line 116, in _index_experiments
    idxr.index()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191123/modules/dials/algorithms/indexing/indexer.py", line 637, in index
    experiments, reflections_for_refinement
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191123/modules/dials/algorithms/indexing/indexer.py", line 891, in refine
    refiner, refined, outliers = refine(self.all_params, reflections, experiments)
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191123/modules/dials/algorithms/indexing/refinement.py", line 21, in refine
    params, reflections, experiments
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191123/modules/dials/algorithms/refinement/refiner.py", line 201, in from_parameters_data_experiments
    return cls._build_components(params, reflections, experiments)
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191123/modules/dials/algorithms/refinement/refiner.py", line 322, in _build_components
    autoreduce()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191123/modules/dials/algorithms/refinement/parameterisation/autoreduce.py", line 254, in __call__
    self.check_and_fail()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191123/modules/dials/algorithms/refinement/parameterisation/autoreduce.py", line 143, in check_and_fail
    self._nref_per_param() < self._options.min_nref_per_parameter
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191123/modules/dials/algorithms/refinement/parameterisation/autoreduce.py", line 118, in _nref_per_param
    self.pred_param.get_gradients(obs, callback=count_associated_refs)
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191123/modules/dials/algorithms/refinement/parameterisation/prediction_parameters.py", line 364, in get_gradients
    self._local_setup(reflections)
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20191123/modules/dials/algorithms/refinement/parameterisation/prediction_parameters.py", line 725, in _local_setup
    assert flex.min(e_r_s0_mag) > 1.0e-6
RuntimeError: min() argument is an empty array
```
Edit: Seen on `dials/latest` e.g. latest/dials-dev20191123 but also happened on nightly

**Comment by rjgildea** [comment]
Is this running indexing on > 1 dataset, i.e. output is >1 crystal? I don't think this use case has ever been tested/supported in the re-cycling indexing results. It is probably just using the first crystal to attempt to index all experiments.

**Comment by graeme-winter** [comment]
Is only one sweep 

```
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.0.2-g25fc2fc43-release
The following parameters have been modified:

input {
  experiments = <image files>
}

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatCBFFullPilatusDLS6MSN126.FormatCBFFullPilatusDLS6MSN126'>
  num images: 200
  sequences:
    still:    0
    sweep:    1
  num stills: 0
--------------------------------------------------------------------------------
Writing experiments to imported.expt
```

**Comment by rjgildea** [comment]
I saw the word "grid" and assumed stills...

**Comment by ndevenish** [comment]
Sorry, I clarified (oscillation, single sweep) on the slack post but forgot to transfer it here

**Comment by rjgildea** [comment]
The following works fine for me with dials/latest:
```
$ dials.index imported.expt strong.refl ; dials.refine indexed.*; dials.index refined.*
```

**Comment by rjgildea** [comment]
I have tried both of the following and can not reproduce your error:
```
$ cat run.sh 
module load dials/latest
dials.import /dls/mx/data/cm20609/cm20609-5/20191127/tryp3/grid4/x3/*.cbf
dials.find_spots imported.expt nproc=10
dials.index imported.expt strong.refl
dials.refine indexed.{expt,refl}
dials.index refined.{expt,refl}
```
```
$ cat run2.sh 
module load dials/latest
dials.import /dls/mx/data/cm20609/cm20609-5/20191127/tryp3/grid4/x3/*.cbf
dials.find_spots imported.expt nproc=10
dials.index imported.expt strong.refl
dials.index indexed.{expt,refl}
dials.refine indexed.{expt,refl}
dials.index refined.{expt,refl}
```

**Comment by ndevenish** [comment]
Sorry, I ran `d_min=2.3` on spotfinding. Without it, it obviously had enough.
