### ISSUE TITLE
image_viewer crashes with sum_image

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#105]
Reported by user:
```
$ dials.image_viewer 1_SWEEP1_datablock.json sum_image=20
The following parameters have been modified:

image_viewer {
  sum_images = 20
}
input {
  datablock = 1_SWEEP1_datablock.json
}

File: /dls/i19-1/data/2016/cm14476-1/20160310_collectionTest/22_chargedensity_0-1s_0-1d/22_fructose_01_00001.cbf
Number of pixels: slow=1679 fast=1475
Pixel size: 0.172000 mm
Saturation: 388705
Detector distance: 160.00 mm
Detector 2theta swing: 0.00 deg.
Rotation start: 0.00 deg.
Rotation width: 0.10 deg.
Beam center: x=148.78 mm  y=125.56 mm
Wavelength: 0.688900 Ang.
Traceback (most recent call last):
  File "/dls_sw/apps/dials/latest/dials-dev20160314/build/../modules/dials/command_line/image_viewer.py", line 168, in <module>
    runner()
  File "/dls_sw/apps/dials/latest/dials-dev20160314/build/../modules/dials/command_line/image_viewer.py", line 105, in __call__
    self.view()
  File "/dls_sw/apps/dials/latest/dials-dev20160314/build/../modules/dials/command_line/image_viewer.py", line 112, in view
    crystals=self.crystals)
  File "/dls_sw/apps/dials/latest/dials-dev20160314/modules/dials/util/spotfinder_wrap.py", line 32, in display
    self.frame.load_image(chooser_wrapper(imagesets[0],idx))
  File "/dls_sw/apps/dials/latest/dials-dev20160314/modules/dials/util/spotfinder_frame.py", line 328, in load_image
    super(SpotFrame, self).load_image(file_name_or_data)
  File "/dls_sw/apps/dials/latest/dials-dev20160314/modules/cctbx_project/rstbx/slip_viewer/frame.py", line 368, in load_image
    self.update_settings()
  File "/dls_sw/apps/dials/latest/dials-dev20160314/modules/dials/util/spotfinder_frame.py", line 726, in update_settings
    self.sum_images()
  File "/dls_sw/apps/dials/latest/dials-dev20160314/modules/dials/util/spotfinder_frame.py", line 489, in sum_images
    rd += raw_data_i[j]
Boost.Python.ArgumentError: Python argument types in
    double.__iadd__(double, tuple)
did not match C++ signature:
    __iadd__(scitbx::af::versa<double, scitbx::af::flex_grid<scitbx::af::small<long, 10ul> > > {lvalue}, double)
    __iadd__(scitbx::af::versa<double, scitbx::af::flex_grid<scitbx::af::small<long, 10ul> > > {lvalue}, scitbx::af::versa<double, scitbx::af::flex_grid<scitbx::af::small<long, 10ul> > >)
```

**Comment by Anthchirp** [comment]
Thanks.
