### ISSUE TITLE
dials.image_viewer can't display images at 2theta=105°

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#106]
```
$ dials.image_viewer /dls/i19-1/data/2016/cm14476-1/20160310_collectionTest/22_chargedensity_0-1s_0-1d/22_fructose_12_00030.cbf
The following parameters have been modified:

input {
  datablock = <image files>
}

File: /dls/i19-1/data/2016/cm14476-1/20160310_collectionTest/22_chargedensity_0-1s_0-1d/22_fructose_12_00030.cbf
Number of pixels: slow=1679 fast=1475
Pixel size: 0.172000 mm
Saturation: 1540843
Detector distance: 160.00 mm
Detector 2theta swing: 0.00 deg.
Rotation start: -67.10 deg.
Rotation width: 0.10 deg.
Beam center: x=148.78 mm  y=722.69 mm
Wavelength: 0.688900 Ang.
Traceback (most recent call last):
  File "/dls_sw/apps/dials/nightly/dials-dev20160314/build/../modules/dials/command_line/image_viewer.py", line 168, in <module>
    runner()
  File "/dls_sw/apps/dials/nightly/dials-dev20160314/build/../modules/dials/command_line/image_viewer.py", line 105, in __call__
    self.view()
  File "/dls_sw/apps/dials/nightly/dials-dev20160314/build/../modules/dials/command_line/image_viewer.py", line 112, in view
    crystals=self.crystals)
  File "/dls_sw/apps/dials/nightly/dials-dev20160314/modules/dials/util/spotfinder_wrap.py", line 32, in display
    self.frame.load_image(chooser_wrapper(imagesets[0],idx))
  File "/dls_sw/apps/dials/nightly/dials-dev20160314/modules/dials/util/spotfinder_frame.py", line 328, in load_image
    super(SpotFrame, self).load_image(file_name_or_data)
  File "/dls_sw/apps/dials/nightly/dials-dev20160314/modules/cctbx_project/rstbx/slip_viewer/frame.py", line 329, in load_image
    x_mm,y_mm = detector[0].get_beam_centre(beam.get_s0())
RuntimeError: dxtbx Internal Error: /scratch/jenkins_slave/workspace/dials_package_linux/build_dials/modules/cctbx_project/dxtbx/model/virtual_panel.h(242): DXTBX_ASSERT(v[2] > 0) failure.
```

**Comment by Anthchirp** [comment]
dials.import on image works

**Comment by Anthchirp** [comment]
Fixed by cctbx https://sourceforge.net/p/cctbx/code/24041/
