### ISSUE TITLE
Problems when template starts from 0000

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1073]
This demonstrates the issue:

```
cd /tmp
cp $(dials.data get -q centroid_test_data)/centroid_0001.cbf centroid_0000.cbf
dials.import centroid_0000.cbf
```
completes successfully, but

```
$ dials.show imported.expt 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
Sorry: Unable to handle the following arguments:
  "imported.expt" failed during ExperimentList processing:
    Traceback (most recent call last):
      File "/home/fcx32934/sw/cctbx/modules/dials/util/options.py", line 328, in try_read_experiments
        self.experiments.append(converter.from_string(argument))
      File "/home/fcx32934/sw/cctbx/modules/dials/util/phil.py", line 40, in from_string
        s, check_format=self._check_format
      File "/home/fcx32934/sw/cctbx/modules/dxtbx/model/experiment_list.py", line 707, in from_json_file
        infile.read(), check_format=check_format, directory=directory
      File "/home/fcx32934/sw/cctbx/modules/dxtbx/model/experiment_list.py", line 697, in from_json
        directory=directory,
      File "/home/fcx32934/sw/cctbx/modules/dxtbx/model/experiment_list.py", line 682, in from_dict
        obj, check_format=check_format, directory=directory
      File "/home/fcx32934/sw/cctbx/modules/dxtbx/model/experiment_list.py", line 100, in __init__
        ("scaling_model", self._scaling_model_from_dict),
      File "/home/fcx32934/sw/cctbx/modules/dxtbx/model/experiment_list.py", line 92, in <dictcomp>
        for model, function in (
      File "/home/fcx32934/sw/cctbx/modules/dxtbx/model/experiment_list.py", line 129, in _extract_models
        mlist = [from_dict(d) for d in mlist]
      File "/home/fcx32934/sw/cctbx/modules/dxtbx/model/scan.py", line 123, in from_dict
        return Scan.from_dict(joint)
    OverflowError: can't convert negative value to unsigned
```

An image template starting from `0000` was seen in eBIC data.

**Comment by dagewa** [comment]
At the point of failure, `joint` is the following `dict`
```
In [1]: joint
Out[1]: 
{'batch_offset': -1,
 'epochs': [1360324992.789],
 'exposure_time': [0.2],
 'image_range': [0, 0],
 'oscillation': [0.0, 0.2],
 'valid_image_ranges': {}}
```

**Comment by graeme-winter** [comment]
Verified, looking now

**Comment by graeme-winter** [comment]
Looks like incorrect assumption about types in mapping from_dict to Scan object - goes via size_t which borks everything. Testing fix.
