### ISSUE TITLE
Support virtual data sets in HDF5

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1088]
At the moment I don't think we support virtual data sets in DIALS / dxtbx - will need to in the near future, to cope with use cases where multiple data sets are triggered as part of the same detector arm / acquisition process. 

Even if we have one master file per data set, we will need to be able to cope with that master referencing into one or more data files in HDF5, not from the start. Example case:

- each data set consists of 300 images
- each data file contains 1000 images
- 7 data sets are acquired

This will mean:

```
Data frame #  File #  Real set   Real set frame #
1 - 300       1         1        1 - 300
301 - 600     1         2        1 - 300
601 - 900     1         3        1 - 300
901 - 1000    1         4        1 - 100
1 - 200       2         4        101 - 300
201 - 500     2         5        1 - 300
501 - 800     2         6        1 - 300
801 - 1000    2         7        1 - 200
1 - 100       3         7        201 - 300
```

Will have master files 1...7 data files 1...3 one nxs file (I would expect) with virtual data sets 

```
/entry/data1
...
/entry/data7
```

which point to the correct sub data sets.

**Comment by graeme-winter** [comment]
N.B. in first instance can assume we are being passed master files not the nxs file, so we only have to deal with one data set at a time (otherwise will break all the things) however do need to be able to actually cope with the VDS being in there.

**Comment by phyy-nx** [comment]
Hi, so I used virtual datasets at the EuXFEL last year with NeXus. See
https://github.com/cctbx/cctbx_project/blob/master/xfel/euxfel/agipd_cxigeom2nexus.py#L24.
That script creates a NeXus master from input data.  The only thing that
changed in the master was referencing how the data was shaped on the disc.
Since describing that is part of the NeXus specification, it was invisible
to nexus.py/FormatNexus.py.  In other words, I think it would be up to the
author of the HDF5 files to create the VDS properly and that our readers
don't need to do anything special.

Unless I don't understand the question :)
-Araon

**Comment by graeme-winter** [comment]
Some subtleties relating to how data are structured could be there - the VDS under discussion above indexes into a larger 3D array rather than joining together smaller ones. I will try to get an example together (though this is in itself a job)

**Comment by graeme-winter** [comment]
This was a validation issue however @phyy-nx you are correct things work fine "by magic"

Wrote a jiffy tool which lives at 

https://github.com/graeme-winter/NXmxtools/blob/master/vdsmaker.py

to prevent pollution of the DIALS namespace which will make multiple "master" NeXus files which reference into a collection of actual data sets. Checked the image viewer and the files loaded are correctly offset into the main real data set. Checked the use of this with xia2 & works fine - one 1,800 image data set is read (in this case) as 6 independent 300 image sets.

**Comment by graeme-winter** [comment]
Slight deviation from the specification in the opening question as we have 6 top level files not one with 6 sets in - the latter is not well defined in NeXus - 

```
insu_d200_1.nxs			insu_d200_1_4.nxs
insu_d200_1_0.nxs		insu_d200_1_5.nxs
insu_d200_1_000001.h5		insu_d200_1_header.cbf
insu_d200_1_000002.h5		insu_d200_1_master.h5
insu_d200_1_1.nxs		insu_d200_1_meta.h5
insu_d200_1_2.nxs		insu_d200_1_meta_pack.h5
insu_d200_1_3.nxs
```

**Comment by graeme-winter** [comment]
```
xia2 image=/Users/graeme/data/i04-ins/insu_d200_1_0.nxs image=/Users/graeme/data/i04-ins/insu_d200_1_1.nxs image=/Users/graeme/data/i04-ins/insu_d200_1_2.nxs image=/Users/graeme/data/i04-ins/insu_d200_1_3.nxs image=/Users/graeme/data/i04-ins/insu_d200_1_4.nxs image=/Users/graeme/data/i04-ins/insu_d200_1_5.nxs

```

however works as expected so \o/

**Comment by graeme-winter** [comment]
Additional - output / merging stats identical so this is doing the right thing 🙂

**Comment by jbeilstenedmands** [comment]
I've just tried to do this and it seems to not work anymore, perhaps as a side effect of the recent work regarding indexing from 0?
I downloaded the dataset from zenodo, then 
```
$ xia2 image=../data/insu_d200_1_{1..6}.nxs

-------------------- Spotfinding SWEEP1 --------------------
Error: dials.generate_mask terminated with an error: see 1_dials.generate_mask.log for more details


$ cat 1_dials.generate_mask.log

The following parameters have been modified:

output {
  mask = "/Users/whi10850/Documents/example_data/insulin/xia2/DEFAULT/NATIVE/SWEEP1/index/1_pixels.mask"
  experiments = "/Users/whi10850/Documents/example_data/insulin/xia2/DEFAULT/NATIVE/SWEEP1/index/1_SWEEP1_masked.expt"
}
input {
  experiments = /Users/whi10850/Documents/example_data/insulin/xia2/DEFAULT/NATIVE/SWEEP1/index/SWEEP1_import.expt
}

DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:
  #000: H5D.c line 375 in H5Dget_space(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:
  #000: H5S.c line 865 in H5Sget_simple_extent_ndims(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
Traceback (most recent call last):
  File "/Users/whi10850/dials/build/../modules/dials/command_line/generate_mask.py", line 181, in <module>
    run()
  File "/Users/whi10850/dials/build/../modules/dials/command_line/generate_mask.py", line 176, in run
    generate_mask(experiments, params)
  File "/Users/whi10850/dials/build/../modules/dials/command_line/generate_mask.py", line 118, in generate_mask
    mask = generator.generate(imageset)
  File "/Users/whi10850/dials/modules/dials/util/masking/__init__.py", line 145, in generate
    
  File "/Users/whi10850/dials/modules/dxtbx/format/FormatMultiImage.py", line 36, in read
    return format_instance.get_raw_data(index)
  File "/Users/whi10850/dials/modules/dxtbx/format/FormatNexus.py", line 129, in get_raw_data
    return self._raw_data[index]
  File "/Users/whi10850/dials/modules/dxtbx/format/nexus.py", line 1363, in __getitem__
    data, (slice(i, i + 1, 1), slice(0, height, 1), slice(0, width, 1))
  File "/Users/whi10850/dials/modules/dxtbx/format/nexus.py", line 43, in dataset_as_flex
    return dataset_as_flex_int(dataset.id.id, selection)
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dxtbx Internal Error: /Users/whi10850/dials/modules/dxtbx/format/boost_python/nexus_ext.cc(85): DXTBX_ASSERT(rank == ndims) failure.
# command line:
# dials.generate_mask  'input.experiments=SWEEP1_import.expt' 'output.mask=1_pixels.mask' 'output.experiments=1_SWEEP1_masked.expt' '1_mask.phil'
#
# timing information:
#   time since process start: 1.4 seconds
#   time since object initialization: 1.4 seconds
```

**Comment by graeme-winter** [comment]
@jbeilstenedmands I suspect your version of the HDF5 libraries is out of date - I look at this and you are running with 1.10.0 which is pretty elderly & VDS is probably broken. 

Running again myself on a more recent build and things _seem_ to be working

**Comment by graeme-winter** [comment]
<oh> we now have a _different_ bug - 

```
Command line: xia2 image=/Users/graeme/data/i04-ins/insu_d200_1_1.nxs image=/Users/graeme/data/i04-ins/insu_d200_1_2.nxs image=/Users/graeme/data/i04-ins/insu_d200_1_3.nxs image=/Users/graeme/data/i04-ins/insu_d200_1_4.nxs image=/Users/graeme/data/i04-ins/insu_d200_1_5.nxs image=/Users/graeme/data/i04-ins/insu_d200_1_6.nxs
-------------------- Spotfinding SWEEP1 --------------------
15728 spots found on 300 images (max 336 / bin)
*                                                          *
** *    *                       *                        * *
******* *  * ********* * ********  * *  * ***  **  ** *  * *
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
1                         image                          300
------------------- Autoindexing SWEEP1 --------------------
All possible indexing solutions:
cI  78.01  78.01  78.01  90.00  90.00  90.00
hR 110.32 110.32  67.59  90.00  90.00 120.00
tI  77.99  77.99  78.02  90.00  90.00  90.00
oI  77.96  78.03  78.06  90.00  90.00  90.00
oF  77.94 110.24 110.32  90.00  90.00  90.00
mC 110.35 110.34  67.63  90.00 144.74  90.00
aP  67.64  67.59  67.59 109.42 109.52 109.52
Indexing solution:
cI  78.01  78.01  78.01  90.00  90.00  90.00
-------------------- Integrating SWEEP1 --------------------
Processed batches 1 to 300
Standard Deviation in pixel range: 0.47 0.67
Integration status per image (60/record):
%ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
"o" => good        "%" => ok        "!" => bad rmsd
"O" => overloaded  "#" => many bad  "." => weak
"@" => abandoned
Mosaic spread: 0.061 < 0.061 < 0.061
-------------------- Preparing DEFAULT ---------------------
--------------------- Scaling DEFAULT ----------------------
Resolution for sweep NATIVE/SWEEP1: 1.34 (cc_half > 0.3)
--------------------- Scaling DEFAULT ----------------------
---------------- Systematic absences check -----------------
Most likely space group: I 2 3
------------------- Unit cell refinement -------------------
Overall:  78.00  78.00  78.00  90.00  90.00  90.00
Overall twinning score: 2.02
Your data do not appear twinned
Project: AUTOMATIC
Crystal: DEFAULT
Sequence: 
Wavelength name: NATIVE
Wavelength 0.97950
Sweeps:
SWEEP SWEEP1 [WAVELENGTH NATIVE]
TEMPLATE insu_d200_1_1.nxs
DIRECTORY /Users/graeme/data/i04-ins
IMAGES (USER) 1 to 300
MTZ file: /Users/graeme/Projects/vds/DEFAULT/NATIVE/SWEEP1/integrate/13_integrated.refl
For AUTOMATIC/DEFAULT/NATIVE                 Overall    Low     High
High resolution limit                           1.34    3.64    1.34
Low resolution limit                           31.85   31.86    1.36
Completeness                                   95.0    97.6    67.9
Multiplicity                                    3.1     3.2     1.8
I/sigma                                        12.6    51.5     0.4
Rmerge(I)                                     0.045   0.027   1.042
Rmerge(I+/-)                                  0.041   0.024   0.969
Rmeas(I)                                      0.053   0.033   1.338
Rmeas(I+/-)                                   0.053   0.031   1.314
Rpim(I)                                       0.028   0.018   0.814
Rpim(I+/-)                                    0.033   0.020   0.881
CC half                                       0.998   0.996   0.348
Wilson B factor                              17.950
Anomalous completeness                         53.7    80.8     9.4
Anomalous multiplicity                          2.0     1.9     1.6
Anomalous correlation                        -0.004  -0.090   0.048
Anomalous slope                               0.905
dF/F                                          0.054
dI/s(dI)                                      0.964
Total observations                            52519    3025    1120
Total unique                                  17011     938     614
Assuming spacegroup: I 2 3
Unit cell (with estimated std devs):
78.00160(18) 78.00160(18)      78.00160(18)     
90.0         89.99999999999999 89.99999999999999
mtz_unmerged format:
Scaled reflections (NATIVE): /Users/graeme/Projects/vds/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged.mtz
mtz format:
Scaled reflections: /Users/graeme/Projects/vds/DataFiles/AUTOMATIC_DEFAULT_free.mtz
Processing took 00h 07m 28s
XIA2 used... ccp4, dials, xia2
Here are the appropriate citations (BIBTeX in xia2-citations.bib.)
Winn, M. D. et al. (2011) Acta Cryst. D67, 235-242.
Winter, G. (2010) J. Appl. Cryst. 43, 186-190.
Winter, G. et al. (2018) Acta Cryst. D74, 85-97.
Status: normal termination
```

These all map to one data set because VDS so ... only one run of 6 is processed 🙄

```
Grey-Area vds :) $ cat automatic.xinfo 
BEGIN PROJECT AUTOMATIC
BEGIN CRYSTAL DEFAULT

BEGIN WAVELENGTH NATIVE
WAVELENGTH 0.979499
END WAVELENGTH NATIVE

BEGIN SWEEP SWEEP1
WAVELENGTH NATIVE
DIRECTORY /Users/graeme/data/i04-ins
IMAGE insu_d200_1_1.nxs
START_END 1 300
END SWEEP SWEEP1

END CRYSTAL DEFAULT
END PROJECT AUTOMATIC
```

**Comment by graeme-winter** [comment]
Pretty sure this works correctly now - at least until I see evidence that it _does not_ will close. We use this routinely for grid scans now.
