### ISSUE TITLE
dials.image_viewer is a not-thing with the dials bootstrap build

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1091]
Platform: macOS Mojave / Python 3.6 / new style DIALS bootstrap build

Error:

```
Grey-Area tmp :) $ dials.image_viewer CM086A-LPO10-01000.mccd 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = <image files>
}

Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/image_viewer.py", line 171, in <module>
    show_image_viewer(params=params, reflections=reflections, experiments=experiments)
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/image_viewer.py", line 122, in show_image_viewer
    wrapper.display(experiments=experiments, reflections=reflections)
  File "/Users/graeme/svn/cctbx/modules/dials/util/image_viewer/spotfinder_wrap.py", line 53, in display
    from dials.util.image_viewer.spotfinder_frame import SpotFrame
  File "/Users/graeme/svn/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py", line 21, in <module>
    from dials.util.image_viewer.mask_frame import MaskSettingsFrame
  File "/Users/graeme/svn/cctbx/modules/dials/util/image_viewer/mask_frame.py", line 10, in <module>
    from wxtbx import metallicbutton
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/wxtbx/metallicbutton.py", line 31, in <module>
    import Carbon.Appearance
ModuleNotFoundError: No module named 'Carbon'
```

Ohai metallic buttons...

Mending suggestions very welcome!

**Comment by graeme-winter** [comment]
@Anthchirp we should probably cherry pick this to the dials release branch however...
