### ISSUE TITLE
dials.export for mtz crashes before integration

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#1113]
Not saying this should attempt to do anything sensible; but should definitely not stack trace (from principle of: User seeing a Stack Trace is _Always_ a Bug)
```
$ dials.export indexed.*
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.1310-g89e7d1e36
The following parameters have been modified:

input {
  experiments = indexed.expt
  reflections = indexed.refl
}

Data appears to be unscaled, setting intensity = profile+sum
Data appears to be unscaled, setting mtz.hklout = 'integrated.mtz'
Traceback (most recent call last):
  File "/Users/nickd/dials/dist3/build/../modules/dials/command_line/export.py", line 474, in <module>
    exporter(params, experiments, reflections)
  File "/Users/nickd/dials/dist3/build/../modules/dials/command_line/export.py", line 239, in export_mtz
    m = export_mtz(reflections[0], experiments, params)
  File "/Users/nickd/dials/dist3/modules/dials/util/export_mtz.py", line 465, in export_mtz
    d_min=params.mtz.d_min,
  File "/Users/nickd/dials/dist3/modules/dials/util/filter_reflections.py", line 113, in filter_reflection_table
    assert "intensity.prf.value" in reflection_table
AssertionError
```

**Comment by graeme-winter** [comment]
This error also suggests that summation integration could fail to export 🤔

**Comment by graeme-winter** [comment]
Looking at this in branch fix-1113
