### ISSUE TITLE
dials.search_beam_position crash

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1125]
```
$ dials.search_beam_position imported.expt strong.refl
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = imported.expt
  reflections = strong.refl
}

Running DPS using 1509 reflections
Found 1 solution with max unit cell 90.04 Angstroms.


easy_mp crash detected; subprocess trace: ----
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/modules/cctbx_project/libtbx/scheduling/job_scheduler.py", line 64, in job_cycle
    value = target( *args, **kwargs )
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/search_beam_position.py", line 396, in run_dps
    "Not enough solutions: found %i, need at least 3" % (len(solutions))
Not enough solutions: found 1, need at least 3
----------------------------------------------


Sorry: Not enough solutions: found 1, need at least 3
```

**Comment by dagewa** [comment]
`run_dps` is appropriately `Sorry`, but this gets swallowed because it is run inside `easy_mp.parallel_map`
