### ISSUE TITLE
Integrating a single image (numbered 0?) fails 

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1128]
```
dials.import th_8_2_0000.cbf ; dials.find_spots imported.expt ; dials.index imported.expt strong.refl ; dials.integrate indexed*
```

=>

```
********************************************************************************
Warning: 9 reference spots were not matched to predictions
********************************************************************************

Using 388 / 391 reflections for sigma calculation
Calculating E.S.D Beam Divergence.
Calculating E.S.D Reflecting Range (mosaicity).
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/integrate.py", line 665, in <module>
    script.run()
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/integrate.py", line 334, in run
    experiments = ProfileModelFactory.create(params, experiments, reference)
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/profile_model/factory.py", line 56, in create
    expr.scan,
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/profile_model/gaussian_rs/model.py", line 228, in create
    params, reflections, crystal, beam, detector, goniometer, scan, profile
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/profile_model/gaussian_rs/model.py", line 397, in create_from_reflections
    centroid_definition=params.gaussian_rs.centroid_definition,
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/profile_model/gaussian_rs/calculator.py", line 579, in __init__
    algorithm=algorithm,
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/profile_model/gaussian_rs/calculator.py", line 491, in __init__
    crystal, beam, detector, goniometer, scan, reflections
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/profile_model/gaussian_rs/calculator.py", line 330, in __init__
    "Something went wrong. Zero pixels selected for estimation of profile parameters."
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: Something went wrong. Zero pixels selected for estimation of profile parameters.
```

**Comment by graeme-winter** [comment]
Yes, it does not work when image is numbered 0 🙄 - the same image numbered 1 works fine.

**Comment by graeme-winter** [comment]
Turns out the mask values are all invalid? 🤔
