### ISSUE TITLE
cell restrained dials.refine sometimes fails with "max() arg is an empty sequence"

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#1142]
`cspad.cbf_metrology` combined 16 still shots and filtered one out (15 left). Then it called `dials.refine`, which crashed saying:

```
Traceback (most recent call last):
  File "/prog/dials/build/../modules/dials/command_line/refine.py", line 481, in <module>
    run()
  File "/prog/dials/build/../modules/dials/command_line/refine.py", line 396, in run
    experiments, reflections, params
  File "/prog/dials/build/../modules/dials/command_line/refine.py", line 284, in run_dials_refine
    refiner, reflections, history = run_macrocycle(params, reflections, experiments)
  File "/prog/dials/build/../modules/dials/command_line/refine.py", line 187, in run_macrocycle
    params, reflections, experiments
  File "/prog/dials/modules/dials/algorithms/refinement/refiner.py", line 276, in from_parameters_data_experiments
    return cls._build_components(params, reflections, experiments)
  File "/prog/dials/modules/dials/algorithms/refinement/refiner.py", line 408, in _build_components
    params.refinement.parameterisation, pred_param
  File "/prog/dials/modules/dials/algorithms/refinement/refiner.py", line 571, in config_restraints
    rp.add_restraints_to_target_xl_unit_cell(exp_id, tie.values, tie.sigmas)
  File "/prog/dials/modules/dials/algorithms/refinement/restraints/restraints_parameterisation.py", line 170, in add_restraints_to_target_xl_unit_cell
    model_parameterisation=param_i.parameterisation, target=values, sigma=sigma
  File "prog/dials/modules/dials/algorithms/refinement/restraints/restraints.py", line 76, in __init__
    if max(grad_diff) < 1e-10:
ValueError: Please report this error to dials-support@lists.sourceforge.net: max() arg is an empty sequence
```

See `combined.*` and `filtered.*` in https://drive.google.com/open?id=1zOV6WxL3yZH1lfDfuZU62mVW52jvba9y (feel free to copy it to `dials-data` if necessary).

After some investigation, I found:
- `dials.refine combined.* cell-restraint.phil` works fine
- `dials.refine filtered.* cell-restraint.phil` fails

So I initially thought `cctbx.xfel.filter_experiments_by_rmsd` might have a bug similar to #1120. 
However, without cell restraint (use `no-cell-restraint.phil` instead), both files before and after filtering work. Thus, the problem might be in `dials.refine`. Could you please look at this?

**Comment by dagewa** [comment]
Ok, I see what's happening. There are too few reflections to parameterise `Crystal1` so its parameters all get fixed. However we try to build restraints for it anyway. This fails because setting up restraints does a check on the gradients, but these are empty.

**Comment by biochem-fan** [comment]
I also tested the above fix on a larger dataset and it worked fine. Thank you very much for your fix.

**Comment by dagewa** [comment]
oh I thought this would be automatically closed by https://github.com/dials/dials/commit/fda53e3fe4ed4f95b30a3db6c8376e3f5cc32a95, but maybe it didn't because I squash-merged the branch. :man_shrugging:
