### ISSUE TITLE
Export bitmaps broken following cctbx changes

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1159]
```
Silver-Surfer dials :) [master] $ pytest --regression test/command_line/test_export_bitmaps.py::test_export_multi_panel
Test session starts (platform: darwin, Python 3.6.7, pytest 4.6.4, pytest-sugar 0.9.2)
rootdir: /Users/graeme/svn/cctbx/modules/dials, inifile: pytest.ini
plugins: sugar-0.9.2, mock-2.0.0, forked-1.1.2, xdist-1.31.0, dials-data-2.0.61
collecting ... 

――――――――――――――――――――――――――― test_export_multi_panel ――――――――――――――――――――――――――――

dials_regression = '/Users/graeme/svn/cctbx/modules/dials_regression'
tmpdir = local('/private/var/folders/hs/gvssfcd910s0jczjhjczj6h80000gn/T/pytest-of-graeme/pytest-4/test_export_multi_panel0')

    def test_export_multi_panel(dials_regression, tmpdir):
        image = os.path.join(
            dials_regression, "image_examples", "DLS_I23", "germ_13KeV_0001.cbf"
        )
    
        for binning in (1, 4):
            result = procrunner.run(
                [
                    "dials.export_bitmaps",
                    image,
                    "binning=%i" % binning,
                    "prefix=binning_%i_" % binning,
                ],
                working_directory=tmpdir.strpath,
            )
>           assert not result.returncode and not result.stderr
E           AssertionError: assert (not 1)
E            +  where 1 = {'exitcode': 1, 'command': ('dials.export_bitmaps', '/Users/graeme/svn/cctbx/modules/dials_regression/image_examples/D...: False, 'runtime': 1.4137243509758264, 'time_start': '2020-02-18 06:16:42 GMT', 'time_end': '2020-02-18 06:16:44 GMT'}.returncode

test/command_line/test_export_bitmaps.py:123: AssertionError
----------------------------- Captured stdout call -----------------------------
The following parameters have been modified:
Traceback (most recent call last):

output {
  prefix = "binning_1_"
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/export_bitmaps.py", line 311, in <module>
}
input {    run(sys.argv[1:])

  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/export_bitmaps.py", line 117, in run
  experiments = <image files>
    imageset_as_bitmaps(imageset, params)}


  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/export_bitmaps.py", line 192, in imageset_as_bitmaps
    show_untrusted=show_untrusted,
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/rstbx/slip_viewer/tile_generation.py", line 70, in _get_flex_image_multipanel
    for data in image_data:
NameError: name 'image_data' is not defined

 test/command_line/test_export_bitmaps.py ⨯                      100% ██████████

Results (1.58s):
       1 failed
         - test/command_line/test_export_bitmaps.py:108 test_export_multi_panel
```

**Comment by graeme-winter** [comment]
Probably changes in 

```
    from rstbx.slip_viewer.tile_generation import (
        _get_flex_image,
        _get_flex_image_multipanel,
    )
```

**Comment by graeme-winter** [comment]
https://github.com/cctbx/cctbx_project/commit/e1e41863aaae4a8944423f3c66f730bca4cac04e
