### ISSUE TITLE
dials.image_viewer broken for multi_panel=True import

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#1176]
```
$ dials.import $(libtbx.find_in_repositories dials_regression)/image_examples/DLS_I23/germ_13KeV_0001.cbf multi_panel=True

$ dials.image_viewer imported.expt 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = imported.expt
}

Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/image_viewer.py", line 176, in <module>
    show_image_viewer(params=params, reflections=reflections, experiments=experiments)
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/image_viewer.py", line 127, in show_image_viewer
    wrapper.display(experiments=experiments, reflections=reflections)
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_wrap.py", line 83, in display
    self.frame.load_image(chooser_wrapper(imagesets[0], 0))
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py", line 574, in load_image
    show_untrusted=show_untrusted,
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/slip_viewer/frame.py", line 448, in load_image
    and self.settings.image_type == "corrected"
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/slip_viewer/tile_generation.py", line 305, in set_image
    color_scheme=self.current_color_scheme,
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/slip_viewer/tile_generation.py", line 66, in get_flex_image_multipanel
    assert len(panels) == len(image_data), (len(panels), len(image_data))
AssertionError: (24, 120)
```

**Comment by rjgildea** [comment]
When `chooser_wrapper.get_image_data()` is called, the imageset appears to be inconsistent with itself:

https://github.com/dials/dials/blob/2beb4f5df3565a8e72351eecd4638b5f431415fb/util/image_viewer/slip_viewer/frame.py#L52-L58

```
len(self.image_set.get_detector())
24
len(self.image_set.get_corrected_data(self.index))
120
len(self.image_set.get_raw_data(self.index))
120
```
