### ISSUE TITLE
Improve error message when attempting to import the wrong type of h5 file.

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1220]
A user did not know to import the `_master.h5` file and instead tried the `_meta.h5` file. Can we detect this and give a friendly report, rather than this?

```
$ dials.import /dls/i03/data/2020/mx26568-5/Enolase_AS/P051_X3_Eno_AS/P051_X3_Eno_AS_1_meta.h5
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.1503-gc2ff66923
Traceback (most recent call last):
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20200406/build/../modules/dials/command_line/dials_import.py", line 921, in <module>
    script.run()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20200406/build/../modules/dials/command_line/dials_import.py", line 752, in run
    params, options = self.parser.parse_args(args=args, show_diff_phil=False)
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20200406/modules/dials/util/options.py", line 852, in parse_args
    quick_parse=quick_parse,
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20200406/modules/dials/util/options.py", line 569, in parse_args
    load_models=load_models,
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20200406/modules/dials/util/options.py", line 235, in __init__
    load_models,
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20200406/modules/dials/util/options.py", line 308, in try_read_experiments_from_images
    load_models=load_models,
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20200406/modules/dxtbx/model/experiment_list.py", line 537, in from_filenames
    format_kwargs=format_kwargs,
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20200406/modules/dxtbx/datablock.py", line 1529, in from_filenames
    format_kwargs=format_kwargs,
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20200406/modules/dxtbx/datablock.py", line 965, in __init__
    format_class, filename, format_kwargs=format_kwargs
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20200406/modules/dxtbx/datablock.py", line 1185, in _create_single_file_imageset
    return format_class.get_imageset(abspath(filename), format_kwargs=format_kwargs)
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20200406/modules/dxtbx/format/FormatMultiImage.py", line 135, in get_imageset
    assert single_file_indices is not None
AssertionError: Please report this error to dials-support@lists.sourceforge.net:
```

**Comment by graeme-winter** [comment]
Agreed - in the principle of "user should not see stack trace for reasonable errors" - would extend this also to data_00001.h5 etc.

**Comment by graeme-winter** [comment]
Am happy to look at this if not urgent?

**Comment by dagewa** [comment]
Thanks :-)

**Comment by kirienko** [comment]
Yep, I've got the same error message, but from `dials.image_viewer`. I'm puzzled as well.

**Comment by dagewa** [comment]
Just checked and the issue is still exactly as described
