### ISSUE TITLE
dials.integrate scan_range broken

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#1227]
I have one continuous rotational dataset and want to integrate a subset of images.
```
dials.import *cbf
dials.find_spots imported.expt nproc=4
dials.index strong.refl imported.expt 
dials.refine indexed.*
dials.integrate refined.* scan_range=10,30
```
crashes with
```
+-----+---------+--------------+------------+--------------+------------+-----------------+
|   # |   Group |   Frame From |   Frame To |   Angle From |   Angle To |   # Reflections |
|-----+---------+--------------+------------+--------------+------------+-----------------|
|   0 |       0 |           10 |         30 |            1 |          3 |             137 |
+-----+---------+--------------+------------+--------------+------------+-----------------+

 Using multiprocessing with 1 parallel job(s)

Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/dials/algorithms/integration/processor.py", line 433, in __call__
    imageset = imageset[frame0:frame1]
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/dxtbx/imageset.py", line 251, in __getitem__
    return self.partial_set(start - offset, stop - offset)
RuntimeError: dxtbx Internal Error: /dls_sw/apps/dials/dials-v2-2-1/modules/dxtbx/imageset.h(936): DXTBX_ASSERT(index < indices_.size()) failure.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v2-2-1/build/../modules/dials/command_line/integrate.py", line 665, in <module>
    script.run()
  File "/dls_sw/apps/dials/dials-v2-2-1/build/../modules/dials/command_line/integrate.py", line 353, in run
    reflections = integrator.integrate()
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/dials/algorithms/integration/integrator.py", line 1083, in integrate
    reference, profile_fitter_list, time_info = processor.process()
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/dials/algorithms/integration/processor.py", line 305, in process
    self.manager.accumulate(task())
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/dials/algorithms/integration/processor.py", line 435, in __call__
    raise RuntimeError("Programmer Error: bad array range: %s" % str(e))
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: Programmer Error: bad array range: dxtbx Internal Error: /dls_sw/apps/dials/dials-v2-2-1/modules/dxtbx/imageset.h(936): DXTBX_ASSERT(index < indices_.size()) failure.
```

Running with `scan_range=1,100 nproc=4` crashes with
```
 block_size: 46 frames

+-----+---------+--------------+------------+--------------+------------+-----------------+
|   # |   Group |   Frame From |   Frame To |   Angle From |   Angle To |   # Reflections |
|-----+---------+--------------+------------+--------------+------------+-----------------|
|   0 |       0 |            1 |         41 |          0.1 |        4.1 |             107 |
|   1 |       0 |           21 |         61 |          2.1 |        6.1 |              65 |
|   2 |       0 |           41 |         81 |          4.1 |        8.1 |              72 |
|   3 |       0 |           61 |        100 |          6.1 |       10   |             183 |
+-----+---------+--------------+------------+--------------+------------+-----------------+

 Using multiprocessing with 4 parallel job(s)



easy_mp crash detected; subprocess trace: ----
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/cctbx_project/libtbx/scheduling/job_scheduler.py", line 64, in job_cycle
    value = target( *args, **kwargs )
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/dials/algorithms/integration/processor.py", line 209, in __call__
    result = task()
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/dials/algorithms/integration/processor.py", line 459, in __call__
    self.params.debug.output,
dials Internal Error: /dls_sw/apps/dials/dials-v2-2-1/modules/dials/algorithms/integration/processor.h(93): DIALS_ASSERT(j < num.size()) failure.
----------------------------------------------


Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v2-2-1/build/../modules/dials/command_line/integrate.py", line 665, in <module>
    script.run()
  File "/dls_sw/apps/dials/dials-v2-2-1/build/../modules/dials/command_line/integrate.py", line 353, in run
    reflections = integrator.integrate()
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/dials/algorithms/integration/integrator.py", line 1083, in integrate
    reference, profile_fitter_list, time_info = processor.process()
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/dials/algorithms/integration/processor.py", line 301, in process
    preserve_exception_message=True,
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/dials/util/mp.py", line 154, in multi_node_parallel_map
    preserve_exception_message=preserve_exception_message,
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/dials/util/mp.py", line 46, in parallel_map
    preserve_exception_message=preserve_exception_message,
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/cctbx_project/libtbx/easy_mp.py", line 634, in parallel_map
    result = res()
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/cctbx_project/libtbx/scheduling/result.py", line 119, in __call__
    self.traceback( exception = self.exception() )
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 117, in __call__
    self.raise_handler( exception = exception )
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 134, in raise_with_traceback
    raise_(type(exception), exception, self.traceback)
  File "/dls_sw/apps/dials/dials-v2-2-1/conda_base/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/cctbx_project/libtbx/scheduling/mainthread.py", line 100, in poll
    value = target( *args, **kwargs )
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/dials/util/mp.py", line 84, in __call__
    preserve_exception_message=self.preserve_exception_message,
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/cctbx_project/libtbx/easy_mp.py", line 634, in parallel_map
    result = res()
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/cctbx_project/libtbx/scheduling/result.py", line 119, in __call__
    self.traceback( exception = self.exception() )
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 117, in __call__
    self.raise_handler( exception = exception )
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 147, in raise_with_stacktrace
    self.stacktrace( exception = exception )
  File "/dls_sw/apps/dials/dials-v2-2-1/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 88, in __call__
    raise exception
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dials Internal Error: /dls_sw/apps/dials/dials-v2-2-1/modules/dials/algorithms/integration/processor.h(93): DIALS_ASSERT(j < num.size()) failure.
```

**Comment by graeme-winter** [comment]
FWIW this is totally borked - 

```
Grey-Area sub :( $ dials.integrate refined.* scan_range=1,900
```

fails

```
Scan:
    image range:   {1,900}
    oscillation:   {0,0.2}
    exposure time: 0.1964
```

🤔

**Comment by graeme-winter** [comment]
Same stack trace as above

**Comment by rjgildea** [comment]
There are a number of dials command line programs that all handle `image_range` or `scan_range` parameters in their own special way. It strikes me that perhaps this would be better handled somewhere centrally like the dials option parser?

**Comment by graeme-winter** [comment]
Agreed, am just looking now at how `find_spots` (which works) handles the option.

**Comment by graeme-winter** [comment]
Actually useful stack trace: 

```
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/integrate.py", line 665, in <module>
    script.run()
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/integrate.py", line 353, in run
    reflections = integrator.integrate()
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/integration/integrator.py", line 1096, in integrate
    reference, profile_fitter_list, time_info = processor.process()
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/integration/processor.py", line 305, in process
    self.manager.accumulate(task())
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/integration/processor.py", line 434, in __call__
    imageset = imageset[frame0:frame1]
  File "/Users/graeme/svn/cctbx/modules/dxtbx/imageset.py", line 251, in __getitem__
    return self.partial_set(start - offset, stop - offset)
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dxtbx Internal Error: /Users/graeme/svn/cctbx/modules/dxtbx/imageset.h(936): DXTBX_ASSERT(index < indices_.size()) failure.
```

(by commenting out the try / except)

**Comment by graeme-winter** [comment]
the slicing call however is _identical_ to how it is done in `dials.find_spots` and in there it works fine.

**Comment by graeme-winter** [comment]
set(bugs).includes(off-by-one)

**Comment by rjgildea** [comment]
See also `dials.slice_sequence` (which should probably be the reference for slicing scans?)

**Comment by graeme-winter** [comment]
@rjgildea verified - 

```
dials.slice_sequence image_range=101,200 refined.*
dials.integrate refined_101_200.*
```

does exactly what it says on the tin

**Comment by graeme-winter** [comment]
Though this rapidly becomes a yak shaving expedition - should we refactor `slice_sequence` to be a thing wrapper around an API, then use this API everywhere? 🤔

**Comment by graeme-winter** [comment]
This is not stale: the issue is still true

**Comment by graeme-winter** [comment]
```
Timing information for integration
+-------------------+----------------+
| Read time         | 122.48 seconds |
| Extract time      | 9.05 seconds   |
| Pre-process time  | 0.02 seconds   |
| Process time      | 25.40 seconds  |
| Post-process time | 0.00 seconds   |
| Total time        | 183.00 seconds |
+-------------------+----------------+

Removing 3329 unintegrated reflections of 38215 total
Saving 34886 reflections to integrated.refl
Saving the experiments to integrated.expt
```

from

```
dials.integrate ../refined.* scan_range=300,450
```

would suggest this is fixed 🎉
