### ISSUE TITLE
Parse duplicate input data sensibly

### ISSUE THREAD

**Issue by benjaminhwilliams** [dials/dials#1228]
I notice that passing a duplicate experiment list/reflection table pair to `dials.scale` results in them being treated as independent data, e.g.
```
$ dials.show integrated.refl
...
Reflection list contains 14025 reflections
+--------+-----+-----+------+
| Column | min | max | mean |
|--------+-----+-----+------|
...
| id     | 0   | 3   | 1    |
...
$ dials.scale integrated.expt integrated.refl integrated.expt integrated.refl
...
$ dials.show scaled.refl
...
Reflection list contains 28050 reflections
+--------+-----+-----+------+
| Column | min | max | mean |
|--------+-----+-----+------|
...
| id     | 0   | 7   | 3    |
...
```
Clearly `dials.scale` is scaling together eight sweeps (two copies of each of four sweeps recorded in teh input `integrated.{expt,refl}`).  Is this desired behaviour? I would have expected duplicates in the list of input experiment lists and reflection tables to be rationalised during parsing.  Is there a valid use case for passing duplicate copies of data into `dials.scale`, or should the file parsing be tidied up to remove duplicates?

Comparing with `dials.index`, I see that we are inconsistent in the way we parse duplicates, though neither program gets it quite right:
```$ dials.index imported.expt strong.refl imported.expt strong.refl 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.1505-gcefb0d330
The following parameters have been modified:

input {
  experiments = imported.expt
  reflections = strong.refl
}

Traceback (most recent call last):
  File "/home/ekm22040/DIALS/build/../modules/dials/command_line/index.py", line 261, in <module>
    run()
  File "/home/ekm22040/DIALS/build/../modules/dials/command_line/index.py", line 245, in run
    experiments, reflections, params
  File "/home/ekm22040/DIALS/build/../modules/dials/command_line/index.py", line 152, in index
    assert len(reflections) == len(experiments)
AssertionError
```

**Comment by graeme-winter** [comment]
Fixed - will now give a RuntimeError about duplicate experiments
