### ISSUE TITLE
dials.detect_blanks crashes if given images with 0 oscillation

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1250]
In trying to track down a user error I note:

```
Grey-Area Downloads :) $ dials.detect_blanks 2_SWEEP1_strong.*
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = 2_SWEEP1_strong.expt
  reflections = 2_SWEEP1_strong.refl
}

Analysis of 1999915 strong reflections:
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/detect_blanks.py", line 325, in <module>
    run(sys.argv[1:])
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/detect_blanks.py", line 251, in run
    fractional_loss=params.counts_fractional_loss,
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/detect_blanks.py", line 52, in blank_counts_analysis
    n_images_per_step = iceil(phi_step / osc)
ZeroDivisionError: float division by zero
```

clearly this is surprising that `xia2 pipeline=dials` got as far as here for 0 oscillation... the xia2.txt file suggests it was interpreted as rotation data:

```
-------------------- Spotfinding SWEEP1 --------------------
1999915 spots found on 3600 images (max 50771 / bin)
              ***                           ***             
             *****                         *****            
            *******                       *******           
           ***********                    **********        
    ***** *************** **      *****  *******************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
1                         image                         3600
```

Have asked for access to the data

**Comment by graeme-winter** [comment]
```
Grey-Area Downloads :) $ dials.show 2_SWEEP1_strong.expt | grep Experiment | wc -l
    7200
```

Looks like a lot of experiments...
