### ISSUE TITLE
UboundLocalError in dials.index

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1254]
I used this command
```
dials.index imported.expt strong.refl detector.fix=distance space_group=p222
```
to run `dials.index` on a case with an incorrect beam centre, which failed with this error:
```
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/index.py", line 261, in <module>
    run()
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/index.py", line 245, in run
    experiments, reflections, params
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/index.py", line 167, in index
    known_crystal_models=known_crystal_models,
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/index.py", line 115, in _index_experiments
    idxr.index()
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/indexing/indexer.py", line 541, in index
    new_expts = self.find_lattices()
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/indexing/lattice_search/__init__.py", line 142, in find_lattices
    self.candidate_crystal_models
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/indexing/lattice_search/__init__.py", line 256, in choose_best_orientation_matrix
    experiments[0].crystal
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/indexing/symmetry.py", line 243, in apply_symmetry
    if best_subgroup is None:
UnboundLocalError: local variable 'best_subgroup' referenced before assignment
```
When the beam centre is correct this case indexes fine.

**Comment by dagewa** [comment]
I will try to figure out what is happening here in the next few days

**Comment by dagewa** [comment]
Thanks!
