### ISSUE TITLE
nexus_ext.cc(122): DXTBX_ASSERT(status2 >= 0) failure.

### ISSUE THREAD

**Issue by picca** [dials/dials#1260]
Hello, still working on the Debian package of dials/cctbx/xia2

So now that I managed to compile all the stack, I try to use 

`xia2 --pipeline=dials image=foo_master.h5`

but I get this error message
 
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages//dials/command_line/generate_mask.py", line 181, in <module>
    run()
  File "/usr/lib/python3/dist-packages//dials/command_line/generate_mask.py", line 176, in run
    generate_mask(experiments, params)
  File "/usr/lib/python3/dist-packages//dials/command_line/generate_mask.py", line 118, in generate_mask
    mask = generator.generate(imageset)
  File "/usr/lib/python3/dist-packages/dials/util/masking.py", line 206, in generate
    image = imageset.get_raw_data(0)
  File "/usr/lib/python3/dist-packages/dxtbx/format/FormatMultiImage.py", line 36, in read
    return format_instance.get_raw_data(index)
  File "/usr/lib/python3/dist-packages/dxtbx/format/FormatHDF5EigerNearlyNexus.py", line 399, in get_raw_data
    return self._raw_data[index]
  File "/usr/lib/python3/dist-packages/dxtbx/format/nexus.py", line 1363, in __getitem__
    data_as_flex = dataset_as_flex(
  File "/usr/lib/python3/dist-packages/dxtbx/format/nexus.py", line 44, in dataset_as_flex
    return dataset_as_flex_int(dataset.id.id, selection)
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dxtbx Internal Error: /builds/science-team/dials/debian/output/dials-2.2.3+dfsg2/modules/dxtbx/format/boost_python/nexus_ext.cc(122): DXTBX_ASSERT(status2 >= 0) failure.
```

So it seems that this is an error when trying to read the data from the files.

I have no problem to read the images using silx from the ESRF. so it seems that my hdf5 stack + pluging is workig fine.

I am trying to debug this issue using gdb but it is not that simple to find the problematic function name

in my case

`_ZN5dxtbx6format12boost_python15dataset_as_flexIiEEN6scitbx2af5versaIT_NS4_9flex_gridINS4_5smallIlLm10EEEEEEElN5boost6python5tupleE` :))

which correspond to `    def("dataset_as_flex_int", &dataset_as_flex<int>);`

so here my questions:

1) how do we print the hdf5 stack in order to understand why the

```
    // Copy the data
    herr_t status2 = custom_read<T>(dataset_id, mem_space_id, file_space_id, data);
    DXTBX_ASSERT(status2 >= 0);
```
failed.

2) do you have some experience with this kind of error ?, do you think about something which could be evident.

thansk

Frederic

**Comment by graeme-winter** [comment]
@picca I think this usually indicates that the hdf5 bitshuffle / lz4 compression plugin has not been found...

**Comment by picca** [comment]
It is lot easier with the hdf5 call stack :))

```
Continuing.
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 140737349957440:
  #000: ../../../src/H5Dio.c line 199 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: ../../../src/H5Dio.c line 603 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: ../../../src/H5Dchunk.c line 2293 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: ../../../src/H5Dchunk.c line 3658 in H5D__chunk_lock(): data pipeline read failed
    major: Dataset
    minor: Filter operation failed
  #004: ../../../src/H5Z.c line 1301 in H5Z_pipeline(): required filter 'bitshuffle; see https://github.com/kiyo-masui/bitshuffle' is not registered
    major: Data filters
    minor: Read failed
  #005: ../../../src/H5PLint.c line 270 in H5PL_load(): search in path table failed
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #006: ../../../src/H5PLpath.c line 604 in H5PL__find_plugin_in_path_table(): search in path /var/lib/conda_base/lib/plugins encountered an error
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #007: ../../../src/H5PLpath.c line 656 in H5PL__find_plugin_in_path(): can't open directory: /var/lib/conda_base/lib/plugins
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
```

since I can read the data with h5dump and h5ls, it seems to me that something is done in dials which supersed  the system hdf5 installation.

the conda path seems suspicious to me. I do not have conda installed on my system.

**Comment by picca** [comment]
It solved my problem great.

```
(gdb) c
Continuing.
[New Thread 0x7fffc25b5700 (LWP 296140)]
[New Thread 0x7fffc1db4700 (LWP 296141)]
[New Thread 0x7fffc15b3700 (LWP 296142)]
Writing mask to 1_pixels.mask
Saving experiments to 1_SWEEP1_masked.expt
[Thread 0x7fffee34d700 (LWP 296135) exited]
[Thread 0x7ffff2b4e700 (LWP 296134) exited]
[Thread 0x7ffff334f700 (LWP 296133) exited]
[Thread 0x7fffc1db4700 (LWP 296141) exited]
[Thread 0x7fffc25b5700 (LWP 296140) exited]
[Thread 0x7ffff7c03740 (LWP 296120) exited]
[Inferior 1 (process 296120) exited normally]
```

let's find other code which modify the environement

**Comment by picca** [comment]
here a first list of suspicious code

```
./modules/ccp4io_adaptbx/__init__.py:    os.environ["SYMINFO"] = _
./modules/ccp4io_adaptbx/__init__.py:    os.environ["SYMINFO"] = op.join( os.getenv( "CLIBD" ), "syminfo.lib" )
./modules/cctbx_project/crys3d/hklview/HKLviewer.py:    os.environ["QTWEBENGINE_CHROMIUM_FLAGS"] = " "
./modules/cctbx_project/crys3d/hklview/HKLviewer.py:      os.environ["QTWEBENGINE_CHROMIUM_FLAGS"] = "--remote-debugging-port=9742 --single-process --js-flags='--expose_gc'"
./modules/cctbx_project/crys3d/hklview/HKLviewer.py:    os.environ["QTWEBENGINE_CHROMIUM_FLAGS"] += QWebEngineViewFlags
./modules/cctbx_project/crys3d/hklview/QtChromiumCheck.py:os.environ["QTWEBENGINE_CHROMIUM_FLAGS"] = "--single-process" # necessary for detecting webgl abilities on Mac
./modules/cctbx_project/iotbx/cif/tests/tst_ucif_examples_compilation.py:  os.environ["LIBTBX_UCIF"] = ucif_dist
./modules/cctbx_project/iotbx/cif/tests/tst_ucif_examples_compilation.py:  os.environ["LIBTBX_ANTLR3"] = antlr3_dist
./modules/cctbx_project/libtbx/auto_build/create_mac_app.py:os.environ["PYTHONPATH"] = ""
./modules/cctbx_project/libtbx/auto_build/create_mac_pkg.py:  os.environ["COPYFILE_DISABLE"] = "true"
./modules/cctbx_project/libtbx/auto_build/install_distribution.py:    os.environ["%s_MTYPE" % self.product_name] = self.mtype
./modules/cctbx_project/libtbx/auto_build/install_distribution.py:    os.environ["%s_INSTALLER" % self.product_name] = self.installer_dir
./modules/cctbx_project/libtbx/auto_build/install_distribution.py:    os.environ["%s_LOC" % self.product_name] = self.dest_dir
./modules/cctbx_project/libtbx/auto_build/install_distribution.py:    os.environ["%s_BUILD" % self.product_name] = self.build_dir
./modules/cctbx_project/libtbx/auto_build/install_distribution.py:      os.environ["LD_LIBRARY_PATH"] = "lib:%s:%s" % \
./modules/cctbx_project/libtbx/auto_build/install_distribution.py:      os.environ["LD_LIBRARY_PATH"] = "lib:%s:%s" % \
./modules/cctbx_project/libtbx/auto_build/install_distribution.py:      os.environ["PATH"] = "%s:%s" % (op.join(self.build_dir, "bin"), os.environ["PATH"])
./modules/cctbx_project/libtbx/auto_build/install_distribution.py:      os.environ["PATH"] = "%s;%s" % (op.join(self.build_dir, "bin"), os.environ["PATH"])
./modules/cctbx_project/libtbx/auto_build/regenerate_module_files.py:  os.environ['PANGO_RC_FILE'] = pangorc
./modules/cctbx_project/libtbx/auto_build/regenerate_module_files.py:  os.environ['FONTCONFIG_PATH'] = fonts_etc_dir
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:os.environ['PYTHONNOUSERSITE'] = '1'
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:      os.environ['CFLAGS'] = old_cflags + ' -march=i686'
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:          del(os.environ['CONFIG_SITE'])
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:    os.environ['PKG_CONFIG_PATH'] = ":".join(pkg_config_paths)
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:      os.environ[env_var] = "None"
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:    os.environ["PATH"] = ("%s/bin:" % self.base_dir) + os.environ['PATH']
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:        lib_paths.append(os.environ["LD_LIBRARY_PATH"])
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:      os.environ['LD_LIBRARY_PATH'] = ":".join(lib_paths)
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:    os.environ['CPPFLAGS'] = "%s %s"%(" ".join(inc_paths), self.cppflags_start)
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:    os.environ['LDFLAGS'] = "%s %s"%(" ".join(lib_paths), self.ldflags_start)
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:      os.environ['PIP_REQ_TRACKER'] = pkg_info['cachedir']
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:    os.environ['HDF5_DIR'] = self.base_dir
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:      os.environ['KERNEL_BITS'] = '64'
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:      os.environ['KERNEL_BITS'] = ''
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:    os.environ['SSL_CERT_FILE'] = cert_file
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:      os.environ['CFLAGS'] = old_cflags + ' -g -O2'
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:      os.environ['CFLAGS'] = old_cflags
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:      os.environ['CXXFLAGS'] = old_cflags + ' -march=i686'
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:      os.environ['CXXFLAGS'] = old_cflags
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:    os.environ['MANSCHEME'] = "bsd-source-cat"
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:    os.environ['DIR_MAN'] = op.join(self.base_dir, "man")
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:      os.environ['CFLAGS'] = os.environ.get('CFLAGS', '') + " -arch x86_64"
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:        os.environ['CPPFLAGS'] = self.min_macos_version_flag
./modules/cctbx_project/libtbx/auto_build/install_base_packages.py:        os.environ['LDFLAGS'] = self.min_macos_version_flag
./modules/cctbx_project/libtbx/command_line/parallel_simple.py:      os.environ[k] = v
./modules/cctbx_project/libtbx/command_line/parallel_simple.py:        os.environ[flds[1]] = flds[2]
./modules/cctbx_project/libtbx/easy_run.py:      os.environ["PYTHONPATH"] = ""
./modules/cctbx_project/libtbx/easy_run.py:      del os.environ["PYTHONPATH"]
./modules/cctbx_project/libtbx/phil/tst.py:  os.environ["_X_Y_Z_"] = "xyz"
./modules/cctbx_project/libtbx/phil/tst.py:  os.environ["_X_Y_Z_"] = "xyz"
./modules/cctbx_project/libtbx/test_utils/parallel.py:    os.environ['OPENBLAS_NUM_THREADS'] = "1"
./modules/cctbx_project/libtbx/test_utils/pytest.py:    os.environ['LIBTBX_SKIP_PYTEST'] = "1"
./modules/cctbx_project/libtbx/test_utils/pytest.py:    del os.environ['LIBTBX_SKIP_PYTEST']
./modules/cctbx_project/libtbx/test_utils/pytest.py:          os.environ['LIBTBX_SKIP_PYTEST'] = '1'
./modules/cctbx_project/libtbx/test_utils/pytest.py:          del os.environ['LIBTBX_SKIP_PYTEST']
./modules/cctbx_project/libtbx/thread_utils.py:        os.environ["OMP_NUM_THREADS"] = "1"
./modules/cctbx_project/libtbx/xmlrpc_utils.py:      os.environ[prog_port_env] = str(self._port)
./modules/cctbx_project/libtbx/xmlrpc_utils.py:        os.environ["CCTBX_XMLRPC_TIMEOUT"] = str(self.timeout)
./modules/cctbx_project/libtbx/xmlrpc_utils.py:        os.environ["CCTBX_XMLRPC_PORT"] = str(self.local_port)
./modules/cctbx_project/libtbx/SConscript:      del os.environ['VS_UNICODE_OUTPUT']
./modules/cctbx_project/libtbx/SConscript:      os.environ['VS_UNICODE_OUTPUT'] = VS_UNICODE_OUTPUT
./modules/cctbx_project/libtbx/SConscript:      os.environ["MACOSX_DEPLOYMENT_TARGET"] = env_etc.mac_os_version
./modules/cctbx_project/libtbx/env_config.py:        os.environ[name.upper()+"_DIST"] = abs(path)
./modules/cctbx_project/libtbx/env_config.py:    os.environ["LIBTBX_BUILD"] = abs(self.build_path) # to support libtbx.load_env
./modules/cctbx_project/libtbx/env_config.py:      os.environ[self.ld_library_path_var_name()] = ":".join(
./modules/cctbx_project/libtbx/env_config.py:  build_path = os.environ["LIBTBX_BUILD"]
./modules/cctbx_project/scitbx/command_line/show_exp_times.py:      del os.environ["LD_PRELOAD"]
./modules/cctbx_project/scitbx/command_line/show_exp_times.py:    os.environ[evar] = "1"
./modules/cctbx_project/xfel/command_line/xtc_process.py:      os.environ['CBF_TMP_DIR'] = tmp_dir
./modules/cctbx_project/xfel/command_line/xtc_dump.py:      os.environ['CBF_TMP_DIR'] = tmp_dir
./modules/cctbx_project/xfel/metrology/mark0.py:        os.environ["BOOST_ADAPTBX_FPE_DEFAULT"]="1"
./modules/dials/__init__.py:    os.environ["BOOST_ADAPTBX_FPE_DEFAULT"] = "1"
./modules/dials/command_line/cluster_exec.py:        return os.environ["SGE_TASK_ID"]
./modules/dxtbx/tests/serialize/test_filename.py:    os.environ["HELLO_WORLD"] = "EXPANDED"
./modules/dxtbx/tests/serialize/test_filename.py:    os.environ["HELLO_WORLD"] = "EXPANDED"
./modules/dxtbx/__init__.py:os.environ["HDF5_PLUGIN_PATH"] = (
./modules/dxtbx/__init__.py:    os.environ["BOOST_ADAPTBX_FPE_DEFAULT"] = "1"
./modules/xia2/Decorators/CCP4Decorator.py:                    self.add_working_environment("LD_LIBRARY_PATH", os.environ["CLIB"])
./modules/xia2/Driver/QSubDriver.py:            self._working_environment["LD_LIBRARY_PATH"] = os.environ[
./modules/xia2/Handlers/Environment.py:    os.environ["CCP4_SCR"] = ccp4_scr
./modules/xia2/__init__.py:    os.environ["BOOST_ADAPTBX_FPE_DEFAULT"] = "1"
```

**Comment by ndevenish** [comment]
> it is a bad practice to modify the env of an user ;)

Hi picca,

This isn't modifying the environment of the user, only the current process. As far as I know, HDF5 doesn't (or didn't) have a non-environment way to specify plugins, and the path where these are going to be isn't known until run-time under the libtbx system that we have to use. I think these restrictions still hold.

I note that a large proportion of those examples you found with `grep` aren't even in `dials` or `dxtbx`. Of the six lines that are in dials and dxtbx, one is setting this, one isn't an assignment, two are explicitly testing environment-based behaviour in tests, and two are are turning off cctbx FPE "handling" that breaks floating-point exceptions, and specified as a compromise for not changing upstream behaviour after extensive discussions. Many of the entries in other projects seem at first glance to be reasonable.

Unfortunately dials needs to work with and within other systems that we either can't, aren't allowed to, or would be a maintenance burden to change. Working within those constraints isn't "bad practice", just realistic. 

Pull requests to dials and dxtbx to fix any of these you consider unnecessary are welcome, as long as they don't break the use cases that they were put in to work around in the first case. I wouldn't embark on large structural or heavy refactoring changes without discussing potential needs or constraints first, though.

In any case, it seems like you have solved your initial problem, so I am closing this.

**Comment by picca** [comment]
thanks for your valuable explanations.

I will just maintain a Debian specific patch in order to fix my problem.

thanks
