### ISSUE TITLE
test_search_beam_position fails on CCP4's Windows build

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1270]
DIALS 2.2.4-g04de204b4-release in the draft update to CCP4 7.1.001 has a problem with test_search_beam_position.py. This command 
```
C:\ccp4temp>ccp4-python -m pytest -s -v --regression %CCP4%\lib\py2\site-packages\dials\test\command_line\test_search_beam_position.py::test_index_after_search
```
gets to this point and then hangs
```
Saved 4993 reflections to strong.refl

DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = imported.expt
  reflections = strong.refl
}

Process Process-1:
Traceback (most recent call last):
  File "C:\CCP4-7\7.1\lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "C:\CCP4-7\7.1\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\CCP4-7\7.1\lib\site-packages\concurrent\futures\process.py", line 122, in _process_worker
    call_item = call_queue.get(block=True)
  File "C:\CCP4-7\7.1\lib\multiprocessing\queues.py", line 117, in get
    res = self._recv()
ArgumentError: Python argument types in
    Beam.__init__(Beam, tuple, float, float, float, tuple, float, float, float)
did not match C++ signature:
    __init__(boost::python::api::object, scitbx::vec3<double> direction, double wavelength, double divergence, double sigma_divergence, scitbx::vec3<double> polarization_normal, double polarization_fraction, double flux, double transmission, bool deg=True)
    __init__(boost::python::api::object, scitbx::vec3<double> s0, double divergence, double sigma_divergence, bool deg=True)
    __init__(boost::python::api::object, scitbx::vec3<double> direction, double wavelength, double divergence, double sigma_divergence, bool deg=True)
    __init__(_object*, scitbx::vec3<double> s0)
    __init__(_object*, scitbx::vec3<double> direction, double wavelength)
    __init__(_object*, dxtbx::model::Beam)
    __init__(_object*)
```

**Comment by dagewa** [comment]
Calling the program via procrunner rather than the functional interface (as per Charles's attached patch) allows the whole test module to run to completion
[dials-test-search-beam-position.patch.txt](https://github.com/dials/dials/files/4671806/dials-test-search-beam-position.patch.txt)

**Comment by dagewa** [comment]
One possibility is that Windows' spawn behaviour in multiprocessing is not producing an environment in which the boost python type conversions are available.
