### ISSUE TITLE
dials.reindex: trap non-rational reindex matrix gracefully

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1281]
Related to #1280 

```
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/reindex.py", line 358, in <module>
    run(sys.argv[1:])
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/reindex.py", line 319, in run
    experiments, change_of_basis_op, space_group=space_group
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/reindex.py", line 153, in reindex_experiments
    cryst_reindexed = cryst_reindexed.change_basis(cb_op)
RuntimeError: cctbx Internal Error: /Users/graeme/svn/cctbx/modules/cctbx_project/cctbx/sgtbx/rot_mx.cpp(19): Unsuitable value for rational rotation matrix.
```

should be trapped gracefully, "users should not see a stack trace" rule

**Comment by graeme-winter** [comment]
```
Grey-Area work :( $ dials.reindex change_of_basis_op=a+2*b+c,-b+c,a scaled.{expt,refl}
The following parameters have been modified:

change_of_basis_op = "a+2*b+c,-b+c,a"
input {
  experiments = scaled.expt
  reflections = scaled.refl
}

Unsuitable change of basis: a+2*b+c,-b+c,a
```

**Comment by graeme-winter** [comment]
Turns out this broke a test - reverting change for revisiting
