### ISSUE TITLE
Installer fails with "Multiple sources for dispatcher"

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#1326]
Reported by Scott Classen on dials-support using the new 3.0.3 installer:
```
(.env) [16:35]classen@als-enable:dials-installer[1070]$ sudo ./install --prefix=/als_sw/

    ==========================================================================
                          DIALS Installation

                          version: v3-0-3
                     machine type: intel-linux-2.6-x86_64
                       OS version: 3.10.0-1127.13.1.el7.x86_64
                      destination: /als_sw/dials-v3-0-3
                  # of processors: 20
    =========================================================================
    
Configuring DIALS components...

 -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=-

An error occured during installation

Excerpt from installation log:
 :   6 entries for entry point dials.integration.background
 :   1 entries for entry point dials.integration.centroid
 :   2 entries for entry point dials.spotfinder.threshold
 : Removing legacy entry points from /als_sw/dials-v3-0-3/build/libtbx.dials.egg-info
 : DIALS 3.0.3-g8d758451f-release
 : Identified autocompletable commands: dials.calc_rmsds dials.combine_found_spots dials.find_spots dials.geometry_viewer dials.index dials.integrate dials.reciprocal_lattice_viewer dials.refine dials.reindex dials.rl_png
 : Installing autocompletion script into: setpaths_debug.sh setpaths.sh setpaths_all.sh 
 : Processing: "/als_sw/dials-v3-0-3/modules/xia2/libtbx_refresh.py"
 : XIA2 0.7.44-ge5e34f04-dials-3.0
 : Traceback (most recent call last):
 :   File "/als_sw/dials-v3-0-3/modules/cctbx_project/libtbx/configure.py", line 34, in <module>
 :     if not run():
 :   File "/als_sw/dials-v3-0-3/modules/cctbx_project/libtbx/configure.py", line 29, in run
 :     libtbx.env_config.cold_start(sys.argv)
 :   File "/als_sw/dials-v3-0-3/modules/cctbx_project/libtbx/env_config.py", line 2630, in cold_start
 :     env.refresh()
 :   File "/als_sw/dials-v3-0-3/modules/cctbx_project/libtbx/env_config.py", line 1866, in refresh
 :     self.generate_entry_point_dispatchers()
 :   File "/als_sw/dials-v3-0-3/modules/cctbx_project/libtbx/env_config.py", line 1747, in generate_entry_point_dispatchers
 :     target_file=os.path.join('bin', ep.name),
 :   File "/als_sw/dials-v3-0-3/modules/cctbx_project/libtbx/env_config.py", line 1316, in write_dispatcher
 :     + "   =%s" % source_file)
 : RuntimeError: Multiple sources for dispatcher:
 :   target file:
 :     "/als_sw/dials-v3-0-3/build/bin/iota"
 :   source files:
 :     "/als_sw/dials-v3-0-3/modules/cctbx_project/iota/command_line/iota_gui_launch.py"
 :    =relocatable_path(anchor="/als_sw/dials-v3-0-3/build", relocatable="../modules/cctbx_project/iota/command_line/iota_gui_launch.py")
 :     "/als_sw/dials-v3-0-3/conda_base/bin/iota"
 :    =relocatable_path(anchor="/als_sw/dials-v3-0-3/build", relocatable="../conda_base/bin/iota")

This led to Traceback (most recent call last):
  File "./bin/install.py", line 67, in reconfigure
  File "/als_sw/dials-installer/lib/libtbx/auto_build/install_distribution.py", line 431, in reconfigure
    call(args=args, log=log, verbose=self.options.verbose)
  File "/als_sw/dials-installer/lib/libtbx/auto_build/installer_utils.py", line 55, in call
    raise RuntimeError("Call to '%s' failed with exit code %d" % (args, rc))
RuntimeError: Call to '/als_sw/dials-v3-0-3/conda_base/bin/python /als_sw/dials-v3-0-3/modules/cctbx_project/libtbx/configure.py --current_working_directory /als_sw/dials-v3-0-3/build dials xia2 iota prime --use_conda' failed with exit code 1


Please report this installation error to dials-support@lists.sourceforge.net
(.env) [16:35]classen@als-enable:dials-installer[1071]$ pip list
Package                Version
---------------------- -------
fast-dp                1.6.2
ispyb                  5.6.2
mysql-connector-python 8.0.20
Pillow                 7.1.2
pip                    20.1.1
progressbar2           3.51.3
protobuf               3.12.2
python-utils           2.4.0
setuptools             47.1.1
six                    1.15.0
tabulate               0.8.7
wheel                  0.34.2
(.env) [16:36]classen@als-enable:dials-installer[1072]$ which python
~/ispyb-populate/.env/bin/python
(.env) [16:36]classen@als-enable:dials-installer[1073]$ python -V
Python 3.8.3
(.env) [16:36]classen@als-enable:dials-installer[1074]$ 
```

I've not found what is causing this yet, but there do seem to be some issues with our installation of IOTA - as in, it isn't being packaged correctly at the moment. I don't know why this is causing conflicts in this particular case yet...

**Comment by ndevenish** [comment]
Have not seen this reoccur.
