### ISSUE TITLE
circular Sorry()

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#1356]
[xia2 tests on Python 3.8/linux shows the following error:](https://dev.azure.com/xia2/xia2/_build/results?buildId=14&view=logs&j=ab83e72f-bb37-5e01-cdeb-beb69439099c&t=a3919d4a-dbe7-59c9-d07f-1dbefe5b12c4&l=278)
```
2020-07-24T19:45:31.2396382Z 
2020-07-24T19:45:31.2396715Z =================================== FAILURES ===================================
2020-07-24T19:45:31.2397144Z _______________________________ test_start_xia2 ________________________________
2020-07-24T19:45:31.2398200Z [gw1] linux -- Python 3.8.5 /home/vsts/work/1/build/../conda_base/bin/python3.8
2020-07-24T19:45:31.2398455Z 
2020-07-24T19:45:31.2398667Z     def test_start_xia2():
2020-07-24T19:45:31.2398934Z         result = procrunner.run(["xia2"])
2020-07-24T19:45:31.2399226Z >       assert result["exitcode"] == 0
2020-07-24T19:45:31.2399465Z E       assert 1 == 0
2020-07-24T19:45:31.2399676Z E         +1
2020-07-24T19:45:31.2400025Z E         -0
2020-07-24T19:45:31.2400158Z 
2020-07-24T19:45:31.2400405Z Test/System/test_run_xia2.py:9: AssertionError
2020-07-24T19:45:31.2400961Z ----------------------------- Captured stdout call -----------------------------
2020-07-24T19:45:31.2401343Z Traceback (most recent call last):
2020-07-24T19:45:31.2401946Z   File "/home/vsts/work/1/conda_base/lib/python3.8/site-packages/tabulate.py", line 59, in <module>
2020-07-24T19:45:31.2402350Z     from html import escape as htmlescape
2020-07-24T19:45:31.2402925Z   File "/home/vsts/work/1/xia2-checkout/command_line/html.py", line 13, in <module>
2020-07-24T19:45:31.2403286Z     from xia2.Modules.Report import Report
2020-07-24T19:45:31.2403661Z   File "/home/vsts/work/1/modules/xia2/Modules/Report/__init__.py", line 7, in <module>
2020-07-24T19:45:31.2403993Z     import dials.pychef
2020-07-24T19:45:31.2404325Z   File "/home/vsts/work/1/modules/dials/pychef/__init__.py", line 8, in <module>
2020-07-24T19:45:31.2404680Z     from dials.util import resolution_analysis
2020-07-24T19:45:31.2405071Z   File "/home/vsts/work/1/modules/dials/util/resolution_analysis.py", line 22, in <module>
2020-07-24T19:45:31.2405502Z     from dials.algorithms.scaling.scaling_library import determine_best_unit_cell
2020-07-24T19:45:31.2405970Z   File "/home/vsts/work/1/modules/dials/algorithms/scaling/scaling_library.py", line 22, in <module>
2020-07-24T19:45:31.2406361Z     from dials.util.options import OptionParser
2020-07-24T19:45:31.2406729Z   File "/home/vsts/work/1/modules/dials/util/options.py", line 18, in <module>
2020-07-24T19:45:31.2407059Z     from dials.util import Sorry
2020-07-24T19:45:31.2407870Z ImportError: cannot import name 'Sorry' from partially initialized module 'dials.util' (most likely due to a circular import) (/home/vsts/work/1/modules/dials/util/__init__.py)
2020-07-24T19:45:31.2408286Z 
2020-07-24T19:45:31.2408597Z During handling of the above exception, another exception occurred:
2020-07-24T19:45:31.2408854Z 
2020-07-24T19:45:31.2409079Z Traceback (most recent call last):
2020-07-24T19:45:31.2409470Z   File "/home/vsts/work/1/build/../modules/xia2/command_line/xia2_main.py", line 13, in <module>
2020-07-24T19:45:31.2409844Z     from dials.util import Sorry
2020-07-24T19:45:31.2410177Z   File "/home/vsts/work/1/modules/dials/util/__init__.py", line 6, in <module>
2020-07-24T19:45:31.2410520Z     import tabulate as _tabulate
2020-07-24T19:45:31.2411103Z   File "/home/vsts/work/1/conda_base/lib/python3.8/site-packages/tabulate.py", line 61, in <module>
2020-07-24T19:45:31.2411502Z     from cgi import escape as htmlescape
2020-07-24T19:45:31.2412114Z ImportError: cannot import name 'escape' from 'cgi' (/home/vsts/work/1/conda_base/lib/python3.8/cgi.py)
```

We might be able to resolve this by [removing `Sorry()` outside of `/command_line/` as we've agreed before](https://github.com/dials/dials/issues/729#issuecomment-488258298) - and replace it with `sys.exit()` inside `/command_line/`.

**Comment by ndevenish** [comment]
Oh,
```
2401946Z   File "/home/vsts/work/1/conda_base/lib/python3.8/site-packages/tabulate.py", line 59, in <module>
2020-07-24T19:45:31.2402350Z     from html import escape as htmlescape
2020-07-24T19:45:31.2402925Z   File "/home/vsts/work/1/xia2-checkout/command_line/html.py", line 13, in <module>
2020-07-24T19:45:31.2403286Z     from xia2.Modules.Report import Report
```
Something very wrong with import paths here

**Comment by graeme-winter** [comment]
Would rename `xia2/command_line/html.py` -> `xia2/command_line/xia2_html.py` be a reasonable response?
