### ISSUE TITLE
py2/3 and precommit

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#1375]
precommit seems to be broken in my conda environment.  Here's an example of an error message I get (this is a build using conda at PAL, `<working>` subbed for bootstrap folder):

```
$ libtbx.precommit install
Conda: <working>/conda_base/bin/conda
Conda python: <working>/conda_base/bin/python3.6
Conda version: 4.8.3
Base Python: 3.6.11
Installing precommit...
Traceback (most recent call last):
  File "<working>/modules/dials/precommitbx/installer.py", line 697, in main
    import pre_commit.constants
ModuleNotFoundError: No module named 'pre_commit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<working>/build/../modules/dials/command_line/precommitbx.py", line 7, in <module>
    dials.precommitbx.installer.main()
  File "<working>/modules/dials/precommitbx/installer.py", line 701, in main
    install_precommit_into_conda(conda)
  File "<working>/modules/dials/precommitbx/installer.py", line 220, in install_precommit_into_conda
    stop_on_error="Error installing pre-commit to conda base",
  File "<working>/modules/dials/precommitbx/installer.py", line 73, in clean_run
    print("\n".join(result.stdout.split("\n")[-10:]))
TypeError: a bytes-like object is required, not 'str'
```

Py3 bug?  Looks like there are two errors?

Comment from @Anthchirp:

> Looks like the precommit helper scripts still support python 2, which seems to be at least partially responsible for this.

**Comment by Anthchirp** [comment]
The main issue was a string handling one. A lot of the complexity in this script however could now be done away with the conda environment. Only need to find the time 🙃
