### ISSUE TITLE
image_viewer: "Save Image" broken for multi-panel detectors

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#1385]
Image viewer:
![image (2)](https://user-images.githubusercontent.com/529963/91853093-9f796900-ec59-11ea-9736-c19dcc55c54e.png)
Saved png:
![image (3)](https://user-images.githubusercontent.com/529963/91853096-a1432c80-ec59-11ea-8dc6-6cd190f314a8.png)

**Comment by benjaminhwilliams** [comment]
There appear to be several skeletons in the image viewer closet.  Until c79eb537bcc2ba14de811dc16b4e13f6350ce321, I wasn't able to save images at all.  Since that hasn't been back-ported yet, DIALS 2.2 may not even be able to generate a saved image using the '💾 Save as' button.

**Comment by Anthchirp** [comment]
DIALS 2.2.8 can export the file referenced in the screenshot just fine. Saved PNG:
![image](https://user-images.githubusercontent.com/2102431/91867061-18cd8780-ec6b-11ea-9518-e74382ba7c80.png)

**Comment by benjaminhwilliams** [comment]
The problem seems to be that the image viewer is working in lab coordinates rather than detector coordinates.  If the 2θ angle is not zero, the saved image is displaced accordingly.  In the example above, the 2θ angle is -20°.  For comparison, this is an example with 2θ = +20°:

![test](https://user-images.githubusercontent.com/11389015/91884465-f98c2580-ec7d-11ea-95b5-8d231d90c6ef.png)

**Comment by benjaminhwilliams** [comment]
Artificially setting 2θ = 45° results in the starting view of the image viewer to look like this.  Note that the beam centre is in the centre of the view:

![image](https://user-images.githubusercontent.com/11389015/91884836-ae264700-ec7e-11ea-8905-4b942daab160.png)

If we move the view to show the whole detector area, we see that the image is stretched (oddly, it is not squashed as we would expect given that we ought to be seeing a projection of the detector from behind the beamstop :shrug:):

![image](https://user-images.githubusercontent.com/11389015/91885031-fc3b4a80-ec7e-11ea-8e2b-30b2fa2553fa.png)

**Comment by benjaminhwilliams** [comment]
The corresponding saved PNG has the expected size and shape (appropriately squashed) but the image has been displaced out of the frame.

![test](https://user-images.githubusercontent.com/11389015/91885217-50462f00-ec7f-11ea-9b19-ba6b42e7a1ff.png)

**Comment by benjaminhwilliams** [comment]
Best of all, if we set 2θ = 89° we get this nonsense:

![image](https://user-images.githubusercontent.com/11389015/91885690-1de90180-ec80-11ea-8065-95552000b287.png)


And if we set 2θ = 90°, we just get a stacktrace because the projection of the detector on our view from behind the beamstop results in no image at all:
```
$ dials.image_viewer test_01_00001.cbf 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = <image files>
}

Gtk-Message: 18:20:35.523: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/home/ekm22040/DIALS/build/../modules/dials/command_line/image_viewer.py", line 216, in <module>
    show_image_viewer(params=params, reflections=reflections, experiments=experiments)
  File "/home/ekm22040/DIALS/build/../modules/dials/command_line/image_viewer.py", line 167, in show_image_viewer
    wrapper.display(experiments=experiments, reflections=reflections)
  File "/home/ekm22040/DIALS/modules/dials/util/image_viewer/spotfinder_wrap.py", line 83, in display
    self.frame.load_image(chooser_wrapper(imagesets[0], 0))
  File "/home/ekm22040/DIALS/modules/dials/util/image_viewer/spotfinder_frame.py", line 565, in load_image
    show_untrusted=show_untrusted,
  File "/home/ekm22040/DIALS/modules/dials/util/image_viewer/slip_viewer/frame.py", line 430, in load_image
    and self.settings.image_type == "corrected"
  File "/home/ekm22040/DIALS/modules/dials/util/image_viewer/slip_viewer/tile_generation.py", line 304, in set_image
    color_scheme=self.current_color_scheme,
  File "/home/ekm22040/DIALS/modules/dials/util/image_viewer/slip_viewer/tile_generation.py", line 118, in get_flex_image_multipanel
    beam_center /= npanels / 1e-3
  File "/home/ekm22040/DIALS/modules/cctbx_project/scitbx/matrix/__init__.py", line 154, in __truediv__
    return rec([e/other for e in self.elems], self.n)
  File "/home/ekm22040/DIALS/modules/cctbx_project/scitbx/matrix/__init__.py", line 154, in <listcomp>
    return rec([e/other for e in self.elems], self.n)
ZeroDivisionError: float division by zero
```

**Comment by graeme-winter** [comment]
Does all this derive from https://github.com/dials/dials/issues/1358 ?

**Comment by graeme-winter** [comment]
OK, this is a game over bug - I have _real user data_ which you cannot look at because of this.

**Comment by benjaminhwilliams** [comment]
Ditto.

**Comment by graeme-winter** [comment]
OK, thanks @ndevenish for https://github.com/dials/dials/tree/revert_single_panel - in this branch with the changes to put the images at a jaunty angle reverted the image viewer works fine

**Comment by graeme-winter** [comment]
> Does all this derive from #1358 ?

Yuuuuup!

**Comment by phyy-nx** [comment]
I'm on leave so can't follow in detail what's going on here, but reverting #1182 will break all the issues #1182 fixed and cause me much more work down the road.  I'd much rather work be done here to fix the underlying problems.  I'd speculate the issue is between old iotbx conventions on the 2theta arm being used with dxtbx conventions, and the right way to fix it is to toss out the iotbx code.

**Comment by graeme-winter** [comment]
@phyy-nx sympathetic re: being on leave however this is now broken for users _now_. Removing the `iotbx` code could be (will probably be) non-trivial. Wonder if a reasonable approach is to branch off where we are for fixing then apply the reversion to master so we can get things fixed for users, then work on a proper fix on the branch which can start from where we are now?

**Comment by phyy-nx** [comment]
Ok, with the assumption that #1182 will be fixed and merged back in sooner rather than later. Thanks.

**Comment by graeme-winter** [comment]
OK this is now a critically needed fix - users unable to use tool for basic beamline work
