### ISSUE TITLE
dials indexing assertion error

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#139]
From xia2/xia2#22
Unfortunately don't have more information because we still lose stacktraces through easy_mp.

xia2 folder ```/dls/i19-1/data/2016/mt11238-5/processing/2015ncs0543_dls2_reprocessed```
log 
```/dls/i19-1/data/2016/mt11238-5/processing/2015ncs0543_dls2_reprocessed/DEFAULT/NATIVE/SWEEP2/index/51_dials.index.log ```:

```
Setting d_min: 0.66
FFT gridding: (256,256,256)
Number of centroids used: 2073
(e X r).s0 too small:
for 1 reflections
out of 464 total
such as (0, 0, 0)
with scattering vector (0.0, 0.0, -1.450873425802333)
where r = (0.0, 0.0, 0.0)
e = (1.0, 0.0, -0.0)
s0 = (0.0, 0.0, -1.450873425802333)
this reflection forms angle with the equatorial plane normal:
1.57079632679
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-dev20160505/build/../modules/dials/command_line/index.py", line 176, in <module>
    run(sys.argv[1:])
  File "/dls_sw/apps/dials/dials-dev20160505/build/../modules/dials/command_line/index.py", line 153, in run
    params=params)
  File "/dls_sw/apps/dials/dials-dev20160505/modules/dials/algorithms/indexing/indexer.py", line 502, in from_parameters
    idxr = indexer_fft3d(reflections, imagesets, params=params)
  File "/dls_sw/apps/dials/dials-dev20160505/modules/dials/algorithms/indexing/fft3d.py", line 33, in __init__
    super(indexer_fft3d, self).__init__(reflections, imagesets, params)
  File "/dls_sw/apps/dials/dials-dev20160505/modules/dials/algorithms/indexing/indexer.py", line 446, in __init__
    self.index()
  File "/dls_sw/apps/dials/dials-dev20160505/modules/dials/algorithms/indexing/indexer.py", line 690, in index
    experiments.extend(self.find_lattices())
  File "/dls_sw/apps/dials/dials-dev20160505/modules/dials/algorithms/indexing/fft3d.py", line 88, in find_lattices
    self.candidate_crystal_models)
  File "/dls_sw/apps/dials/dials-dev20160505/modules/dials/algorithms/indexing/indexer.py", line 1353, in choose_best_orientation_matrix
    preserve_exception_message=True,
  File "/dls_sw/apps/dials/dials-dev20160505/modules/cctbx_project/libtbx/easy_mp.py", line 608, in parallel_map
    result = res()
  File "/dls_sw/apps/dials/dials-dev20160505/modules/cctbx_project/libtbx/scheduling/result.py", line 119, in __call__
    self.traceback( exception = self.exception() )
  File "/dls_sw/apps/dials/dials-dev20160505/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 106, in __call__
    self.handler( exception = exception )
  File "/dls_sw/apps/dials/dials-dev20160505/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 128, in raise_with_stacktrace
    self.stacktrace( exception = exception )
  File "/dls_sw/apps/dials/dials-dev20160505/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 78, in __call__
    raise exception
AssertionError
# command line:
# dials.index  '15_optimized_datablock.json' '14_SWEEP2_strong.pickle' 'indexing.method=fft3d' 'indexing.nproc=12' 'filter_ice=false' 'reflections_per_degree=100' 'close_to_spindle_cutoff=0.020000' 'outlier.algorithm=auto' 'max_cell=30' 'min_cell=3' 'known_symmetry.space_group=3' 'known_symmetry.unit_cell="7.63932129844,5.69683806926,19.0768578359,90.0,89.6972551981,90.0"' 'output.experiments=51_experiments.json' 'output.reflections=51_indexed.pickle'
```

**Comment by dagewa** [comment]
Ok, comes from refinement. I'll look at it.

-- David
