### ISSUE TITLE
mp.method fails with Eiger data for spot finding

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#144]
<pre>
[gw56@cs04r-sc-com99-01 parallel]$ dials.find_spots ../datablock.json njobs=10 nproc=20 mp.method=sge
DIALS 1.dev.297-gd7ebd46
The following parameters have been modified:

spotfinder {
  mp {
    method = none *sge lsf pbs
    njobs = 10
    nproc = 20
  }
}
input {
  datablock = ../datablock.json
}

Setting spotfinder.filter.min_spot_size=3
Configuring spot finder from input parameters
--------------------------------------------------------------------------------
Finding strong spots in imageset 0
--------------------------------------------------------------------------------

Finding spots in image 1 to 1800...
Extracting strong pixels from images
 Using sge with 10 parallel job(s) and 20 processes per node

gw56 has deleted job 151556
Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/find_spots.py", line 196, in <module>
    halraiser(e)
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/find_spots.py", line 194, in <module>
    script.run()
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/find_spots.py", line 143, in run
    datablocks[0], params)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/array_family/flex.py", line 173, in from_observations
    return find_spots(datablock)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 415, in __call__
    table, hot_mask = self._find_in_imageset(imageset)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 499, in _find_in_imageset
    spots_all.extend(extract_spots(imageset[j0:j1]))
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 301, in __call__
    callback       = process_output)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/mp.py", line 225, in batch_multi_node_parallel_map
    preserve_exception_message = True)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/mp.py", line 134, in multi_node_parallel_map
    preserve_exception_message = preserve_exception_message)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/libtbx/easy_mp.py", line 608, in parallel_map
    result = res()
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/libtbx/scheduling/result.py", line 119, in __call__
    self.traceback( exception = self.exception() )
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 107, in __call__
    self.raise_handler( exception = exception )
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 137, in raise_with_stacktrace
    self.stacktrace( exception = exception )
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 78, in __call__
    raise exception
IOError: Please report this error to dials-support@lists.sourceforge.net: Can't read data (Could not allocate output buffer.)
</pre>

Works a treat for CBF files, so think we have something odd going on here

**Comment by Anthchirp** [comment]
file handles issue?

**Comment by graeme-winter** [comment]
I'd believe that. How to debug?

**Comment by jmp1985** [comment]
@graeme-winter Did you get this to work?

**Comment by graeme-winter** [comment]
Nope

This remains a problem, would welcome a solution!
