### ISSUE TITLE
In fresh bootstrap, dials.image_viewer actually broken

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1442]
Freshly bootstrapped DIALS build, on Python 3.8 platform:

```
dials_data/vmxi_thaumatin> dials.image_viewer image_15799_master.h5 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = <image files>
}

/Users/graeme/svn/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py:153: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  btn = self.toolbar.AddLabelTool(
/Users/graeme/svn/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py:173: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  btn = self.toolbar.AddLabelTool(
/Users/graeme/svn/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py:202: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  btn = self.toolbar.AddLabelTool(
/Users/graeme/svn/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py:210: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  btn = self.toolbar.AddLabelTool(
/Users/graeme/svn/cctbx/modules/dials/util/image_viewer/slip_viewer/pyslip.py:189: wxPyDeprecationWarning: Call to deprecated item EmptyBitmap. Use :class:`wx.Bitmap` instead
  self.buffer = wx.EmptyBitmap(width, height)
/Users/graeme/svn/cctbx/modules/dials/util/image_viewer/slip_viewer/tile_generation.py:403: wxPyDeprecationWarning: Call to deprecated item EmptyImage. Use :class:`Image` instead.
  wx_image = wx.EmptyImage(256, 256)
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/image_viewer.py", line 217, in <module>
    show_image_viewer(params=params, reflections=reflections, experiments=experiments)
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/image_viewer.py", line 168, in show_image_viewer
    wrapper.display(experiments=experiments, reflections=reflections)
  File "/Users/graeme/svn/cctbx/modules/dials/util/image_viewer/spotfinder_wrap.py", line 83, in display
    self.frame.load_image(chooser_wrapper(imagesets[0], 0))
  File "/Users/graeme/svn/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py", line 550, in load_image
    super().load_image(
  File "/Users/graeme/svn/cctbx/modules/dials/util/image_viewer/slip_viewer/frame.py", line 401, in load_image
    self.OnShowSettings(None)
  File "/Users/graeme/svn/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py", line 576, in OnShowSettings
    self.settings_frame = SpotSettingsFrame(
  File "/Users/graeme/svn/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py", line 1681, in __init__
    super().__init__(*args, **kwds)
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/rstbx/viewer/frame.py", line 363, in __init__
    panel = SettingsPanel(self, -1)
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/rstbx/viewer/frame.py", line 397, in __init__
    grid = wx.FlexGridSizer(cols=2, rows=2)
TypeError: FlexGridSizer(): arguments did not match any overloaded call:
  overload 1: 'rows' is not a valid keyword argument
  overload 2: 'rows' is not a valid keyword argument
  overload 3: not enough arguments
  overload 4: not enough arguments
```

Package manifest:

```
# packages in environment at /Users/graeme/svn/cctbx/conda_base:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
apipkg                    1.5                        py_0    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
attrs                     20.2.0             pyh9f0ad1d_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.lzma            0.0.14           py38ha1d0bda_1    conda-forge
biopython                 1.78             py38h4d0b108_0    conda-forge
bitshuffle                0.3.5            py38hf64814c_7    conda-forge
boost                     1.70.0           py38hbf1eeb5_1    conda-forge
boost-cpp                 1.70.0               hef959ae_3    conda-forge
brotlipy                  0.7.0           py38h4d0b108_1000    conda-forge
bzip2                     1.0.8                haf1e3a3_3    conda-forge
c-compiler                1.1.1                haf1e3a3_0    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cctools                   949.0.1              h22b1bf0_7    conda-forge
cctools_osx-64            949.0.1              h5ba7a2e_7    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
cffi                      1.14.3           py38hc4dd44e_0    conda-forge
cfgv                      3.2.0                      py_0    conda-forge
chardet                   3.0.4           py38h32f6830_1007    conda-forge
clang                     10.0.1          default_hf57f61e_1    conda-forge
clang_osx-64              10.0.1              h05bbb7f_10    conda-forge
clangxx                   10.0.1          default_hf57f61e_1    conda-forge
clangxx_osx-64            10.0.1              h05bbb7f_10    conda-forge
colorlog                  4.2.1            py38h32f6830_0    conda-forge
compiler-rt               10.0.1               he6db49b_0    conda-forge
compiler-rt_osx-64        10.0.1               h033240e_0    conda-forge
conda                     4.8.5            py38h32f6830_1    conda-forge
conda-package-handling    1.7.0            py38h4d0b108_5    conda-forge
cryptography              3.1.1            py38h52adbb4_0    conda-forge
cxx-compiler              1.1.1                h879752b_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.21          py38h11c0d25_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
dials-data                2.1.30             pyh9f0ad1d_0    conda-forge
distlib                   0.3.1              pyh9f0ad1d_0    conda-forge
dnspython                 2.0.0                      py_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
docutils                  0.16             py38h32f6830_1    conda-forge
drmaa                     0.7.9                   py_1000    conda-forge
editdistance              0.5.3            py38h11c0d25_1    conda-forge
eigen                     3.3.7             ha1b3eb9_1001    conda-forge
execnet                   1.7.1                      py_0    conda-forge
expat                     2.2.9                hb1e8313_2    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
freetype                  2.10.2               h8da9a1a_0    conda-forge
future                    0.18.2           py38h32f6830_1    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
graypy                    2.1.0                      py_0    conda-forge
h5py                      2.10.0          nompi_py38he4534f8_104    conda-forge
hdf5                      1.10.6          nompi_haae91d6_101    conda-forge
hdf5-external-filter-plugins 0.1.0                         4    conda-forge
hdf5-external-filter-plugins-bitshuffle 0.1.0                h81e4017_4    conda-forge
hdf5-external-filter-plugins-bzip2 0.1.0                h00b02fa_4    conda-forge
hdf5-external-filter-plugins-lz4 0.1.0                h81e4017_4    conda-forge
icu                       67.1                 hb1e8313_0    conda-forge
identify                  1.5.5              pyh9f0ad1d_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib_resources       3.0.0            py38h32f6830_0    conda-forge
iniconfig                 1.0.1              pyh9f0ad1d_0    conda-forge
iota                      1.4.20                    dev_0    <develop>
ispyb                     5.6.2              pyh9f0ad1d_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.17.0                     py_0    conda-forge
jpeg                      9d                   h0b31af3_0    conda-forge
junit-xml                 1.9                pyh9f0ad1d_0    conda-forge
kiwisolver                1.2.0            py38ha0d09dd_0    conda-forge
lcms2                     2.11                 h174193d_0    conda-forge
ld64                      530                           7    conda-forge
ld64_osx-64               530                  h3c32e8a_7    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libclang-cpp10            10.0.1          default_hf57f61e_1    conda-forge
libcxx                    10.0.1               h5f48129_0    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libgfortran               4.0.0               h2d743fc_11    conda-forge
libgfortran4              7.5.0               h2d743fc_11    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libllvm10                 10.0.1               h009f743_3    conda-forge
libopenblas               0.3.10          openmp_h63d9170_4    conda-forge
libpng                    1.6.37               hb0a8c7a_2    conda-forge
libprotobuf               3.13.0               hab81aa3_0    conda-forge
libsodium                 1.0.18               haf1e3a3_1    conda-forge
libtiff                   4.1.0                h2ae36a8_6    conda-forge
libwebp-base              1.1.0                h0b31af3_3    conda-forge
llvm-openmp               10.0.1               h28b9765_0    conda-forge
llvm-tools                10.0.1               h1341992_3    conda-forge
lz4-c                     1.9.2                hb1e8313_3    conda-forge
markupsafe                1.1.1            py38h4d0b108_1    conda-forge
matplotlib-base           3.3.2            py38haed9462_0    conda-forge
mock                      4.0.2            py38h32f6830_0    conda-forge
more-itertools            8.5.0                      py_0    conda-forge
mrcfile                   1.1.2                      py_1    conda-forge
msgpack-c                 3.2.0                h69fbfa3_1    conda-forge
msgpack-python            1.0.0            py38ha0d09dd_1    conda-forge
mysql-common              8.0.21                        2    conda-forge
mysql-connector-python    8.0.21           py38h8028358_1    conda-forge
mysql-libs                8.0.21               hfb8f7af_2    conda-forge
ncurses                   6.2                  hb1e8313_1    conda-forge
networkx                  2.5                        py_0    conda-forge
nodeenv                   1.5.0              pyh9f0ad1d_0    conda-forge
numpy                     1.19.1           py38h8ccc501_2    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1h               haf1e3a3_0    conda-forge
orderedset                2.0.3            py38h64e0658_2    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pathlib2                  2.3.5            py38h32f6830_1    conda-forge
pillow                    7.2.0            py38h83dc5e5_1    conda-forge
pip                       20.2.3                     py_0    conda-forge
pluggy                    0.13.1           py38h32f6830_2    conda-forge
pre-commit                2.7.1            py38h32f6830_0    conda-forge
procrunner                2.2.0              pyh9f0ad1d_0    conda-forge
protobuf                  3.13.0           py38h11c0d25_0    conda-forge
psutil                    5.7.2            py38h4d0b108_0    conda-forge
pthread-stubs             0.4               h1de35cc_1001    conda-forge
py                        1.9.0              pyh9f0ad1d_0    conda-forge
pycosat                   0.6.3           py38h4d0b108_1004    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pypubsub                  4.0.3                      py_0    conda-forge
pyrtf                     0.45                       py_2    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
pytest                    6.1.1            py38h32f6830_0    conda-forge
pytest-forked             1.2.0              pyh9f0ad1d_0    conda-forge
pytest-mock               1.13.0                   py38_0    conda-forge
pytest-sugar              0.9.4              pyh9f0ad1d_1    conda-forge
pytest-xdist              2.1.0                      py_0    conda-forge
python                    3.8.5           h0ed32c4_9_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python.app                1.3              py38h64e0658_1    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py38h4d0b108_0    conda-forge
pyzmq                     19.0.2           py38h2c785a9_1    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
reportlab                 3.5.51           py38hece02dc_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
ruamel_yaml               0.15.80         py38h4d0b108_1002    conda-forge
scikit-learn              0.23.2           py38hfde8033_0    conda-forge
scipy                     1.5.2            py38h1402333_0    conda-forge
scons                     4.0.1            py38h32f6830_0    conda-forge
setuptools                49.6.0           py38h32f6830_1    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sphinx                    3.1.2                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
sqlite                    3.33.0               h960bd1c_0    conda-forge
stomp.py                  6.1.0              pyh9f0ad1d_0    conda-forge
tabulate                  0.8.7              pyh9f0ad1d_0    conda-forge
tapi                      1000.10.8            h879752b_4    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               hb0a8c7a_0    conda-forge
toml                      0.10.1             pyh9f0ad1d_0    conda-forge
tornado                   6.0.4            py38h64e0658_1    conda-forge
tqdm                      4.50.0             pyh9f0ad1d_0    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
virtualenv                20.0.20          py38h32f6830_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
workflows                 2.1                pyh9f0ad1d_0    conda-forge
wxpython                  4.0.7.post2      py38h10bb4de_3    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
zeromq                    4.3.3                hb1e8313_1    conda-forge
zlib                      1.2.11            h7795811_1009    conda-forge
zocalo                    0.6.3              pyh9f0ad1d_1    conda-forge
zstd                      1.4.5                h289c70a_2    conda-forge
```

**Comment by dwpaley** [comment]
from @dermen : setting grid = wx.FlexGridSizer(cols=2, rows=2, vgap=2, hgap=2) fixes the crash with no obvious jumbling of the control panel.

**Comment by graeme-winter** [comment]
Awesome, thank you, will test this out in the morning 👍

**Comment by dermen** [comment]
Setting the vgap, hgap = 2  fixes the crash with no jumbles on linx.. on mac os, the jumbles persist with vgap, hgap = 2 ..

**Comment by graeme-winter** [comment]
> Setting the vgap, hgap = 2 fixes the crash with no jumbles on linux.. on mac os, the jumbles persist with vgap, hgap = 2 ..

Shame, but somewhat expected. Suspect toolkit error

**Comment by ndevenish** [comment]
Need to fix this before 3.2, going to look at this

**Comment by dermen** [comment]
So SpotSettingsFrame in util/image_viewer/spotfinder_frame.py is inheriting from SettingsFrame in cctbx_project/rstbx . If you were to go into the SettingsFrame code in rstbx/viewer/frame.py and then return in the __init__ method, just after the super call, e.g.

```
class SettingsFrame(wx.MiniFrame):
  def __init__(self, *args, **kwds):
    super(SettingsFrame, self).__init__(*args, **kwds)
    return
```
then you'd see the image viewer displaying properly in Mac OS ( I just tested) Maybe therein lies a clue on how to fix it.. Perhaps adding a boolean argument to SettingsFrame in rstbx on whether to return after initializing wx MiniFrame ..

**Comment by Anthchirp** [comment]
Yes, you're right. The dials `SpotSettingsFrame` init repeats steps that are already done in the rstbx `SettingsFrame` init. For example, it creates a second `self.panel`.

I believe the cleanest solution is to not inherit from `rstbx.SettingsFrame`, but from `wx.MiniFrame` directly, and remove all irrelevant commands.

**Comment by ndevenish** [comment]
Ahah, tracked it down. This broke because of https://github.com/dials/dials/commit/0b211a53cb530ab489b397b963683a83c9911126 - fixed an LGTM warning that was warning that `super()` wasn't calling the parent class (presumably deliberately, but this was really hard to guess). Fixing.
