### ISSUE TITLE
dials.find_spots_server does not start on Python 3.8 platform

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1447]
Just tried to start this on my development build, freshly bootstrapped a couple days ago on a Python 3.8 platform:

```
Grey-Area fss :( $ dials.find_spots_server 
Thu Oct  8 06:33:01 2020 Serving 8 processes on port 1701
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/find_spots_server.py", line 337, in <module>
    main(params.nproc, params.port)
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/find_spots_server.py", line 320, in main
    proc.start()
  File "/Users/graeme/svn/cctbx/conda_base/python.app/Contents/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/graeme/svn/cctbx/conda_base/python.app/Contents/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/graeme/svn/cctbx/conda_base/python.app/Contents/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/graeme/svn/cctbx/conda_base/python.app/Contents/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/graeme/svn/cctbx/conda_base/python.app/Contents/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/graeme/svn/cctbx/conda_base/python.app/Contents/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/graeme/svn/cctbx/conda_base/python.app/Contents/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread.lock' object
```

Computer say nope

**Comment by rjgildea** [comment]
Not actually fixed, according to https://github.com/dials/dials/commit/1dbf32450765e3f97ac5370c9df5aa4a0cc6a773

**Comment by Anthchirp** [comment]
The test isn't. Whether that is the same as this issue - 🤷
