### ISSUE TITLE
image_viewer prints exception when closing with ring tool open

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#1467]
1. Open Image viewer
2. Open ring tool
3. Close main window

```
Exception ignored in: <function RingSettingsPanel.__del__ at 0x1457395e0>
Traceback (most recent call last):
  File "/Users/nickd/dials/dist/modules/dials/util/image_viewer/slip_viewer/ring_frame.py", line 144, in __del__
    self._pyslip.DeleteLayer(self._ring_layer)
  File "/Users/nickd/dials/dist/modules/dials/util/image_viewer/slip_viewer/pyslip.py", line 1549, in DeleteLayer
    self.Update()
  File "/Users/nickd/dials/dist/modules/dials/util/image_viewer/slip_viewer/pyslip.py", line 167, in Update
    dc = wx.BufferedDC(wx.ClientDC(self), self.buffer)
RuntimeError: wrapped C/C++ object of type PySlip has been deleted
```

**Comment by biochem-fan** [comment]
This happens with other overlays as well, e.g. circle and rectangles from the masking tool.
