### ISSUE TITLE
Reflection files generated with release can't be read by dials/latest

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#1503]
```
$ module load dials
$ xia2 image=$(dials.data get -q x4wide)/X4_wide_M1S4_2_0001.cbf:1:20
Environment configuration...
Python => /dls_sw/apps/dials/dials-v3-2-1/build/../conda_base/bin/python3.8
CCTBX => /dls_sw/apps/dials/dials-v3-2-1/modules
CCP4 => /dls_sw/apps/ccp4/7.1.008/ccp4-7.1
CCP4_SCR => /tmp/tmp3cp7cs9o
Starting directory: /dls/tmp/rjgildea/tst
Working directory: /dls/tmp/rjgildea/tst
Free space:        4799.91 GB
Host: cs05r-sc-serv-08
Contact: xia2.support@gmail.com
XIA2 0.7.107-g95bc1153-dials-3.2
DIALS 3.2.1-gcf2f28512-release
CCP4 7.1.008
...
```
The same version of dials can read back in the output files OK:
```
$ dials.export DataFiles/AUTOMATIC_DEFAULT_NATIVE_SWEEP1.{expt,refl}
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 3.2.1-gcf2f28512-release
The following parameters have been modified:

input {
  experiments = DataFiles/AUTOMATIC_DEFAULT_NATIVE_SWEEP1.expt
  reflections = DataFiles/AUTOMATIC_DEFAULT_NATIVE_SWEEP1.refl
}
```
However:
```
$ module load dials/latest
$ dials.export DataFiles/AUTOMATIC_DEFAULT_NATIVE_SWEEP1.{expt,refl}
Sorry: Unable to handle the following arguments:
  "DataFiles/AUTOMATIC_DEFAULT_NATIVE_SWEEP1.refl" failed during ExperimentList processing:
    Traceback (most recent call last):
      File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20201118/modules/dials/util/options.py", line 311, in try_read_experiments
        argument, check_format=check_format
      File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20201118/modules/dxtbx/model/experiment_list.py", line 702, in from_json_file
        infile.read(), check_format=check_format, directory=directory
      File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20201118/build/../conda_base/lib/python3.7/codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

  "DataFiles/AUTOMATIC_DEFAULT_NATIVE_SWEEP1.refl" failed during Reflections processing:
    Traceback (most recent call last):
      File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20201118/modules/dials/array_family/flex_ext.py", line 231, in from_file
        filename
      File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20201118/modules/dials/array_family/flex_ext.py", line 212, in from_msgpack_file
        infile.read()
    RuntimeError: dials Error: /scratch/jenkins_agent/workspace/dials_package_linux_conda3/build_dials/modules/dials/array_family/reflection_table_msgpack_adapter.h(719): dials::af::reflection_table: msgpack type is not an array
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20201118/modules/dials/util/options.py", line 341, in try_read_reflections
        data=flex.reflection_table.from_file(argument),
      File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20201118/modules/dials/array_family/flex_ext.py", line 234, in from_file
        return dials_array_family_flex_ext.reflection_table.from_pickle(filename)
      File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20201118/modules/dials/array_family/flex_ext.py", line 188, in from_pickle
        result = pickle.load(infile, encoding="bytes")
    ValueError: unsupported pickle protocol: 5

**Comment by ndevenish** [comment]
`module load dials` is running python 3.8, whereas `module load dials/latest` is 3.7. It's saving in a newer pickle format - looks like 3.8 introduced v5 - https://docs.python.org/3/whatsnew/3.8.html#pickle-protocol-5-with-out-of-band-data-buffers

**Comment by ndevenish** [comment]
So, fixing this on internal diamond infrastructure - the overnight builds should do it.

Do we consider this a wider problem than that?
