### ISSUE TITLE
Image viewer error during opening the file with MultiBlockSlice

### ISSUE THREAD

**Issue by kirienko** [dials/dials#1517]
I have a valid NeXus file (it means it passes validation with `nxvalidate`), and this file contains [Mutli-Block Selections](https://docs.h5py.org/en/stable/high/dataset.html#multi-block-selection). I suppose that's the reason why I have the following error message from the Image Viewer:
```
Traceback (most recent call last):
  File "/gpfs/exfel/data/scratch/nexus/new_dials/build/../modules/dials/command_line/image_viewer.py", line 207, in <module>
    run()
  File "/gpfs/exfel/data/scratch/nexus/new_dials/build/../conda_base/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/gpfs/exfel/data/scratch/nexus/new_dials/build/../modules/dials/command_line/image_viewer.py", line 203, in run
    show_image_viewer(params=params, reflections=reflections, experiments=experiments)
  File "/gpfs/exfel/data/scratch/nexus/new_dials/build/../modules/dials/command_line/image_viewer.py", line 168, in show_image_viewer
    wrapper.display(experiments=experiments, reflections=reflections)
  File "/gpfs/exfel/data/scratch/nexus/new_dials/modules/dials/util/image_viewer/spotfinder_wrap.py", line 83, in display
    self.frame.load_image(chooser_wrapper(imagesets[0], 0))
  File "/gpfs/exfel/data/scratch/nexus/new_dials/modules/dials/util/image_viewer/spotfinder_frame.py", line 552, in load_image
    show_untrusted=show_untrusted,
  File "/gpfs/exfel/data/scratch/nexus/new_dials/modules/dials/util/image_viewer/slip_viewer/frame.py", line 432, in load_image
    and self.settings.image_type == "corrected"
  File "/gpfs/exfel/data/scratch/nexus/new_dials/modules/dials/util/image_viewer/slip_viewer/tile_generation.py", line 294, in set_image
    self.raw_image.set_image_data(get_image_data(self.raw_image))
  File "/gpfs/exfel/data/scratch/nexus/new_dials/modules/dials/util/image_viewer/spotfinder_frame.py", line 849, in get_image_data
    image_data = image.get_image_data()
  File "/gpfs/exfel/data/scratch/nexus/new_dials/modules/dials/util/image_viewer/slip_viewer/frame.py", line 58, in get_image_data
    return self.image_set.get_corrected_data(self.index)
  File "/gpfs/exfel/data/scratch/nexus/new_dials/modules/dxtbx/format/FormatMultiImage.py", line 36, in read
    return format_instance.get_raw_data(index)
  File "/gpfs/exfel/data/scratch/nexus/new_dials/modules/dxtbx/format/FormatNexus.py", line 130, in get_raw_data
    return self._raw_data[index]
  File "/gpfs/exfel/data/scratch/nexus/new_dials/modules/dxtbx/format/nexus.py", line 1248, in __getitem__
    return tuple(itertools.chain.from_iterable(dl[index] for dl in self._datalists))
  File "/gpfs/exfel/data/scratch/nexus/new_dials/modules/dxtbx/format/nexus.py", line 1248, in <genexpr>
    return tuple(itertools.chain.from_iterable(dl[index] for dl in self._datalists))
  File "/gpfs/exfel/data/scratch/nexus/new_dials/modules/dxtbx/format/nexus.py", line 1307, in __getitem__
    data_as_flex = dataset_as_flex(self._datasets[d], tuple(slices))
  File "/gpfs/exfel/data/scratch/nexus/new_dials/modules/dxtbx/format/nexus.py", line 54, in dataset_as_flex
    return dataset_as_flex_float(dataset.id.id, selection)
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dxtbx Internal Error: /gpfs/exfel/data/scratch/nexus/new_dials/modules/dxtbx/format/boost_python/nexus_ext.cc(104): DXTBX_ASSERT(start[i] + count[i] <= dataset_dims[i]) failure.
```
I have no clue yet, what does it mean, but maybe you have any ideas on that?

**Comment by phyy-nx** [comment]
Hi, reviewing [nexusformat.org](https://manual.nexusformat.org/classes/base_classes/NXdata.html), I don't believe these kind of hyperslabs are supported in the spec. `nxvalidate` might not catch this.  Some follow ups:

- Could you elaborate on why you'd like to use this h5 feature?  Is it because of event matching?  If so, is this approach better than virtual datasets?  (I'm assuming hyperslabs are different than VDSs.)
- Supporting this feature may need modifications to the NeXus spec.  Could you open an issue on [nexusformat/definitions](https://github.com/nexusformat/definitions) to discuss hyperslabs?  Perhaps include the background from the previous point?
- If you could upload a small dataset showing the issue somewhere where we can see it, that would help.

Thanks!

**Comment by takluyver** [comment]
To be clear, @kirienko is using a virtual dataset. The hyperslab selection is part of the mapping for the virtual dataset. I'm surprised that this affects code reading it, though: virtual datasets are meant to be transparent to code reading them, so HDF5 should handle all of the details, unless the code in question goes out of its way to do something special for virtual datasets.

**Comment by graeme-winter** [comment]
I've done some fairly extensive processing with virtual data sets and things _worked_ however I would not infer from this that there are no bugs / bits of weirdness. Can you share the file in question? Or something which is the same shape as this?

It is also worth noting that there are a few gremlins in the precise support for NeXus - the various iterations of Eiger NeXus-like data have left the code in a fairly non-optimal state and replacing this is high on our to-do.

**Comment by takluyver** [comment]
@kirienko is going to try to make a smaller example - he can share the file itself easily enough, but I guess it would fall over before this if it can't find the data files which the VDS refers to.

**Comment by dagewa** [comment]
Hey folks, is this still relevant? It looks like we're waiting on a file. If that's not likely to arrive then I think we should close this.

**Comment by takluyver** [comment]
Thanks, I think you can close it for now. I'm not aware of anyone working with DIALS and our data at the moment - which might mean no-one is trying that, or it might mean that someone has got it working.

It's possible this will pop back up one day if the issue still exists and someone runs into it again, but in the meantime I don't think there's anything to do.

**Comment by dagewa** [comment]
Sure, thanks for the reply. Feel free to reopen if this does show up again
