### ISSUE TITLE
dials.predict does not generate enough information for the reciprocal lattice viewer

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#155]
```
dials.reciprocal_lattice_viewer experiments.json predicted.pickle 
The following parameters have been modified:

input {
  experiments = experiments.json
  reflections = predicted.pickle
}

RuntimeError: dials Error: Could not find "xyzobs.px.value" in table
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 619, in <module>
    run(sys.argv[1:])
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 610, in run
    f.load_models(imagesets, reflections)
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 211, in load_models
    render_3d.load_models(self, imagesets, reflections)
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 89, in load_models
    self.map_points_to_reciprocal_space()
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 113, in map_points_to_reciprocal_space
    imageset.get_detector(), imageset.get_scan())
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/indexing/indexer.py", line 1020, in map_spots_pixel_to_mm_rad
    spots_panel['xyzobs.px.value'],
RuntimeError: dials Error: Could not find "xyzobs.px.value" in table
```

should be possible to compute this?

**Comment by graeme-winter** [comment]
From

```
 dials.import ~/data/i04-bag-training-sum/*cbf
 dials.find_spots datablock.json nproc=8
 dials.index datablock.json strong.pickle 
 dials.predict experiments.json 
 dials.reciprocal_lattice_viewer experiments.json predicted.pickle 
```
