### ISSUE TITLE
dials.scale fails with summation integrated data

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1552]
Protocol:

```
dials.find_spots imported.expt nproc=6
dials.index imported.expt strong.refl 
dials.refine indexed.*
dials.integrate refined.* nproc=6 profile.fitting=0
dials.symmetry integrated.*
dials.scale symmetrized.*
```

Giveth:

```
Reflections below a partiality_cutoff of 0.4 are not considered for any
part of the scaling analysis or for the reporting of merging statistics.
Additionally, if applicable, only reflections with a min_partiality > 0.95
were considered for use when refining the scaling model.

Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/scaling/algorithm.py", line 210, in run
    self.scale()
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/scaling/algorithm.py", line 254, in scale
    self.scaler = scaling_algorithm(self.scaler)
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/scaling/algorithm.py", line 556, in scaling_algorithm
    do_intensity_combination(scaler, reselect=True)
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/scaling/algorithm.py", line 525, in do_intensity_combination
    scaler.combine_intensities()
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/scaling/scaler.py", line 514, in combine_intensities
    self._combine_intensities()
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/scaling/scaler.py", line 535, in _combine_intensities
    intensity, variance = combiner.calculate_suitable_combined_intensities()
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/scaling/combine_intensities.py", line 141, in calculate_suitable_combined_intensities
    return _calculate_suitable_combined_intensities(self.scaler, self.max_key)
AttributeError: 'SingleDatasetIntensityCombiner' object has no attribute 'scaler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/scale.py", line 261, in <module>
    run()
  File "/Users/graeme/svn/cctbx/conda_base/python.app/Contents/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/scale.py", line 234, in run
    scaled_experiments, joint_table = run_scaling(params, experiments, reflections)
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/scale.py", line 195, in run_scaling
    algorithm.run()
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/scaling/algorithm.py", line 231, in run
    logger.info("%s%s%s", "\n", "=" * 80, "\n")
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/scaling/observers.py", line 190, in __exit__
    _make_scaling_html(self.script)
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/scaling/observers.py", line 207, in _make_scaling_html
    data.update(make_merging_stats_plots(scaling_script))
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/scaling/observers.py", line 391, in make_merging_stats_plots
    ) = reflection_tables_to_batch_dependent_properties(  # pylint: disable=unbalanced-tuple-unpacking
  File "/Users/graeme/svn/cctbx/modules/dials/report/analysis.py", line 88, in reflection_tables_to_batch_dependent_properties
    scaled_array = scaled_data_as_miller_array(reflection_tables, experiments)
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/scaling/scaling_library.py", line 330, in scaled_data_as_miller_array
    data=joint_table["intensity.scale.value"] / joint_table["inverse_scale_factor"],
KeyError: "Please report this error to dials-support@lists.sourceforge.net: Unknown column 'intensity.scale.value'"
```

Humbly suggest this is undesirable behaviour: if input contains no profile fitted data kindly do not crash 😉

**Comment by graeme-winter** [comment]
Obviously 

```
dials.scale symmetrized.* intensity_choice=sum
```

works -> should probably select this by default if no profile fitted intensities in input
