### ISSUE TITLE
precommit on Windows is unhappy

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1585]
Attempt to commit with git on Windows. Ultimately it worked, but there were errors on the way...
```
C:\Users\fcx32934\sw\cctbx\modules\dxtbx>git commit
.git/hooks/pre-commit: line 10: C:Usersfcx32934swcctbxconda_baseetcprofile.dconda.sh: No such file or directory

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If using 'conda activate' from a batch script, change your
invocation to 'CALL conda.bat activate'.

To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - cmd.exe
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


[INFO] Initializing environment for https://github.com/PyCQA/isort.git.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/PyCQA/flake8.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for https://github.com/PyCQA/isort.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing C:\Users\fcx32934\sw\cctbx\modules\dxtbx\datablock.py
Fixing C:\Users\fcx32934\sw\cctbx\modules\dxtbx\format\Registry.py
Fixing C:\Users\fcx32934\sw\cctbx\modules\dxtbx\util\__init__.py
Fixing C:\Users\fcx32934\sw\cctbx\modules\dxtbx\format\Format.py
Fixing C:\Users\fcx32934\sw\cctbx\modules\dxtbx\model\experiment_list.py
Fixing C:\Users\fcx32934\sw\cctbx\modules\dxtbx\tests\test_regression_images.py

black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "C:\Users\fcx32934\sw\cctbx\conda_base\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\fcx32934\sw\cctbx\conda_base\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\fcx32934\sw\cctbx\modules\dxtbx\Usersfcx32934swcctbxconda_base\.precommit\repo4n3rgbrf\py_env-python3\Scripts\black.EXE\__main__.py", line 4, in <module>
  File "c:\users\fcx32934\sw\cctbx\modules\dxtbx\usersfcx32934swcctbxconda_base\.precommit\repo4n3rgbrf\py_env-python3\lib\site-packages\black\__init__.py", line 17, in <module>
    import regex as re
  File "c:\users\fcx32934\sw\cctbx\modules\dxtbx\usersfcx32934swcctbxconda_base\.precommit\repo4n3rgbrf\py_env-python3\lib\site-packages\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "c:\users\fcx32934\sw\cctbx\modules\dxtbx\usersfcx32934swcctbxconda_base\.precommit\repo4n3rgbrf\py_env-python3\lib\site-packages\regex\regex.py", line 419, in <module>
    import regex._regex_core as _regex_core
  File "c:\users\fcx32934\sw\cctbx\modules\dxtbx\usersfcx32934swcctbxconda_base\.precommit\repo4n3rgbrf\py_env-python3\lib\site-packages\regex\_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'

flake8...................................................................Failed
- hook id: flake8
- exit code: 1

util/__init__.py:72:58: W292 no newline at end of file

Check python ast.........................................................Passed
Check Yaml...........................................(no files to check)Skipped
Check for merge conflicts................................................Passed
Check for added large files..............................................Passed
Don't commit to master directly..........................................Passed

C:\Users\fcx32934\sw\cctbx\modules\dxtbx>
```

**Comment by dagewa** [comment]
Attempt to commit with git on Windows. Ultimately it worked, but there were errors on the way...
```
C:\Users\fcx32934\sw\cctbx\modules\dxtbx>git commit
.git/hooks/pre-commit: line 10: C:Usersfcx32934swcctbxconda_baseetcprofile.dconda.sh: No such file or directory

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If using 'conda activate' from a batch script, change your
invocation to 'CALL conda.bat activate'.

To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - cmd.exe
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


[INFO] Initializing environment for https://github.com/PyCQA/isort.git.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/PyCQA/flake8.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for https://github.com/PyCQA/isort.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing C:\Users\fcx32934\sw\cctbx\modules\dxtbx\datablock.py
Fixing C:\Users\fcx32934\sw\cctbx\modules\dxtbx\format\Registry.py
Fixing C:\Users\fcx32934\sw\cctbx\modules\dxtbx\util\__init__.py
Fixing C:\Users\fcx32934\sw\cctbx\modules\dxtbx\format\Format.py
Fixing C:\Users\fcx32934\sw\cctbx\modules\dxtbx\model\experiment_list.py
Fixing C:\Users\fcx32934\sw\cctbx\modules\dxtbx\tests\test_regression_images.py

black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "C:\Users\fcx32934\sw\cctbx\conda_base\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\fcx32934\sw\cctbx\conda_base\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\fcx32934\sw\cctbx\modules\dxtbx\Usersfcx32934swcctbxconda_base\.precommit\repo4n3rgbrf\py_env-python3\Scripts\black.EXE\__main__.py", line 4, in <module>
  File "c:\users\fcx32934\sw\cctbx\modules\dxtbx\usersfcx32934swcctbxconda_base\.precommit\repo4n3rgbrf\py_env-python3\lib\site-packages\black\__init__.py", line 17, in <module>
    import regex as re
  File "c:\users\fcx32934\sw\cctbx\modules\dxtbx\usersfcx32934swcctbxconda_base\.precommit\repo4n3rgbrf\py_env-python3\lib\site-packages\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "c:\users\fcx32934\sw\cctbx\modules\dxtbx\usersfcx32934swcctbxconda_base\.precommit\repo4n3rgbrf\py_env-python3\lib\site-packages\regex\regex.py", line 419, in <module>
    import regex._regex_core as _regex_core
  File "c:\users\fcx32934\sw\cctbx\modules\dxtbx\usersfcx32934swcctbxconda_base\.precommit\repo4n3rgbrf\py_env-python3\lib\site-packages\regex\_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'

flake8...................................................................Failed
- hook id: flake8
- exit code: 1

util/__init__.py:72:58: W292 no newline at end of file

Check python ast.........................................................Passed
Check Yaml...........................................(no files to check)Skipped
Check for merge conflicts................................................Passed
Check for added large files..............................................Passed
Don't commit to master directly..........................................Passed

C:\Users\fcx32934\sw\cctbx\modules\dxtbx>
```

**Comment by ndevenish** [comment]
```
ModuleNotFoundError: No module named 'regex._regex'
```
Is a stubbornly persistent packaging-related issue. _something_ is caching an old version of `regex` which black uses. This bug was fixed in 2019 but for some reason the packaging stuff keeps hitting it https://github.com/psf/black/issues/1207

**Comment by Anthchirp** [comment]
There is no Windows support in `libtbx.precommit`. In fact I'm rather surprised you got that far.

**Comment by dagewa** [comment]
It looks like it _almost_ works. I may be able to muddle through with changes to the `precommitbx_template` function. Whether it is worth it though :man_shrugging:

**Comment by ndevenish** [comment]
This black issue specifically was solved by a black version update. Also, we don't use black any more.
