### ISSUE TITLE
dials.import: import on subset of grid scan fails

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1592]
```

cs04r-sc-com99-25 vmxi-thau-grid-example-76xx :( $ dials.import mask=pixels.mask image_range=7600,7700 $(cat ../vmxi-thau-grid-example/imported_data.txt)
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 3.3.2-g209f02519-release
The following parameters have been modified:

input {
  experiments = <image files>
}
geometry {
  scan {
    image_range = 7600 7700
  }
}
lookup {
  mask = "pixels.mask"
}


Applying input geometry in the following order:
  1. Manual geometry

Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v3-3-2/build/../modules/dials/command_line/dials_import.py", line 933, in <module>
    run()
  File "/dls_sw/apps/dials/dials-v3-3-2/conda_base/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/dls_sw/apps/dials/dials-v3-3-2/build/../modules/dials/command_line/dials_import.py", line 929, in run
    script.run(args)
  File "/dls_sw/apps/dials/dials-v3-3-2/build/../modules/dials/command_line/dials_import.py", line 790, in run
    experiments = metadata_updater(imageset_importer())
  File "/dls_sw/apps/dials/dials-v3-3-2/build/../modules/dials/command_line/dials_import.py", line 555, in __call__
    subset = imageset[j : j + 1]
  File "/dls_sw/apps/dials/dials-v3-3-2/modules/dxtbx/imageset.py", line 279, in __getitem__
    return self.partial_set(start - offset, stop - offset)
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dxtbx Internal Error: /scratch/jenkins_agent/workspace/dials_release_build_linux/build_dials/modules/dxtbx/imageset.h(932): DXTBX_ASSERT(index < indices_.size()) failure.
```

Feels like this should work...

**Comment by graeme-winter** [comment]
Additional: without the `image_range=` this worked fine.

**Comment by graeme-winter** [comment]
Looking at the code I am certain that this _used_ to work... 🤔

**Comment by graeme-winter** [comment]
> Looking at the code I am certain that this _used_ to work... 🤔

I think this is statement was false
