### ISSUE TITLE
dials.integrate (dials 3.3.2) MemoryError issue

### ISSUE THREAD

**Issue by TH-Chang** [dials/dials#1615]
Dear dials team,

The data processing was terminated at the step of dials.integrate due to the “MemoryError”. When I reduce nproc from 10 to 5, the program can run. But, it seems it will run forever.

In addition, the error message shows "shoebox size is 47 x 48 pixels x 58 images "; however, the mosaic spread is estimated to be 0.02 < 0.16 < 0.26 by using FastDP.

I paste the key error message below and I enclose a INTEGRATE.log file.

Any suggestions would be greatly appreciated. Thank you.

Best wishes,
Tao-Hsin

[FMX_H4_E5_A1_SAD_SWEEP1_INTEGRATE.log](https://github.com/dials/dials/files/6073205/FMX_H4_E5_A1_SAD_SWEEP1_INTEGRATE.log)

Integrating reflections

 Split 86973 reflections overlapping job boundaries

Memory situation report:
  Available system memory (excluding swap)          :252.1 GB
  Available swap memory                             : 34.4 GB
  Available system memory (including swap)          :286.4 GB
  Maximum memory for processing (including swap)    :257.8 GB
  Maximum memory for processing (excluding swap)    :226.9 GB
  Memory required per process                       :280.0 GB
  no memory ulimit set

Traceback (most recent call last):
  File "/home/sbgrid/programs/x86_64-linux/dials/3.3.2/dials-v3-3-2/build/../modules/dials/command_line/integrate.py", line 715, in <module>
    run()
  File "/home/sbgrid/programs/x86_64-linux/dials/3.3.2/dials-v3-3-2/conda_base/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/sbgrid/programs/x86_64-linux/dials/3.3.2/dials-v3-3-2/build/../modules/dials/command_line/integrate.py", line 693, in run
    experiments, reflections, report = run_integration(
  File "/home/sbgrid/programs/x86_64-linux/dials/3.3.2/dials-v3-3-2/build/../modules/dials/command_line/integrate.py", line 567, in run_integration
    reflections = integrator.integrate()
  File "/home/sbgrid/programs/x86_64-linux/dials/3.3.2/dials-v3-3-2/modules/dials/algorithms/integration/integrator.py", line 1176, in integrate
    self.reflections, _, time_info = processor.process()
  File "/home/sbgrid/programs/x86_64-linux/dials/3.3.2/dials-v3-3-2/modules/dials/algorithms/integration/processor.py", line 259, in process
    self.manager.initialize()
  File "/home/sbgrid/programs/x86_64-linux/dials/3.3.2/dials-v3-3-2/modules/dials/algorithms/integration/processor.py", line 573, in initialize
    self.compute_processors()
  File "/home/sbgrid/programs/x86_64-linux/dials/3.3.2/dials-v3-3-2/modules/dials/algorithms/integration/processor.py", line 896, in compute_processors
    raise MemoryError(
MemoryError: Please report this error to dials-support@lists.sourceforge.net: 
          Not enough memory to run integration jobs.  This could be caused by a
          highly mosaic crystal model.  Possible solutions include increasing the
          percentage of memory allowed for shoeboxes or decreasing the block size.
          The average shoebox size is 47 x 48 pixels x 58 images - is your crystal
          really this mosaic?

**Comment by dagewa** [comment]
Related: #659

**Comment by dagewa** [comment]
We're not going to forget this is a problem. Closed as duplicate
