### ISSUE TITLE
dials.integrate crash in prediction step

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#165]
```
Initialising

Processing reference reflections
 read 1215 strong spots
 removing 792 unindexed reflections
 removing 240 reflections marked as centroid outliers
 using 552 indexed reflections
 found 663 junk reflections
 time taken: 0.00122094


================================================================================

Predicting reflections

Prediction type: scan varying prediction
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-dev20160613/build/../modules/dials/command_line/integrate.py", line 498, in <module>
    halraiser(e)
  File "/dls_sw/apps/dials/dials-dev20160613/build/../modules/dials/command_line/integrate.py", line 496, in <module>
    script.run()
  File "/dls_sw/apps/dials/dials-dev20160613/build/../modules/dials/command_line/integrate.py", line 240, in run
    force_static=params.prediction.force_static)
  File "/dls_sw/apps/dials/dials-dev20160613/modules/dials/array_family/flex.py", line 138, in from_predictions_multi
    force_static=force_static)
  File "/dls_sw/apps/dials/dials-dev20160613/modules/dials/array_family/flex.py", line 111, in from_predictions
    return predict()
  File "/dls_sw/apps/dials/dials-dev20160613/modules/dials/algorithms/spot_prediction/reflection_predictor.py", line 125, in __call__
    table = self._predict()
  File "/dls_sw/apps/dials/dials-dev20160613/modules/dials/algorithms/spot_prediction/reflection_predictor.py", line 75, in __call__
    result = self.func()
  File "/dls_sw/apps/dials/dials-dev20160613/modules/dials/algorithms/spot_prediction/reflection_predictor.py", line 96, in <lambda>
    lambda: predictor.for_ub(flex.mat3_double(A)))
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dials Internal Error: /scratch/jenkins_slave/workspace/dials_package_linux/build_dials/modules/dials/algorithms/spot_prediction/reeke_index_generator.h(422): DIALS_ASSERT(sin_theta <= 1.0 && sin_theta >= -1.0) failure.
```

**Comment by dagewa** [comment]
Prediction is requested to d_min of 0.7, but the wavelength is 1.4879. I'll try to find the right place in spot prediction code to add a sanity check that will crash out sooner with a useful message.
