### ISSUE TITLE
dials.scale crash when merging stats bin has no reflections

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1683]
A user reports a crash in `dials.scale` when trying to scale a narrow wedge of data from a small molecule crystal:
```
            ----------Merging statistics by resolution bin----------           

 d_max  d_min   #obs  #uniq   mult.  %comp       <I>  <I/sI>    r_mrg   r_meas    r_pim   r_anom   cc1/2   cc_ano
  6.36   1.87     22     12    1.83  19.35    4441.0    59.6    0.112    0.158    0.112    0.122   0.723*   0.000
  1.87   1.49     17      9    1.89  15.25    3222.5    52.2    0.240    0.339    0.240    0.236  -0.335   0.000
  1.49   1.31      7      4    1.75  12.50    2097.8    48.2    0.147    0.208    0.147    0.308  -0.584   0.000
  1.31   1.19     13      7    1.86  12.73    1899.8    45.7    0.180    0.254    0.180    0.493   0.189   0.000
  1.19   1.10      7      4    1.75   7.27    2553.3    37.3    0.256    0.362    0.256    0.619   0.975   0.000
  1.10   1.04     10      5    2.00  15.15    1976.9    41.7    0.205    0.290    0.205    0.598   0.253   0.000
  1.04   0.99      7      4    1.75  11.76    1312.0    32.4    0.121    0.171    0.121    0.250   0.961   0.000
  0.99   0.94      3      2    1.50   3.77    1714.2    31.7    0.270    0.382    0.270    0.628   0.000   0.000
  0.94   0.91      9      6    1.50  10.17     816.1    24.9    0.415    0.587    0.415    1.142  -0.564   0.000
  0.91   0.88      2      1    2.00   3.12     370.5    20.5    0.438    0.619    0.438    1.224   0.000   0.000
  0.88   0.85      3      2    1.50   3.92      53.1     3.8    0.999    1.413    0.999   2149.508   0.000   0.000
  0.85   0.83      4      2    2.00   5.41     648.3    20.0    0.402    0.568    0.402    1.157   1.000   0.000
  0.83   0.80      0      0    0.00   0.00       0.0     0.0     None     None     None     0.000   0.000
  0.80   0.78      2      1    2.00   4.76     333.8    14.5    0.093    0.131    0.093    0.197   0.000   0.000
  0.78   0.77      1      1    1.00   3.12     136.2     8.7    0.000    0.000    0.000     0.000   0.000
  0.77   0.75      0      0    0.00   0.00       0.0     0.0     None     None     None     0.000   0.000
  0.75   0.73      1      1    1.00   2.63     380.8     4.7    0.000    0.000    0.000     0.000   0.000
  0.73   0.72      0      0    0.00   0.00       0.0     0.0     None     None     None     0.000   0.000
  0.72   0.71      0      0    0.00   0.00       0.0     0.0     None     None     None     0.000   0.000
  0.71   0.70      1      1    1.00   2.44      90.9     5.2    0.000    0.000    0.000     0.000   0.000
  6.36   0.70    109     62    1.76   5.60    2264.0    40.3    0.290    0.411    0.290    0.817  -0.021   0.000


Writing html report to dials.scale.html
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/scale.py", line 258, in <module>
    run()
  File "/home/fcx32934/sw/cctbx/conda_base/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/scale.py", line 231, in run
    scaled_experiments, joint_table = run_scaling(params, experiments, reflections)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/scale.py", line 192, in run_scaling
    algorithm.run()
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/scaling/algorithm.py", line 230, in run
    logger.info("%s%s%s", "\n", "=" * 80, "\n")
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/scaling/observers.py", line 90, in __exit__
    print_scaling_summary(self.script)
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/scaling/observers.py", line 152, in print_scaling_summary
    d_min = resolution_cc_half(stats, limit=0.3).d_min
  File "/home/fcx32934/sw/cctbx/modules/dials/util/resolution_analysis.py", line 258, in resolution_cc_half
    critical_values = _get_cc_half_critical_values(merging_stats, cc_half_method)
  File "/home/fcx32934/sw/cctbx/modules/dials/util/resolution_analysis.py", line 227, in _get_cc_half_critical_values
    return flex.double(
TypeError: Please report this error to dials-support@lists.sourceforge.net: No registered converter was able to produce a C++ rvalue of type double from this Python object of type NoneType
```

The issue is that some of the merging stats bins have zero reflections and the CC1/2 critical value is then `None`:
```
In [1]: [(b.cc_one_half_critical_value, b.n_obs) for b in merging_stats.bins]
Out[1]: 
[(0.7154592459862855, 22),
 (0.7887203128984536, 17),
 (0.9995065603657316, 7),
 (0.8821937284436094, 13),
 (0.9995065603657316, 7),
 (0.9343329933968081, 10),
 (0.9995065603657316, 7),
 (0, 3),
 (0.9995065603657316, 9),
 (0, 2),
 (0, 3),
 (0, 4),
 (None, 0),
 (0, 2),
 (0, 1),
 (None, 0),
 (0, 1),
 (None, 0),
 (None, 0),
 (0, 1)]
```

It may not be reasonable to run scaling on this single small wedge, but perhaps it should not crash like this.

**Comment by dagewa** [comment]
`merging.nbins=5` is one way to get through without crashing

**Comment by jbeilstenedmands** [comment]
Tested and this now no longer crashes, so closing.
To verify, take a thin slice of rotation data and up number the merging bins e.g. `dials.scale scaled.{expt,refl} exclude_images=10:100000 merging.nbins=1000`
