### ISSUE TITLE
dials profile model determination fails for some single image scans

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#169]
```
dials.import /dls/tmp/for_richard/th_8_1_000*.cbf allow_multiple_sweeps=True
dials.find_spots datablock.json 
dials.index datablock.json strong.pickle space_group=P422
dials.integrate experiments.json indexed.pickle profile.fitting=False
```
Gives the following error:
```
DIALS 1.dev.422-g0a39eef
The following parameters have been modified:

integration {
  profile {
    fitting = False
  }
}
input {
  experiments = experiments.json
  reflections = indexed.pickle
}

================================================================================

Initialising

Processing reference reflections
 read 8601 strong spots
 removing 8377 unindexed reflections
 removing 1314 reflections marked as centroid outliers
 using 7063 indexed reflections
 found 1538 junk reflections
 time taken: 0.00492692


================================================================================

Predicting reflections

Prediction type: scan static prediction
Predicted 2330 reflections
Prediction type: scan static prediction
Predicted 2314 reflections
Prediction type: scan static prediction
Predicted 2288 reflections
Matching reference spots with predicted reflections
 7063 observed reflections input
 6932 reflections predicted
 4840 reflections matched
 4840 reflections accepted

********************************************************************************
Warning: 2223 reference spots were not matched to predictions
********************************************************************************

Calculating E.S.D Beam Divergence.
Calculating E.S.D Reflecting Range.
Traceback (most recent call last):
  File "/home/hko55533/software/cctbx/build/../modules/dials/command_line/integrate.py", line 498, in <module>
    halraiser(e)
  File "/home/hko55533/software/cctbx/build/../modules/dials/command_line/integrate.py", line 496, in <module>
    script.run()
  File "/home/hko55533/software/cctbx/build/../modules/dials/command_line/integrate.py", line 269, in run
    experiments = ProfileModelFactory.create(params, experiments, reference)
  File "/home/hko55533/software/cctbx/modules/dials/algorithms/profile_model/factory.py", line 55, in create
    expr.scan)
  File "/home/hko55533/software/cctbx/modules/dials/algorithms/profile_model/gaussian_rs/model.py", line 239, in create
    params.gaussian_rs.filter.min_zeta)
  File "/home/hko55533/software/cctbx/modules/dials/algorithms/profile_model/gaussian_rs/calculator.py", line 294, in __init__
    goniometer, scan, reflections)
  File "/home/hko55533/software/cctbx/modules/dials/algorithms/profile_model/gaussian_rs/calculator.py", line 240, in __init__
    crystal, beam, detector, goniometer, scan, reflections)
  File "/home/hko55533/software/cctbx/modules/dials/algorithms/profile_model/gaussian_rs/calculator.py", line 219, in __init__
    tolerance=1e-7)
  File "/home/hko55533/software/cctbx/modules/cctbx_project/scitbx/simplex.py", line 54, in __init__
    self.optimize()
  File "/home/hko55533/software/cctbx/modules/cctbx_project/scitbx/simplex.py", line 84, in optimize
    self.explore()
  File "/home/hko55533/software/cctbx/modules/cctbx_project/scitbx/simplex.py", line 102, in explore
    self.FindReflectionPt()
  File "/home/hko55533/software/cctbx/modules/cctbx_project/scitbx/simplex.py", line 159, in FindReflectionPt
    self.reflectionPtValue=self.function(self.reflectionPt)
  File "/home/hko55533/software/cctbx/modules/cctbx_project/scitbx/simplex.py", line 193, in function
    return self.evaluator.target( point )
  File "/home/hko55533/software/cctbx/modules/dials/algorithms/profile_model/gaussian_rs/calculator.py", line 228, in target
    return -flex.sum(self._R(exp(log_sigma[0])))
  File "/home/hko55533/software/cctbx/modules/dials/algorithms/profile_model/gaussian_rs/calculator.py", line 158, in __call__
    assert(sigma_m > TINY)
AssertionError: Please report this error to dials-support@lists.sourceforge.net:

```

**Comment by rjgildea** [comment]
See also 6e40dc64849c846165f5ca47f86dbc0e703f3f9e

**Comment by jmp1985** [comment]
So, I think the problem comes down to the fact that for single images, the distribution of (\phi_{image} - \phi_{reflection}) no longer resembles anything like a normal distribution. Look at th_8_2 (sweep) and th_8_1 (single image) below. I guess I'll have to think about how to fix this but it's not a small change (I've tried messing around with it a bit). 

![th_8_2](https://cloud.githubusercontent.com/assets/2241889/16731319/5707aab2-476f-11e6-8421-a30e9eed7fdf.png)
![th_8_1](https://cloud.githubusercontent.com/assets/2241889/16731321/58a6d30c-476f-11e6-9ef3-63a584852623.png)
