### ISSUE TITLE
Integrating > 1 experiment ends in stack trace

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#174]
Following up from Luca Jovine comment:

Small molecule data set, find spots on 4 sweeps, index, run dials.integrate get:

```
================================================================================

Modelling reflection profiles

Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/integrate.py", line 498, in <module>
    halraiser(e)
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/integrate.py", line 496, in <module>
    script.run()
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/integrate.py", line 285, in run
    reflections = integrator.integrate()
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/integration/integrator.py", line 987, in integrate
    reference, profile_fitter_list, time_info = processor.process()
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/integration/processor.py", line 208, in process
    self.manager.initialize()
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/integration/processor.py", line 541, in initialize
    self.compute_jobs()
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/integration/processor.py", line 706, in compute_jobs
    self.jobs.add((i0, i1), array_range, block_size_frames)
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dials Internal Error: /Users/graeme/svn/cctbx/modules/dials/algorithms/integration/integrator.h(97): DIALS_ASSERT(index[0] == groups_[groups_.size()-1].expr()[1]) failure.
```

If this is expected behaviour please check that len(experiments) == 1 at the start of processing & produce more helpful error, otherwise we should make this work

**Comment by rjgildea** [comment]
Multiple experiments is not in itself a problem (e.g. multiple lattices on same imageset), probably more likely multiple scans/imagesets is the issue.

**Comment by jmp1985** [comment]
So I thought I added the ability to do multiple sweeps. Where can I get access to the data?

**Comment by graeme-winter** [comment]
It’s referenced as the small molecule example in the paper, I will pass over location of data @ diamond in a mo

**Comment by graeme-winter** [comment]
scp -r l-cyst.tar.gz gw56@nx-staff:/dls/tmp/gw56

**Comment by graeme-winter** [comment]
```
       DIALS_ASSERT(index[1] > index[0]);
       if (groups_.size() > 0) {
         DIALS_ASSERT(expr[0] == groups_[groups_.size()-1].expr()[1]);
-        DIALS_ASSERT(index[0] == groups_[groups_.size()-1].expr()[1]);
+        DIALS_ASSERT(index[0] == groups_[groups_.size()-1].index()[1]);
       } else {
         DIALS_ASSERT(expr[0] == 0);
       }
```

@jmp1985 is this correct?
