### ISSUE TITLE
What can you do with `dials.integrate` reference profile output ?

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1745]
Reference profiles can be created by `dials.integrate` like this:
```
dials.integrate refined.{expt,refl} debug.reference.output=True
```

But this file does not load as a reflection table

```
>>> from dials.array_family import flex
>>> rt=flex.reflection_table.from_file("reference_profiles.refl")
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/modules/dials/array_family/flex_ext.py", line 228, in from_file
    return dials_array_family_flex_ext.reflection_table.from_msgpack_file(
  File "/home/fcx32934/sw/cctbx/modules/dials/array_family/flex_ext.py", line 209, in from_msgpack_file
    return dials_array_family_flex_ext.reflection_table.from_msgpack(
RuntimeError: dials Error: /home/fcx32934/sw/cctbx/modules/dials/array_family/reflection_table_msgpack_adapter.h(719): dials::af::reflection_table: msgpack type is not an array

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fcx32934/sw/cctbx/modules/dials/array_family/flex_ext.py", line 232, in from_file
    return dials_array_family_flex_ext.reflection_table.from_pickle(filename)
  File "/home/fcx32934/sw/cctbx/modules/dials/array_family/flex_ext.py", line 189, in from_pickle
    assert isinstance(result, dials_array_family_flex_ext.reflection_table)
AssertionError

```

although it seems to want to be one:
```
$ strings reference_profiles.refl | head
scitbx_array_family_flex_ext
double
grid
'S" 
?'[:?8
j	Gim
H-Dd
 7) 
W$j4
[lV5
```

**Comment by dagewa** [comment]
Right, it's a pickled list.

https://github.com/dials/dials/blob/bb555992211d689ef86e3b581d1ed97edbe94e4f/algorithms/integration/integrator.py#L1080-L1091
