### ISSUE TITLE
dials.import  fails for single image Eiger data sets

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#177]
```
[gw56@cs03r-sc-serv-16 dials-bugs]$ dials.import ref-thaumatin_1_1_master.h5
DIALS 1.dev.521-gb352022
Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/import.py", line 906, in <module>
    halraiser(e)
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/import.py", line 904, in <module>
    script.run()
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/import.py", line 780, in run
    params, options = self.parser.parse_args(show_diff_phil=False)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/options.py", line 723, in parse_args
    quick_parse=quick_parse)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/options.py", line 462, in parse_args
    scan_tolerance=scan_tolerance)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/options.py", line 169, in __init__
    scan_tolerance)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/options.py", line 223, in try_read_datablocks_from_images
    scan_tolerance=scan_tolerance)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 830, in from_filenames
    scan_tolerance=None)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 453, in __init__
    imageset = self._create_single_file_imageset(fmt, filename)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 608, in _create_single_file_imageset
    format_instance = format_class(filename)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/format/FormatHDFEigerNearlyNexus.py", line 264, in __init__
    FormatHDF5.__init__(self, image_file)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/format/FormatHDF5.py", line 14, in __init__
    Format.__init__(self, image_file)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/format/Format.py", line 119, in __init__
    self.setup()
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/format/Format.py", line 129, in setup
    self._start()
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/format/FormatHDFEigerNearlyNexus.py", line 310, in _start
    self._scan_model = ScanFactory(sample, detector).model
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/format/nexus.py", line 1060, in __init__
    for i, image in range(image_range[0], image_range[1]+1):
TypeError: Please report this error to dials-support@lists.sourceforge.net: 'int' object is not iterable
```

In /dls/mx-scratch/dials-bugs/bug#

**Comment by graeme-winter** [comment]
Putative fix:

```
/modules/cctbx_project/dxtbx/format/
Graemes-MacBook-Pro-4:format graeme$ svn diff
Index: nexus.py
===================================================================
--- nexus.py	(revision 24947)
+++ nexus.py	(working copy)
@@ -1044,7 +1044,7 @@
       exposure_time = flex.double(num_images, 0)
       epochs = flex.double(num_images, 0)
 
-    if is_sweep is True:
+    if is_sweep is True or (image_range[0] == image_range[1]):
 
       # Construct the model
       self.model = Scan(
```

**Comment by graeme-winter** [comment]
@jmp1985 is this sane?

**Comment by jmp1985** [comment]
Hi Graeme. I've fixed and committed. I have no idea what I was thinking when I wrote the original code since it clearly would never work! I've verified that the images import and find spots works.

**Comment by graeme-winter** [comment]
Just updated & still get error; did you push your fix?

**Comment by jmp1985** [comment]
Ooops, sorry I didn't realise I got a permission denied error when trying to commit.

I've tried again and I still get the error.

James

________________________________

**Comment by jmp1985** [comment]
OK, this explains it http://sourceforge.net/error-404.html. Looks like sourceforge is down.

James


________________________________
From: Parkhurst, James (DLSLtd,RAL,LSCI)
Sent: 13 July 2016 14:01
To: dials/dials; dials/dials
Cc: State change
Subject: RE: [dials/dials] dials.import fails for single image Eiger data sets (#177)

Ooops, sorry I didn't realise I got a permission denied error when trying to commit.

I've tried again and I still get the error.

James

________________________________
