### ISSUE TITLE
`dials.reindex` allows reindexing to a left-handed cell

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1779]
```
dials.reindex refined.expt refined.refl change_of_basis_op=-h,-k,-l
```
works without failure or warning, but the result crashes refinement, quite reasonably:
```
dials.refine reindexed.expt reindexed.refl
...
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dxtbx Internal Error: /home/fcx32934/sw/cctbx/modules/dxtbx/model/crystal.h(432): DXTBX_ASSERT(detail::is_r3_rotation_matrix(U)) failure.
```

**Comment by scaleop09** [comment]
![i](https://user-images.githubusercontent.com/90257562/135234255-fa26e1b7-fb40-40c1-a725-a1e3f381233e.jpg)

**Comment by dagewa** [comment]
It looks like this has been fixed, or at least the error has now moved into `dials.reindex` itself:
```
$ dials.reindex refined.expt refined.refl change_of_basis_op=-h,-k,-l
The following parameters have been modified:

change_of_basis_op = "-h,-k,-l"
input {
  experiments = refined.expt
  reflections = refined.refl
}

Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/reindex.py", line 380, in <module>
    run()
  File "/home/fcx32934/sw/cctbx/conda_base/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/reindex.py", line 336, in run
    experiments = reindex_experiments(
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/reindex.py", line 152, in reindex_experiments
    cryst_reindexed = cryst_reindexed.change_basis(cb_op)
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dxtbx Internal Error: /home/fcx32934/sw/cctbx/modules/dxtbx/src/dxtbx/model/crystal.h(437): DXTBX_ASSERT(detail::is_r3_rotation_matrix(U)) failure.
```
