### ISSUE TITLE
Would have expected indexing to work; it did not

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#178]
As discussed...
[indexing_should_work.zip](https://github.com/dials/dials/files/365686/indexing_should_work.zip)

**Comment by graeme-winter** [comment]
<img width="1380" alt="screen shot 2016-07-15 at 10 58 53" src="https://cloud.githubusercontent.com/assets/1241716/16870771/2ae19984-4a7b-11e6-9cb6-263284c2060f.png">

**Comment by graeme-winter** [comment]
FFT 3D map; points

For reference
```
coot --map fft3d.map -c '(set-last-map-contour-level-by-sigma 15)(set-map-radius 40)(set-map-sampling-rate 1)(set-dynamic-map-sampling-on) (set-dynamic-map-size-display-on)' --pdb peaks.pdb --no-guano

```

**Comment by rjgildea** [comment]
All candidate crystal models failing in refinement with similar error:
```
Summary statistics for 1228 observations matched to predictions:
---------------------------------------------------------------------
|                   | Min    | Q1      | Med      | Q3      | Max   |
---------------------------------------------------------------------
| Xc - Xo (mm)      | -3.01  | 0.03117 | 0.1598   | 0.3057  | 2.153 |
| Yc - Yo (mm)      | -1.965 | -0.2592 | -0.1295  | 0.01045 | 1.747 |
| Phic - Phio (deg) | -8.491 | -0.3013 | 0.002377 | 0.4281  | 11.06 |
| X weights         | 376.9  | 403.1   | 404.6    | 405.3   | 405.6 |
| Y weights         | 376.1  | 403.4   | 404.8    | 405.3   | 405.6 |
| Phi weights       | 236.2  | 295.9   | 297.6    | 298.5   | 300   |
---------------------------------------------------------------------

Detecting centroid outliers using the Tukey algorithm
424 reflections have been flagged as outliers

Summary statistics for 804 observations matched to predictions:
-----------------------------------------------------------------------
|                   | Min     | Q1      | Med     | Q3       | Max    |
-----------------------------------------------------------------------
| Xc - Xo (mm)      | -0.3443 | 0.03683 | 0.1402  | 0.2435   | 0.9366 |
| Yc - Yo (mm)      | -0.6702 | -0.2245 | -0.1305 | -0.02417 | 0.387  |
| Phic - Phio (deg) | -1.396  | -0.1823 | 0.01701 | 0.2916   | 3.576  |
| X weights         | 385.1   | 403.4   | 404.7   | 405.3    | 405.6  |
| Y weights         | 383.1   | 403.6   | 404.9   | 405.3    | 405.6  |
| Phi weights       | 270.3   | 296.7   | 297.8   | 298.5    | 300    |
-----------------------------------------------------------------------

Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/modules/dials/algorithms/indexing/indexer.py", line 1287, in run_one_refinement
    verbosity=2)
  File "/Users/rjgildea/software/cctbx/modules/dials/algorithms/refinement/refiner.py", line 429, in from_parameters_data_experiments
    verbosity=verbosity)
  File "/Users/rjgildea/software/cctbx/modules/dials/algorithms/refinement/refiner.py", line 489, in _build_components
    cls.config_parameterisation(params, experiments, refman, do_stills)
  File "/Users/rjgildea/software/cctbx/modules/dials/algorithms/refinement/refiner.py", line 975, in config_parameterisation
    raise Sorry(msg)
Sorry: Too few reflections to parameterise Beam3
Try modifying refinement.parameterisation.auto_reduction options
```

**Comment by rjgildea** [comment]
Either:
`dials.index *_SWEEP*_datablock.json *_SWEEP*_strong.pickle detector.fix=all beam.fix=all
`
or:
`dials.index *_SWEEP*_datablock.json *_SWEEP*_strong.pickle  auto_reduction.action=fix`
result in successful indexing (well, indexing gives _an answer_). But only two experiments listed in final table of RMSDs:
```
RMSDs by experiment:
-------------------------------------------
| Exp | Nref | RMSD_X | RMSD_Y | RMSD_Z   |
| id  |      | (px)   | (px)   | (images) |
-------------------------------------------
| 0   | 642  | 1.3324 | 0.839  | 1.1445   |
| 1   | 168  | 2.5286 | 1.6161 | 5.305    |
-------------------------------------------
```

**Comment by dagewa** [comment]
Another case where outlier rejection in blocks removes too many reflections?

`dials.index *_SWEEP*_datablock.json *_SWEEP*_strong.pickle auto_reduction.action=fix outlier.separate_blocks=False`

gives 

```
RMSDs by experiment:
---------------------------------------------
| Exp | Nref | RMSD_X  | RMSD_Y  | RMSD_Z   |
| id  |      | (px)    | (px)    | (images) |
---------------------------------------------
| 0   | 614  | 1.2335  | 0.67007 | 2.5086   |
| 1   | 204  | 0.71933 | 0.49137 | 5.3763   |
| 2   | 89   | 0.60115 | 0.57405 | 2.6213   |
| 3   | 69   | 1.4183  | 0.76727 | 4.695    |
---------------------------------------------

```

Don't know if this is what is wanted though as RMSD_Z is pretty bad

**Comment by dagewa** [comment]
(block_width=Auto is next on my to do list btw)

**Comment by dagewa** [comment]
Why are the initial Phi residuals so bad?

```
Summary statistics for 1228 observations matched to predictions:
-----------------------------------------------------------------------
|                   | Min    | Q1       | Med       | Q3      | Max   |
-----------------------------------------------------------------------
| Xc - Xo (mm)      | -1.638 | -0.1421  | 0.0005757 | 0.137   | 2.045 |
| Yc - Yo (mm)      | -1.875 | -0.07766 | 0.003007  | 0.08159 | 1.6   |
| Phic - Phio (deg) | -12.43 | -0.4622  | -0.05906  | 0.4867  | 15.89 |
| X weights         | 383.8  | 403.1    | 404.6     | 405.2   | 405.6 |
| Y weights         | 378.5  | 403.4    | 404.8     | 405.3   | 405.6 |
| Phi weights       | 236.2  | 296      | 297.6     | 298.5   | 300   |
-----------------------------------------------------------------------
```

Outlier rejection struggles here, and there are still bad Phi residuals afterwards:

```
Summary statistics for 699 observations matched to predictions:
-----------------------------------------------------------------------
|                   | Min     | Q1      | Med      | Q3      | Max    |
-----------------------------------------------------------------------
| Xc - Xo (mm)      | -0.8188 | -0.1088 | 0.01481  | 0.1369  | 0.5533 |
| Yc - Yo (mm)      | -0.5005 | -0.0616 | -0.00218 | 0.05734 | 0.3618 |
| Phic - Phio (deg) | -2.335  | -0.3468 | -0.04615 | 0.2686  | 2.921  |
| X weights         | 385.1   | 403.5   | 404.7    | 405.3   | 405.6  |
| Y weights         | 382     | 403.6   | 404.9    | 405.3   | 405.6  |
| Phi weights       | 270.3   | 296.9   | 298      | 298.6   | 300    |
-----------------------------------------------------------------------
```

**Comment by rjgildea** [comment]
This command line turns out to be sufficient:
`dials.index *_SWEEP*_datablock.json *_SWEEP*_strong.pickle separate_blocks=False`
Until `block_width=Auto` is implemented, `separate_blocks=False` should probably be the default for small molecule indexing (i.e. xia2.small_molecule)

**Comment by graeme-winter** [comment]
10-4 testing now

**Comment by graeme-winter** [comment]
Verified

I will work that in now

Cheerio Graeme

**Comment by rjgildea** [comment]
This now appears to work:
```
$ dials.index *_SWEEP*
RMSDs by experiment:
---------------------------------------------
| Exp | Nref | RMSD_X  | RMSD_Y  | RMSD_Z   |
| id  |      | (px)    | (px)    | (images) |
---------------------------------------------
| 0   | 635  | 1.1533  | 0.61716 | 2.5517   |
| 1   | 201  | 0.81901 | 0.61576 | 5.5769   |
| 2   | 90   | 0.56829 | 0.66315 | 3.1015   |
| 3   | 69   | 1.3811  | 0.92388 | 3.9601   |
---------------------------------------------

Refined crystal models:
model 1 (760 reflections):
Crystal:
    Unit cell: (16.655, 19.842, 39.069, 89.899, 90.485, 89.696)
    Space group: P 1
    U matrix:  {{-0.7144, -0.4679, -0.5203},
                {-0.3981, -0.3397,  0.8521},
                {-0.5754,  0.8159,  0.0564}}
    B matrix:  {{ 0.0600,  0.0000,  0.0000},
                {-0.0003,  0.0504,  0.0000},
                { 0.0005, -0.0001,  0.0256}}
    A = UB:    {{-0.0430, -0.0235, -0.0133},
                {-0.0234, -0.0172,  0.0218},
                {-0.0348,  0.0411,  0.0014}}
...
------------------------------------
| Imageset | #indexed | #unindexed |
------------------------------------
| 0        | 760      | 467        |
| 1        | 255      | 246        |
| 2        | 121      | 159        |
| 3        | 99       | 307        |
------------------------------------
```
