### ISSUE TITLE
dials.scale imageset wrangling breaks xia2.small_molecule

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1790]
```
                                             Overall    Low     High
High resolution limit                           0.59    1.59    0.59
Low resolution limit                            8.95    8.95    0.60
Completeness                                   97.9   100.0    64.9
Multiplicity                                   12.5    11.9     1.8
I/sigma                                       300.9   704.3    71.2
Rmerge(I)                                     0.019   0.008   0.050
Rmerge(I+/-)                                  0.018   0.008   0.055
Rmeas(I)                                      0.020   0.009   0.067
Rmeas(I+/-)                                   0.020   0.009   0.076
Rpim(I)                                       0.006   0.003   0.045
Rpim(I+/-)                                    0.008   0.004   0.053
CC half                                       1.000   1.000   0.994
Anomalous completeness                         90.4    90.9    13.8
Anomalous multiplicity                          7.4     8.3     1.5
Anomalous correlation                         0.106  -0.408   0.000
Anomalous slope                               4.271
dF/F                                          0.015
dI/s(dI)                                      2.919
Total observations                             8845     549      42
Total unique                                    709      46      24

Writing html report to /Users/graeme/Projects/Cu2OSe03/DEFAULT/scale/33_scaling.html
Traceback (most recent call last):
  File "/Users/graeme/git/dials/build/../modules/dials/command_line/scale.py", line 258, in <module>
    run()
  File "/Users/graeme/git/dials/conda_base/python.app/Contents/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/graeme/git/dials/build/../modules/dials/command_line/scale.py", line 231, in run
    scaled_experiments, joint_table = run_scaling(params, experiments, reflections)
  File "/Users/graeme/git/dials/build/../modules/dials/command_line/scale.py", line 194, in run_scaling
    experiments, joint_table = algorithm.finish()
  File "/Users/graeme/git/dials/modules/dials/algorithms/scaling/algorithm.py", line 311, in finish
    self.reflections = update_imageset_ids(self.experiments, self.reflections)
  File "/Users/graeme/git/dials/modules/dials/util/multi_dataset_handling.py", line 388, in update_imageset_ids
    assert len(set(table["imageset_id"])) == 1
```

Data from 4 sweeps here 

```
xia2 small_molecule=true absorption_level=high /Volumes/Black/Data/i19-Cu2OSeO3-Zr-edge
```

**Comment by graeme-winter** [comment]
OK, what is happening here is sweep 0 has imageset_id 0 but subsequent sweeps have imageset_id j _and also_ 0 -> boom.

**Comment by jbeilstenedmands** [comment]
Ok, I've confirmed that the issue here is with dials.split_experiments behaviour being incompatible with the current workflow of managing imageset_ids. Split experiments does not alter imageset_id, so split_0 has imageset_id=0, split_1 has imageset_id=1 etc (here we're splitting a multi-sweep dials.refine output). In integration, the integrated reflections are given an imageset_id=0, and then if `include_bad_reference=True`, the integrated reflections are extended with the unmatched data from split_*. 
The proposed solution is that any output (expt,refl)-pair from split_experiments should be internally consistent, i.e. the (expt,refl)-pair contains one imageset, and the imageset_id should be zero so that one can index into the list of imagesets. This enables any (expt,refl)-pair to be processed individually, which I believe is the general purpose of splitting. So in this case, all individual split_* should have imageset_id=0
