### ISSUE TITLE
Cannot get install to complete: " RuntimeError: Call to 'libtbx.py_compile_all -i' failed with exit code 137 "

### ISSUE THREAD

**Issue by adioni** [dials/dials#1801]
Am I missing something obvious here? I'm trying this on an Ubuntu 18 machine. 

`$ sudo ./install --prefix /opt`

The install stops, stating: ProcessRuntimeError: Call to 'libtbx.py_compile_all -i' failed with exit code 137

```
    ==========================================================================
                          DIALS Installation

                          version: v3-5-2
                     machine type: intel-linux-2.6-x86_64
                       OS version: 5.0.0-29-generic
                      destination: /opt/dials-v3-5-2
                  # of processors: 4
    =========================================================================

Configuring DIALS components...

*********************************
* Finalizing DIALS installation *
*********************************

Log file: /home/testuser/di/dials-installer/base_tmp/install_finalize.log
Generating DIALS environment setup scripts...
Generating DIALS environment additions for dispatchers...
Calling write_gui_dispatcher_include
  args ['--build_dir=/opt/dials-v3-5-2/build', '--base_dir=/opt/dials-v3-5-2/conda_base', '--suffix=dials', '--gtk_version=2.10.0', '--quiet', '--use_conda', '--ignore_missing_dirs']
  prologue export DIALS="/opt/dials-v3-5-2"
export DIALS_VERSION=v3-5-2
export DIALS_ENVIRONMENT=1
export DIALS_MTYPE=intel-linux-2.6-x86_64
  epilogue
Configuring DIALS components...
Precompiling .py files...
Traceback (most recent call last):
  File "./bin/install.py", line 234, in <module>
    installer(sys.argv[1:]).install()
  File "/home/testuser/di/dials-installer/lib/libtbx/auto_build/install_distribution.py", line 201, in install
    self.install_finalize()
  File "/home/testuser/di/dials-installer/lib/libtbx/auto_build/install_distribution.py", line 519, in install_finalize
    call(args="libtbx.py_compile_all -i", log=log)
  File "/home/testuser/di/dials-installer/lib/libtbx/auto_build/installer_utils.py", line 55, in call
    raise RuntimeError("Call to '%s' failed with exit code %d" % (args, rc))
RuntimeError: Call to 'libtbx.py_compile_all -i' failed with exit code 137
```

**Comment by adioni** [comment]
Yes, something obvious was missed: system needed more system RAM allocated to it. After that was done, the install completed successfully.

**Comment by ndevenish** [comment]
How much RAM did the system have allocated? Was this a real system or a VM? If this is a normal system, we should look into making it so that the install doesn't fail.....

**Comment by adioni** [comment]
It was a VM and was set to just 2GB (inadvertently). Upping to 8GB fixed things as mentioned, but did not try out any other RAM intervals between the two values.
