### ISSUE TITLE
DIALS 3.6 stable installer requires internet connection

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#1870]
I tried to install DIALS 3.6 from the stable installer https://github.com/dials/dials/releases/download/v3.6.0/dials-v3-6-0-linux-x86_64.tar.xz into a Cent OS 7 machine without direct internet connection by copying the archive and running `install`.

It failed as below:

```
[sacla_sfx_app@fep02 dials-installer]$ ./install --prefix=$HOME/packages

 -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=- -=-

An error occurred during installation  

Excerpt from installation log:
 :   ERROR: Command errored out with exit status 1:
 :    command: /home/sacla_sfx_app/packages/dials-v3-6-0/conda_base/bin/python /tmp/pip-standalone-pip-sxnkg_85/__env_pi
p__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-62py6dip/overlay --no-warn-script-location 
--no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
 :        cwd: None
 :   Complete output (7 lines):
 :   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5776321430>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
 :   WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f57767d5700>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
 :   WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f57767d5ac0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
 :   WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f57767d5880>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
 :   WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f57767d5cd0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
 :   ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
 :   ERROR: No matching distribution found for setuptools>=40.8.0
 :   ----------------------------------------
 : WARNING: Discarding file:///home/sacla_sfx_app/packages/dials-v3-6-0/modules/xia2. Command errored out with exit status 1: /home/sacla_sfx_app/packages/dials-v3-6-0/conda_base/bin/python /tmp/pip-standalone-pip-sxnkg_85/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-62py6dip/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
 : ERROR: Command errored out with exit status 1: /home/sacla_sfx_app/packages/dials-v3-6-0/conda_base/bin/python /tmp/pip-standalone-pip-sxnkg_85/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-62py6dip/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
 : Traceback (most recent call last):  
 :   File "/home/sacla_sfx_app/packages/dials-v3-6-0/modules/cctbx_project/libtbx/configure.py", line 34, in <module>
 :     if not run():
 :   File "/home/sacla_sfx_app/packages/dials-v3-6-0/modules/cctbx_project/libtbx/configure.py", line 29, in run
 :     libtbx.env_config.cold_start(sys.argv)
 :   File "/home/sacla_sfx_app/packages/dials-v3-6-0/modules/cctbx_project/libtbx/env_config.py", line 3017, in cold_start
 :     env.refresh()
 :   File "/home/sacla_sfx_app/packages/dials-v3-6-0/modules/cctbx_project/libtbx/env_config.py", line 2251, in refresh
 :     module.process_libtbx_refresh_py()
 :   File "/home/sacla_sfx_app/packages/dials-v3-6-0/modules/cctbx_project/libtbx/env_config.py", line 2568, in process_libtbx_refresh_py
 :     exec(to_str(fh.read()), global_vars)
 :   File "<string>", line 38, in <module>
 :   File "<string>", line 14, in _install_xia2_setup
 :   File "/home/sacla_sfx_app/packages/dials-v3-6-0/conda_base/lib/python3.9/subprocess.py", line 528, in run
 :     raise CalledProcessError(retcode, process.args,
 : subprocess.CalledProcessError: Command '['/home/sacla_sfx_app/packages/dials-v3-6-0/conda_base/bin/python', '-m', 'pip', 'install', '--no-deps', '-e', '/home/sacla_sfx_app/packages/dials-v3-6-0/modules/xia2']' returned non-zero exit status 1.

This led to Traceback (most recent call last):
  File "./bin/install.py", line 66, in reconfigure
  File "/home/sacla_sfx_app/dials-installer/lib/libtbx/auto_build/install_distribution.py", line 431, in reconfigure
    call(args=args, log=log, verbose=self.options.verbose)
  File "/home/sacla_sfx_app/dials-installer/lib/libtbx/auto_build/installer_utils.py", line 55, in call
    raise RuntimeError("Call to '%s' failed with exit code %d" % (args, rc))
RuntimeError: Call to '/home/sacla_sfx_app/packages/dials-v3-6-0/conda_base/bin/python /home/sacla_sfx_app/packages/dials-v3-6-0/modules/cctbx_project/libtbx/configure.py --current_working_directory /home/sacla_sfx_app/packages/dials-v3-6-0/build dials xia2 iota prime --use_conda' failed with exit code 1
```

**Comment by ndevenish** [comment]
Currently looking into this after being pointed to your tweet!

We had reports of this failing offline for dxtbx, which was fixed in https://github.com/cctbx/dxtbx/commit/53a968dd4381a5f7ed993e0d7f0b0c312e150f75. It looks like this same issue happens for xia2.

**Comment by ndevenish** [comment]
So, yes, it's quite a simple fix: https://github.com/xia2/xia2/pull/619 - which can easily be added in-place for 3.6.0 in `dials_installer/modules/xia2/libtbx_refresh.py`.

However, we were due a 3.6.1 today if there were any other hotfixes, so if it's not urgent, then that should be available in a few hours when merged and our CI system has processed it.

**Comment by biochem-fan** [comment]
Thank you very much. I will wait for 3.6.1 and test it tomorrow.

**Comment by ndevenish** [comment]
Hi @biochem-fan,

https://github.com/dials/dials/releases/tag/v3.6.1 is now out, and contains this fix. Please let us know if you have any more problems!

**Comment by biochem-fan** [comment]
I successfully install 3.6.1. Thank you very much for your quick fix.
