### ISSUE TITLE
`dials.integrate` `overlaps_filter` options broken

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1890]
Reported on the support list. We don't have a multi lattice data at hand to test (I think?) but the issue can be demonstrated with any old dataset

```
dials.import $(dials.data get -q insulin)
dials.find_spots imported.expt
dials.index imported.expt strong.refl space_group=I23
dials.integrate indexed.expt indexed.refl\
  integration.overlaps_filter.foreground_foreground.enable=True\
  integration.overlaps_filter.foreground_background.enable=True
```
Ends with
```
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/integrate.py", line 734, in <module>
    run()
  File "/home/fcx32934/sw/cctbx/conda_base/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/integrate.py", line 712, in run
    experiments, reflections, report = run_integration(
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/integrate.py", line 585, in run_integration
    reflections = integrator.integrate()
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/integration/integrator.py", line 1322, in integrate
    self.reflections, self.experiments = self.finalize_reflections(
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/integration/integrator.py", line 524, in _finalize_rotation
    reflections, experiments = _finalize(reflections, experiments, params)
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/integration/integrator.py", line 512, in _finalize
    overlaps_filter.remove_foreground_foreground_overlaps()
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/integration/overlaps_filter.py", line 160, in remove_foreground_foreground_overlaps
    f.remove_foreground_foreground_overlaps()
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/integration/overlaps_filter.py", line 136, in remove_foreground_foreground_overlaps
    self.create_referenced_mask(self.code_fgd, "foreground")
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/integration/overlaps_filter.py", line 67, in create_referenced_mask
    shoebox = obs["shoebox"]
KeyError: 'Please report this error to dials-support@lists.sourceforge.net: shoebox'
```

**Comment by graeme-winter** [comment]
I'll find you something

**Comment by dagewa** [comment]
If there are multi-lattice images with overlaps on Zenodo, I think that would make a good addition for dials.data. We probably only need a fairly narrow wedge to test success (or not) of whatever our overlap handling facilities are.

**Comment by graeme-winter** [comment]
@dagewa  what do you know https://zenodo.org/record/10820

Like, we did this 7 years back 😀👍

Fortune favours the prepared

**Comment by dagewa** [comment]
Nice. Possibly a bit big for `dials data` though for writing a new test?

**Comment by dagewa** [comment]
Right, I have integrated the 6 lattices in the semisynthetic set `acegik`, but according to flags, there are no overlaps:
```
>>> from dials.array_family import flex
>>> rt=flex.reflection_table.from_file("integrated.refl")
>>> rt.get_flags(rt.flags.overlapped_fg).count(True)
0
>>> rt.get_flags(rt.flags.overlapped_bg).count(True)
0
```
Does anybody understand the overlap handling in DIALS?

**Comment by dagewa** [comment]
Here they are on the image:
![Screenshot from 2021-10-11 16-12-57](https://user-images.githubusercontent.com/11502083/136814436-a03c0399-41b1-4777-92f1-3e15493c4df2.png)
So, these are very clearly overlapped reflections, but DIALS does not count them as such.

**Comment by dagewa** [comment]
I don't think a script like that was tried before. I won't have time to look at it unfortunately, but I would be interested in your results.
