### ISSUE TITLE
Error in dials.report after usual processing chain

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1942]
```
index
refine
integrate
symmetry
scale
```
->

```
Calculating and generating merging statistics plots
Traceback (most recent call last):
  File "/Users/graeme/git/dials/build/../modules/dials/command_line/report.py", line 2512, in <module>
    run()
  File "/Users/graeme/git/dials/conda_base/python.app/Contents/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/Users/graeme/git/dials/build/../modules/dials/command_line/report.py", line 2508, in run
    script.run(args)
  File "/Users/graeme/git/dials/build/../modules/dials/command_line/report.py", line 2502, in run
    analyse(reflections, experiments)
  File "/Users/graeme/git/dials/build/../modules/dials/command_line/report.py", line 2222, in __call__
    ) = merging_stats_results(rlist, experiments)
  File "/Users/graeme/git/dials/build/../modules/dials/command_line/report.py", line 2116, in merging_stats_results
    scaled_array = scaled_data_as_miller_array([reflections], experiments)
  File "/Users/graeme/git/dials/modules/dials/algorithms/scaling/scaling_library.py", line 325, in scaled_data_as_miller_array
    best_unit_cell = determine_best_unit_cell(experiments)
  File "/Users/graeme/git/dials/modules/dials/algorithms/scaling/scaling_library.py", line 366, in determine_best_unit_cell
    best_unit_cell = uctbx.unit_cell(parameters=[flex.median(p) for p in uc_params])
  File "/Users/graeme/git/dials/modules/dials/algorithms/scaling/scaling_library.py", line 366, in <listcomp>
    best_unit_cell = uctbx.unit_cell(parameters=[flex.median(p) for p in uc_params])
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: scitbx Internal Error: /Users/graeme/git/dials/modules/cctbx_project/scitbx/math/basic_statistics.h(173): SCITBX_ASSERT(data.size()) failure.
```

Am guessing this is because we don't have scan varying unit cell after using `dials.symmetry` to map from P1 to I23.

**Comment by graeme-winter** [comment]
Verified

`dials.refine scaled.*` -> `dials.report refined.*`

worked without error

**Comment by graeme-winter** [comment]
CNR; suspect my dials at home was out of date
