### ISSUE TITLE
dials.reindex does not allow h,k+1,l

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#207]
I would however like this because:

```
[gw56@ws133 index]$ dials.check_indexing_symmetry /dls/tmp/gw56/20160915/process/DEFAULT/SAD/SWEEP1/index/4_experiments.json /dls/tmp/gw56/20160915/process/DEFAULT/SAD/SWEEP1/index/4_indexed.pickle grid_search_scope=3 symop_threshold=0.7
The following parameters have been modified:

symop_threshold = 0.7
grid_search_scope = 3
input {
  experiments = /dls/tmp/gw56/20160915/process/DEFAULT/SAD/SWEEP1/index/4_experiments.json
  reflections = /dls/tmp/gw56/20160915/process/DEFAULT/SAD/SWEEP1/index/4_indexed.pickle
}

Checking HKL origin:

dH dK dL   Nref    CC
 0  0  0 115484 0.268
 0  1  0  20392 0.846

Check symmetry operations on 178291 reflections:

               Symop   Nref    CC
               x,y,z 178291 0.625

Derived point group from symmetry operations: P 1

usr+sys time: 39.80 seconds, ticks: 1666632, micro-seconds/tick: 23.880
wall clock time: 49.57 seconds
[gw56@ws133 index]$ dials.index change_of_basis_op='h,k+1,l' /dls/tmp/gw56/20160915/process/DEFAULT/SAD/SWEEP1/index/4_indexed.pickle
Sorry: Unknown command line parameter definition: change_of_basis_op = h,k+1,l
[gw56@ws133 index]$ dials.reindex change_of_basis_op='h,k+1,l' /dls/tmp/gw56/20160915/process/DEFAULT/SAD/SWEEP1/index/4_indexed.pickle
The following parameters have been modified:

change_of_basis_op = "h,k+1,l"
input {
  reflections = /dls/tmp/gw56/20160915/process/DEFAULT/SAD/SWEEP1/index/4_indexed.pickle
}

Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/reindex.py", line 243, in <module>
    run(sys.argv[1:])
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/reindex.py", line 192, in run
    change_of_basis_op = sgtbx.change_of_basis_op(params.change_of_basis_op)
RuntimeError: cctbx Internal Error: /dls/science/users/gw56/svn/cctbx/modules/cctbx_project/cctbx/sgtbx/change_of_basis_op.cpp(20): CCTBX_ASSERT(result.t().is_zero()) failure.

```

**Comment by graeme-winter** [comment]
I have a recollection (i) this used to work and (ii) we used this before..

Oh, my bad

hkl_offset=...

http://twiddling-dials.blogspot.co.uk/2015/10/checking-indexing-symmetry.html

**Comment by graeme-winter** [comment]
Useful comment: if not pure rotation; suggest in error message to user to use hkl_offset...
