### ISSUE TITLE
`.sfrm` files create utf-8 encoding error

### ISSUE THREAD

**Issue by dennisbrookner** [dials/dials#2097]
I have collected data on a (pretty outdated) Bruker homesource, which gave me diffraction images as `.sfrm` files. I ran
```
dials.import file.sfrm
```
And got the following error:
```
Traceback (most recent call last):
  File "/Applications/dials-v3-9-1/build/../modules/dials/command_line/dials_import.py", line 954, in <module>
    run()
  File "/Applications/dials-v3-9-1/conda_base/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Applications/dials-v3-9-1/build/../modules/dials/command_line/dials_import.py", line 950, in run
    importer.import_image(args)
  File "/Applications/dials-v3-9-1/build/../modules/dials/command_line/dials_import.py", line 779, in import_image
    params, options, unhandled = self.parser.parse_args(
  File "/Applications/dials-v3-9-1/modules/dials/util/options.py", line 854, in parse_args
    params, args = self._phil_parser.parse_args(
  File "/Applications/dials-v3-9-1/modules/dials/util/options.py", line 537, in parse_args
    importer = Importer(
  File "/Applications/dials-v3-9-1/modules/dials/util/options.py", line 199, in __init__
    self.unhandled = self.try_read_experiments_from_images(
  File "/Applications/dials-v3-9-1/modules/dials/util/options.py", line 270, in try_read_experiments_from_images
    experiments = ExperimentListFactory.from_filenames(
  File "/Applications/dials-v3-9-1/modules/dxtbx/src/dxtbx/model/experiment_list.py", line 557, in from_filenames
    format_object = format_class(filename, **format_kwargs)
  File "/Applications/dials-v3-9-1/modules/dxtbx/src/dxtbx/format/FormatBruker.py", line 101, in __init__
    super().__init__(str(image_file), **kwargs)
  File "/Applications/dials-v3-9-1/modules/dxtbx/src/dxtbx/format/Format.py", line 168, in __init__
    self.setup()
  File "/Applications/dials-v3-9-1/modules/dxtbx/src/dxtbx/format/Format.py", line 178, in setup
    self._start()
  File "/Applications/dials-v3-9-1/modules/dxtbx/src/dxtbx/format/FormatBrukerFixedChi.py", line 27, in _start
    header_text = open(self._image_file).read().split("......")[0]
  File "/Applications/dials-v3-9-1/build/../conda_base/python.app/Contents/MacOS/../../../lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 20218: invalid start byte
```
I will not profess to fully understand this error, but I believe it has to do with a change in the default behavior of utf-8 encoding. @kmdalton suggested the following fix, which I made locally and it worked. In `dxtbx/format/FormatBrukerFixedChi.py` line 27, I changed
```
header_text = open(self._image_file).read().split("......")[0]
```
to
```
image_blob = open(self._image_file, 'rb').read()
header_text = image_blob.decode(errors='ignore').split("......")[0]
```
Rick Hewitt suggested the following alternative fix:
```
header_text = open(self._image_file, encoding='iso8859_16').read().split("......")[0]
```

I leave to the devs what the best and most general solution is here, but I wanted to raise the problem. 

## Steps to reproduce

Here is an example `.sfrm` file: [cu_DB22001_01_0001.sfrm.zip](https://github.com/dials/dials/files/8556083/cu_DB22001_01_0001.sfrm.zip)

Calling `dials.import` with that file should reproduce this error. I have personally tested this with `v3-6-1` and `v3-9-1`.

Please let me know if I've missed anything!

**Comment by dennisbrookner** [comment]
Under the new package architecture, the relevant file no longer lives in `dials` proper, but rather in `dxtbx`. I have linked the relevant PR in the `dxtbx` repo.
