### ISSUE TITLE
dials.slice_sequence failure: "Input experiment list and image_ranges are not of the same length"

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2098]
As reported on helpdesk, this fails with an error:
```
$ dials.slice_sequence integrated.expt integrated.refl image_range="1 35" image_range="36 112"
The following parameters have been modified:

image_range = 1 35
image_range = 36 112
input {
  experiments = integrated.expt
  reflections = integrated.refl
}

Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/slice_sequence.py", line 250, in <module>
    run()
  File "/home/fcx32934/sw/cctbx/conda_base/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/slice_sequence.py", line 246, in run
    script.run(args)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/slice_sequence.py", line 200, in run
    sliced_experiments = slice_experiments(experiments, params.image_range)
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/util/slice.py", line 20, in slice_experiments
    raise ValueError(
ValueError: Please report this error to dials-support@lists.sourceforge.net: Input experiment list and image_ranges are not of the same length
```
The help message gives this example:
```
  # two experiments and reflections with IDs '0' and '1'
  dials.slice_sequence models.expt observations.refl     "image_range=1 20" "image_range=5 30"
```
I suppose this implies that `integrated.expt` and `integrated.refl` should have two experiments, whereas what the user was probably trying to do is produce two separate slices from a single experiment. I found the help text quite confusing, so I'm not totally sure of the intention here.

**Comment by jbeilstenedmands** [comment]
Just stumbled across this, I think the best thing here would be to change to a Sorry (to avoid the traceback) and update the message to say how many experiments there are, and to suggest either multiple runs of the program, or to use dials.split_experiments.
