### ISSUE TITLE
dials.symmetry divide by zero

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2123]
Not investigated in detail yet, but this command 
```
xia2 small_molecule=true integrate.min_spots.overall=1 integrate.min_spots.per_degree=1 $(dials.data get -q l_cysteine_dials_output)
```
results in a `dials.symmetry` error, namely
```
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/symmetry.py", line 572, in <module>
    run()
  File "/home/fcx32934/sw/cctbx/conda_base/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/symmetry.py", line 566, in run
    symmetry(experiments, reflections, params=params)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/symmetry.py", line 351, in symmetry
    result = LaueGroupAnalysis(
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/algorithms/symmetry/laue_group.py", line 84, in __init__
    self._score_symmetry_elements()
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/algorithms/symmetry/laue_group.py", line 220, in _score_symmetry_elements
    ScoreSymmetryElement(
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/algorithms/symmetry/laue_group.py", line 546, in __init__
    self.z_cc = self.cc.coefficient() / self.sigma_cc
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/algorithms/symmetry/laue_group.py", line 760, in coefficient
    return self.numerator() / self.denominator()
ZeroDivisionError: Please report this error to dials-support@lists.sourceforge.net: float division by zero
```
Divide-by-zero suggests :bug: to me

**Comment by dagewa** [comment]
Looked a bit closer. The issue happens here https://github.com/dials/dials/blob/8aef2b1dc2a56df77f1fb4accabeb1ba45b5e99f/src/dials/algorithms/symmetry/laue_group.py#L788-L790
because the argument to the first `sqrt`, i.e. `self._n * self._sum_x_sq - self._sum_x**2`, is zero.

This seems to be a corner case where $n=2$ and the values $x_i$ are identical. In that case, $\sum x_i^2 = 2 \bar{x}^2$ and $\sum x_i = 2 \bar{x}$. The expression above therefore cancels to zero.

**Comment by dagewa** [comment]
For a sample size of $n=2$ the only possible values of Pearson's correlation coefficient are in ${-1, 0, 1}$ anyway. Performing the calculation probably only makes sense for $n \geq 3$, and even then there is the issue of small sample bias.

**Comment by dagewa** [comment]
I got another different failure (perhaps because I used CCP4 9.0), in `dials.scale`:
```
WARNING: No profile-integrated reflections found
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/util/filter_reflections.py", line 153, in filter_reflection_table
    reflection_table = reducer.filter_for_export(reflection_table, *args, **kwargs)
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/util/filter_reflections.py", line 469, in filter_for_export
    reflection_table = cls.reduce_on_intensities(reflection_table)
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/util/filter_reflections.py", line 282, in wrapper
    reflections = func(*args, **kwargs)
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/util/filter_reflections.py", line 544, in reduce_on_intensities
    raise NoProfilesException(
dials.util.filter_reflections.NoProfilesException: WARNING: No profile-integrated reflections found
```

**Comment by jbeilstenedmands** [comment]
Thanks for the reminder, looking into it.
