### ISSUE TITLE
dials.symmetry fails on multi-lattice data

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2130]
```
Performing Laue group analysis

Couldn't match unit cell to target symmetry:
Unit cell: (6.39831, 12.5646, 18.2163, 69.8368, 81.2146, 90.0254)
Space group: P 1 (No. 1)
Target symmetry: P 1 2/m 1
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v3-9-0-1/build/../modules/dials/command_line/symmetry.py", line 572, in <module>
    run()
  File "/dls_sw/apps/dials/dials-v3-9-0-1/conda_base/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/dls_sw/apps/dials/dials-v3-9-0-1/build/../modules/dials/command_line/symmetry.py", line 566, in run
    symmetry(experiments, reflections, params=params)
  File "/dls_sw/apps/dials/dials-v3-9-0-1/build/../modules/dials/command_line/symmetry.py", line 328, in symmetry
    experiments, reflection_tables = apply_change_of_basis_ops(
  File "/dls_sw/apps/dials/dials-v3-9-0-1/build/../modules/dials/command_line/symmetry.py", line 242, in apply_change_of_basis_ops
    refl["miller_index"] = cb_op_inp_min.apply(refl["miller_index"])
AttributeError: Please report this error to dials-support@lists.sourceforge.net: 'NoneType' object has no attribute 'apply'
```

I suspect that this relates to something added in recent history - will see if I can dig out the commit

**Comment by graeme-winter** [comment]
I take that back - this is in a 3.9 release not a development build so could be a real bug not a regression

**Comment by jbeilstenedmands** [comment]
Note appears to be the same fallure as https://github.com/dials/dials/issues/2355
