### ISSUE TITLE
dials.merge is broken for P-1 datasets

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#2173]
`dials.merge` fails with P-1 datasets during the French-Wilson procedure.

```
Performing French-Wilson treatment of scaled intensities
ValueError: zero-size array to reduction operation minimum which has no identity

During handling of the above exception, another exception occurred:

Sorry: zero-size array to reduction operation minimum which has no identity
```

`implementation=cctbx` helps but fails in a later step.

```
Traceback (most recent call last):
  File "/opt/dials-dev/build/../modules/dials/src/dials/command_line/merge.py", line 320, in <module>
    run()
  File "/opt/dials-dev/conda_base/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/dials-dev/build/../modules/dials/src/dials/command_line/merge.py", line 316, in run
    generate_html_report(mtz_file, params.output.html)
  File "/opt/dials-dev/modules/dials/src/dials/algorithms/merging/merge.py", line 461, in generate_html_report
    data = make_dano_plots(anom_data)
  File "/opt/dials-dev/modules/dials/src/dials/algorithms/merging/merge.py", line 396, in make_dano_plots
    dFsdF, resolution_bin_edges = dano_over_sigdano_stats(anom)
  File "/opt/dials-dev/modules/dials/src/dials/algorithms/merging/merge.py", line 337, in dano_over_sigdano_stats
    vals.append(dano_over_sigdano(arr))
  File "/opt/dials-dev/modules/dials/src/dials/algorithms/merging/merge.py", line 345, in dano_over_sigdano
    diff = anomalous_amplitudes.anomalous_differences()
  File "/opt/dials-dev/modules/cctbx_project/cctbx/miller/__init__.py", line 3052, in anomalous_differences
    asu, matches = tmp_array.match_bijvoet_mates()
  File "/opt/dials-dev/modules/cctbx_project/cctbx/miller/__init__.py", line 1092, in match_bijvoet_mates
    assert self.anomalous_flag() in (None, True)
AssertionError: Please report this error to dials-support@lists.sourceforge.net:
```

`implementation=cctbx anomalous=False` finally succeeds. I think `anomalous` should be automatically turned off for P-1.

Interestingly, the program succeeds without `anomalous=False` when `truncate=False`.

**Comment by jbeilstenedmands** [comment]
The PR should fix the current crashes, I tested on a dataset reindexed to P-1 and reproduced the issues you reported. It could be nice to have an auto anomalous option that handles P-1, but the program should still complete in that case hence the current fix. I think auto anomalous could be considered as an additional enhancement separate to fixing the crashes.

**Comment by biochem-fan** [comment]
Great! Thank you very much for your very quick fix.
