### ISSUE TITLE
dials.integrate: scan range = causes user stack trace

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2218]
540 image data set

```
dials.integrate scan_range=1,300 ../refined.*
```

should do what it says on the tin

```
Modified experiment list to integrate over requested scan range
 scan_range = 1 -> 300
```

but

```


easy_mp crash detected; subprocess trace: ----
Traceback (most recent call last):
  File "/Users/graeme/git/dials/modules/cctbx_project/libtbx/scheduling/job_scheduler.py", line 64, in job_cycle
    value = target( *args, **kwargs )
  File "/Users/graeme/git/dials/modules/dials/src/dials/algorithms/integration/processor.py", line 298, in execute_parallel_task
    result = task()
  File "/Users/graeme/git/dials/modules/dials/src/dials/algorithms/integration/processor.py", line 538, in __call__
    processor = ShoeboxProcessor(
dials Internal Error: /Users/graeme/git/dials/modules/dials/src/dials/algorithms/integration/processor.h(93): DIALS_ASSERT(j < num.size()) failure.
----------------------------------------------
```

**Comment by graeme-winter** [comment]
Oh god, it is _another_ off-by-one error 🤦‍♂️

```
dials.integrate scan_range=0,30 ../refined.* nproc=1
```

works fine 🤬

**Comment by graeme-winter** [comment]
OK, not off-by-one but if the start is any non-zero number -> segmentation fault. Tests need extending to handle this case.

**Comment by graeme-winter** [comment]
OK, this is buried deep in the C++ code (no surprise, given error == `Segmentation fault`)

**Comment by dagewa** [comment]
Related: #1227

**Comment by graeme-winter** [comment]
> Related: #1227

<strange echo-y voice from deep in the onion mines>
Thanks

By "related" you mean "duplicate"
</strange echo-y voice from deep in the onion mines>

**Comment by graeme-winter** [comment]
Anyhow - previous suggestion was to retire the option, from where I am stood this seems wise.
