### ISSUE TITLE
dials.find_spots error

### ISSUE THREAD

**Issue by KevinBattaile** [dials/dials#2239]
Had the following error when spotfinding. OS is CentOS Stream with DIALS v3-11-2.

```
[kbattaile@Nostromo dials]$ dials.find_spots imported.expt 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 3.11.2-gab6081be1-release
The following parameters have been modified:

input {
  experiments = imported.expt
}

Setting spotfinder.filter.min_spot_size=3
Configuring spot finder from input parameters
--------------------------------------------------------------------------------
Finding strong spots in imageset 0
--------------------------------------------------------------------------------

Finding spots in image 1 to 5400...
Setting nproc=28
Setting chunksize=24
Extracting strong pixels from images
 Using multiprocessing with 28 parallel job(s)



easy_mp crash detected; subprocess trace: ----
Traceback (most recent call last):
  File "/data/Software/DIALS/dials-v3-11-2/modules/cctbx_project/libtbx/scheduling/job_scheduler.py", line 64, in job_cycle
    value = target( *args, **kwargs )
  File "/data/Software/DIALS/dials-v3-11-2/modules/dials/src/dials/util/mp.py", line 163, in __call__
    return [self.__function(item) for item in iterable]
  File "/data/Software/DIALS/dials-v3-11-2/modules/dials/src/dials/util/mp.py", line 163, in <listcomp>
    return [self.__function(item) for item in iterable]
  File "/data/Software/DIALS/dials-v3-11-2/modules/dials/src/dials/algorithms/spot_finding/finder.py", line 258, in __call__
    result = self.function(task)
  File "/data/Software/DIALS/dials-v3-11-2/modules/dials/src/dials/algorithms/spot_finding/finder.py", line 79, in __call__
    mask = self.imageset.get_mask(index)
dxtbx Internal Error: /scratch/jenkins_agent/workspace/dials_patch_release/build_dials/modules/dxtbx/src/dxtbx/model/panel.h(397): DXTBX_ASSERT(data.accessor()[0] == image_size_[1]) failure.
----------------------------------------------


Traceback (most recent call last):
  File "/data/Software/DIALS/dials-v3-11-2/build/../modules/dials/src/dials/command_line/find_spots.py", line 242, in <module>
    run()
  File "/data/Software/DIALS/dials-v3-11-2/conda_base/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/Software/DIALS/dials-v3-11-2/build/../modules/dials/src/dials/command_line/find_spots.py", line 236, in run
    results = do_spotfinding(experiments, params)
  File "/data/Software/DIALS/dials-v3-11-2/build/../modules/dials/src/dials/command_line/find_spots.py", line 127, in do_spotfinding
    reflections = flex.reflection_table.from_observations(experiments, params)
  File "/data/Software/DIALS/dials-v3-11-2/modules/dials/src/dials/array_family/flex_ext.py", line 179, in from_observations
    return spotfinder.find_spots(experiments)
  File "/data/Software/DIALS/dials-v3-11-2/modules/dials/src/dials/algorithms/spot_finding/finder.py", line 702, in find_spots
    table, hot_mask = self._find_spots_in_imageset(imageset)
  File "/data/Software/DIALS/dials-v3-11-2/modules/dials/src/dials/algorithms/spot_finding/finder.py", line 815, in _find_spots_in_imageset
    r, h = extract_spots(imageset[j0:j1])
  File "/data/Software/DIALS/dials-v3-11-2/modules/dials/src/dials/algorithms/spot_finding/finder.py", line 415, in __call__
    return self._find_spots(imageset)
  File "/data/Software/DIALS/dials-v3-11-2/modules/dials/src/dials/algorithms/spot_finding/finder.py", line 506, in _find_spots
    batch_multi_node_parallel_map(
  File "/data/Software/DIALS/dials-v3-11-2/modules/dials/src/dials/util/mp.py", line 243, in batch_multi_node_parallel_map
    return multi_node_parallel_map(
  File "/data/Software/DIALS/dials-v3-11-2/modules/dials/src/dials/util/mp.py", line 214, in multi_node_parallel_map
    result = libtbx.easy_mp.parallel_map(
  File "/data/Software/DIALS/dials-v3-11-2/modules/cctbx_project/libtbx/easy_mp.py", line 637, in parallel_map
    result = res()
  File "/data/Software/DIALS/dials-v3-11-2/modules/cctbx_project/libtbx/scheduling/result.py", line 119, in __call__
    self.traceback( exception = self.exception() )
  File "/data/Software/DIALS/dials-v3-11-2/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 117, in __call__
    self.raise_handler( exception = exception )
  File "/data/Software/DIALS/dials-v3-11-2/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 134, in raise_with_traceback
    raise_(type(exception), exception, self.traceback)
  File "/data/Software/DIALS/dials-v3-11-2/conda_base/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/data/Software/DIALS/dials-v3-11-2/modules/cctbx_project/libtbx/scheduling/mainthread.py", line 100, in poll
    value = target( *args, **kwargs )
  File "/data/Software/DIALS/dials-v3-11-2/modules/dials/src/dials/util/mp.py", line 137, in __call__
    return libtbx.easy_mp.parallel_map(
  File "/data/Software/DIALS/dials-v3-11-2/modules/cctbx_project/libtbx/easy_mp.py", line 637, in parallel_map
    result = res()
  File "/data/Software/DIALS/dials-v3-11-2/modules/cctbx_project/libtbx/scheduling/result.py", line 119, in __call__
    self.traceback( exception = self.exception() )
  File "/data/Software/DIALS/dials-v3-11-2/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 117, in __call__
    self.raise_handler( exception = exception )
  File "/data/Software/DIALS/dials-v3-11-2/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 147, in raise_with_stacktrace
    self.stacktrace( exception = exception )
  File "/data/Software/DIALS/dials-v3-11-2/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 88, in __call__
    raise exception
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dxtbx Internal Error: /scratch/jenkins_agent/workspace/dials_patch_release/build_dials/modules/dxtbx/src/dxtbx/model/panel.h(397): DXTBX_ASSERT(data.accessor()[0] == image_size_[1]) failure.
```

**Comment by rjgildea** [comment]
What beamline/detector are the images from? If the images are Eiger/NeXus format, could you post the output of the following?
```
$ h5ls -rv --follow-symlinks  h5ls -rv --follow-symlinks /path/to/master.h5/entry/instrument/detector/pixel_mask
$ h5ls -d /path/to/master.h5/entry/instrument/detector/module/data_size
$ h5ls -rv --follow-symlinks /path/to/master.h5/entry/data
```

**Comment by KevinBattaile** [comment]
This is from an Eiger2 9M XE at NSLS-II 19-ID. Here is the output you asked for.

----
[kbattaile@Nostromo NYX-test_1]$ h5ls -rv --follow-symlinks NYX-test01_33_master.h5/entry/instrument/detector/pixel_mask
Opened "NYX-test01_33_master.h5" with sec2 driver.
entry/instrument/detector/pixel_mask**NOT FOUND** [kbattaile@Nostromo NYX-test_1]$ 
[kbattaile@Nostromo NYX-test_1]$ h5ls -d NYX-test01_33_master.h5/entry/instrument/detector/module/data_size
data_size                Dataset {2}
    Data:
        (0) 3108, 3262
[kbattaile@Nostromo NYX-test_1]$ h5ls -rv --follow-symlinks NYX-test01_33_master.h5/entry/data
Opened "NYX-test01_33_master.h5" with sec2 driver.
/data_000001             External Link {NYX-test01_33_data_000001.h5//entry/data/data} {Dataset {500/Inf, 3262/3262, 3108/3108}
    Attribute: image_nr_high scalar
        Type:      native unsigned long
        Data:  500
    Attribute: image_nr_low scalar
        Type:      native unsigned long
        Data:  1
    Location:  4:489
    Links:     1
    Modified:  2022-07-19 16:59:33 EDT
    Chunks:    {1, 3262, 3108} 40553184 bytes
    Storage:   20276592000 logical bytes, 1236995163 allocated bytes, 1639.18% utilization
    Filter-0:  bitshuffle; see https://github.com/kiyo-masui/bitshuffle-32008  {0, 3, 4, 0, 2}
    Type:      native unsigned int
}
/data_000002             External Link {NYX-test01_33_data_000002.h5//entry/data/data} {Already Visited}
/data_000003             External Link {NYX-test01_33_data_000003.h5//entry/data/data} {Already Visited}
/data_000004             External Link {NYX-test01_33_data_000004.h5//entry/data/data} {Already Visited}
/data_000005             External Link {NYX-test01_33_data_000005.h5//entry/data/data} {Already Visited}
/data_000006             External Link {NYX-test01_33_data_000006.h5//entry/data/data} {Already Visited}
/data_000007             External Link {NYX-test01_33_data_000007.h5//entry/data/data} {Already Visited}
/data_000008             External Link {NYX-test01_33_data_000008.h5//entry/data/data} {Already Visited}
/data_000009             External Link {NYX-test01_33_data_000009.h5//entry/data/data} {Already Visited}
/data_000010             External Link {NYX-test01_33_data_000010.h5//entry/data/data} {Already Visited}
/data_000011             External Link {NYX-test01_33_data_000011.h5//entry/data/data} {Already Visited}

**Comment by graeme-winter** [comment]
I note the detector mask is `not_found` -> is the detector in basic header mode?

What if you prod simplon into full header mode?

**Comment by rjgildea** [comment]
This is your problem - the dimensions in `/entry/instrument/detector/module/data_size` are reversed compared to those of the underlying dataset in `/entry/data/`.
```
$ h5ls -d NYX-test01_33_master.h5/entry/instrument/detector/module/data_size
data_size Dataset {2}
Data:
(0) 3108, 3262

$ h5ls -rv --follow-symlinks NYX-test01_33_master.h5/entry/data
Opened "NYX-test01_33_master.h5" with sec2 driver.
/data_000001 External Link {NYX-test01_33_data_000001.h5//entry/data/data} {Dataset {500/Inf, 3262/3262, 3108/3108}
```

https://manual.nexusformat.org/classes/applications/NXmx.html#nxmx-entry-instrument-detector-detector-module-data-size-field

> data_size: (required) [NX_INT](https://manual.nexusformat.org/nxdl-types.html#nx-int)
> 
> Two or three values for the size of the module in pixels in each direction. Dimensionality and order of indices is the same as for data_origin.
>
> data_origin: (required) [NX_INT](https://manual.nexusformat.org/nxdl-types.html#nx-int)
> ...
> The [order](https://manual.nexusformat.org/datarules.html#design-arraystorageorder) of indices (i, j or i, j, k) is slow to fast.

See also: https://manual.nexusformat.org/datarules.html#design-arraystorageorder

For comparison with some recent data from DLS:
```
$ h5ls -d /dls/i03/data/2022/cm31105-4/TestProteinaseK/protk_3/protk_3_1_master.h5/entry/instrument/detector/module/data_size
data_size                Dataset {2}
    Data:
        (0) 4362, 4148

$ h5ls -rv --follow-symlinks /dls/i03/data/2022/cm31105-4/TestProteinaseK/protk_3/protk_3_1_master.h5/entry/data | head -n 2
Opened "/dls/i03/data/2022/cm31105-4/TestProteinaseK/protk_3/protk_3_1_master.h5" with sec2 driver.
/data                    Dataset {3600/Inf, 4362/4362, 4148/4148}
```

**Comment by KevinBattaile** [comment]
Thanks for the hints. I'll check if there is a misconfiguration in ADEiger and then try again.

**Comment by JunAishima** [comment]
that's strange - I looked at some data from one of our Eiger(1) detectors and it doesn't have this detector/module/data_size field. both detectors do see to have /entry/instrument/detector/detectorSpecific/[x,y]_pixels_in_detector that could be another source of this information.

could this just be an Eiger2 issue as well?

**Comment by dagewa** [comment]
I'm satisfied this can be closed, following https://github.com/dials/dials/issues/2239#issuecomment-1271286201 that notes there is inconsistent metadata.
