### ISSUE TITLE
dials.import convert_stills_to_sequences does not work with HDF5

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2252]
```
cs04r-sc-com18-02 163 :) $ dials.import -v convert_stills_to_sequence=1 scan.oscillation=0,0 ../0000163.h5 
Warning: Ambiguous parameter definition: oscillation = 0,0
Best matches:
  input.tolerance.scan.oscillation
  geometry.scan.oscillation
Assuming geometry.scan.oscillation was intended.
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 3.dev.855-g010e9a395
Warning: Ambiguous parameter definition: oscillation = 0,0
Best matches:
  input.tolerance.scan.oscillation
  geometry.scan.oscillation
Assuming geometry.scan.oscillation was intended.
The following parameters have been modified:

input {
  experiments = <image files>
}
geometry {
  scan {
    oscillation = 0 0
  }
  convert_stills_to_sequences = True
}


Applying input geometry in the following order:
  1. Manual geometry

Traceback (most recent call last):
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/src/dials/command_line/dials_import.py", line 978, in <module>
    run()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/conda_base/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/src/dials/command_line/dials_import.py", line 943, in run
    do_import(args, phil=phil, configure_logging=True)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/src/dials/command_line/dials_import.py", line 870, in do_import
    experiments = metadata_updater(imagesets)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/src/dials/command_line/dials_import.py", line 533, in __call__
    imageset = updater(imageset)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/src/dials/command_line/dials_import.py", line 360, in __call__
    imageset = self.convert_stills_to_sequence(imageset)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/src/dials/command_line/dials_import.py", line 455, in convert_stills_to_sequence
    template, indices = template_regex_from_list(imageset.paths())
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dxtbx/src/dxtbx/sequence_filenames.py", line 113, in template_regex_from_list
    return common_prefix + template, indices
TypeError: Please report this error to dials-support@lists.sourceforge.net: can only concatenate str (not "NoneType") to str
```

It would appear that teh use of this flag is hard coded to assume that the data are in separate files

**Comment by jbeilstenedmands** [comment]
See also https://github.com/dials/dials/issues/476
