### ISSUE TITLE
cannot do dials.import input.directory=... on windows 

### ISSUE THREAD

**Issue by luisodls** [dials/dials#2255]
On Linux this runs fine, but on Windows 10 I got this: 

```
>dials.import ..\diff_imgs\X4_wide
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 3.10
Traceback (most recent call last):
  File "C:\Users\luija\miniconda3\Scripts\dials.import-script.py", line 10, in <module>
    sys.exit(run())
  File "C:\Users\luija\miniconda3\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\Users\luija\miniconda3\lib\site-packages\dials\command_line\dials_import.py", line 943, in run
    do_import(args, phil=phil, configure_logging=True)
  File "C:\Users\luija\miniconda3\lib\site-packages\dials\command_line\dials_import.py", line 837, in do_import
    params, options, unhandled = parser.parse_args(
  File "C:\Users\luija\miniconda3\lib\site-packages\dials\util\options.py", line 867, in parse_args
    params, args = self._phil_parser.parse_args(
  File "C:\Users\luija\miniconda3\lib\site-packages\dials\util\options.py", line 550, in parse_args
    importer = Importer(
  File "C:\Users\luija\miniconda3\lib\site-packages\dials\util\options.py", line 202, in __init__
    self.unhandled = self.try_read_experiments_from_images(
  File "C:\Users\luija\miniconda3\lib\site-packages\dials\util\options.py", line 279, in try_read_experiments_from_images
    experiments = ExperimentListFactory.from_filenames(
  File "C:\Users\luija\miniconda3\lib\site-packages\dxtbx\model\experiment_list.py", line 535, in from_filenames
    format_class = find_format.find_format(filename)
  File "C:\Users\luija\miniconda3\lib\site-packages\dxtbx\datablock.py", line 270, in find_format
    self._format_class = get_format_class_for_file(filename)
  File "C:\Users\luija\miniconda3\lib\site-packages\dxtbx\format\Registry.py", line 122, in get_format_class_for_file
    if scheme in format_class.schemes and format_class.understand(image_file_str):
  File "C:\Users\luija\miniconda3\lib\site-packages\dxtbx\format\FormatCBF.py", line 24, in understand
    with FormatCBF.open_file(image_file, "rb") as fh:
  File "C:\Users\luija\miniconda3\lib\site-packages\dxtbx\format\Format.py", line 565, in open_file
    return cls.get_cache_controller().check(filename_str, fh_func)
  File "C:\Users\luija\miniconda3\lib\site-packages\dxtbx\filecache_controller.py", line 69, in check
    self._cache = dxtbx.filecache.lazy_file_cache(open_method())
PermissionError: [Errno 13] Permission denied: '..\\diff_imgs\\X4_wide
```

**Comment by dagewa** [comment]
Have reproduced this
