### ISSUE TITLE
dials.reciprocal_lattice_viewer: make it work for still images

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2256]
Still images can be mapped to reciprocal space _but_ `dials.reciprocal_lattice_viewer` says no

```
Grey-Area 200 :) $ dials.reciprocal_lattice_viewer indexed.*
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = indexed.expt
  reflections = indexed.refl
}

RuntimeError: Please report this error to dials-support@lists.sourceforge.net: scitbx Internal Error: /Users/graeme/git/dials/modules/cctbx_project/scitbx/math/minimum_covering_sphere.h(151): SCITBX_ASSERT(sum_w_r != 0) failure.
Traceback (most recent call last):
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/reciprocal_lattice_viewer.py", line 79, in <module>
    run()
  File "/Users/graeme/git/dials/conda_base/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/reciprocal_lattice_viewer.py", line 72, in run
    f.load_models(experiments, reflections)
  File "/Users/graeme/git/dials/modules/dials/src/dials/util/reciprocal_lattice/viewer.py", line 91, in load_models
    Render3d.load_models(self, experiments, reflections)
  File "/Users/graeme/git/dials/modules/dials/src/dials/util/reciprocal_lattice/__init__.py", line 111, in load_models
    self.set_points()
  File "/Users/graeme/git/dials/modules/dials/src/dials/util/reciprocal_lattice/viewer.py", line 163, in set_points
    Render3d.set_points(self)
  File "/Users/graeme/git/dials/modules/dials/src/dials/util/reciprocal_lattice/__init__.py", line 233, in set_points
    self.viewer.set_points(points)
  File "/Users/graeme/git/dials/modules/dials/src/dials/util/reciprocal_lattice/viewer.py", line 511, in set_points
    self.update_minimum_covering_sphere()
  File "/Users/graeme/git/dials/modules/dials/src/dials/util/reciprocal_lattice/viewer.py", line 564, in update_minimum_covering_sphere
    self.minimum_covering_sphere = minimum_covering_sphere(self.points.select(isel))
  File "/Users/graeme/git/dials/modules/cctbx_project/scitbx/math/__init__.py", line 246, in minimum_covering_sphere
    return impl(
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: scitbx Internal Error: /Users/graeme/git/dials/modules/cctbx_project/scitbx/math/minimum_covering_sphere.h(151): SCITBX_ASSERT(sum_w_r != 0) failure.
```

I understand why, but equally I think we can work around this.

**Comment by graeme-winter** [comment]
Wait, what? It seems to be workable with _integrated_ data?

**Comment by graeme-winter** [comment]
This appears to now work, and is might perty t'boot

<img width="1247" alt="Screenshot 2023-10-17 at 14 56 29" src="https://github.com/dials/dials/assets/1241716/b4c7ac61-8c92-409f-a7ea-32d0d3a708bb">
