### ISSUE TITLE
dials.combine_experiments for ImageSet jsons

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#227]
This is probably related to #226. When I run `cspad.cbf_metrology`, it crashes within `dials.combine_experiments`.

The problem is again in the fact that `self._indices` and `self._filenames` contain only one entry.
Thus, it crashes at the following lines.

```
  def paths(self):
    ''' Return a list of filenames referenced by this set. '''
    filenames = self.reader().get_image_paths()
    return [filenames[i] for i in self._indices] # HERE

  def get_path(self, index=None):
    ''' Get an image path. '''
    if index == None:
      return self._filenames[0]
    return self._filenames[index] # HERE
```

The refinement itself worked very well after my dirty hack to return a dummy string (because the filename does not matter for the metrology refinement).

After refinement on 188 images:
```
Detector 1 RMSDs by panel:
----------------------------------------------------
| Panel | Nref | RMSD_X  | RMSD_Y  | RMSD_DeltaPsi |
| id    |      | (px)    | (px)    | (deg)         |
----------------------------------------------------
| 0     | 229  | 1.0133  | 0.51942 | 0.038532      |
| 1     | 994  | 0.54302 | 0.67578 | 0.050565      |
| 2     | 983  | 0.53952 | 0.51663 | 0.043583      |
| 3     | 194  | 1.0249  | 0.44037 | 0.036991      |
| 4     | 141  | 1.0274  | 0.45503 | 0.041961      |
| 5     | 969  | 0.59563 | 0.6765  | 0.047861      |
| 6     | 995  | 0.55292 | 0.72666 | 0.047785      |
| 7     | 214  | 1.0295  | 0.58858 | 0.039778      |
----------------------------------------------------
```

Then I rerun `dials.stills_process` with the reference geometry. Now it indexed 309 images and the second refinement produced:
```
Detector 1 RMSDs by panel:
----------------------------------------------------
| Panel | Nref | RMSD_X  | RMSD_Y  | RMSD_DeltaPsi |
| id    |      | (px)    | (px)    | (deg)         |
----------------------------------------------------
| 0     | 379  | 0.59378 | 0.31889 | 0.026812      |
| 1     | 1277 | 0.29821 | 0.38569 | 0.037638      |
| 2     | 1193 | 0.29561 | 0.3033  | 0.03352       |
| 3     | 331  | 0.63555 | 0.30334 | 0.027487      |
| 4     | 304  | 0.52255 | 0.30587 | 0.027159      |
| 5     | 1242 | 0.32004 | 0.34054 | 0.033825      |
| 6     | 1316 | 0.33505 | 0.43733 | 0.037888      |
| 7     | 315  | 0.54616 | 0.27179 | 0.02869       |
----------------------------------------------------
```
(In MPCCD, panels 0, 3, 4, 7 are in the corners, so higher RMSD is reasonable)

**Comment by biochem-fan** [comment]
@jmp1985, could you please look at this? 
This seems to be related with `single_file_indices` introduced in  https://sourceforge.net/p/cctbx/code/25360/.

**Comment by phyy-nx** [comment]
Also related to #199

**Comment by biochem-fan** [comment]
Can we assume that the associated file name is the same regardless of the index when the `reader` is a singe file reader? If so, the following changes to `imageset.py` solve the problem.

In  `NullReader.get_path`
```python
    if index == None or self._single_file: #  WAS if index == None:
       return self._filenames[0]
     return self._filenames[index]
```

In `ImageSet.paths`
```python
    if self.reader().is_single_file_reader(): # ADDED
      return [filenames[0]] * len(self._indices) # ADDED
    else:
      return [filenames[i] for i in self._indices]
```

In `ImageSetFactory#make_imageset`
```python
     if format_class is None:
      reader = NullReader(filenames, single_file_indices is not None) # WAS  reader = NullReader(filenames)
```

**Comment by jmp1985** [comment]
@biochem-fan is there a simple test script I can run to reproduce this?

**Comment by biochem-fan** [comment]
Hi James, thank you very much for investigation.

Run   

```
dials.stills_process index.phil dials_regression/image_examples/SACLA_MPCCD_Cheetah/run266702-0-subset.h5
```
using `index.phil` on #226 with the following modifications in indexing parameters:
```
    method = fft1d
    refinement_protocol.d_min_start = 2.2
    stills.rmsd_min_px = 3
```
(this forces the program to accept bad solutions to make example pickles)

Now you should have three `idx-run266702-0-subset_0000N_refined_experiments.json`.

Next, run:
```
cspad.cbf_metrology index.phil .
```
This internally executes
```
dials.combine_experiments reference_from_experiment.average_detector=True reference_from_experiment.average_hierarchy_level=0 output.experiments_filename=cspad_combined_experiments.json output.reflections_filename=cspad_combined_reflections.pickle cspad_combine.phil
```
after creating several input files and dies.

```
  Traceback (most recent call last):
    File "/home/app/dials/build/../modules/dials/command_line/combine_experiments.py", line 338, in <module>
      halraiser(e)
    File "/home/app/dials/build/../modules/dials/command_line/combine_experiments.py", line 336, in <module>
      script.run()
    File "/home/app/dials/build/../modules/dials/command_line/combine_experiments.py", line 194, in run
      params, options = self.parser.parse_args(show_diff_phil=True)
    File "/home/app/dials/modules/dials/util/options.py", line 855, in parse_args
      quick_parse=quick_parse)
    File "/home/app/dials/modules/dials/util/options.py", line 533, in parse_args
      track_unused_definitions=True)
    File "/home/app/dials/modules/cctbx_project/libtbx/phil/__init__.py", line 1857, in fetch
      skip_incompatible_objects=skip_incompatible_objects)
    File "/home/app/dials/modules/cctbx_project/libtbx/phil/__init__.py", line 1881, in fetch
      source=candidate).as_str()
    File "/home/app/dials/modules/cctbx_project/libtbx/phil/__init__.py", line 1137, in extract_format
      return self.format(python_object=source.extract())
    File "/home/app/dials/modules/cctbx_project/libtbx/phil/__init__.py", line 1122, in extract
      return self._type_from_words()(self.words, master=self)
    File "/home/app/dials/modules/dials/phil.py", line 89, in from_words
      return self.from_string(libtbx.phil.str_from_words(words=words))
    File "/home/app/dials/modules/dials/phil.py", line 85, in from_string
      check_format=self._check_format))
    File "/home/app/dials/modules/cctbx_project/dxtbx/model/experiment/experiment_list.py", line 994, in from_json_file
      return ExperimentListFactory.from_json(infile.read(), check_format)
    File "/home/app/dials/modules/cctbx_project/dxtbx/model/experiment/experiment_list.py", line 984, in from_json
      check_format)
    File "/home/app/dials/modules/cctbx_project/dxtbx/model/experiment/experiment_list.py", line 969, in from_dict
      experiments = ExperimentListDict(obj, check_format).decode()
    File "/home/app/dials/modules/cctbx_project/dxtbx/model/experiment/experiment_list.py", line 447, in decode
      return self._extract_experiments()
    File "/home/app/dials/modules/cctbx_project/dxtbx/model/experiment/experiment_list.py", line 596, in _extract_experiments
      goniometer = imageset.get_goniometer()
    File "/home/app/dials/modules/cctbx_project/dxtbx/imageset.py", line 711, in get_goniometer
      return self.get_image_models(index)['goniometer']
    File "/home/app/dials/modules/cctbx_project/dxtbx/imageset.py", line 660, in get_image_models
      path = self.get_image_identifier(index)
    File "/home/app/dials/modules/cctbx_project/dxtbx/imageset.py", line 744, in get_image_identifier
      return self.get_path(index)
    File "/home/app/dials/modules/cctbx_project/dxtbx/imageset.py", line 735, in get_path
      return self.reader().get_path(self._image_index(index))
    File "/home/app/dials/modules/cctbx_project/dxtbx/imageset.py", line 94, in get_path
      return self._filenames[index]
  IndexError: Please report this error to dials-support@lists.sourceforge.net: list index out of range
```

If you apply my patch above, it then dies after refining two cycles; that is an expected behaviour (as MPCCD have only two levels instead of three in CSPAD).

**Comment by jmp1985** [comment]
So applying this patch seems to work and doesn't break any tests so I'm going to go ahead and close this ticket.

**Comment by jmp1985** [comment]
Thanks,

I'll have a look shortly.

James

________________________________

**Comment by jmp1985** [comment]
Hi Takanori,

So I've added the patch. I think dxtbx needs a good tidying though!

James
________________________________
From: Parkhurst, James (DLSLtd,RAL,LSCI)
Sent: 25 October 2016 16:14
To: dials/dials; dials/dials
Cc: Assign
Subject: RE: [dials/dials] dials.combine_experiments for ImageSet jsons (#227)

Thanks,

I'll have a look shortly.

James

________________________________
