### ISSUE TITLE
Warning message when importing gridscan data

### ISSUE THREAD

**Issue by evalott100** [dials/dials#2270]
Sat on VMXi with @graeme-winter 

```
/dls_sw/apps/dials/dials-v3-12-0/conda_base/lib/python3.9/site-packages/pint/facets/plain/quantity.py:1119: RuntimeWarning: invalid value encountered in divide
  magnitude = magnitude_op(new_self._magnitude, other._magnitude)
```

**Comment by rjgildea** [comment]
Running Python with `-W error` to get the full stack trace:
```
$ dials.python -W error $(libtbx.find_in_repositories dials)/src/dials/command_line/dials_import.py /dls/mx/data/nt30330/nt30330-15/VMXi-AB1698/well_11/images/image_58732.nxs
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 3.dev.850-g0c90509d3-release
Traceback (most recent call last):
  File "/dls/science/users/hko55533/software/cctbx/modules/dials/src/dials/command_line/dials_import.py", line 946, in <module>
    run()
  File "/dls/science/users/hko55533/software/cctbx/conda_base/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/dls/science/users/hko55533/software/cctbx/modules/dials/src/dials/command_line/dials_import.py", line 942, in run
    do_import(args, phil=phil, configure_logging=True)
  File "/dls/science/users/hko55533/software/cctbx/modules/dials/src/dials/command_line/dials_import.py", line 836, in do_import
    params, options, unhandled = parser.parse_args(
  File "/dls/science/users/hko55533/software/cctbx/modules/dials/src/dials/util/options.py", line 867, in parse_args
    params, args = self._phil_parser.parse_args(
  File "/dls/science/users/hko55533/software/cctbx/modules/dials/src/dials/util/options.py", line 550, in parse_args
    importer = Importer(
  File "/dls/science/users/hko55533/software/cctbx/modules/dials/src/dials/util/options.py", line 202, in __init__
    self.unhandled = self.try_read_experiments_from_images(
  File "/dls/science/users/hko55533/software/cctbx/modules/dials/src/dials/util/options.py", line 279, in try_read_experiments_from_images
    experiments = ExperimentListFactory.from_filenames(
  File "/dls/science/users/hko55533/software/cctbx/modules/dxtbx/src/dxtbx/model/experiment_list.py", line 551, in from_filenames
    imageset = format_class.get_imageset(
  File "/dls/science/users/hko55533/software/cctbx/modules/dxtbx/src/dxtbx/format/FormatMultiImage.py", line 161, in get_imageset
    format_instance = cls.get_instance(filenames[0], **format_kwargs)
  File "/dls/science/users/hko55533/software/cctbx/modules/dxtbx/src/dxtbx/format/Format.py", line 274, in get_instance
    Class._current_instance_ = Class(filename, **kwargs)
  File "/dls/science/users/hko55533/software/cctbx/modules/dxtbx/src/dxtbx/format/FormatNXmxDLS.py", line 65, in __init__
    super().__init__(image_file, **kwargs)
  File "/dls/science/users/hko55533/software/cctbx/modules/dxtbx/src/dxtbx/format/FormatNXmx.py", line 58, in __init__
    super().__init__(image_file, **kwargs)
  File "/dls/science/users/hko55533/software/cctbx/modules/dxtbx/src/dxtbx/format/FormatHDF5.py", line 16, in __init__
    Format.__init__(self, image_file, **kwargs)
  File "/dls/science/users/hko55533/software/cctbx/modules/dxtbx/src/dxtbx/format/Format.py", line 168, in __init__
    self.setup()
  File "/dls/science/users/hko55533/software/cctbx/modules/dxtbx/src/dxtbx/format/Format.py", line 178, in setup
    self._start()
  File "/dls/science/users/hko55533/software/cctbx/modules/dxtbx/src/dxtbx/format/FormatNXmxDLS.py", line 68, in _start
    super()._start()
  File "/dls/science/users/hko55533/software/cctbx/modules/dxtbx/src/dxtbx/format/FormatNXmx.py", line 81, in _start
    self._scan_model = dxtbx.nexus.get_dxtbx_scan(nxsample, nxdetector)
  File "/dls/science/users/hko55533/software/cctbx/modules/dxtbx/src/dxtbx/nexus/__init__.py", line 220, in get_dxtbx_scan
    if np.any(np.abs((steps - step) / step) >= 0.1):
  File "/dls/science/users/hko55533/software/cctbx/conda_base/lib/python3.9/site-packages/pint/quantity.py", line 1341, in __truediv__
    return self._mul_div(other, operator.truediv)
  File "/dls/science/users/hko55533/software/cctbx/conda_base/lib/python3.9/site-packages/pint/quantity.py", line 139, in wrapped
    return f(self, *args, **kwargs)
  File "/dls/science/users/hko55533/software/cctbx/conda_base/lib/python3.9/site-packages/pint/quantity.py", line 119, in wrapped
    result = f(self, *args, **kwargs)
  File "/dls/science/users/hko55533/software/cctbx/conda_base/lib/python3.9/site-packages/pint/quantity.py", line 1313, in _mul_div
    magnitude = magnitude_op(new_self._magnitude, other._magnitude)
RuntimeWarning: Please report this error to dials-support@lists.sourceforge.net: invalid value encountered in true_divide
```

**Comment by rjgildea** [comment]
We also get the same warning with e.g. i03 gridscan data, so this isn't specific to VMXi:
```
$ dials.import /dls/i03/data/2022/cm31105-4/xraycentring/TestThaumatin/sethau_1/sethau_1_1.nxs
```

**Comment by rjgildea** [comment]
This stems from the changes introduced in https://github.com/cctbx/dxtbx/pull/526 to use the median oscillation width (and print a warning if values differ significantly from the median). I think a minor change to the inequality would eliminate the warning:
```
$ git diff
diff --git a/src/dxtbx/nexus/__init__.py b/src/dxtbx/nexus/__init__.py
index d938b9e4..9888c378 100644
--- a/src/dxtbx/nexus/__init__.py
+++ b/src/dxtbx/nexus/__init__.py
@@ -217,10 +217,10 @@ def get_dxtbx_scan(
 
         step = np.median(steps).to("degree")
         try:
-            if np.any(np.abs((steps - step) / step) >= 0.1):
+            if np.any(np.abs(steps - step) > (0.1 * step)):
                 logger.warning(
                     "One or more recorded oscillation widths differ from the median "
-                    "by 10% or more.  The rotation axis of your goniometer may not "
+                    "by more than 10%. The rotation axis of your goniometer may not "
                     "have been scanning at a constant speed throughout the data "
                     "collection."
                 )
```

**Comment by graeme-winter** [comment]
> This stems from the changes introduced in [cctbx/dxtbx#526](https://github.com/cctbx/dxtbx/pull/526) to use the median oscillation width (and print a warning if values differ significantly from the median). I think a minor change to the inequality would eliminate the warning:
> 
> ```
> $ git diff
> diff --git a/src/dxtbx/nexus/__init__.py b/src/dxtbx/nexus/__init__.py
> index d938b9e4..9888c378 100644
> --- a/src/dxtbx/nexus/__init__.py
> +++ b/src/dxtbx/nexus/__init__.py
> @@ -217,10 +217,10 @@ def get_dxtbx_scan(
>  
>          step = np.median(steps).to("degree")
>          try:
> -            if np.any(np.abs((steps - step) / step) >= 0.1):
> +            if np.any(np.abs(steps - step) > (0.1 * step)):
>                  logger.warning(
>                      "One or more recorded oscillation widths differ from the median "
> -                    "by 10% or more.  The rotation axis of your goniometer may not "
> +                    "by more than 10%. The rotation axis of your goniometer may not "
>                      "have been scanning at a constant speed throughout the data "
>                      "collection."
>                  )
> ```

Looks like a pretty sensible diff - assume that the change from `>=` to `>` is of purely theoretical interest anyway: from the report I thought that the issue was `quantity / quantity` rather than the inequality itself?

**Comment by rjgildea** [comment]
No, the error is from the divide by zero because `steps` is zero:
```
$ dials.python
>>> import numpy as np
>>> import pint
ur>>> ureg = pint.UnitRegistry()
>>> steps = np.array([0,0,0,0,0]) * ureg.degree
>>> steps / (0.1 * ureg.degree)
<Quantity([0. 0. 0. 0. 0.], 'dimensionless')>
>>> steps / (0 * ureg.degree)
/path/to/conda_base/lib/python3.9/site-packages/pint/quantity.py:1313: RuntimeWarning: invalid value encountered in true_divide
  magnitude = magnitude_op(new_self._magnitude, other._magnitude)
<Quantity([nan nan nan nan nan], 'dimensionless')>
```

**Comment by graeme-winter** [comment]
So "from the report I thought that the issue was quantity / quantity rather than the inequality itself?" - yes the issue is the divide not the inequality 🙂 (as you are changing the inequality from `>=` to `>`)

**Comment by graeme-winter** [comment]
Anyhow the proposed fix still looks sensible @rjgildea you got this? Seems like a useful fix
