### ISSUE TITLE
no_read flag of ImageSet.get_image_models

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#228]
In `ImageSet`, `get_image_models` has `no_read` flag. Can we set this True in `set_beam`, `set_detector`, etc? 

Currently, reading combined experiment json takes very long, because `get_detector` and `get_beam` of the format class are called MANY times to read metadata from HDF5 files. But these object are soon replaced by `set_beam/detector`  with objects deserialized from the json file.

**Comment by phyy-nx** [comment]
Hi, why does reading combined_experiments.json touch the HDF5 at all?  It should be reading from a serialized json and that should be fast.  Is that not the case?

Regardless, I made the suggested change locally and ran the tests.  Things seem to be ok.  However, I'm reluctant to check it in.  Changing no_read=True like this means if you call set_beam and only set beam on an imageset but get_image_models hasn't been called before, the imageset will have None set for detector, scan and gonio.  Demonstration:

```
import libtbx.load_env, os
from dxtbx.datablock import DataBlockFactory

dr = libtbx.env.find_in_repositories("dials_regression")
assert dr is not None
path = os.path.join(dr, "image_examples", "SACLA_MPCCD_Cheetah", "run266702-0-subset.h5")

datablock = DataBlockFactory.from_filenames([path])[0]
imageset = datablock.extract_imagesets()[0]

print imageset.get_beam()

datablock = DataBlockFactory.from_filenames([path])[0]
imageset = datablock.extract_imagesets()[0]

imageset.set_goniometer(None)
print imageset.get_beam()

```
Output:

```
Beam:
    wavelength: 1.76846
    sample to source direction : {0,0,1}
    divergence: 0
    sigma divergence: 0
    polarization normal: {0,1,0}
    polarization fraction: 0.999

None
```

Here, changing the goniometer is causing the beam to go away because none of the models are being read.

Perhaps the right solution is to get rid of get_image_models and refactor the code so ImageSet only caches on read. Then set_* could use no_read correctly.  get_image_models is only used internally anyway.

Comments from @jmp1985 are appreciated :)

**Comment by biochem-fan** [comment]
> Hi, why does reading combined_experiments.json touch the HDF5 at all? It should be reading from a serialized json and that should be fast. Is that not the case?

For example, it takes very very long to run `cctbx.xfel.filter_experiments_by_rmsd` on combined experiments of 1,500 still images in an EIGER dataset. When I press Ctrl-C, it is stuck at:

```
Traceback (most recent call last):
  File "/home/app/packages/dials/build/../modules/cctbx_project/xfel/command_line/filter_experiments_by_rmsd.py", line 152, in <module>
    script.run()
  File "/home/app/packages/dials/build/../modules/cctbx_project/xfel/command_line/filter_experiments_by_rmsd.py", line 77, in run
    params, options = self.parser.parse_args(show_diff_phil=True)
  File "/home/app/packages/dials/modules/dials/util/options.py", line 841, in parse_args
    quick_parse=quick_parse)
  File "/home/app/packages/dials/modules/dials/util/options.py", line 579, in parse_args
    scan_tolerance=scan_tolerance)
  File "/home/app/packages/dials/modules/dials/util/options.py", line 296, in __init__
    self.unhandled, check_format, verbose)
  File "/home/app/packages/dials/modules/dials/util/options.py", line 383, in try_read_experiments
    self.experiments.append(converter.from_string(argument))
  File "/home/app/packages/dials/modules/dials/phil.py", line 85, in from_string
    check_format=self._check_format))
  File "/home/app/packages/dials/modules/cctbx_project/dxtbx/model/experiment/experiment_list.py", line 988, in from_json_file
    return ExperimentListFactory.from_json(infile.read(), check_format)
  File "/home/app/packages/dials/modules/cctbx_project/dxtbx/model/experiment/experiment_list.py", line 978, in from_json
    check_format)
  File "/home/app/packages/dials/modules/cctbx_project/dxtbx/model/experiment/experiment_list.py", line 963, in from_dict
    experiments = ExperimentListDict(obj, check_format).decode()
  File "/home/app/packages/dials/modules/cctbx_project/dxtbx/model/experiment/experiment_list.py", line 446, in decode
    return self._extract_experiments()
  File "/home/app/packages/dials/modules/cctbx_project/dxtbx/model/experiment/experiment_list.py", line 568, in _extract_experiments
    imageset = self._make_stills(imageset)
  File "/home/app/packages/dials/modules/cctbx_project/dxtbx/model/experiment/experiment_list.py", line 647, in _make_stills
    single_file_indices=indices)
  File "/home/app/packages/dials/modules/cctbx_project/dxtbx/imageset.py", line 1567, in make_imageset
    format_instance = format_class(filenames[0])
  File "/home/app/packages/dials/modules/cctbx_project/dxtbx/format/FormatHDFEigerNearlyNexus.py", line 264, in __init__
# ...
# somewhere depending on the timing
```

By putting a debug message in `FormatHDFEigerNearlyNexus.__init__()`, I could confirm that the dxtbx class is instantiated many times.

**Comment by biochem-fan** [comment]
Hi Aaron (@phyy-nx), I found a simple solution. Just adding `check_format=False` to the `OptionParser` of `filter_experiments_by_rmsd.py` solves the problem. `dials.combine_experiments` and `dials.refine` already have this flag.

```python
    self.parser = OptionParser(
      usage=usage,
      sort_options=True,
      phil=phil_scope,
      read_experiments=True,
      read_reflections=True,
      check_format=False, # ADDED
      epilog=help_message)
```
https://sourceforge.net/p/cctbx/code/HEAD/tree/trunk/xfel/command_line/filter_experiments_by_rmsd.py#l62

Could you please make sure this does no harm and commit this?

**Comment by phyy-nx** [comment]
Tested and checked in.  Ok to close this issue?

**Comment by biochem-fan** [comment]
Thank you very much.
