### ISSUE TITLE
exclude_images=0:1:200 not working in dials.integrate

### ISSUE THREAD

**Issue by cdavidowen** [dials/dials#2285]
DIALS 3.12.0-g13ced8fbc-release

Attempting to use format dataset_number:first_excluded_image:last_excluded_image. eg 0:1:200

dials.integrate crashes pretty quickly with a sample of the error message below. 

`Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v3-12-0/build/../modules/dials/src/dials/command_line/integrate.py", line 736, in <module>
    run()
  File "/dls_sw/apps/dials/dials-v3-12-0/conda_base/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/dls_sw/apps/dials/dials-v3-12-0/build/../modules/dials/src/dials/command_line/integrate.py", line 677, in run
    params, options = parser.parse_args(args=args, show_diff_phil=False)
  File "/dls_sw/apps/dials/dials-v3-12-0/modules/dials/src/dials/util/options.py", line 867, in parse_args
    params, args = self._phil_parser.parse_args(
  File "/dls_sw/apps/dials/dials-v3-12-0/modules/dials/src/dials/util/options.py", line 502, in parse_args
    params = self._phil.extract()
  File "/dls_sw/apps/dials/dials-v3-12-0/modules/cctbx_project/libtbx/phil/__init__.py", line 1782, in extract
    value = object.extract(parent=result)
  File "/dls_sw/apps/dials/dials-v3-12-0/modules/cctbx_project/libtbx/phil/__init__.py", line 1145, in extract
    return self._type_from_words()(self.words, master=self)
  File "/dls_sw/apps/dials/dials-v3-12-0/modules/cctbx_project/libtbx/phil/__init__.py", line 452, in from_words
    numbers = numbers_from_words(words=words, path=path)
  File "/dls_sw/apps/dials/dials-v3-12-0/modules/cctbx_project/libtbx/phil/__init__.py", line 249, in numbers_from_words
    result.append(number_from_value_string(
  File "/dls_sw/apps/dials/dials-v3-12-0/modules/cctbx_project/libtbx/phil/__init__.py", line 223, in number_from_value_string
    raise RuntimeError(
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: Error interpreting exclude_images="0:1:100" as a numeric expression: SyntaxError: invalid syntax (line 1) (command line argument, line 1)
`
It doesn't crash in the same when I use commas instead of colons but I am also not convinced it is actually excluding the images.

**Comment by dagewa** [comment]
Hi @cdavidowen, unfortunately `dials.integrate` and `dials.scale` use a different syntax for the same-named parameter `exclude_images`. The `dials.integrate` version uses a comma-separated list of individual images to exclude. I'm not sure how to specify individual experiments within that version. The behaviour of the `dials.integrate` version has also confused me in the past, documented at #1992.

I think we need a more consistent way of specifying image exclusions across the DIALS programs. I can't find an issue for that topic exactly, so I'll rename this one accordingly. Note also #1363, which is related, but limited to consistency _within_ `dials.scale` between inclusions and exclusions.

**Comment by dagewa** [comment]
NB #2111 is also related
