### ISSUE TITLE
dials.scale absorption=medium shows a stack trace

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2330]
Probably to be avoided on the User Should Not See A Stack Trace principle:

```
ws448 work :) $ dials.scale symmetrized.* absorption=medium
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v3-12-1-2/build/../modules/dials/src/dials/command_line/scale.py", line 262, in <module>
    run()
  File "/dls_sw/apps/dials/dials-v3-12-1-2/conda_base/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/dls_sw/apps/dials/dials-v3-12-1-2/build/../modules/dials/src/dials/command_line/scale.py", line 217, in run
    params, options = parser.parse_args(args=args, show_diff_phil=False)
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/dials/src/dials/util/options.py", line 867, in parse_args
    params, args = self._phil_parser.parse_args(
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/dials/src/dials/util/options.py", line 502, in parse_args
    params = self._phil.extract()
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/cctbx_project/libtbx/phil/__init__.py", line 1782, in extract
    value = object.extract(parent=result)
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/cctbx_project/libtbx/phil/__init__.py", line 1782, in extract
    value = object.extract(parent=result)
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/cctbx_project/libtbx/phil/__init__.py", line 1782, in extract
    value = object.extract(parent=result)
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/cctbx_project/libtbx/phil/__init__.py", line 1145, in extract
    return self._type_from_words()(self.words, master=self)
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/cctbx_project/libtbx/phil/__init__.py", line 192, in from_words
    return bool_from_words(words=words, path=master.full_path())
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/cctbx_project/libtbx/phil/__init__.py", line 181, in bool_from_words
    raise RuntimeError(
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: One True or False value expected, physical.share.absorption="medium" found (command line argument, line 1)
```

**Comment by graeme-winter** [comment]
I was trying to get to `absorption_level=medium` which is legitimate

**Comment by rjgildea** [comment]
I think this issue is more general than `dials.scale` - it is a question of the phil error handling in the DIALS `ArgumentParser` and would affect any command line parameter where the user provides an incompatible type, e.g.:
```
$ dials.find_spots nproc=foo
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/cctbx_project/libtbx/phil/__init__.py", line 220, in number_from_value_string
    try: return eval(value_string, math.__dict__, {})
  File "<string>", line 1, in <module>
NameError: name 'foo' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v3-12-1-2/build/../modules/dials/src/dials/command_line/find_spots.py", line 242, in <module>
    run()
  File "/dls_sw/apps/dials/dials-v3-12-1-2/conda_base/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/dls_sw/apps/dials/dials-v3-12-1-2/build/../modules/dials/src/dials/command_line/find_spots.py", line 219, in run
    params, options = parser.parse_args(args=args, show_diff_phil=False)
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/dials/src/dials/util/options.py", line 867, in parse_args
    params, args = self._phil_parser.parse_args(
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/dials/src/dials/util/options.py", line 502, in parse_args
    params = self._phil.extract()
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/cctbx_project/libtbx/phil/__init__.py", line 1782, in extract
    value = object.extract(parent=result)
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/cctbx_project/libtbx/phil/__init__.py", line 1782, in extract
    value = object.extract(parent=result)
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/cctbx_project/libtbx/phil/__init__.py", line 1782, in extract
    value = object.extract(parent=result)
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/cctbx_project/libtbx/phil/__init__.py", line 1145, in extract
    return self._type_from_words()(self.words, master=self)
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/cctbx_project/libtbx/phil/__init__.py", line 333, in from_words
    value = self._value_from_words(words=words, path=master.full_path())
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/cctbx_project/libtbx/phil/__init__.py", line 361, in _value_from_words
    return int_from_words(words=words, path=path)
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/cctbx_project/libtbx/phil/__init__.py", line 270, in int_from_words
    result = number_from_words(words=words, path=path)
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/cctbx_project/libtbx/phil/__init__.py", line 228, in number_from_words
    return number_from_value_string(
  File "/dls_sw/apps/dials/dials-v3-12-1-2/modules/cctbx_project/libtbx/phil/__init__.py", line 223, in number_from_value_string
    raise RuntimeError(
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: Error interpreting spotfinder.mp.nproc="foo" as a numeric expression: NameError: name 'foo' is not defined (command line argument, line 1)
```
