### ISSUE TITLE
Little graphical issues with macOS Ventura / M2

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2340]
Probably other combinations have the same issue - greyed out buttons - 

<img width="1800" alt="Screenshot 2023-02-13 at 16 32 29" src="https://user-images.githubusercontent.com/1241716/218516312-f33100e7-a270-4121-935a-bb05169781e9.png">

I will add more to issue as I find

**Comment by graeme-winter** [comment]
On RLV close, wall-of-errors 

```
Ethics-Gradient work :) $ dials.reciprocal_lattice_viewer refined.*
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = refined.expt
  reflections = refined.refl
}

TypeError: DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'
Traceback (most recent call last):
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 60, in <lambda>
    self.Bind(wx.EVT_PAINT, lambda evt: self.__DrawButtons())
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 224, in __DrawButtons
    gc.DrawRectangle(current_x, current_y, seg_w, seg_h)
TypeError: DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'

TypeError: DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'
Traceback (most recent call last):
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 60, in <lambda>
    self.Bind(wx.EVT_PAINT, lambda evt: self.__DrawButtons())
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 224, in __DrawButtons
    gc.DrawRectangle(current_x, current_y, seg_w, seg_h)
TypeError: DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'

TypeError: DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'
Traceback (most recent call last):
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 60, in <lambda>
    self.Bind(wx.EVT_PAINT, lambda evt: self.__DrawButtons())
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 224, in __DrawButtons
    gc.DrawRectangle(current_x, current_y, seg_w, seg_h)
TypeError: DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'

TypeError: DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'
Traceback (most recent call last):
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 60, in <lambda>
    self.Bind(wx.EVT_PAINT, lambda evt: self.__DrawButtons())
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 224, in __DrawButtons
    gc.DrawRectangle(current_x, current_y, seg_w, seg_h)
TypeError: DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'

TypeError: DC.DrawLine(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'float'
Traceback (most recent call last):
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 60, in <lambda>
    self.Bind(wx.EVT_PAINT, lambda evt: self.__DrawButtons())
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 207, in __DrawButtons
    dc.DrawLine(current_x, self._border + 1, current_x,
TypeError: DC.DrawLine(): arguments did not match any overloaded call:
  overload 1: argument 1 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'float'

TypeError: DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'
Traceback (most recent call last):
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 60, in <lambda>
    self.Bind(wx.EVT_PAINT, lambda evt: self.__DrawButtons())
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 224, in __DrawButtons
    gc.DrawRectangle(current_x, current_y, seg_w, seg_h)
TypeError: DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'

TypeError: DC.DrawText(): arguments did not match any overloaded call:
  overload 1: argument 2 has unexpected type 'float'
  overload 2: argument 2 has unexpected type 'float'
Traceback (most recent call last):
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 60, in <lambda>
    self.Bind(wx.EVT_PAINT, lambda evt: self.__DrawButtons())
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 257, in __DrawButtons
    gc.DrawText(label, txt_x, txt_y)
TypeError: DC.DrawText(): arguments did not match any overloaded call:
  overload 1: argument 2 has unexpected type 'float'
  overload 2: argument 2 has unexpected type 'float'

TypeError: DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'
Traceback (most recent call last):
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 60, in <lambda>
    self.Bind(wx.EVT_PAINT, lambda evt: self.__DrawButtons())
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 224, in __DrawButtons
    gc.DrawRectangle(current_x, current_y, seg_w, seg_h)
TypeError: DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'

TypeError: DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'
Traceback (most recent call last):
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 60, in <lambda>
    self.Bind(wx.EVT_PAINT, lambda evt: self.__DrawButtons())
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 224, in __DrawButtons
    gc.DrawRectangle(current_x, current_y, seg_w, seg_h)
TypeError: DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'

No action for this key stroke.
TypeError: DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'
Traceback (most recent call last):
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 60, in <lambda>
    self.Bind(wx.EVT_PAINT, lambda evt: self.__DrawButtons())
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 224, in __DrawButtons
    gc.DrawRectangle(current_x, current_y, seg_w, seg_h)
TypeError: DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'

TypeError: DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'
Traceback (most recent call last):
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 60, in <lambda>
    self.Bind(wx.EVT_PAINT, lambda evt: self.__DrawButtons())
  File "/Users/graeme/git/dials/modules/cctbx_project/wxtbx/segmentedctrl.py", line 224, in __DrawButtons
    gc.DrawRectangle(current_x, current_y, seg_w, seg_h)
TypeError: DC.DrawRectangle(): arguments did not match any overloaded call:
  overload 1: argument 3 has unexpected type 'float'
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'

Fatal Python error: Segmentation fault

Current thread 0x000000020dd92500 (most recent call first):
  File "/Users/graeme/git/dials/conda_base/lib/python3.10/site-packages/wx/core.py", line 2262 in MainLoop
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/reciprocal_lattice_viewer.py", line 75 in run
  File "/Users/graeme/git/dials/conda_base/lib/python3.10/contextlib.py", line 79 in inner
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/reciprocal_lattice_viewer.py", line 79 in <module>

Extension modules: wx._core, boost_python_meta_ext, boost_optional_ext, std_pair_ext, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, scitbx_array_family_flex_ext, scitbx_stl_set_ext, scitbx_stl_vector_ext, scitbx_stl_map_ext, scitbx_random_ext, orderedset._orderedset, cctbx_array_family_flex_ext, cctbx_crystal_ext, scitbx_array_family_shared_ext, cctbx_uctbx_ext, cctbx_sgtbx_ext, boost_rational_ext, cctbx_covariance_ext, cctbx_geometry_ext, scitbx_cubicle_neighbors_ext, dxtbx_format_image_ext, dxtbx_imageset_ext, dxtbx_ext, _pycbf, dxtbx_model_ext, cctbx_eltbx_attenuation_coefficient_ext, sklearn.__check_build._check_build, scipy._lib._ccallback_c, scipy.sparse._sparsetools, scipy.sparse._csparsetools, scipy.sparse.linalg._isolve._iterative, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg._cythonized_array_utils, scipy.linalg._flinalg, scipy.linalg._solve_toeplitz, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_lapack, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, sklearn.utils.murmurhash, psutil._psutil_osx, psutil._psutil_posix, numpy.linalg.lapack_lite, scipy.spatial._ckdtree, scipy._lib.messagestream, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.spatial.transform._rotation, scipy.ndimage._nd_image, _ni_label, scipy.ndimage._ni_label, scipy.optimize._minpack2, scipy.optimize._group_columns, scipy.optimize._trlib._trlib, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize.__nnls, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.optimize._direct, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.integrate._lsoda, scipy.special.cython_special, scipy.stats._stats, beta_ufunc, scipy.stats._boost.beta_ufunc, binom_ufunc, scipy.stats._boost.binom_ufunc, nbinom_ufunc, scipy.stats._boost.nbinom_ufunc, hypergeom_ufunc, scipy.stats._boost.hypergeom_ufunc, ncf_ufunc, scipy.stats._boost.ncf_ufunc, ncx2_ufunc, scipy.stats._boost.ncx2_ufunc, nct_ufunc, scipy.stats._boost.nct_ufunc, skewnorm_ufunc, scipy.stats._boost.skewnorm_ufunc, invgauss_ufunc, scipy.stats._boost.invgauss_ufunc, scipy.interpolate._fitpack, scipy.interpolate.dfitpack, scipy.interpolate._bspl, scipy.interpolate._ppoly, scipy.interpolate.interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, scipy.stats._biasedurn, scipy.stats._levy_stable.levyst, scipy.stats._stats_pythran, scipy._lib._uarray._uarray, scipy.stats._statlib, scipy.stats._mvn, scipy.stats._sobol, scipy.stats._qmc_cy, scipy.stats._rcont.rcont, sklearn.utils._isfinite, sklearn.utils._openmp_helpers, sklearn.utils._logistic_sigmoid, sklearn.utils.sparsefuncs_fast, sklearn.preprocessing._csr_polynomial_expansion, sklearn.utils._typedefs, sklearn.utils._readonly_array_wrapper, sklearn.metrics._dist_metrics, sklearn.metrics.cluster._expected_mutual_info_fast, sklearn.metrics._pairwise_distances_reduction._datasets_pair, sklearn.utils._cython_blas, sklearn.metrics._pairwise_distances_reduction._base, sklearn.metrics._pairwise_distances_reduction._middle_term_computer, sklearn.utils._heap, sklearn.utils._sorting, sklearn.metrics._pairwise_distances_reduction._argkmin, sklearn.utils._vector_sentinel, sklearn.metrics._pairwise_distances_reduction._radius_neighbors, sklearn.metrics._pairwise_fast, sklearn.neighbors._partition_nodes, sklearn.neighbors._ball_tree, sklearn.neighbors._kd_tree, sklearn.decomposition._cdnmf_fast, sklearn.utils._random, sklearn.utils._seq_dataset, sklearn.utils.arrayfuncs, sklearn.linear_model._cd_fast, sklearn._loss._loss, sklearn.utils._weight_vector, sklearn.linear_model._sgd_fast, sklearn.linear_model._sag_fast, sklearn.svm._libsvm, sklearn.svm._liblinear, sklearn.svm._libsvm_sparse, sklearn.decomposition._online_lda_fast, sklearn._isotonic, sklearn.manifold._utils, sklearn.tree._utils, sklearn.tree._tree, sklearn.tree._splitter, sklearn.tree._criterion, sklearn.neighbors._quad_tree, sklearn.manifold._barnes_hut_tsne, sklearn.cluster._k_means_common, sklearn.cluster._k_means_minibatch, sklearn.cluster._k_means_lloyd, sklearn.cluster._k_means_elkan, sklearn.utils._fast_dict, sklearn.cluster._hierarchical_fast, sklearn.cluster._dbscan_inner, omptbx_ext, dials_model_data_ext, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.tslib, pandas._libs.lib, pandas._libs.hashing, pandas._libs.ops, pandas._libs.arrays, pandas._libs.index, pandas._libs.join, pandas._libs.sparse, pandas._libs.reduction, pandas._libs.indexing, pandas._libs.internals, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.tslibs.strptime, pandas._libs.groupby, pandas._libs.testing, pandas._libs.parsers, pandas._libs.json, annlib_ext, cctbx_miller_ext, cctbx_asymmetric_map_ext, cctbx_maptbx_ext, scitbx_math_ext, scitbx_linalg_ext, cctbx_adptbx_ext, scitbx_fftpack_ext, dials_util_ext, dials_array_family_flex_ext, gltbx_gl_ext, gltbx_fonts_ext, gltbx_glu_ext, gltbx_util_ext, wx._glcanvas (total: 250)
Segmentation fault: 11
```

**Comment by dagewa** [comment]
I suspect these were fixed by #2365

**Comment by graeme-winter** [comment]
Thank you - I will update later and test it out

**Comment by dagewa** [comment]
Any update here @graeme-winter ? I think this should be fixed now

**Comment by graeme-winter** [comment]
Well reminded @dagewa; the issues are indeed resolved thank you
