### ISSUE TITLE
dials 3.14.0 release error in reciprocal lattice viewer

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2395]
Stack trace on execution of `dials.reciprocal_lattice_viewer` in release 3.14.0

```
ws448 bug :) $ dials.reciprocal_lattice_viewer imported.expt strong.refl 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = imported.expt
  reflections = strong.refl
}

Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v3-14-0/build/../modules/dials/src/dials/command_line/reciprocal_lattice_viewer.py", line 79, in <module>
    run()
  File "/dls_sw/apps/dials/dials-v3-14-0/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/dls_sw/apps/dials/dials-v3-14-0/build/../modules/dials/src/dials/command_line/reciprocal_lattice_viewer.py", line 63, in run
    a = wxtbx.app.CCTBXApp(0, gtk_suppress_diagnostics=True)
  File "/dls_sw/apps/dials/dials-v3-14-0/modules/cctbx_project/wxtbx/app.py", line 9, in __init__
    wx.App.__init__(self, *args, **kwds)
TypeError: Please report this error to dials-support@lists.sourceforge.net: App.__init__() got an unexpected keyword argument 'gtk_suppress_diagnostics'
```

**Comment by graeme-winter** [comment]
Also issue for geometry viewer

**Comment by ndevenish** [comment]
This has been reverted in the release. I don't think we need to do this on main also, because builds on main should have the changes in cctbx that the release was missing. So I'm closing this as fixed, and next release we should make sure to bump the dependent cctbx version.
