### ISSUE TITLE
`dials.model_background` fails for datasets that do not start at image 1

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2405]
This was reported by a user, and I have reproduced using test data:

```
dials.import $(dials.data get -q insulin)/insulin_1_0{05..45}.img
dials.find_spots imported.expt 
dials.index imported.expt strong.refl 
dials.refine indexed.expt indexed.refl 
dials.integrate refined.expt refined.refl 
dials.model_background integrated.expt
```
fails with

```
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/algorithms/integration/image_integrator.py", line 167, in __call__
    imageset = imageset[index0:index1]
  File "/home/fcx32934/sw/cctbx/modules/dxtbx/src/dxtbx/imageset.py", line 330, in __getitem__
    return self.partial_set(reader, start, stop)
OverflowError: can't convert negative value to unsigned int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/model_background.py", line 307, in <module>
    run()
  File "/home/fcx32934/sw/cctbx/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/model_background.py", line 303, in run
    script.run(args)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/model_background.py", line 276, in run
    model = modeller.compute()
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/algorithms/background/modeller.py", line 340, in compute
    _, time_info = processor.process()
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/algorithms/integration/image_integrator.py", line 100, in process
    self.manager.accumulate(task())
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/algorithms/integration/image_integrator.py", line 169, in __call__
    raise RuntimeError("Programmer Error: bad array range")
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: Programmer Error: bad array range
```
The block of code being executed is something to do with slicing an imageset
https://github.com/dials/dials/blob/f11792932d3cf67086b48098d91078ddb74f60c2/src/dials/algorithms/integration/image_integrator.py#L157-L169
Here, `index0 == 0` and `index1 == 1`. However, the first single slice that works in this case is `imageset[4:5]`

**Comment by dagewa** [comment]
Fixed by #2411
