### ISSUE TITLE
`dials.model_background` only works with one experiment

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2406]
User data has a split crystal, indexed with two lattices diffracting about equally strongly, and ice rings. Attempting to run `dials.model_background` appears to start well, but then fails on an assert that there is only one lattice:
```
$ dials.model_background integrated.expt 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 3.dev.966-g5249789f0
The following parameters have been modified:

input {
  experiments = integrated.expt
}


================================================================================

Predicting reflections

Prediction type: scan varying crystal prediction
Predicted 2213279 reflections
Prediction type: scan varying crystal prediction
Predicted 2214320 reflections
 Processing the following experiments:

 Experiments: 2
 Beams:       1
 Detectors:   1
 Goniometers: 1
 Scans:       1
 Crystals:    2
 Imagesets:   1

================================================================================

Modelling background

Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/model_background.py", line 307, in <module>
    run()
  File "/home/fcx32934/sw/cctbx/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/model_background.py", line 303, in run
    script.run(args)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/model_background.py", line 276, in run
    model = modeller.compute()
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/algorithms/background/modeller.py", line 337, in compute
    processor.executor = BackgroundModellerExecutor(self.experiments, self.params)
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/algorithms/background/modeller.py", line 180, in __init__
    assert len(experiments) == 1
AssertionError: Please report this error to dials-support@lists.sourceforge.net:
```
I can split the experiments and process each half separately, but it seems to me this would be doing the wrong thing: the global background model should be excluding reflections from both lattices.

**Comment by dagewa** [comment]
Mentioned again today by users at DESY
