### ISSUE TITLE
dials.image_viewer gave an error when 'Show hkl' is checked without 'Show predictions'

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#241]
```
Traceback (most recent call last):
  File "/home/packages/dials/modules/dials/util/spotfinder_frame.py", line 1440, in OnUpdateCM
    self.GetParent().GetParent().update_settings(layout=False)
  File "/home/packages/dials/modules/dials/util/spotfinder_frame.py", line 694, in update_settings
    spotfinder_data = self.get_spotfinder_data()
  File "/home/packages/dials/modules/dials/util/spotfinder_frame.py", line 1060, in get_spotfinder_data
    miller_indices_data.append((x, y, str(reflection['miller_index']),
UnboundLocalError: local variable 'x' referenced before assignment
```

**Comment by biochem-fan** [comment]
I need this because small circles from "show predictions" tend to overlap and hide reflections.
