### ISSUE TITLE
Reciprocal Lattice Viewer: scitbx Internal Error: /.../cctbx_project/scitbx/math/minimum_covering_sphere.h(151): SCITBX_ASSERT(sum_w_r != 0) failure

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2418]
```
ws460 gw-test :( $ dials.reciprocal_lattice_viewer indexed.* d_min=0.6
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

d_min = 0.6
input {
  experiments = indexed.expt
  reflections = indexed.refl
}

Gtk-Message: 15:33:03.983: Failed to load module "pk-gtk-module"
Gtk-Message: 15:33:03.984: Failed to load module "canberra-gtk-module"
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: scitbx Internal Error: /scratch/jenkins_agent/workspace/dials_patch_release/build_dials/modules/cctbx_project/scitbx/math/minimum_covering_sphere.h(151): SCITBX_ASSERT(sum_w_r != 0) failure.
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v3-14-1-1/build/../modules/dials/src/dials/command_line/reciprocal_lattice_viewer.py", line 79, in <module>
    run()
  File "/dls_sw/apps/dials/dials-v3-14-1-1/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/dls_sw/apps/dials/dials-v3-14-1-1/build/../modules/dials/src/dials/command_line/reciprocal_lattice_viewer.py", line 72, in run
    f.load_models(experiments, reflections)
  File "/dls_sw/apps/dials/dials-v3-14-1-1/modules/dials/src/dials/util/reciprocal_lattice/viewer.py", line 91, in load_models
    Render3d.load_models(self, experiments, reflections)
  File "/dls_sw/apps/dials/dials-v3-14-1-1/modules/dials/src/dials/util/reciprocal_lattice/__init__.py", line 111, in load_models
    self.set_points()
  File "/dls_sw/apps/dials/dials-v3-14-1-1/modules/dials/src/dials/util/reciprocal_lattice/viewer.py", line 163, in set_points
    Render3d.set_points(self)
  File "/dls_sw/apps/dials/dials-v3-14-1-1/modules/dials/src/dials/util/reciprocal_lattice/__init__.py", line 233, in set_points
    self.viewer.set_points(points)
  File "/dls_sw/apps/dials/dials-v3-14-1-1/modules/dials/src/dials/util/reciprocal_lattice/viewer.py", line 511, in set_points
    self.update_minimum_covering_sphere()
  File "/dls_sw/apps/dials/dials-v3-14-1-1/modules/dials/src/dials/util/reciprocal_lattice/viewer.py", line 564, in update_minimum_covering_sphere
    self.minimum_covering_sphere = minimum_covering_sphere(self.points.select(isel))
  File "/dls_sw/apps/dials/dials-v3-14-1-1/modules/cctbx_project/scitbx/math/__init__.py", line 246, in minimum_covering_sphere
    return impl(
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: scitbx Internal Error: /scratch/jenkins_agent/workspace/dials_patch_release/build_dials/modules/cctbx_project/scitbx/math/minimum_covering_sphere.h(151): SCITBX_ASSERT(sum_w_r != 0) failure.


```

**Comment by graeme-winter** [comment]
Offending data

[indexed.zip](https://github.com/dials/dials/files/11600624/indexed.zip)

**Comment by dagewa** [comment]
Indeed there is something off with this data. All reciprocal lattice points map to the origin:
```
(base) fcx32934@nedvedice:~/Downloads/foo$ dials.python 
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dxtbx.model.experiment_list import ExperimentList
>>> el=ExperimentList.from_file("indexed.expt", check_format=False)
>>> from dials.array_family import flex
>>> rt=flex.reflection_table.from_file("indexed.refl")
>>> rt.map_centroids_to_reciprocal_space(el)
>>> x,y,z=rt["rlp"].parts()
>>> x.all_eq(0)
True
>>> y.all_eq(0)
True
>>> z.all_eq(0)
True
>>>
```

**Comment by graeme-winter** [comment]
> Indeed there is something off with this data. All reciprocal lattice points map to the origin:
> 
> ```
> (base) fcx32934@nedvedice:~/Downloads/foo$ dials.python 
> Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from dxtbx.model.experiment_list import ExperimentList
> >>> el=ExperimentList.from_file("indexed.expt", check_format=False)
> >>> from dials.array_family import flex
> >>> rt=flex.reflection_table.from_file("indexed.refl")
> >>> rt.map_centroids_to_reciprocal_space(el)
> >>> x,y,z=rt["rlp"].parts()
> >>> x.all_eq(0)
> True
> >>> y.all_eq(0)
> True
> >>> z.all_eq(0)
> True
> >>>
> ```

Well now, that _is_ interesting. I shall investigate. I promise you that I had done nothing "interesting" to get this data 🤔

**Comment by dagewa** [comment]
@graeme-winter any further discoveries with this, or should I close it?

**Comment by graeme-winter** [comment]
Weird, closing
