### ISSUE TITLE
dials.integrate dynamic mask bug

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#243]
I believe that there is a bug in dials.integrate using multiple processors, whereby the integration is not always using the mask from the correct image. The following patch highlights the bug:
```
$ git diff dxtbx/imageset.py
diff --git a/dxtbx/imageset.py b/dxtbx/imageset.py
index 7168be8..af2f581 100644
--- a/dxtbx/imageset.py
+++ b/dxtbx/imageset.py
@@ -594,6 +594,9 @@ class ImageSet(object):
     # Check for a dynamic mask
     if goniometer is None:
       goniometer = self.get_goniometer(index)
+    path1 = self.reader().get_format(index).get_image_file()
+    path2 = self.get_path(index)
+    assert path1 == path2, (path1, path2)
     dyn_mask = self.reader().get_format(index).get_mask(goniometer=goniometer)
     if dyn_mask is None:
```

Running dials.integrate on e.g. X4_wide test dataset using nproc=8 shows that the imageset get_mask() function is getting the format object for the wrong image file:
```
Traceback (most recent call last):
  File "/home/hko55533/software/cctbx/build/../modules/dials/command_line/integrate.py", line 497, in <module>
    halraiser(e)
  File "/home/hko55533/software/cctbx/build/../modules/dials/command_line/integrate.py", line 495, in <module>
    script.run()
  File "/home/hko55533/software/cctbx/build/../modules/dials/command_line/integrate.py", line 288, in run
    reflections = integrator.integrate()
  File "/home/hko55533/software/cctbx/modules/dials/algorithms/integration/integrator.py", line 982, in integrate
    reference, profile_fitter_list, time_info = processor.process()
  File "/home/hko55533/software/cctbx/modules/dials/algorithms/integration/processor.py", line 248, in process
    preserve_exception_message=True)
  File "/home/hko55533/software/cctbx/modules/cctbx_project/libtbx/easy_mp.py", line 623, in parallel_map
    result = res()
  File "/home/hko55533/software/cctbx/modules/cctbx_project/libtbx/scheduling/result.py", line 119, in __call__
    self.traceback( exception = self.exception() )
  File "/home/hko55533/software/cctbx/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 115, in __call__
    self.raise_handler( exception = exception )
  File "/home/hko55533/software/cctbx/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 145, in raise_with_stacktrace
    self.stacktrace( exception = exception )
  File "/home/hko55533/software/cctbx/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 86, in __call__
    raise exception
AssertionError: Please report this error to dials-support@lists.sourceforge.net: ('/home/hko55533/software/cctbx/build/xia2_regression/test_data/X4_wide/X4_wide_M1S4_2_0001.cbf', '/home/hko55533/software/cctbx/build/xia2_regression/test_data/X4_wide/X4_wide_M1S4_2_0024.cbf')
```

**Comment by jmp1985** [comment]
Added a get_format method to imageset which fixes this.
