### ISSUE TITLE
reciprocal_lattice_viewer not working on Windows

### ISSUE THREAD

**Issue by xjxrjx** [dials/dials#2443]
When trying to view my reciprocal lattice using XDS output files, I ran into an issue. I ran
```powershell
dials.reciprocal_lattice_viewer xds_models.expt strong.refl
``` 
and received this as output:
```powershell
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\DIALS\lib\site-packages\boost_adaptbx\boost\python.py", line 22, in import_ext
    try: mod = __import__(name)
ImportError: DLL load failed while importing gltbx_glu_ext: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\DIALS\Scripts\dials.reciprocal_lattice_viewer-script.py", line 6, in <module>
    from dials.command_line.reciprocal_lattice_viewer import run
  File "C:\Users\user\anaconda3\envs\DIALS\lib\site-packages\dials\command_line\reciprocal_lattice_viewer.py", line 16, in <module>
    from dials.util.reciprocal_lattice.viewer import ReciprocalLatticeViewer, phil_scope
  File "C:\Users\user\anaconda3\envs\DIALS\lib\site-packages\dials\util\reciprocal_lattice\viewer.py", line 22, in <module>
    from dials.util import wx_viewer
  File "C:\Users\user\anaconda3\envs\DIALS\lib\site-packages\dials\util\wx_viewer.py", line 14, in <module>
    import gltbx.glu as glu
  File "C:\Users\user\anaconda3\envs\DIALS\lib\site-packages\gltbx\glu.py", line 3, in <module>
    ext = bp.import_ext("gltbx_glu_ext")
  File "C:\Users\user\anaconda3\envs\DIALS\lib\site-packages\boost_adaptbx\boost\python.py", line 31, in import_ext
    raise ImportError(
ImportError: __import__("gltbx_glu_ext"): DLL load failed while importing gltbx_glu_ext: A dynamic link library (DLL) initialization routine failed.
``` 
I am running DIALS on windows 11; it is installed in a python 3.10 environment using conda. I tried installing TensorFlow, as this can apparently help with DLL loading issues, but nothing changed. 

I'd be grateful for any help :)

**Comment by xjxrjx** [comment]
I forgot to add that I also get the sys.path as output:
```powershell
sys.path:
    C:\Users\user\anaconda3\envs\DIALS\Scripts
    C:\Program Files\PerkinElmerInformatics\ChemOffice2021\ChemScript\Lib
    C:\Users\user\anaconda3\envs\DIALS\python310.zip
    C:\Users\user\anaconda3\envs\DIALS\DLLs
    C:\Users\user\anaconda3\envs\DIALS\lib
    C:\Users\user\anaconda3\envs\DIALS
    C:\Users\user\anaconda3\envs\DIALS\lib\site-packages
    C:\Users\user\anaconda3\envs\DIALS\lib\site-packages\cctbx_base-2023.5-py3.10.egg
```

**Comment by ndevenish** [comment]
@bkpoon @phyy-nx do you know any outstanding issues with gltbx on conda-forge windows installs?

**Comment by dagewa** [comment]
I've just reproduced this, on Windows 10. For reference,
```
conda 23.5.0
DIALS 3.15
Python 3.11.4
```

**Comment by dagewa** [comment]
Hmm, this also failed similarly on my latest local build, following https://github.com/dials/dials/wiki/DIALS-on-Windows
```
dials.rlv imported.expt strong.refl
Traceback (most recent call last):
  File "c:\Users\fcx32934\sw\cctbx\modules\cctbx_project\boost_adaptbx\boost\python.py", line 22, in import_ext
    try: mod = __import__(name)
ImportError: DLL load failed while importing gltbx_glu_ext: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\fcx32934\sw\cctbx\modules\dials\src\dials\command_line\reciprocal_lattice_viewer.py", line 16, in <module>
    from dials.util.reciprocal_lattice.viewer import ReciprocalLatticeViewer, phil_scope
  File "c:\Users\fcx32934\sw\cctbx\modules\dials\src\dials\util\reciprocal_lattice\viewer.py", line 22, in <module>
    from dials.util import wx_viewer
  File "c:\Users\fcx32934\sw\cctbx\modules\dials\src\dials\util\wx_viewer.py", line 14, in <module>
    import gltbx.glu as glu
  File "c:\Users\fcx32934\sw\cctbx\modules\cctbx_project\gltbx\glu.py", line 3, in <module>
    ext = bp.import_ext("gltbx_glu_ext")
  File "c:\Users\fcx32934\sw\cctbx\modules\cctbx_project\boost_adaptbx\boost\python.py", line 31, in import_ext
    raise ImportError(
ImportError: __import__("gltbx_glu_ext"): DLL load failed while importing gltbx_glu_ext: A dynamic link library (DLL) initialization routine failed.
  sys.path:
    c:\Users\fcx32934\sw\cctbx\modules\dials\src\dials\command_line
    c:\Users\fcx32934\sw\cctbx\modules\xia2\src
    c:\Users\fcx32934\sw\cctbx\modules\dials\src
    c:\Users\fcx32934\sw\cctbx\modules\dxtbx\src
    c:\Users\fcx32934\sw\cctbx\modules\cctbx_project
    c:\Users\fcx32934\sw\cctbx\modules
    c:\Users\fcx32934\sw\cctbx\modules\cctbx_project\boost_adaptbx
    c:\Users\fcx32934\sw\cctbx\build\lib
    c:\Users\fcx32934\sw\cctbx\conda_base\lib\site-packages
    c:\Users\fcx32934\sw\cctbx\conda_base
    C:\Users\fcx32934\dials-test
    c:\Users\fcx32934\sw\cctbx\conda_base\python310.zip
    c:\Users\fcx32934\sw\cctbx\conda_base\DLLs
    c:\Users\fcx32934\sw\cctbx\conda_base\lib
```

**Comment by dagewa** [comment]
@xjxrjx, as a workaround, if you install napari you can try this alternative reciprocal lattice viewer instead:
```
dev.dials.napari_rlv xds_models.expt strong.refl
```

**Comment by dagewa** [comment]
I just tried an updated build on Windows and still see the same error.

**Comment by dagewa** [comment]
As expected, this also affects other `gltbx` programs, like `cctbx.multiplicity_viewer`

**Comment by phyy-nx** [comment]
Chatting with @bkpoon, this comes from https://github.com/python/cpython/issues/80266

If understood right, a cctbx change needs to be made which will propagate to fixing these problems.  Something something library compilation order :)

**Comment by dagewa** [comment]
Thanks @phyy-nx. Is there a cctbx issue to track regarding this?

**Comment by ase25** [comment]
I'm having the same issue but on an ubuntu install with 3.18.0, I'll try the napari method for now

**Comment by dagewa** [comment]
You might like to try https://toastisme.github.io/dials_browser_rlv/ as another option. This is working well on the Firefox browser

**Comment by dagewa** [comment]
This should eventually be fixed upstream: https://github.com/cctbx/cctbx_project/pull/980 (this needs testing)

**Comment by dagewa** [comment]
Confirmed! The upstream change does indeed unbreak the reciprocal lattice viewer on Windows :tada:
