### ISSUE TITLE
Image viewer: Opening h5 data files throws UnicodeDecodeError

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#2453]
```
% dials.image_viewer /dls/i24/data/2023/cm33852-3/blank/blank1_4595_000001.h5
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
Sorry: Unable to handle the following arguments:
  "blank1_4595_000001.h5" failed during ExperimentList processing:
    Traceback (most recent call last):
      File "/dls_sw/apps/dials/dials-v3-14-1-1/modules/dials/src/dials/util/options.py", line 321, in try_read_experiments
        data=ExperimentListFactory.from_json_file(
      File "/dls_sw/apps/dials/dials-v3-14-1-1/modules/dxtbx/src/dxtbx/model/experiment_list.py", line 768, in from_json_file
        infile.read(), check_format=check_format, directory=directory
      File "/dls_sw/apps/dials/dials-v3-14-1-1/build/../conda_base/lib/python3.10/codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

```

**Comment by h-mitchell** [comment]
Getting the same issue with h5 files but only when running dials.index or dials.reciprocal_lattice_viewer. Have tried using dials and dials/latest. Am able to open this h5 file using dials.image_viewer.

````
groups: cannot find name for group ID 50848
Sorry: Unable to handle the following arguments:
  "xtal_master.h5" failed during ExperimentList processing:
    Traceback (most recent call last):
      File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20230706/modules/dials/src/dials/util/options.py", line 321, in try_read_experiments
        data=ExperimentListFactory.from_json_file(
      File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20230706/modules/dxtbx/src/dxtbx/model/experiment_list.py", line 766, in from_json_file
        infile.read(), check_format=check_format, directory=directory
      File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20230706/build/../conda_base/lib/python3.10/codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
````

````
groups: cannot find name for group ID 51556
Sorry: Unable to handle the following arguments:
  "xtal_1_master.h5" failed during ExperimentList processing:
    Traceback (most recent call last):
      File "/dls_sw/apps/dials/dials-v3-14-1-1/modules/dials/src/dials/util/options.py", line 321, in try_read_experiments
        data=ExperimentListFactory.from_json_file(
      File "/dls_sw/apps/dials/dials-v3-14-1-1/modules/dxtbx/src/dxtbx/model/experiment_list.py", line 768, in from_json_file
        infile.read(), check_format=check_format, directory=directory
      File "/dls_sw/apps/dials/dials-v3-14-1-1/build/../conda_base/lib/python3.10/codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
````

**Comment by ndevenish** [comment]
That's a different issue, I think. Mine was because I was opening the data .h5 file instead of the .nxs file.

Your instance appears to be because `dials.index` and `dials.reciprocal_lattice_viewer` don't take image .h5 files directly, instead you must import/spotfind before `dials.index` or the reciprocal lattice viewer can handle them.

It is, however, the same extremely unhelpful error message.

**Comment by h-mitchell** [comment]
Thanks for this - I'd skipped that (crucial) step. I was able to run `dials.image_viewer` on the data .h5 file myself, however.

**Comment by dagewa** [comment]
Just to note, this is an error that comes up in various contexts (see https://github.com/cctbx/dxtbx/issues/427#issuecomment-910558373 for example). Evidently we don't quite do the right thing when sorting out file types during import.

**Comment by dennisbrookner** [comment]
I don't know if this is directly relevant or helpful, but this seems somewhat related in concept to https://github.com/dials/dials/issues/2097 and https://github.com/dials/dxtbx/pull/139
