### ISSUE TITLE
dials.image_viewer fails to show a full CBF example in CBFlib

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#2496]
I realized that a full CBF file, `1191_00005.cbf`, from the CBFlib examples (http://downloads.sf.net/cbflib/CBFlib_0.9.6_Data_Files_Input.tar.gz) cannot be displayed in `dials.image_viewer`. `dials.import` works fine.

```
Traceback (most recent call last):
  File "/home/prog/dials-dev/build/../modules/dials/src/dials/command_line/image_viewer.py", line 217, in <module>
    run()
  File "/home/prog/dials-dev/conda_base/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/prog/dials-dev/build/../modules/dials/src/dials/command_line/image_viewer.py", line 213, in run
    show_image_viewer(params=params, reflections=reflections, experiments=experiments)
  File "/home/prog/dials-dev/build/../modules/dials/src/dials/command_line/image_viewer.py", line 178, in show_image_viewer
    wrapper.display(experiments=experiments, reflections=reflections)
  File "/home/prog/dials-dev/modules/dials/src/dials/util/image_viewer/spotfinder_wrap.py", line 86, in display
    self.frame.load_image(chooser_wrapper(imagesets[0], 0))
  File "/home/prog/dials-dev/modules/dials/src/dials/util/image_viewer/spotfinder_frame.py", line 750, in load_image
    super().load_image(
  File "/home/prog/dials-dev/modules/dials/src/dials/util/image_viewer/slip_viewer/frame.py", line 428, in load_image
    self.pyslip.tiles.set_image(
  File "/home/prog/dials-dev/modules/dials/src/dials/util/image_viewer/slip_viewer/tile_generation.py", line 75, in set_image
    self.flex_image = get_flex_image_multipanel(
  File "/home/prog/dials-dev/modules/dials/src/dials/util/image_viewer/slip_viewer/flex_image.py", line 113, in get_flex_image_multipanel
    beam_center /= npanels / 1e-3
  File "/home/prog/dials-dev/modules/cctbx_project/scitbx/matrix/__init__.py", line 154, in __truediv__
    return rec([e/other for e in self.elems], self.n)
  File "/home/prog/dials-dev/modules/cctbx_project/scitbx/matrix/__init__.py", line 154, in <listcomp>
    return rec([e/other for e in self.elems], self.n)
ZeroDivisionError: Please report this error to dials-support@lists.sourceforge.net: float division by zero
```

**Comment by biochem-fan** [comment]
I updated to the latest commit (DIALS 3.dev.1033-g484c773cc) and it was fine.
DIALS 3.8 from CCP4 is indeed broken.
