### ISSUE TITLE
Issue with reading in MarCCD images

### ISSUE THREAD

**Issue by DHekstra** [dials/dials#2498]
hi, I am trying to read in some MarCCD images (collected at APS 14-ID-B some 12 years ago). These files have incomplete headers. A naive import

```
dials.import 
    directory="my/path/to/images/"
``` 
yields an unsurprising traceback starting with 

```
Sorry: 
          Imageset contains no beam or detector model. This means you will be
          unable to process your data.

          Possible causes of this error are:
             - A problem reading the images with one of the dxtbx format classes
             - A lack of header information in the file itself.

          You can override this by specifying the metadata as geometry parameters
```

When I add some information on beam and goniometer, using some informed guesses,

```
dials.import \
    geometry.goniometer.angles=0.0,0.0,-90.0 \
    geometry.goniometer.axes=0,1,0 \
    geometry.beam.wavelength=1.04 \
    geometry.beam.direction=0.0,0.0,1.0 \
    geometry.beam.polarization_fraction=0.99 \
    directory="my/path/to/images/"
```

I get a traceback which starts with 

```
Traceback (most recent call last):
  File "/n/hekstra_lab/people/dhekstra/conda_envs/laue-dials/bin/dials.import", line 11, in <module>
    sys.exit(run())
             ^^^^^
  File "/n/hekstra_lab/people/dhekstra/conda_envs/laue-dials/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/n/hekstra_lab/people/dhekstra/conda_envs/laue-dials/lib/python3.11/site-packages/dials/command_line/dials_import.py", line 965, in run
    do_import(args, phil=phil, configure_logging=True)
  File "/n/hekstra_lab/people/dhekstra/conda_envs/laue-dials/lib/python3.11/site-packages/dials/command_line/dials_import.py", line 877, in do_import
    experiments = metadata_updater(imagesets)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/hekstra_lab/people/dhekstra/conda_envs/laue-dials/lib/python3.11/site-packages/dials/command_line/dials_import.py", line 482, in __call__
    imageset = updater(imageset)
               ^^^^^^^^^^^^^^^^^
  File "/n/hekstra_lab/people/dhekstra/conda_envs/laue-dials/lib/python3.11/site-packages/dials/command_line/dials_import.py", line 393, in __call__
    detector = DetectorFactory.from_phil(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/hekstra_lab/people/dhekstra/conda_envs/laue-dials/lib/python3.11/site-packages/dxtbx/model/detector.py", line 492, in from_phil
    detector = DetectorFactory.generate_from_phil(params, beam)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/hekstra_lab/people/dhekstra/conda_envs/laue-dials/lib/python3.11/site-packages/dxtbx/model/detector.py", line 365, in generate_from_phil
    for panel_id in range(max(panel_list.keys()) + 1):
                          ^^^^^^^^^^^^^^^^^^^^^^
ValueError: Please report this error to dials-support@lists.sourceforge.net: max() arg is an empty sequence
```
followed by a  `CalledProcessError` error.

Presumably the issue is that it does not yet have an adequate detector model. How do I initialize that?

Adding the line `geometry.detector.panel.multiple=False ` results in an error `Unknown command line parameter definition: multiple = False`.

**Comment by DHekstra** [comment]
That would be great. Shared with you via the DIALS support Slack channel.

**Comment by DHekstra** [comment]
solved per the creation of a FormatTIFFBadRayonixHeader class (custom code per David Waterman).
