### ISSUE TITLE
dials.import_xds is useless

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2527]
... or broken, select 

```
Grey-Area x-mplx :( $ dials.import_xds ../image_140501/INTEGRATE.HKL 
Traceback (most recent call last):
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/import_xds.py", line 463, in <module>
    run()
  File "/Users/graeme/git/dials/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/import_xds.py", line 459, in run
    script.run(args)
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/import_xds.py", line 441, in run
    importer(params, options)
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/import_xds.py", line 185, in __call__
    raise RuntimeError("No XDS file found")
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: No XDS file found
```

OK, so need to set `method=reflections`

```
Grey-Area x-mplx :( $ dials.import_xds method=reflections ../image_140501/INTEGRATE.HKL 
The following parameters have been modified:

input {
  method = experiment *reflections
}

Traceback (most recent call last):
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/import_xds.py", line 463, in <module>
    run()
  File "/Users/graeme/git/dials/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/import_xds.py", line 459, in run
    script.run(args)
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/import_xds.py", line 438, in run
    importer = self.select_importer(args)
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/import_xds.py", line 448, in select_importer
    assert len(args) == 2
AssertionError: Please report this error to dials-support@lists.sourceforge.net:
```

now you are trolling me... <sighs>

**Comment by dagewa** [comment]
Possibly duplicate of https://github.com/dials/dials/issues/2205 - at least in spirit?

**Comment by graeme-winter** [comment]
Noted, agreed
