### ISSUE TITLE
dials.combine_experiments fails with multiple multi-run experiments as input

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2558]
# Use Case

Collected multiple datasets from multiple meshes and then

- import all data from each mesh, find spots, index
- process using the usual main sequence chain

Then wanting to combine the indexed experiments to look at the lattices in reciprocal space across _all_ the meshes e.g. for preferential orientation or just to bask in the glory of reciprocal space sparkles

# Problem

This does not work:

```
cs03r-sc-serv-36 rlv :) $ dials.combine_experiments ../2*/indexed.*
The following parameters have been modified:

input {
  experiments = ../2nd_Mesh_12/indexed.expt
  experiments = ../2nd_Mesh_13/indexed.expt
  experiments = ../2nd_Mesh_14/indexed.expt
  experiments = ../2nd_Mesh_15/indexed.expt
  experiments = ../2nd_Mesh_1/indexed.expt
  experiments = ../2nd_Mesh_3/indexed.expt
  experiments = ../2nd_Mesh_5/indexed.expt
  experiments = ../2nd_Mesh_6/indexed.expt
  experiments = ../2nd_Mesh_7/indexed.expt
  experiments = ../2nd_Mesh_9/indexed.expt
  reflections = ../2nd_Mesh_12/indexed.refl
  reflections = ../2nd_Mesh_13/indexed.refl
  reflections = ../2nd_Mesh_14/indexed.refl
  reflections = ../2nd_Mesh_15/indexed.refl
  reflections = ../2nd_Mesh_1/indexed.refl
  reflections = ../2nd_Mesh_3/indexed.refl
  reflections = ../2nd_Mesh_5/indexed.refl
  reflections = ../2nd_Mesh_6/indexed.refl
  reflections = ../2nd_Mesh_7/indexed.refl
  reflections = ../2nd_Mesh_9/indexed.refl
}

DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v3-17-0-1/build/../modules/dials/src/dials/command_line/combine_experiments.py", line 403, in <module>
    run()
  File "/dls_sw/apps/dials/dials-v3-17-0-1/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/dls_sw/apps/dials/dials-v3-17-0-1/build/../modules/dials/src/dials/command_line/combine_experiments.py", line 388, in run
    expts, refls = combine_experiments(params, experiment_lists, reflection_tables)
  File "/dls_sw/apps/dials/dials-v3-17-0-1/modules/dials/src/dials/util/combine_experiments.py", line 568, in combine_experiments
    subs["imageset_id"] = flex.int(len(subs), imageset_result_map[old_id])
KeyError: 'Please report this error to dials-support@lists.sourceforge.net: 11'
```

presumably this fails because we have colliding values in the combined reflection table `id` columns?

# Data

Above command run in

```
/dls/i24/data/2023/mx37045-6/processing/gw/insulin-good/rlv
```

# Requested resolution

Suspect we need to extend combine experiments to consider the case where you have > 1 experiment in more than two input data sets.

# Workaround

Am aware I could `split_experiment` in every mesh then `combine_experiments` on the split files but this feels inelegant (but it is what I will do this morning)

**Comment by graeme-winter** [comment]
Verified - this workaround

```
for d in 2*; do cd $d; dials.split_experiments indexed.*; cd - ; done
dials.combine_experiments 2*/split*
```

Worked - inelegant but successful
