### ISSUE TITLE
find_spots_server fails with unicode filenames

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#256]
```
>>> from dials.command_line.find_spots_server import work
>>> filename="/dls/mx-scratch/mgerstel/zenodo-NiDPPE/data/j3_04_00001.cbf"
>>> work(filename)
{'d_min_distl_method_2': -1.0, 'noisiness_method_2': -1.0, 'noisiness_method_1': -1.0, 'd_min_distl_method_1': -1.0, 'total_intensity': 753.0, 'n_spots_no_ice': 3, 'estimated_d_min': -1.0, 'n_spots_4A': 0, 'n_spots_total': 11}
>>> work(unicode(filename))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/wra62962/files/dials/modules/dials/command_line/find_spots_server.py", line 96, in work
    datablock = DataBlockFactory.from_filenames([filename])[0]
IndexError: list index out of range
```

Why does this matter?
```
>>> work(json.loads(json.dumps(filename)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/wra62962/files/dials/modules/dials/command_line/find_spots_server.py", line 96, in work
    datablock = DataBlockFactory.from_filenames([filename])[0]
IndexError: list index out of range
```

**Comment by rjgildea** [comment]
This looks like a problem with DatablockFactory.from_filenames() rather than specific to find_spots_server?

**Comment by Anthchirp** [comment]
Very much possible. find_spots_server is just how I found it.

**Comment by rjgildea** [comment]
Confirmed DatablockFactory bug. Strangely it seems to be find for some filenames but not others:

```
>>> filename="/dls/mx-scratch/mgerstel/zenodo-NiDPPE/data/j3_04_00001.cbf"
>>> from dxtbx.datablock import DataBlockFactory
>>> datablock = DataBlockFactory.from_filenames([filename])[0]
>>> datablock = DataBlockFactory.from_filenames([unicode(filename)])[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
>>> filename = "/dls/science/users/hko55533/software/cctbx/modules/dials_regression/centroid_test_data/centroid_0001.cbf"
>>> datablock = DataBlockFactory.from_filenames([filename])[0]
>>> datablock = DataBlockFactory.from_filenames([unicode(filename)])[0]
```

**Comment by rjgildea** [comment]
Pycbf can't handle unicode filenames:
```
>>> filename = '/dls/mx-scratch/mgerstel/zenodo-NiDPPE/data/j3_04_00001.cbf'
>>> ufilename = unicode(filename)
>>> from dxtbx.format.FormatCBFFullPilatus import FormatCBFFullPilatus
>>> FormatCBFFullPilatus.understand(filename)
True
>>> FormatCBFFullPilatus.understand(ufilename)
True
>>> FormatCBFFullPilatus(filename)
<dxtbx.format.FormatCBFFullPilatus.FormatCBFFullPilatus object at 0x7f22b7fd3bd0>
>>> FormatCBFFullPilatus(ufilename)
Traceback (most recent call last):
  File "/dls/science/users/hko55533/software/cctbx/modules/cctbx_project/dxtbx/format/Format.py", line 132, in setup
    goniometer_instance = self._goniometer()
  File "/dls/science/users/hko55533/software/cctbx/modules/cctbx_project/dxtbx/format/FormatCBFFull.py", line 63, in _goniometer
    return self._goniometer_factory.imgCIF_H(self._get_cbf_handle())
  File "/dls/science/users/hko55533/software/cctbx/modules/cctbx_project/dxtbx/format/FormatCBFFull.py", line 57, in _get_cbf_handle
    self._cbf_handle.read_widefile(self._image_file, pycbf.MSG_DIGEST)
  File "/dls/science/users/hko55533/software/cctbx/build/lib/pycbf.py", line 3309, in read_widefile
    return _pycbf.cbf_handle_struct_read_widefile(self, filename, headers)
TypeError: in method 'cbf_handle_struct_read_widefile', argument 2 of type 'char *'
<dxtbx.format.FormatCBFFullPilatus.FormatCBFFullPilatus object at 0x7f22a95ae790>
```
