### ISSUE TITLE
dials.sequence_to_stills does not work on imported, strong data

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2577]
Working with @maggie-klureza found that you cannot run `dials.sequences_to_stills` on unindexed data - this is a shame

```
Grey-Area tmp :) $ dials.sequence_to_stills imported_summed_raw_EFX53_01.expt strong_summed_raw_EFX53_01.refl 
The following parameters have been modified:

input {
  experiments = imported_summed_raw_EFX53_01.expt
  reflections = strong_summed_raw_EFX53_01.refl
}

DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
Traceback (most recent call last):
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/sequence_to_stills.py", line 276, in <module>
    run()
  File "/Users/graeme/git/dials/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/sequence_to_stills.py", line 265, in run
    (new_experiments, new_reflections) = sequence_to_stills(
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/sequence_to_stills.py", line 92, in sequence_to_stills
    raise RuntimeError(f"Expected key not found in reflection table: {key}")
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: Expected key not found in reflection table: miller_index
```

This probably _should_ be something you could do?

**Comment by phyy-nx** [comment]
Probably ya.  The original intent of this program was to handle a) the half oscillation angle offset needed to break up a scan into stills, and b) to split up 3d reflections into 2d reflections.  For unindexed data, a) isn't relevant but b) is still valid.  

I'd re-write the code as follows:
- [This](https://github.com/dials/dials/blob/main/src/dials/command_line/sequence_to_stills.py#L68) for loop should copy all keys across instead of individual keys
- [This](https://github.com/dials/dials/blob/main/src/dials/command_line/sequence_to_stills.py#L123-L176) code needs to be put in a check for `if expt.crystal is not None`
- [This](https://github.com/dials/dials/blob/main/src/dials/command_line/sequence_to_stills.py#L186) for loop is probably fine, I think those column names are in the strong refl table
- [Re-predicting](https://github.com/dials/dials/blob/main/src/dials/command_line/sequence_to_stills.py#L214-L219) predicted centroid locations should be skipped

I'd tag the laue_dials folks in the PR as sequences_to_stills in their pipeline.
