### ISSUE TITLE
`dials.ssx_integrate`: do not write out zero-length reflection list

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2589]
I have a case where every image fails to process in a `dials.ssx_integrate` run. In such a case, the program writes out a zero length reflection list:
```
Saving 0 reflections to integrated_1.refl
Saving the experiments to integrated_1.expt
```
That seems fair enough, but then the script I'm running combines many `integrated_1.{expt,refl}` files from many different runs. The zero length reflection list causes failures in places like `dials.reindex`, which spits out an error like this:
```
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/reindex.py", line 315, in <module>
    run()
  File "/home/fcx32934/sw/cctbx/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/reindex.py", line 130, in run
    reflections, experiments = reflections_and_experiments_from_files(
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/util/options.py", line 1192, in reflections_and_experiments_from_files
    tables = sort_tables_to_experiments_order(tables, experiments)
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/util/multi_dataset_handling.py", line 249, in sort_tables_to_experiments_order
    assert len(sorted_tables) == len(reflection_tables)
AssertionError: Please report this error to dials-support@lists.sourceforge.net:
```
Should `dials.ssx_integrate` write out a zero-length reflection list or just write out nothing in this case? If it should continue to write out an empty list, then can this be handled appropriately in the option parser when loading the experiments and reflections?

**Comment by dagewa** [comment]
I think a good reason to not write out the zero-length list is that the situation is actually worse than having a table with zero rows: it doesn't even have column keys, so it is a file that is not of a comparable type to one that does have reflections.

**Comment by jbeilstenedmands** [comment]
I think not writing out a zero-length list will be the most sensible option for the reasons you say.
