### ISSUE TITLE
dials.import: too many path separators breaks template=

### ISSUE THREAD

**Issue by dagewa** [dials/dials#263]
This happens:

```
$ dials.import template=/tmp//xtal01_1_###.mar1600
DIALS 1.dev.990-g85a786e
The following parameters have been modified:

input {
  template = "/tmp//xtal01_1_###.mar1600"
}

Traceback (most recent call last):
  File "/home/david/bsx/cctbx-svn/build/../sources/dials/command_line/dials_import.py", line 884, in <module>
    halraiser(e)
  File "/home/david/bsx/cctbx-svn/build/../sources/dials/command_line/dials_import.py", line 882, in <module>
    script.run()
  File "/home/david/bsx/cctbx-svn/build/../sources/dials/command_line/dials_import.py", line 776, in run
    datablock = metadata_updater(datablock_importer())
  File "/home/david/bsx/cctbx-svn/build/../sources/dials/command_line/dials_import.py", line 185, in __call__
    format_kwargs=format_kwargs)
  File "/home/david/bsx/cctbx-svn/sources/cctbx_project/dxtbx/datablock.py", line 391, in __init__
    imageset = self._create_imageset(fmt, template, paths, **kwargs)
  File "/home/david/bsx/cctbx-svn/sources/cctbx_project/dxtbx/datablock.py", line 401, in _create_imageset
    first = int(filenames[0][index])

```

`$ dials.import template=/tmp/xtal01_1_###.mar1600` is of course fine

**Comment by jmp1985** [comment]
Fixed by using os.path.normpath
