### ISSUE TITLE
`dials.predict ignore_shadows=False` is broken

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2630]
@graeme-winter I tried testing this with any old data set:
```
dials.predict $(dials.data get -q centroid_test_data)/indexed.expt ignore_shadows=False
The following parameters have been modified:

ignore_shadows = False
input {
  experiments = /home/fcx32934/sw/cctbx/build/dials_data/centroid_test_data/indexed.expt
}

Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/predict.py", line 141, in <module>
    run()
  File "/home/fcx32934/sw/cctbx/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/predict.py", line 137, in run
    script.run(args)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/src/dials/command_line/predict.py", line 118, in run
    shadowed = filter_shadowed_reflections(
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/algorithms/shadowing/filter.py", line 19, in filter_shadowed_reflections
    shadow = masker.project_extrema(
AttributeError: Please report this error to dials-support@lists.sourceforge.net: 'NoneType' object has no attribute 'project_extrema'
```

Seems to me that the shadowing stuff you added is broken? This error is the same on main.

_Originally posted by @dagewa in https://github.com/dials/dials/issues/2553#issuecomment-1920888724_

**Comment by graeme-winter** [comment]
Will have a look

**Comment by graeme-winter** [comment]
OK, if the masker is `None` then we have two choices:

 - practical - if no masker then none in shadows so just return "unshadowed"
 - dogmatic - if you say `ignore_shadows=false` and `masker is None` then throw an error

Probably, the first of these is the more expected one.
