### ISSUE TITLE
dials.import_xds shows no signs of working

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2647]
I am not sure how it should work so I check

```
ws448 xds :( $ dials.import_xds --help
usage: usage: dials.import_xds [options] (SPOT.XDS|INTEGRATE.HKL)
```

OK then:

```
ws448 xds :) $ dials.import_xds INTEGRATE.HKL
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v3-18-1/build/../modules/dials/src/dials/command_line/import_xds.py", line 463, in <module>
    run()
  File "/dls_sw/apps/dials/dials-v3-18-1/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/dls_sw/apps/dials/dials-v3-18-1/build/../modules/dials/src/dials/command_line/import_xds.py", line 459, in run
    script.run(args)
  File "/dls_sw/apps/dials/dials-v3-18-1/build/../modules/dials/src/dials/command_line/import_xds.py", line 441, in run
    importer(params, options)
  File "/dls_sw/apps/dials/dials-v3-18-1/build/../modules/dials/src/dials/command_line/import_xds.py", line 185, in __call__
    raise RuntimeError("No XDS file found")
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: No XDS file found
```

YOU ARE HOLDING IT WRONG!!1!

OK I will try again

```
ws448 xds :( $ dials.import_xds xds_file=INTEGRATE.HKL
The following parameters have been modified:

input {
  xds_file = "INTEGRATE.HKL"
}

usage: usage: dials.import_xds [options] (SPOT.XDS|INTEGRATE.HKL)

options:
  -c, --show-config     Show the configuration parameters.
  -a ATTRIBUTES_LEVEL, --attributes-level ATTRIBUTES_LEVEL
                        Set the attributes level for showing configuration
                        parameters
  -e EXPERT_LEVEL, --expert-level EXPERT_LEVEL
                        Set the expert level for showing configuration
                        parameters
  -h, --help            Show this help message and exit. Can be specified
                        multiple times to increase verbosity.
  -v                    Increase verbosity (can be specified multiple times)
  --phil FILE           PHIL files to read. Pass '-' for STDIN. Can be
                        specified multiple times, but duplicates ignored.
```

Nope... 

OK so the other example was SPOT.XDS, let's test that 

```
ws448 xds :) $ dials.import_xds SPOT.XDS 
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v3-18-1/build/../modules/dials/src/dials/command_line/import_xds.py", line 463, in <module>
    run()
  File "/dls_sw/apps/dials/dials-v3-18-1/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/dls_sw/apps/dials/dials-v3-18-1/build/../modules/dials/src/dials/command_line/import_xds.py", line 459, in run
    script.run(args)
  File "/dls_sw/apps/dials/dials-v3-18-1/build/../modules/dials/src/dials/command_line/import_xds.py", line 441, in run
    importer(params, options)
  File "/dls_sw/apps/dials/dials-v3-18-1/build/../modules/dials/src/dials/command_line/import_xds.py", line 185, in __call__
    raise RuntimeError("No XDS file found")
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: No XDS file found
```

`dials.pope_of_nope` is not being helpful today

I really have no idea what this is supposed to do, but whatever it is it is working very hard to not do that

Raising as an issue because user contacted me directly

**Comment by graeme-winter** [comment]
By a process of reading much code and no small amount of random permutations I found a set of things which _does not crash_

```
ws448 xds :( $ dials.import_xds . INTEGRATE.HKL
--------------------------------------------------------------------------------
Read 1 experiments from ./XDS_ASCII.HKL
--------------------------------------------------------------------------------
Experiment 0
  format: <class 'dxtbx.format.Format.Format'>
  type: <class 'dxtbx_imageset_ext.ImageSequence'>
  num images: 1
--------------------------------------------------------------------------------
Writing experiments to xds_models.expt
```

**Comment by graeme-winter** [comment]
This only imports the experiments: how to get the reflections imported?

Maybe I should have been alerted by the author `F. Kafka`? 🤔

**Comment by graeme-winter** [comment]
I nearly won!

```
ws448 xds :( $ dials.import_xds method=reflections INTEGRATE.HKL xds_models.expt 
The following parameters have been modified:

input {
  method = experiment *reflections
}

Read 600295 reflections from INTEGRATE.HKL file............................3.15s
Reindex matrix:
1 1 0
1 0 1
0 -1 -1
Reindexing reflections...Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v3-18-1/build/../modules/dials/src/dials/command_line/import_xds.py", line 463, in <module>
    run()
  File "/dls_sw/apps/dials/dials-v3-18-1/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/dls_sw/apps/dials/dials-v3-18-1/build/../modules/dials/src/dials/command_line/import_xds.py", line 459, in run
    script.run(args)
  File "/dls_sw/apps/dials/dials-v3-18-1/build/../modules/dials/src/dials/command_line/import_xds.py", line 441, in run
    importer(params, options)
  File "/dls_sw/apps/dials/dials-v3-18-1/build/../modules/dials/src/dials/command_line/import_xds.py", line 118, in __call__
    cb_op = sgtbx.change_of_basis_op(sgtbx.rt_mx(sgtbx.rot_mx(rdx.elems)))
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: cctbx Internal Error: /scratch/jenkins_agent/workspace/dials_patch_release/build_dials/modules/cctbx_project/cctbx/sgtbx/rot_mx.cpp(36): Unsuitable value for rational rotation matrix.
```

Oh, fail. But this failure I suspect reflects that you need to have a non-centred crystal for this to work.

**Comment by dagewa** [comment]
Agree with all of the above. Some similar commentary exists at https://github.com/dials/dials/issues/2205

**Comment by graeme-winter** [comment]
> Agree with all of the above. Some similar commentary exists at #2205

Thank you: I searched for import XDS in the issue list and that didn't pop up, which is weird.
