### ISSUE TITLE
Add docstring to `reindex_reflections` to make it clear it takes a list of reflection tables

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2682]
The command line program works:
```bash
dials.import $(dials.data get -q insulin)/*.img
dials.find_spots imported.expt
dials.index imported.expt strong.refl
dials.reindex indexed.refl change_of_basis_op="b+c,a+c,a+b"
```

But try to do the same in python using the function, and it fails. The program must be doing "more stuff", but it is a shame this is not also done by the function.

```python
>>> from dials.array_family import flex
>>> from dials.util.reindex import reindex_reflections
>>> from cctbx import sgtbx
>>> cb_op = sgtbx.change_of_basis_op("b+c,a+c,a+b")
>>> indexed = flex.reflection_table.from_file("indexed.refl")
>>> reindex_reflections(indexed, cb_op)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/util/reindex.py", line 127, in reindex_reflections
    reflections = flex.reflection_table.concat(reflections)
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/array_family/flex_ext.py", line 533, in concat
    tables = renumber_table_id_columns(tables)
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/util/multi_dataset_handling.py", line 124, in renumber_table_id_columns
    table_id_values = sorted(set(table["id"]).difference({-1}), reverse=True)
TypeError: string indices must be integers
```

**Comment by jbeilstenedmands** [comment]
Is it just that `reindex_reflections` requires a list of reflection tables?

**Comment by dagewa** [comment]
Yep, you are absolutely right :facepalm: Now I understand why it starts with
```
reflections = flex.reflection_table.concat(reflections)
```
Thanks for the quick reply, sorry for the noise.

**Comment by dagewa** [comment]
...and add type hints, I suppose
