### ISSUE TITLE
dials.geometry_viewer not as general as it could be, perhaps

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#269]
```
[gw56@cs03r-sc-serv-20 index]$ dials.geometry_viewer 1_SWEEP1_datablock.json 
The following parameters have been modified:

input {
  datablock = 1_SWEEP1_datablock.json
}

Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/geometry_viewer.py", line 486, in <module>
    run(sys.argv[1:])
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/geometry_viewer.py", line 469, in run
    for angle in gonio.get_angles():
AttributeError: 'Goniometer' object has no attribute 'get_angles'
```

This is probably a known thing but...

**Comment by rjgildea** [comment]
This should now be more general: https://github.com/dials/dials/commit/74050b196e12f42ff9d76c2ffe00d997739d2f99
