### ISSUE TITLE
OpenGL missing from DIALS from conda on Windows

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2703]
I've been testing a conda install of DIALS on Windows. Most things seem to work, but `dials.reciprocal_lattice_viewer` fails with 
```
(dials-conda-test) C:\Users\fcx32934\data\dials-test>dials.reciprocal_lattice_viewer indexed.expt indexed.refl
Traceback (most recent call last):
  File "C:\Users\fcx32934\AppData\Local\miniconda3\envs\dials-conda-test\Lib\site-packages\gltbx\glu.py", line 3, in <module>
    import OpenGL  # implicit import
    ^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'OpenGL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fcx32934\AppData\Local\miniconda3\envs\dials-conda-test\Lib\site-packages\boost_adaptbx\boost\python.py", line 22, in import_ext
    try: mod = __import__(name)
               ^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing gltbx_glu_ext: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fcx32934\AppData\Local\miniconda3\envs\dials-conda-test\Scripts\dials.reciprocal_lattice_viewer-script.py", line 6, in <module>
    from dials.command_line.reciprocal_lattice_viewer import run
  File "C:\Users\fcx32934\AppData\Local\miniconda3\envs\dials-conda-test\Lib\site-packages\dials\command_line\reciprocal_lattice_viewer.py", line 16, in <module>
    from dials.util.reciprocal_lattice.viewer import ReciprocalLatticeViewer, phil_scope
  File "C:\Users\fcx32934\AppData\Local\miniconda3\envs\dials-conda-test\Lib\site-packages\dials\util\reciprocal_lattice\viewer.py", line 22, in <module>
    from dials.util import wx_viewer
  File "C:\Users\fcx32934\AppData\Local\miniconda3\envs\dials-conda-test\Lib\site-packages\dials\util\wx_viewer.py", line 14, in <module>
    import gltbx.glu as glu
  File "C:\Users\fcx32934\AppData\Local\miniconda3\envs\dials-conda-test\Lib\site-packages\gltbx\glu.py", line 7, in <module>
    ext = bp.import_ext("gltbx_glu_ext")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fcx32934\AppData\Local\miniconda3\envs\dials-conda-test\Lib\site-packages\boost_adaptbx\boost\python.py", line 31, in import_ext
    raise ImportError(
ImportError: __import__("gltbx_glu_ext"): DLL load failed while importing gltbx_glu_ext: A dynamic link library (DLL) initialization routine failed.
  sys.path:
    C:\Users\fcx32934\AppData\Local\miniconda3\envs\dials-conda-test\Scripts
    C:\Users\fcx32934\AppData\Local\miniconda3\envs\dials-conda-test\python312.zip
    C:\Users\fcx32934\AppData\Local\miniconda3\envs\dials-conda-test\DLLs
    C:\Users\fcx32934\AppData\Local\miniconda3\envs\dials-conda-test\Lib
    C:\Users\fcx32934\AppData\Local\miniconda3\envs\dials-conda-test
    C:\Users\fcx32934\AppData\Local\miniconda3\envs\dials-conda-test\Lib\site-packages
    C:\Users\fcx32934\AppData\Local\miniconda3\envs\dials-conda-test\Lib\site-packages\setuptools\_vendor
```

**Comment by dagewa** [comment]
Turns out this issue is fixed by running
```
conda install pyopengl
```
so probably that needs adding to dependencies somewhere?

**Comment by ndevenish** [comment]
Possibly this dependency needs to be added to the cctbx package on conda-forge? Simultaneously having issues getting the DIALS builds through, so is still on 3.19.

**Comment by dagewa** [comment]
Yes, I think that sounds right, as it affects `cctbx.multiplicity_viewer` too

**Comment by dagewa** [comment]
Ok, the GUI dependencies are in the cctbx package, not the cctbx-base package. So I think we should add pyopengl to the dials dependencies in that case

**Comment by ndevenish** [comment]
Isn’t it a gltbx dependency, which is included in cctbx-base?

**Comment by dagewa** [comment]
It's possible to import `gltbx` without it (though not sure why you'd want to), but you cannot `import gltbx.glu`

**Comment by dagewa** [comment]
Can't import `gltbx.gl` or `gltbx.util` either, so yes, I think it is a dependency if gltbx is to be used. I guess the assumption is that gltbx is not to be used in cctbx-base...
