### ISSUE TITLE
dials.find_spots_server crashes on modern MacOS

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2746]
```
Traceback (most recent call last):
  File "/Applications/dials-v3-21-1/build/../modules/dials/src/dials/command_line/find_spots_server.py", line 379, in <module>
    run()
  File "/Applications/dials-v3-21-1/conda_base/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Applications/dials-v3-21-1/build/../modules/dials/src/dials/command_line/find_spots_server.py", line 369, in run
    multiprocessing.set_start_method("fork")
  File "/Applications/dials-v3-21-1/conda_base/lib/python3.11/multiprocessing/context.py", line 247, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: Please report this error to [dials-support@lists.sourceforge.net](mailto:dials-support@lists.sourceforge.net): context has already been set
```

Assigning to myself to verify

**Comment by graeme-winter** [comment]
Verified with development build

```
Grey-Area tmp :) $ dials.find_spots_server 
Traceback (most recent call last):
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/find_spots_server.py", line 379, in <module>
    run()
  File "/Users/graeme/git/dials/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/graeme/git/dials/build/../modules/dials/src/dials/command_line/find_spots_server.py", line 369, in run
    multiprocessing.set_start_method("fork")
  File "/Users/graeme/git/dials/conda_base/lib/python3.10/multiprocessing/context.py", line 247, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: context has already been set
```
