### ISSUE TITLE
`RLVWindow` error with `dials.reciprocal_lattice_viewer`

### ISSUE THREAD

**Issue by tianyu-liu** [dials/dials#2760]
Hi, I have encountered an error when trying to start the `dials.reciprocal_lattice_viewer`.

```
$ dials.reciprocal_lattice_viewer indexed.expt indexed.refl
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = indexed.expt
  reflections = indexed.refl
}

SystemError: Please report this error to dials-support@lists.sourceforge.net: <built-in method IsDisplaySupported of RLVWindow object at 0x74e1be7089d0> returned a result with an exception set
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at ./src/unix/glx11.cpp(672) in InitXVisualInfo(): wxGLAttributes object is empty.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tt/dials-v3-21-1/build/../modules/dials/src/dials/command_line/reciprocal_lattice_viewer.py", line 79, in <module>
    run()
  File "/home/tt/dials-v3-21-1/conda_base/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/tt/dials-v3-21-1/build/../modules/dials/src/dials/command_line/reciprocal_lattice_viewer.py", line 65, in run
    f = ReciprocalLatticeViewer(
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tt/dials-v3-21-1/modules/dials/src/dials/util/reciprocal_lattice/viewer.py", line 80, in __init__
    self.create_viewer_panel()
  File "/home/tt/dials-v3-21-1/modules/dials/src/dials/util/reciprocal_lattice/viewer.py", line 158, in create_viewer_panel
    self.viewer = RLVWindow(
                  ^^^^^^^^^^
  File "/home/tt/dials-v3-21-1/modules/dials/src/dials/util/reciprocal_lattice/viewer.py", line 501, in __init__
    super().__init__(*args, **kwds)
  File "/home/tt/dials-v3-21-1/modules/dials/src/dials/util/wx_viewer.py", line 801, in __init__
    wxGLWindow.__init__(self, *args, **keyword_args)
  File "/home/tt/dials-v3-21-1/modules/dials/src/dials/util/wx_viewer.py", line 112, in __init__
    if self.IsDisplaySupported(
       ^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: Please report this error to dials-support@lists.sourceforge.net: <built-in method IsDisplaySupported of RLVWindow object at 0x74e1be7089d0> returned a result with an exception set
```

Dials version as listed is the latest stable v3.21.1. I tried on both Ubuntu 22.04 and 24.04, following the binary installation guide. `dials.image_viewer` can start successfully, although something may be missing from its interface:
![image](https://github.com/user-attachments/assets/d08e0bd8-7fc2-4914-8124-53f448468c11)

Please let me know if you need other information. Many thanks in advance.

**Comment by dagewa** [comment]
Hi, I haven't come across this problem with DIALS 3.21.1 on Ubuntu 22.04.5 LTS. I don't have 24.04 to test. Can you confirm which display server session are you using, Wayland or X11?

The image viewer looks normal to me. That is, I also don't see a scroll bar.

**Comment by dagewa** [comment]
Ah good, glad it is sorted

**Comment by dagewa** [comment]
You are right though that the image viewer scroll bar used to be present and is now missing. I'll raise another issue.
