### ISSUE TITLE
`dials.ssx_index`: unhelpful error when passed a scan

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2797]
A user tried processing images from a rotation scan as if they were stills. This fails with an unhelpful error message, demonstrated with
```
dials.import $(dials.data get -q insulin)
dials.find_spots imported.expt
dials.ssx_index imported.expt strong.refl
```
which produces
```
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/conda_base/bin/dials.ssx_index", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/fcx32934/sw/cctbx/conda_base/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/command_line/ssx_index.py", line 163, in run
    indexed_experiments, indexed_reflections, summary_data = index(
                                                             ^^^^^^
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/algorithms/indexing/ssx/processing.py", line 489, in index
    indexed_experiments, indexed_reflections, results_summary = index_all_concurrent(
                                                                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fcx32934/sw/cctbx/modules/dials/src/dials/algorithms/indexing/ssx/processing.py", line 241, in index_all_concurrent
    if reflections[refl_index]:
       ~~~~~~~~~~~^^^^^^^^^^^^
IndexError: Please report this error at https://github.com/dials/dials/issues: list index out of range
```

If instead the images are imported with `convert_sequences_to_stills=True`, then the program runs to completion.

**Comment by dagewa** [comment]
To be clear, I'm not saying this _should_ work, just that the program should exit with a helpful message
