### ISSUE TITLE
dials.export should cope with > 1 experiment

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#283]
i.e. after successfully integrating three lattices on a single data set; export the resulting data

currently computer says no

```
[gw56@cs04r-sc-com99-01 abc]$ dials.export integrated*
DIALS 1.dev.1048-g9a4ffc5
The following parameters have been modified:

input {
  experiments = integrated_experiments.json
  reflections = integrated.pickle
}

Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/export.py", line 624, in <module>
    exporter.export()
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/export.py", line 247, in export
    ignore_profile_fitting=params.mtz.ignore_profile_fitting)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/export_mtz.py", line 205, in export_mtz
    assert(len(experiment_list) == 1)
AssertionError

```

**Comment by graeme-winter** [comment]
[d283.zip](https://github.com/dials/dials/files/1114295/d283.zip)

example case

**Comment by graeme-winter** [comment]
DIALS_EXPORT_DO_NOT_CHECK_FORMAT=1 dials.export integrated* should work @ndevenish should add this to _regression I guess?
