### ISSUE TITLE
dials.index: Krivy-Gruber iteration limit exceeded

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#286]
```
DIALS 1.4.1-gba385ba-release
The following parameters have been modified:

indexing {
  nproc = 20
  max_cell_estimation {
    filter_ice = False
  }
}
refinement {
  reflections {
    outlier {
      algorithm = Auto
    }
  }
}
output {
  experiments = "/dls/i19-1/data/2017/mt11231-14/processed/MJR1946_CD52_C1_300_2/1/DEFAULT/NATIVE/SWEEP1/index/3_experiments.json"
  reflections = "/dls/i19-1/data/2017/mt11231-14/processed/MJR1946_CD52_C1_300_2/1/DEFAULT/NATIVE/SWEEP1/index/3_indexed.pickle"
}
input {
  datablock = 1_SWEEP1_datablock.json
  reflections = /dls/i19-1/data/2017/mt11231-14/processed/MJR1946_CD52_C1_300_2/1/DEFAULT/NATIVE/SWEEP1/index/1_SWEEP1_strong.pickle
}

Found max_cell: 214.3 Angstrom
Setting d_min: 4.19
FFT gridding: (256,256,256)
Number of centroids used: 199
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v1-4-1/build/../modules/dials/command_line/index.py", line 179, in <module>
    run(sys.argv[1:])
  File "/dls_sw/apps/dials/dials-v1-4-1/build/../modules/dials/command_line/index.py", line 156, in run
    params=params)
  File "/dls_sw/apps/dials/dials-v1-4-1/modules/dials/algorithms/indexing/indexer.py", line 541, in from_parameters
    idxr = indexer_fft3d(reflections, imagesets, params=params)
  File "/dls_sw/apps/dials/dials-v1-4-1/modules/dials/algorithms/indexing/fft3d.py", line 35, in __init__
    super(indexer_fft3d, self).__init__(reflections, imagesets, params)
  File "/dls_sw/apps/dials/dials-v1-4-1/modules/dials/algorithms/indexing/indexer.py", line 475, in __init__
    self.index()
  File "/dls_sw/apps/dials/dials-v1-4-1/modules/dials/algorithms/indexing/indexer.py", line 729, in index
    experiments.extend(self.find_lattices())
  File "/dls_sw/apps/dials/dials-v1-4-1/modules/dials/algorithms/indexing/fft3d.py", line 90, in find_lattices
    self.candidate_crystal_models)
  File "/dls_sw/apps/dials/dials-v1-4-1/modules/dials/algorithms/indexing/indexer.py", line 1362, in choose_best_orientation_matrix
    self.correct_non_primitive_basis(experiments, refl, threshold)
  File "/dls_sw/apps/dials/dials-v1-4-1/modules/dials/algorithms/indexing/indexer.py", line 1447, in correct_non_primitive_basis
    cb_op = crystal_model.get_unit_cell().change_of_basis_op_to_niggli_cell()
  File "/dls_sw/apps/dials/dials-v1-4-1/modules/cctbx_project/cctbx/uctbx/__init__.py", line 194, in change_of_basis_op_to_niggli_cell
    relative_epsilon, iteration_limit).change_of_basis_op()
  File "/dls_sw/apps/dials/dials-v1-4-1/modules/cctbx_project/cctbx/uctbx/__init__.py", line 182, in niggli_reduction
    return krivy_gruber_1976.reduction(self, relative_epsilon, iteration_limit)
  File "/dls_sw/apps/dials/dials-v1-4-1/modules/cctbx_project/cctbx/uctbx/krivy_gruber_1976.py", line 10, in __init__
    while (self.step()): pass
  File "/dls_sw/apps/dials/dials-v1-4-1/modules/cctbx_project/cctbx/uctbx/krivy_gruber_1976.py", line 31, in step
    s.a4_action()
  File "/dls_sw/apps/dials/dials-v1-4-1/modules/cctbx_project/cctbx/uctbx/krivy_gruber_1976.py", line 67, in a4_action
    s.n3_false_action()
  File "/dls_sw/apps/dials/dials-v1-4-1/modules/cctbx_project/cctbx/uctbx/reduction_base.py", line 185, in n3_false_action
    self.cb_update((f[0],0,0, 0,f[1],0, 0,0,f[2]))
  File "/dls_sw/apps/dials/dials-v1-4-1/modules/cctbx_project/cctbx/uctbx/reduction_base.py", line 146, in cb_update
    % (self._name(), self._iteration_limit))
cctbx.uctbx.reduction_base.iteration_limit_exceeded: Krivy-Gruber iteration limit exceeded (limit=1000).
# command line:
# dials.index  '1_SWEEP1_datablock.json' '1_SWEEP1_strong.pickle' 'indexing.method=fft3d' 'indexing.nproc=20' 'filter_ice=false' 'reflections_per_degree=100' 'close_to_spindle_cutoff=0.020000' 'outlier.algorithm=auto' 'min_cell=3' 'output.experiments=3_experiments.json' 'output.reflections=3_indexed.pickle'
```

**Comment by graeme-winter** [comment]
This is very unlikely to work with 4A highest resolution used for indexing
and a 5A cell...!

**Comment by rjgildea** [comment]
What is the expected unit cell for this?

RLV looks very strange, clear lattice in one direction, just lines of very close spots in other direction:
![rlv1](https://cloud.githubusercontent.com/assets/2810624/23758101/941cab08-04e0-11e7-9e61-689f7e6f1132.png)
![rlv2](https://cloud.githubusercontent.com/assets/2810624/23758114/98d3c9f6-04e0-11e7-9862-64fea850589b.png)

Nearest neighbour histogram shows big peak at ~200A:
![nn_hist](https://cloud.githubusercontent.com/assets/2810624/23758172/c9c2dcaa-04e0-11e7-85d8-7ea7a8d0ade6.png)

**Comment by rjgildea** [comment]
Setting `indexing.method=fft1d` gives the unit cell 5.867, 5.868, **153.774**, 91.078, 90.015, 120.012. Is this to be expected? In this case this is just a case where fft3d method is unlikely to succeed due to the ~26-fold difference in unit cell parameters. fft1d is more likely to succeed in this case.

```
$ dials.index  1_SWEEP1_datablock.json 1_SWEEP1_strong.pickle filter_ice=false indexing.method=fft1d

RMSDs by experiment:
---------------------------------------------
| Exp | Nref | RMSD_X  | RMSD_Y  | RMSD_Z   |
| id  |      | (px)    | (px)    | (images) |
---------------------------------------------
| 0   | 3569 | 0.24717 | 0.18407 | 0.34255  |
---------------------------------------------

Refined crystal models:
model 1 (3838 reflections):
Crystal:
    Unit cell: (5.867, 5.868, 153.774, 91.078, 90.015, 120.012)
    Space group: P 1
    U matrix:  {{ 0.3894,  0.3298, -0.8600},
                { 0.3632, -0.9130, -0.1857},
                {-0.8464, -0.2400, -0.4753}}
    B matrix:  {{ 0.1704,  0.0000,  0.0000},
                { 0.0985,  0.1968,  0.0000},
                { 0.0022,  0.0043,  0.0065}}
    A = UB:    {{ 0.0970,  0.0612, -0.0056},
                {-0.0284, -0.1805, -0.0012},
                {-0.1689, -0.0493, -0.0031}}

1068 unindexed reflections
```

**Comment by rjgildea** [comment]
xia2 succeeds with the addition of `dials.index.method=auto`:

```
$ xia2 small_molecule=true read_all_image_headers=false trust_beam_centre=true pipeline=dials image=/dls/i19-1/data/2017/mt11231-14/MJR1946_CD52_C1_300_2/MJR1946_CD52_C1_300_2_01_00001.cbf dials.index.method=auto

For AUTOMATIC/DEFAULT/NATIVE                Suggested   Low    High  Overall
High resolution limit                           1.22    3.06    1.22    1.21
Low resolution limit                            5.12    5.12    1.24    5.12
Completeness                                   78.2    99.0    13.6    77.5
Multiplicity                                    4.9     4.7     1.0     4.9
I/sigma                                         5.8     6.1     2.8     5.7
Rmerge(I)                                     0.178   0.168   0.000   0.178
Rmeas(I)                                      0.205   0.189   0.000   0.205
Rpim(I)                                       0.098   0.085   0.000   0.098
CC half                                       0.963   0.941   0.000   0.963
Total observations                             5098     471       8    5099
Total unique                                   1038     100       8    1039
Assuming spacegroup: R -3 m :H
Other likely alternatives are:
H -3 c
H 3 2
H 3 m
H 3 c
Unit cell (with estimated std devs):
 5.8678462(10)  5.8678462(10) 461.204(4)
90.0           90.0           120.0  
```

**Comment by rjgildea** [comment]
Turns out if we just ignore that error then fft3d indexing succeeds anyway!
