### ISSUE TITLE
dials.refine error

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#289]
```
$ pwd
/dls/tmp/rjgildea/for_david

$ dials.refine  '5_refined_experiments.json' '5_refined.pickle' 'scan_varying=True' 'close_to_spindle_cutoff=0.020000' 'outlier.algorithm=auto' 'output.experiments=6_refined_experiments.json' 'output.reflections=6_refined.pickle' 'reflections_per_degree=100' 'unit_cell.smoother.interval_width_degrees=3' 'orientation.smoother.interval_width_degrees=3' 'detector.fix=all' 'beam.fix=all'
Performing refinement of a single Experiment...
Traceback (most recent call last):
  File "/dls/science/users/hko55533/software/cctbx/build/../modules/dials/command_line/refine.py", line 402, in <module>
    halraiser(e)
  File "/dls/science/users/hko55533/software/cctbx/build/../modules/dials/command_line/refine.py", line 400, in <module>
    script.run()
  File "/dls/science/users/hko55533/software/cctbx/build/../modules/dials/command_line/refine.py", line 264, in run
    history = refiner.run()
  File "/dls/science/users/hko55533/software/cctbx/modules/dials/algorithms/refinement/refiner.py", line 1887, in run
    self._refinery.run()
  File "/dls/science/users/hko55533/software/cctbx/modules/dials/algorithms/refinement/engine.py", line 844, in run
    self._run_core()
  File "/dls/science/users/hko55533/software/cctbx/modules/dials/algorithms/refinement/engine.py", line 755, in _run_core
    self.build_up()
  File "/dls/science/users/hko55533/software/cctbx/modules/dials/algorithms/refinement/engine.py", line 538, in build_up
    self._target.compute_residuals_and_gradients(block)
  File "/dls/science/users/hko55533/software/cctbx/modules/dials/algorithms/refinement/target.py", line 375, in compute_residuals_and_gradients
    gradients = self.calculate_gradients(matches)
  File "/dls/science/users/hko55533/software/cctbx/modules/dials/algorithms/refinement/target.py", line 210, in calculate_gradients
    reflections, callback)
  File "/dls/science/users/hko55533/software/cctbx/modules/dials/algorithms/refinement/parameterisation/prediction_parameters.py", line 339, in get_gradients
    assert w.all_ne(0)
AssertionError: Please report this error to dials-support@lists.sourceforge.net:
```

**Comment by dagewa** [comment]
UB has become (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0) for many reflections. Investigating why...
