### ISSUE TITLE
tst_stills_process still failing

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#301]
```
Traceback (most recent call last):
  File "/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials/test/command_line/tst_stills_process.py", line 116, in <module>
    test.run()
  File "/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials/test/command_line/tst_stills_process.py", line 19, in run
    self.test_sacla_h5()
  File "/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials/test/command_line/tst_stills_process.py", line 106, in test_sacla_h5
    table = pickle.load(open(result, 'rb'))
IOError: [Errno 2] No such file or directory: 'idx-run266702-0-subset_00001_integrated.pickle'
```

According to Jenkins this appears to have been caused by either @6efbc692a1dc98e865b44c762d1bbec4154c0b09 or @562b9caad89ca11461d7c15af436a43ef593aa22.

More useful information can be found in [STDOUT](https://github.com/dials/dials/files/753953/stdout.txt).

**Comment by Anthchirp** [comment]
Part of the problem here is the error handling in https://github.com/dials/dials/blob/master/command_line/stills_process.py#L361

**Comment by Anthchirp** [comment]
Backing out @562b9ca fixed the build. You can retrieve the changes from that commit by running
```git cherry-pick 562b9ca; git reset --soft HEAD^``` in the dials modules directory.
When you recommit after testing you may want to reuse the original commit message of @562b9ca.

**Comment by phyy-nx** [comment]
Great. Thanks Markus. 

-Aaron

**Comment by graeme-winter** [comment]
So this is fixed now?

**Comment by phyy-nx** [comment]
Yeppers.  Thanks.
