### ISSUE TITLE
LIBTBX_IMPORTCACHE fails phenix and cctbx regression tests

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#308]
With LIBTBX_IMPORTCACHE, two tests fail:
phenix_regression/gui/tst_import.py
cctbx_project/mmtbx/ringer/tst_emringer.py

They both fail in matplotlib in the same way, with either version 1.5.1 or 2.0.0.  Here is Nigel's test (note there is a simpler way to get the failure included below):
<pre>
nigel@anaconda>  setenv LIBTBX_IMPORTCACHE 1
nigel@anaconda> libtbx.python "/dev/shm/nigel/bootstrap/modules/cctbx_project/mmtbx/ringer/tst_emringer.py"
Traceback (most recent call last):
  File "/dev/shm/nigel/bootstrap/modules/cctbx_project/mmtbx/ringer/tst_emringer.py", line 126, in <module>
    exercise_emringer_residue_scan()
  File "/dev/shm/nigel/bootstrap/modules/cctbx_project/mmtbx/ringer/tst_emringer.py", line 21, in exercise_emringer_residue_scan
    results, scoring, rolling = emringer.run([pdb_file, map_file], out=null_out())
  File "/dev/shm/nigel/bootstrap/modules/cctbx_project/mmtbx/command_line/emringer.py", line 163, in run
    import matplotlib
  File "/dev/shm/nigel/bootstrap/build/../base/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/dev/shm/nigel/bootstrap/base/lib/python2.7/site-packages/matplotlib/__init__.py", line 122, in <module>
    from matplotlib.cbook import is_string_like, mplDeprecation, dedent, get_label
  File "/dev/shm/nigel/bootstrap/build/../base/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/dev/shm/nigel/bootstrap/base/lib/python2.7/site-packages/matplotlib/cbook.py", line 13, in <module>
    from six.moves import xrange, zip
ImportError: No module named moves
nigel@anaconda> unsetenv LIBTBX_IMPORTCACHE
nigel@anaconda> libtbx.python "/dev/shm/nigel/bootstrap/modules/cctbx_project/mmtbx/ringer/tst_emringer.py"
OK
</pre>

Simpler way to get the failure:
$ python -c "from six.moves import xrange, zip"
$ export LIBTBX_IMPORTCACHE=1
$ python -c "from six.moves import xrange, zip"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named moves

**Comment by graeme-winter** [comment]
Additional useful information

https://pythonhosted.org/six/ <https://pythonhosted.org/six/>

> Six provides simple utilities for wrapping over differences between Python 2 and Python 3. It is intended to support codebases that work on both Python 2 and 3 without modification. six consists of only one Python file, so it is painless to copy into a project.

**Comment by graeme-winter** [comment]
Verified

```
Graemes-MacBook-Pro-5:i04-bag-training graeme$ dials.python  -c "from six.moves import xrange, zip"
Graemes-MacBook-Pro-5:i04-bag-training graeme$ LIBTBX_IMPORTCACHE=1 dials.python  -c "from six.moves import xrange, zip"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named moves
```

**Comment by Anthchirp** [comment]
Thanks. I'll look into that when I revisit the mechanism. Sidenote: At the moment the actual performance improvement measured in time is less than what would be expected based on the file system calls alone. So there is little point in deploying anywhere it at this time.

**Comment by Anthchirp** [comment]
Import cache mechanism has been removed
