### ISSUE TITLE
RLV broken in 1.4.4

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#313]
```
dials.import *cbf
dials.find_spots datablock.json  # nproc=4
dials.reciprocal_lattice_viewer datablock.json strong.pickle
```

=>

```
RuntimeError: dials Error: Could not find "imageset_id" in table
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v1-4-4/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 737, in <module>
    run(sys.argv[1:])
  File "/dls_sw/apps/dials/dials-v1-4-4/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 728, in run
    f.load_models(imagesets, reflections)
  File "/dls_sw/apps/dials/dials-v1-4-4/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 267, in load_models
    render_3d.load_models(self, imagesets, reflections)
  File "/dls_sw/apps/dials/dials-v1-4-4/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 94, in load_models
    self.set_points()
  File "/dls_sw/apps/dials/dials-v1-4-4/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 333, in set_points
    render_3d.set_points(self)
  File "/dls_sw/apps/dials/dials-v1-4-4/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 229, in set_points
    for i in range(0, flex.max(reflections['imageset_id'])+1):
RuntimeError: dials Error: Could not find "imageset_id" in table
```

**Comment by Anthchirp** [comment]
Fixed by cherry-picking 08b0bcbfc27e0c243a3afc75be0de576ae38f9c5
