### ISSUE TITLE
rl_png broken

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#315]
load_models() call is incorrect.

With that fixed:

```
Traceback (most recent call last):
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/rl_png.py", line 217, in <module>
    run(sys.argv[1:])
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/rl_png.py", line 159, in run
    f.load_models(imagesets, reflections, None)
  File "/scratch/wra62962/files/dials/modules/dials/command_line/reciprocal_lattice_viewer.py", line 99, in load_models
    self.set_points()
  File "/scratch/wra62962/files/dials/modules/dials/command_line/reciprocal_lattice_viewer.py", line 232, in set_points
    self.viewer.set_palette(palette)
AttributeError: 'PngScene' object has no attribute 'set_palette'
```

with that skipped:

```
Traceback (most recent call last):
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/rl_png.py", line 217, in <module>
    run(sys.argv[1:])
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/rl_png.py", line 204, in run
    result = run_dps((imagesets[0], reflections, hardcoded_phil))
  File "/scratch/wra62962/files/dials/modules/dials/command_line/discover_better_experimental_model.py", line 285, in run_dps
    imageset, spots_mm, max_cell, params = args
ValueError: need more than 3 values to unpack
```

**Comment by Anthchirp** [comment]
Caused by @dagewa in bf440a1886dda6069a965d96cd62b653c297c7fa

@dagewa, is it ok to set crystals=None in the function signatures for backward compatibility?

**Comment by dagewa** [comment]
Yes, I should think so. Maybe I should have suggested cherry-picking those
commits too. I would like the reciprocal unit cell display in a release by
the middle of May - it is useful for the DPF3 case being presented at Oulu.

What's the timeline for 1.5?

-- David

**Comment by Anthchirp** [comment]
1.5 is end-of-March-y (#260)

**Comment by rjgildea** [comment]
I think this is resolved?

**Comment by Anthchirp** [comment]
Negative. 

```
$ dials.rl_png experiments.json indexed.pickle  marker_size=2 size_inches=20,20
The following parameters have been modified:

marker_size = 2
plot {
  size_inches = 20 20
}
input {
  experiments = experiments.json
  reflections = indexed.pickle
}

Traceback (most recent call last):
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/rl_png.py", line 217, in <module>
    run(sys.argv[1:])
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/rl_png.py", line 159, in run
    f.load_models(imagesets, reflections, None)
  File "/scratch/wra62962/files/dials/modules/dials/command_line/reciprocal_lattice_viewer.py", line 99, in load_models
    self.set_points()
  File "/scratch/wra62962/files/dials/modules/dials/command_line/reciprocal_lattice_viewer.py", line 232, in set_points
    self.viewer.set_palette(palette)
AttributeError: 'PngScene' object has no attribute 'set_palette'

$ dials.version
DIALS 1.dev.1195-geff8d69
```
