### ISSUE TITLE
dials.combine_found_spots error

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#320]
```
$ dials.import template=$(libtbx.find_under_build xia2_regression/test_data/i04_bag_training)/th_8_2_####.cbf image_range=1,270 output.datablock=datablock_1_270.json
$ dials.import template=$(libtbx.find_under_build xia2_regression/test_data/i04_bag_training)/th_8_2_####.cbf image_range=271,540 output.datablock=datablock_271_540.json
$ dials.find_spots datablock_1_270.json output.reflections=strong_1_270.pickle nproc=8
$ dials.find_spots datablock_271_540.json output.reflections=strong_271_540.pickle nproc=8
$ dials.combine_found_spots datablock_1_270.json datablock_271_540.json strong_1_270.pickle strong_271_540.pickle
DIALS 1.dev.1213-gdbe753c
The following parameters have been modified:

input {
  datablock = datablock_1_270.json
  datablock = datablock_271_540.json
  reflections = strong_1_270.pickle
  reflections = strong_271_540.pickle
}

Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/combine_found_spots.py", line 318, in <module>
    halraiser(e)
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/combine_found_spots.py", line 316, in <module>
    script.run()
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/combine_found_spots.py", line 292, in run
    params)
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/combine_found_spots.py", line 184, in combine
    raise RuntimeError('Scans do not match')
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: Scans do not match
```

**Comment by rjgildea** [comment]
Originally reported at https://github.com/dials/dials/issues/138#issuecomment-227468421 but reporting here as separate issue

**Comment by jmp1985** [comment]
Now fixed, so closing
