### ISSUE TITLE
dials.import reference geometry "__id__ does not equal imageset"

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#334]
```
dials.import  /dls/i19-2/data/2017/mt15000-1/11_Ptdddt2_p1/11_Ptdddt2_*.cbf  allow_multiple_sweeps=True reference_geometry=/dls/i19-2/data/2017/mt14928-1/processing/mrw_processing_UBcrysalis/qzpd01_run2/3_experiments.json
(..)
Traceback (most recent call last):
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/dials_import.py", line 731, in <module>
    halraiser(e)
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/dials_import.py", line 729, in <module>
    script.run()
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/dials_import.py", line 619, in run
    metadata_updater = MetaDataUpdater(params)
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/dials_import.py", line 410, in __init__
    self.update_geometry.append(ReferenceGeometryUpdater(self.params))
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/dials_import.py", line 216, in __init__
    self.reference = self.load_reference_geometry(params)
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/dials_import.py", line 254, in load_reference_geometry
    datablock = load.datablock(params.input.reference_geometry)
  File "/scratch/wra62962/files/dials/modules/cctbx_project/dxtbx/serialize/load.py", line 86, in datablock
    filename, check_format=check_format)
  File "/scratch/wra62962/files/dials/modules/cctbx_project/dxtbx/datablock.py", line 974, in from_serialized_format
    return DataBlockFactory.from_imageset_json_file(filename)
  File "/scratch/wra62962/files/dials/modules/cctbx_project/dxtbx/datablock.py", line 954, in from_imageset_json_file
    imageset = load.imageset(filename)
  File "/scratch/wra62962/files/dials/modules/cctbx_project/dxtbx/serialize/load.py", line 72, in imageset
    return imageset_from_string(infile.read())
  File "/scratch/wra62962/files/dials/modules/cctbx_project/dxtbx/serialize/load.py", line 54, in imageset_from_string
    return imageset_from_dict(json.loads(string, object_hook=_decode_dict))
  File "/scratch/wra62962/files/dials/modules/cctbx_project/dxtbx/serialize/imageset.py", line 205, in imageset_from_dict
    raise ValueError("\"__id__\" does not equal \"imageset\"")
ValueError: Please report this error to dials-support@lists.sourceforge.net: "__id__" does not equal "imageset"
```
```__id__``` is in fact ```ExperimentList```

**Comment by Anthchirp** [comment]
Underlying error:
```
Traceback (most recent call last):
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/dials_import.py", line 735, in <module>
    halraiser(e)
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/dials_import.py", line 733, in <module>
    script.run()
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/dials_import.py", line 623, in run
    metadata_updater = MetaDataUpdater(params)
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/dials_import.py", line 414, in __init__
    self.update_geometry.append(ReferenceGeometryUpdater(self.params))
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/dials_import.py", line 216, in __init__
    self.reference = self.load_reference_geometry(params)
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/dials_import.py", line 253, in load_reference_geometry
    assert len(experiments.detectors()) == 1
```

**Comment by graeme-winter** [comment]
Ah we should trap that more gracefully then…

**Comment by Anthchirp** [comment]
Unless we want to support multiple reference geometries this will be a _wontfix_
