### ISSUE TITLE
dials.export_bitmaps for multiple panel detector

### ISSUE THREAD

**Issue by dagewa** [dials/dials#338]
This gives a strange result (pink oblong below):

```
wget https://www.dropbox.com/s/a9w4p8ll5v0vkmh/distortion.tgz
tar xzf distortion.tgz
dials.export_bitmaps db_one_image.json
```

I'm guessing it is because this is a multi-panel detector.

![image0001](https://cloud.githubusercontent.com/assets/11502083/25181902/edcf113c-250a-11e7-893f-0b299be0d4b6.png)

**Comment by rjgildea** [comment]
dials.image_viewer also fails on this image - possibly this is the same reason dials.export_bitmaps isn't working correctly?
```
$ dials.image_viewer db_one_image.json 
The following parameters have been modified:

input {
  datablock = db_one_image.json
}

Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/image_viewer.py", line 200, in <module>
    runner()
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/image_viewer.py", line 137, in __call__
    self.view()
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/image_viewer.py", line 145, in view
    reflections=self.reflections)
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_wrap.py", line 32, in display
    self.frame.load_image(chooser_wrapper(imagesets[0], 0))
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py", line 463, in load_image
    show_untrusted=show_untrusted)
  File "/Users/rjgildea/software/cctbx/modules/cctbx_project/rstbx/slip_viewer/frame.py", line 345, in load_image
    get_raw_data=get_raw_data)
  File "/Users/rjgildea/software/cctbx/modules/cctbx_project/rstbx/slip_viewer/tile_generation.py", line 272, in set_image
    color_scheme=self.current_color_scheme)
  File "/Users/rjgildea/software/cctbx/modules/cctbx_project/rstbx/slip_viewer/tile_generation.py", line 65, in _get_flex_image_multipanel
    assert len(panels) == len(raw_data)
AssertionError

```

**Comment by dagewa** [comment]
Interesting, works for me

```
$ dials.image_viewer db_one_image.json 
The following parameters have been modified:

input {
  datablock = db_one_image.json
}

```

But I may not be at the bleeding edge and perhaps there is breakage on the horizon. I will check...

![im_view](https://cloud.githubusercontent.com/assets/11502083/25182229/da726fc0-250b-11e7-9686-9c8b541dedc2.png)

**Comment by rjgildea** [comment]
I can't reproduce your multi-panel datablock.json:
```
$ dials.import 1_000001.img 
DIALS 1.dev.1313-g376ec50
The following parameters have been modified:

input {
  datablock = <image files>
}

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatSMVFakeADSC.FormatSMVFakeADSC'>
  num images: 1
  num sweeps: 1
  num stills: 0
--------------------------------------------------------------------------------
Writing datablocks to datablock.json
$ dials.show datablock.json 
The following parameters have been modified:

input {
  datablock = datablock.json
}

/Users/rjgildea/Downloads/1_######.img
Detector:
Panel:
  name: Panel
  type: SENSOR_CCD
  identifier: 
  pixel_size:{0.055,0.055}
  image_size: {512,512}
  trusted_range: {-1,1e+06}
  thickness: 0
  material: 
  mu: 0
  gain: 1
  fast_axis: {1,0,0}
  slow_axis: {0,1,0}
  origin: {-249.36,-246.34,-1089.42}
Max resolution: 0.080959

Beam:
    wavelength: 0.0251
    sample to source direction : {0,0,1}
    divergence: 0
    sigma divergence: 0
    polarization normal: {0,1,0}
    polarization fraction: 0.999
Beam centre (mm): (249.36,246.34)
Beam centre (px): (4533.82,4478.91)

Scan:
    image range:   {1,1}
    oscillation:   {-43.4,0.9}
    exposure time: 0

Goniometer:
    Rotation axis:   {1,0,0}
    Fixed rotation:  {1,0,0,0,1,0,0,0,1}
    Setting rotation:{1,0,0,0,1,0,0,0,1}
```

**Comment by dagewa** [comment]
It should pick up FormatSMVTimePix_SU

```
$ dxtbx.print_header 1_000001.img 
=== 1_000001.img ===
Using header reader: FormatSMVTimePix_SU
Beam:
    wavelength: 0.0251
    sample to source direction : {0,0,1}
    divergence: 0
    sigma divergence: 0
    polarization normal: {0,1,0}
    polarization fraction: 0.999

Detector:
Panel:
  name: Panel0
  type: SENSOR_PAD
  identifier: 
  pixel_size:{0.055,0.055}
  image_size: {254,254}
  trusted_range: {-1,65535}
  thickness: 0.3
  material: Si
  mu: 0
  gain: 1
  fast_axis: {1,0,0}
  slow_axis: {0,-1,0}
  origin: {-13.6598,13.4937,-1089.42}
Panel:
  name: Panel1
  type: SENSOR_PAD
  identifier: 
  pixel_size:{0.055,0.055}
  image_size: {254,254}
  trusted_range: {-1,65535}
  thickness: 0.3
  material: Si
  mu: 0
  gain: 1
  fast_axis: {1,0,0}
  slow_axis: {0,-1,0}
  origin: {0.6402,13.4937,-1089.42}
Panel:
  name: Panel2
  type: SENSOR_PAD
  identifier: 
  pixel_size:{0.055,0.055}
  image_size: {254,254}
  trusted_range: {-1,65535}
  thickness: 0.3
  material: Si
  mu: 0
  gain: 1
  fast_axis: {1,0,0}
  slow_axis: {0,-1,0}
  origin: {-13.6598,-0.8063,-1089.42}
Panel:
  name: Panel3
  type: SENSOR_PAD
  identifier: 
  pixel_size:{0.055,0.055}
  image_size: {254,254}
  trusted_range: {-1,65535}
  thickness: 0.3
  material: Si
  mu: 0
  gain: 1
  fast_axis: {1,0,0}
  slow_axis: {0,-1,0}
  origin: {0.6402,-0.8063,-1089.42}

Goniometer:
    Rotation axis:   {-0.754864,-0.655882,0}
    Fixed rotation:  {1,0,0,0,1,0,0,0,1}
    Setting rotation:{1,0,0,0,1,0,0,0,1}

Scan:
    image range:   {1,1}
    oscillation:   {-43.4,0.9}
    exposure time: 2

Total Counts: 14951363
```

**Comment by rjgildea** [comment]
Release and nightly don't have the same behaviour:
```
$ module load dials
$ dials.import 1_000001.img 
DIALS 1.5.0-gbc51d76c
--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatSMVTimePix_SU.FormatSMVTimePix_SU'>
  num images: 1
  num sweeps: 1
  num stills: 0
--------------------------------------------------------------------------------
Writing datablocks to datablock.json
$ module load dials/nightly
$ dials.import 1_000001.img 
DIALS 1.dev.1311-g69dbd946
--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatSMVFakeADSC.FormatSMVFakeADSC'>
  num images: 1
  num sweeps: 1
  num stills: 0
--------------------------------------------------------------------------------
Writing datablocks to datablock.json
```

**Comment by dagewa** [comment]
I don't understand that, unless nightly has an older cctbx than release, which sounds wrong. The relevant commits were a month or more ago https://github.com/cctbx/cctbx_project/commit/53b635ce8aebe395a2858cf61b2e8922a60f9349

**Comment by rjgildea** [comment]
@jmp1985 added the format class FormatSMVFakeADSC recently as part of this commit: https://github.com/cctbx/cctbx_project/commit/6beeb1f1c505a72cf537834f86b968dddac36047#diff-157438586405348e094942d1c10354b9

**Comment by dagewa** [comment]
I have that Format class too, and indeed it does 'understand' my image. I suppose that on my computer, the proper one wins the race.

```
$ dials.python $(libtbx.find_in_repositories dxtbx)/format/FormatSMVFakeADSC.py 1_000001.img
True
Beam:
    wavelength: 0.0251
    sample to source direction : {0,0,1}
    divergence: 0
    sigma divergence: 0
    polarization normal: {0,1,0}
    polarization fraction: 0.999

Detector:
Panel:
  name: Panel
  type: SENSOR_CCD
  identifier: 
  pixel_size:{0.055,0.055}
  image_size: {512,512}
  trusted_range: {-1,1e+06}
  thickness: 0
  material: 
  mu: 0
  gain: 1
  fast_axis: {1,0,0}
  slow_axis: {0,1,0}
  origin: {-249.36,-246.34,-1089.42}

Goniometer:
    Rotation axis:   {1,0,0}
    Fixed rotation:  {1,0,0,0,1,0,0,0,1}
    Setting rotation:{1,0,0,0,1,0,0,0,1}

Scan:
    image range:   {1,1}
    oscillation:   {-43.4,0.9}
    exposure time: 0

<scitbx_array_family_flex_ext.int object at 0x7fc8c82ad4d0>
```

**Comment by dagewa** [comment]
Getting a bit off topic here, but FormatSMVADSC tended to be rather promiscuous and a slightly ugly, but successful, way to get it to behave was to explicitly exclude other FormatSMV types. See e.g. https://github.com/cctbx/cctbx_project/commit/82ad419f7c78ef6fef7df926b7fd4c2bd606dddd

It looks like FormatSMVFakeADSC needs the same trick.

**Comment by rjgildea** [comment]
I'm not sure dials.export_bitmaps has ever worked properly for multi-panel detectors. Fixing it looks to be non-trivial, therefore it now fails early saying only single panel detectors are supported.

**Comment by dagewa** [comment]
No problem, I expected this was the case
