### ISSUE TITLE
"image not found" error on MacOS

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#341]
```
$ dials.python
Python 2.7.13 (default, May  2 2017, 01:42:27) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dials
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dlshudson/jenkins_slave/workspace/dials_tests_mac/build_dials/modules/dials/__init__.py", line 2, in <module>
    import dials.extensions
  File "/Users/dlshudson/jenkins_slave/workspace/dials_tests_mac/build_dials/modules/dials/extensions/__init__.py", line 70, in <module>
    _modules = import_extensions()
  File "/Users/dlshudson/jenkins_slave/workspace/dials_tests_mac/build_dials/modules/dials/extensions/__init__.py", line 49, in import_extensions
    return import_sub_modules(paths)
  File "/Users/dlshudson/jenkins_slave/workspace/dials_tests_mac/build_dials/modules/dials/extensions/__init__.py", line 32, in import_sub_modules
    modules.append(loader.load_module(modname))
  File "/Users/dlshudson/jenkins_slave/workspace/dials_bootstrap_platforms/label/dials-mac-mini/build_dials/base/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/Users/dlshudson/jenkins_slave/workspace/dials_tests_mac/build_dials/modules/dials/extensions/gaussian_rs_profile_model_ext.py", line 13, in <module>
    from dials.interfaces import ProfileModelIface
  File "/Users/dlshudson/jenkins_slave/workspace/dials_tests_mac/build_dials/modules/dials/interfaces/__init__.py", line 63, in <module>
    class ProfileModelIface(interface.Interface):
  File "/Users/dlshudson/jenkins_slave/workspace/dials_tests_mac/build_dials/modules/dials/interfaces/__init__.py", line 55, in __init__
    from dxtbx.model.profile import ProfileModelFactory
  File "/Users/dlshudson/jenkins_slave/workspace/dials_tests_mac/build_dials/modules/cctbx_project/dxtbx/model/__init__.py", line 5, in <module>
    from dxtbx_model_ext import *
ImportError: dlopen(/Users/dlshudson/jenkins_slave/workspace/dials_tests_mac/build_dials/build/lib/dxtbx_model_ext.so, 2): Library not loaded: /Users/dlshudson/jenkins_slave/workspace/dials_bootstrap_platforms/label/dials-mac-mini/build_dials/base/lib/libtiff.5.dylib
  Referenced from: /Users/dlshudson/jenkins_slave/workspace/dials_tests_mac/build_dials/build/lib/dxtbx_model_ext.so
  Reason: image not found
```

**Comment by Anthchirp** [comment]
resolved now
