### ISSUE TITLE
kapton test broken

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#367]
```test/command_line/tst_kapton_correction.py``` keeps failing:
```
Traceback (most recent call last):
  File "/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials/test/command_line/tst_kapton_correction.py", line 104, in <module>
    test.run()
  File "/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials/test/command_line/tst_kapton_correction.py", line 19, in run
    self.test_integrate_with_kapton()
  File "/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials/test/command_line/tst_kapton_correction.py", line 79, in test_integrate_with_kapton
    'dials.integrate', pickle_path, json_path, phil
  File "/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/cctbx_project/libtbx/easy_run.py", line 39, in raise_if_errors
    raise Error(msg)
RuntimeError: child process stderr output:
  command: ['dials.integrate', '/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials_regression/integration_test_data/stills_PSII/idx-20161021225550223_indexed.pickle', '/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials_regression/integration_test_data/stills_PSII/idx-20161021225550223_refined_experiments.json', 'integrate_without_kapton.phil']
  Sorry: Unable to handle the following arguments:
    /scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials_regression/integration_test_data/stills_PSII/idx-20161021225550223_refined_experiments.json
  
  Please check that your image data is accessible
```
The test depends on the pickle files being in /Users/idyoung/(...).
This is not generally true.

The absolute path is contained in both .phil and .json files.

**Comment by idyoung** [comment]
Removed the test from run_tests.py for the time being. I can imagine a few options for fixing this but none seem ideal. 

1. Leave %s in place of any absolute paths, and copy and fill these in when the test is run
2. Generate everything from the image pickle even though the earlier steps are unrelated
3. Use absolute paths on viper instead and skip the test if we're not on viper

Is there a preferred way?

**Comment by dagewa** [comment]
I would say option 1 in any case and you can still choose whether or not to skip the test without viper, depending on your use case.
