### ISSUE TITLE
Not really new; I think this one is old; dials.image_viewer borks with I23 P12M images

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#380]
Have seen this one on and off in the past... it's back

```
[gw56@ws133 armin]$ dials.geometry_viewer datablock.json 
The following parameters have been modified:

input {
  datablock = datablock.json
}

Gtk-Message: Failed to load module "canberra-gtk-module"
[gw56@ws133 armin]$ dials.image_viewer datablock.json 
The following parameters have been modified:

input {
  datablock = datablock.json
}

Gtk-Message: Failed to load module "canberra-gtk-module"
Memory usage: 108.6 MB
Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/image_viewer.py", line 200, in <module>
    runner()
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/image_viewer.py", line 137, in __call__
    self.view()
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/image_viewer.py", line 145, in view
    reflections=self.reflections)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/image_viewer/spotfinder_wrap.py", line 35, in display
    self.frame.load_image(chooser_wrapper(imagesets[0], 0))
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py", line 470, in load_image
    show_untrusted=show_untrusted)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/rstbx/slip_viewer/frame.py", line 345, in load_image
    get_raw_data=get_raw_data)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/rstbx/slip_viewer/tile_generation.py", line 262, in set_image
    color_scheme=self.current_color_scheme)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/rstbx/slip_viewer/tile_generation.py", line 104, in _get_flex_image_multipanel
    beam_center += col(panel.get_beam_centre_lab(beam.get_s0()))
RuntimeError: dxtbx Internal Error: /dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/model/virtual_panel.h(247): DXTBX_ASSERT(v[2] > 0) failure.

```

**Comment by graeme-winter** [comment]
OK, also with straight image - as attached

[380.zip](https://github.com/dials/dials/files/1082392/380.zip)

**Comment by graeme-winter** [comment]
Relevant to #378 because I was trying to test multi-panel as requested...

**Comment by graeme-winter** [comment]
OK, logic in here should check if panels are (roughly) coplanar - if they are then use this else get the lab frame intersection with the detector as a whole.

**Comment by rjgildea** [comment]
The beam centre is nonsense in the image header:

```
$ strings data_1_0001.cbf | grep Beam
# Beam_xy (0.00, 0.00) pixels
```

**Comment by graeme-winter** [comment]
Good spot!

**Comment by rjgildea** [comment]
<img width="684" alt="screen shot 2017-06-19 at 09 00 47" src="https://user-images.githubusercontent.com/2810624/27288930-dd305a32-54cd-11e7-88f0-ea5ce9a58582.png">

**Comment by rjgildea** [comment]
I can't reproduce your error above, and it looks like the problem here is with the image headers rather than the image viewer - can we close this issue?

**Comment by graeme-winter** [comment]
Will test again with correct images but closing with prejudice, assume is fine
