### ISSUE TITLE
dials.estimate_gain fails on multiple image file

### ISSUE THREAD

**Issue by dagewa** [dials/dials#390]
An example is the file below on /dls/tmp (also on viper /scratch/)

```
$ dials.estimate_gain /dls/tmp/david/Lys2_grid1_diffraction_lamella2_1.ser
The following parameters have been modified:

input {
  datablock = <image files>
}

q1, q2, q3: 1.00, 1.00, 1.00
Traceback (most recent call last):
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20170626/build/../modules/dials/command_line/estimate_gain.py", line 163, in <module>
    run(sys.argv[1:])
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20170626/build/../modules/dials/command_line/estimate_gain.py", line 156, in run
    estimate_gain(imageset, params.kernel_size, params.output.gain_map, params.max_images)
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20170626/build/../modules/dials/command_line/estimate_gain.py", line 82, in estimate_gain
    gain = sorted_dispersion[nint(len(sorted_dispersion)/2)]
IndexError: Index out of range.

```

**Comment by graeme-winter** [comment]
This is not universally true, viz:

```
Graemes-MacBook-Pro-5:390 graeme$ dials.estimate_gain ~/data/esrf-eiger/thaumatin28_w1_3_1_master.h5 
The following parameters have been modified:

input {
  datablock = <image files>
}

q1, q2, q3: 0.97, 1.01, 1.10
Estimated gain: 1.00
```

**Comment by graeme-winter** [comment]
Actually I think the issue here is gains of 1.0, 1.0, 1.0 sorted may not give behaviour you expect?

**Comment by dagewa** [comment]
The issue seems to be here:
`sorted_dispersion = sorted_dispersion.select(inlier_sel)`
After this `sorted_dispersion` has length 0

**Comment by dagewa** [comment]
Indeed, originally because `q1=q2=q3=0`
