### ISSUE TITLE
libtbx.import_all_ext

### ISSUE THREAD

**Issue by bkpoon** [dials/dials#392]
We've been seeing a warning and an error on buildbot when running `libtbx.import_all_ext`. I also just verified the issue with dials-dev20170626 on CentOS 6.5. I copied the log below

```log
dials
dials.report
dials.array_family
dials.extensions
dials.algorithms
dials.algorithms.background
dials.algorithms.background.gmodel
dials.algorithms.background.simple
dials.algorithms.background.median
dials.algorithms.background.glm
/dev/shm/bkpoon/software/dials-dev20170626/modules/dials/algorithms/background/glm/__init__.py:3: RuntimeWarning: to-Python converter for dials::algorithms::Creator already registered; second conversion method ignored.
  from dials_algorithms_background_glm_ext import *
dials.algorithms.background_lookup
dials.algorithms.shoebox
dials.algorithms.spot_finding
dials.algorithms.spot_finding.helen
dials.algorithms.profile_model
dials.algorithms.profile_model.gaussian_rs
dials.algorithms.profile_model.gaussian_rs.transform
dials.algorithms.profile_model.modeller
dials.algorithms.filtering
dials.algorithms.integration
dials.algorithms.integration.sum
dials.algorithms.integration.fit
dials.algorithms.integration.bayes
Traceback (most recent call last):
  File "/dev/shm/bkpoon/software/dials-dev20170626/build/../modules/cctbx_project/libtbx/command_line/import_all_ext.py", line 106, in <module>
    run(args=sys.argv[1:])
  File "/dev/shm/bkpoon/software/dials-dev20170626/build/../modules/cctbx_project/libtbx/command_line/import_all_ext.py", line 58, in run
    import_modules()
  File "/dev/shm/bkpoon/software/dials-dev20170626/build/../modules/cctbx_project/libtbx/command_line/import_all_ext.py", line 54, in import_modules
    raise e
ImportError: dynamic module does not define init function (initdials_algorithms_integration_bayes_ext)
```

**Comment by jmp1985** [comment]
Hi Billy,

This should now be fixed.

James

________________________________

**Comment by bkpoon** [comment]
Awesome, thanks James!
