### ISSUE TITLE
dials.image_viewer mask generation tool broken

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#395]
I guess this is probably a result of recent changes to image viewer code?

(mask tool under Actions -> show mask tool)

Works in `module load dials`, but fails in `module load dials/nightly`

```
$ dials.image_viewer /dls/mx-scratch/dials/example_data/wide_rotation/X4_wide_M1S4_1_0001.cbf
The following parameters have been modified:

input {
  datablock = <image files>
}

Gtk-Message: Failed to load module "canberra-gtk-module"
Memory usage: 130.7 MB
Memory usage: 365.0 MB

(image_viewer.py:23400): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(image_viewer.py:23400): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(image_viewer.py:23400): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(image_viewer.py:23400): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed
Traceback (most recent call last):
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20170628/modules/dials/util/image_viewer/spotfinder_frame.py", line 190, in OnMask
    style=wx.CAPTION | wx.CLOSE_BOX | wx.RESIZE_BORDER)
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20170628/modules/dials/util/image_viewer/mask_frame.py", line 24, in __init__
    panel = MaskSettingsPanel(self)
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20170628/modules/dials/util/image_viewer/mask_frame.py", line 63, in __init__
    self.UpdateMask()
  File "/dls/science/groups/scisoft/DIALS/CD/nightly/dials-dev20170628/modules/dials/util/image_viewer/mask_frame.py", line 588, in UpdateMask
    image_viewer_frame.update_settings(layout=False)
TypeError: update_settings() got an unexpected keyword argument 'layout'
```

**Comment by ndevenish** [comment]
Dammit I thought I'd tested everything. I removed that parameter because it appeared to be written out and did nothing. Since it's called like an interface should be fine to put back in.
