### ISSUE TITLE
Crash with two image sweep

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#415]
Wanted to test something with a deliberately small 'sweep' e.g. not a still:
```
 cp l-cyst/l-cyst_01_0000[12].cbf .
 dials.import *.cbf
 dials.find_spots datablock.json 
 dials.index strong.pickle datablock.json 
```
And got this error:
```
Traceback (most recent call last):
  File "/dls/science/users/mep23677/dials_pure/build/../modules/dials/command_line/index.py", line 186, in <module>
    run(sys.argv[1:])
  File "/dls/science/users/mep23677/dials_pure/build/../modules/dials/command_line/index.py", line 157, in run
    params=params)
  File "/dls/science/users/mep23677/dials_pure/modules/dials/algorithms/indexing/indexer.py", line 564, in from_parameters
    idxr = indexer_fft3d(reflections, imagesets, params=params)
  File "/dls/science/users/mep23677/dials_pure/modules/dials/algorithms/indexing/fft3d.py", line 35, in __init__
    super(indexer_fft3d, self).__init__(reflections, imagesets, params)
  File "/dls/science/users/mep23677/dials_pure/modules/dials/algorithms/indexing/indexer.py", line 498, in __init__
    self.setup_indexing()
  File "/dls/science/users/mep23677/dials_pure/modules/dials/algorithms/indexing/indexer.py", line 706, in setup_indexing
    self.find_max_cell()
  File "/dls/science/users/mep23677/dials_pure/modules/dials/algorithms/indexing/indexer.py", line 1032, in find_max_cell
    overlaps_border=params.overlaps_border).max_cell
  File "/dls/science/users/mep23677/dials_pure/modules/dials/algorithms/indexing/indexer.py", line 1994, in find_max_cell
    q3 = sorted_bin_counts[nint(len(sorted_bin_counts)*3/4)]
IndexError: Index out of range.
```

**Comment by rjgildea** [comment]
```
$ dials.find_spots datablock.json
...
Saved 10 reflections to strong.pickle
```
Trying to index off 10 spots is not going to end well...

**Comment by Anthchirp** [comment]
is data dependent. Works for my default MX test dataset (52 indexed, 15 non-indexed reflns)

**Comment by rjgildea** [comment]
I suggest that you might want to use an MX dataset rather than a small molecule data set for this, e.g.:
```
$ dials.import $(libtbx.find_in_repositories dials_regression)/centroid_test_data/centroid_000[1-2].cbf
$ dials.find_spots datablock.json
$ dials.index datablock.json strong.pickle 
...
RMSDs by experiment:
---------------------------------------------
| Exp | Nref | RMSD_X  | RMSD_Y  | RMSD_Z   |
| id  |      | (px)    | (px)    | (images) |
---------------------------------------------
| 0   | 205  | 0.48766 | 0.40876 | 1.4474   |
---------------------------------------------

Refined crystal models:
model 1 (250 reflections):
Crystal:
    Unit cell: (39.894, 42.411, 42.833, 89.612, 90.155, 90.121)
    Space group: P 1
    U matrix:  {{-0.2863,  0.7884, -0.5445},
                {-0.9492, -0.3110,  0.0486},
                {-0.1310,  0.5307,  0.8374}}
    B matrix:  {{ 0.0251,  0.0000,  0.0000},
                { 0.0001,  0.0236,  0.0000},
                { 0.0001, -0.0002,  0.0233}}
    A = UB:    {{-0.0072,  0.0187, -0.0127},
                {-0.0238, -0.0073,  0.0011},
                {-0.0032,  0.0124,  0.0195}}

------------------------------------
| Imageset | #indexed | #unindexed |
------------------------------------
| 0        | 250      | 17         |
------------------------------------
Saving refined experiments to experiments.json
Saving refined reflections to indexed.pickle
```

**Comment by Anthchirp** [comment]
dials.index.debug.log for reported issue:
```
DIALS 1.dev.1546-gb291a90
The following parameters have been modified:

input {
  datablock = datablock.json
  reflections = strong.pickle
}

Finding suitable max_cell based on 10 reflections
Rejecting 8 reflections at ice ring resolution
Rejecting 0 overlapping bounding boxes
2 reflections remain for max_cell identification
```

**Comment by rjgildea** [comment]
```
$ dials.index datablock.json strong.pickle
Sorry: Too few spots (2) for nearest neighbour analysis.
```

**Comment by Anthchirp** [comment]
```
DIALS 1.dev.1548-g2a10bb1
The following parameters have been modified:

input {
  datablock = datablock.json
  reflections = strong.pickle
}

Sorry: Too few spots (2) for nearest neighbour analysis.
```
👍
