### ISSUE TITLE
dials.integrate error for I23 dataset

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#425]
Possibly related to #423, but this dials.integrate error persists after the previous refinement bug has been fixed:
/dls/tmp/rjgildea/tst-423/DEFAULT/SAD/SWEEP1/integrate/9_dials.integrate_INTEGRATE.log

```
================================================================================

Initialising

Processing reference reflections
 read 318524 strong spots
 removing 5332 unindexed reflections
 removing 55534 reflections marked as centroid outliers
 using 257658 indexed reflections
 found 60866 junk reflections
 time taken: 0.134388
 masked neighbouring pixels in 257658 shoeboxes


================================================================================

Predicting reflections

Prediction type: scan varying prediction
Predicted 939642 reflections
Matching reference spots with predicted reflections
 257658 observed reflections input
 939642 reflections predicted
 257617 reflections matched
 257617 reflections accepted

********************************************************************************
Warning: 41 reference spots were not matched to predictions
********************************************************************************

Calculating E.S.D Beam Divergence.
Calculating E.S.D Reflecting Range.
Traceback (most recent call last):
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/command_line/integrate.py", line 574, in <module>
    halraiser(e)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/command_line/integrate.py", line 572, in <module>
    script.run()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/command_line/integrate.py", line 315, in run
    experiments = ProfileModelFactory.create(params, experiments, reference)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/algorithms/profile_model/factory.py", line 60, in create
    expr.scan)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/algorithms/profile_model/gaussian_rs/model.py", line 231, in create
    profile)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/algorithms/profile_model/gaussian_rs/model.py", line 386, in create_from_reflections
    algorithm=params.gaussian_rs.sigma_m_algorithm)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/algorithms/profile_model/gaussian_rs/calculator.py", line 536, in __init__
    algorithm=algorithm)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/algorithms/profile_model/gaussian_rs/calculator.py", line 476, in __init__
    crystal, beam, detector, goniometer, scan, reflections)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/algorithms/profile_model/gaussian_rs/calculator.py", line 338, in __init__
    tolerance=1e-3)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/cctbx_project/scitbx/simplex.py", line 53, in __init__
    self.initialize(matrix)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/cctbx_project/scitbx/simplex.py", line 63, in initialize
    self.simplexValue.append(self.function(vector))
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/cctbx_project/scitbx/simplex.py", line 193, in function
    return self.evaluator.target( point )
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/algorithms/profile_model/gaussian_rs/calculator.py", line 371, in target
    assert(mask.count(True) < len(mask))
AssertionError: Please report this error to dials-support@lists.sourceforge.net:
```

**Comment by rjgildea** [comment]
The output of dials.predict on the refined_experiments.json looks perfectly sensible:
![screenshot-62](https://user-images.githubusercontent.com/2810624/28569682-cf1c3a70-7132-11e7-83ce-45993f3d5b83.png)
![screenshot-63](https://user-images.githubusercontent.com/2810624/28569683-d1a5306c-7132-11e7-87ae-5b885afd78c4.png)

**Comment by rjgildea** [comment]
Output of previous scan-varying refinement job (/dls/tmp/rjgildea/tst-423/DEFAULT/SAD/SWEEP1/refine/7_dials.refine_REFINE.log):
```
Refinement steps:
-------------------------------------------------
| Step | Nref  | RMSD_X   | RMSD_Y   | RMSD_Phi |
|      |       | (mm)     | (mm)     | (deg)    |
-------------------------------------------------
| 0    | 18000 | 0.047546 | 0.059373 | 0.019795 |
| 1    | 18000 | 0.04917  | 0.053452 | 0.019587 |
| 2    | 18000 | 0.049014 | 0.053198 | 0.019673 |
| 3    | 18000 | 0.048847 | 0.053124 | 0.019763 |
| 4    | 18000 | 0.048778 | 0.053083 | 0.019807 |
| 5    | 18000 | 0.048765 | 0.053054 | 0.019818 |
| 6    | 18000 | 0.048765 | 0.053041 | 0.019823 |
| 7    | 18000 | 0.048765 | 0.053038 | 0.019825 |
-------------------------------------------------
RMSD no longer decreasing

RMSDs by experiment:
----------------------------------------------
| Exp | Nref  | RMSD_X  | RMSD_Y  | RMSD_Z   |
| id  |       | (px)    | (px)    | (images) |
----------------------------------------------
| 0   | 18000 | 0.28352 | 0.30836 | 0.19825  |
----------------------------------------------

Detector 1 RMSDs by panel:
-----------------------------------------------
| Panel | Nref | RMSD_X  | RMSD_Y  | RMSD_Z   |
| id    |      | (px)    | (px)    | (images) |
-----------------------------------------------
| 1     | 6    | 0.60295 | 0.30095 | 0.27396  |
| 2     | 82   | 0.3517  | 0.58717 | 0.2881   |
| 3     | 396  | 0.35452 | 0.45994 | 0.28579  |
| 4     | 1141 | 0.29181 | 0.36094 | 0.24581  |
| 5     | 1576 | 0.28692 | 0.33117 | 0.21722  |
| 6     | 1698 | 0.27096 | 0.26035 | 0.18962  |
| 7     | 1803 | 0.2724  | 0.26559 | 0.15425  |
| 8     | 1588 | 0.21734 | 0.20902 | 0.14754  |
| 9     | 1122 | 0.3144  | 0.37969 | 0.17423  |
| 10    | 633  | 0.1613  | 0.17221 | 0.1741   |
| 11    | 255  | 0.26504 | 0.18953 | 0.26878  |
| 12    | 80   | 0.12947 | 0.18369 | 0.34352  |
| 13    | 453  | 0.38607 | 0.13308 | 0.25274  |
| 14    | 828  | 0.30622 | 0.19467 | 0.17088  |
| 15    | 1087 | 0.33481 | 0.20735 | 0.14116  |
| 16    | 1347 | 0.20602 | 0.247   | 0.15447  |
| 17    | 1132 | 0.29334 | 0.28895 | 0.17365  |
| 18    | 1113 | 0.34541 | 0.36434 | 0.2143   |
| 19    | 925  | 0.2429  | 0.42028 | 0.25384  |
| 20    | 547  | 0.29664 | 0.44433 | 0.26878  |
| 21    | 153  | 0.34369 | 0.70534 | 0.26472  |
| 22    | 31   | 0.28004 | 0.63588 | 0.29106  |
| 23    | 4    | 0.2366  | 0.84608 | 0.24824  |
-----------------------------------------------
```

**Comment by jmp1985** [comment]
This should now be fixed

**Comment by rjgildea** [comment]
Trying to run dials.integrate on a test dataset gives the following error:
```
$ dials.import /dls/i23/data/2017/nr16818-43/20170518/germanate_11p0keV/data_1_000*.cbf 
$ dials.find_spots datablock.json 
$ dials.index datablock.json strong.pickle space_group=I23
$ dials.refine experiments.json indexed.pickle 
$ dials.integrate refined_experiments.json refined.pickle 
...
Initialising

Processing reference reflections
 read 1237 strong spots
 removing 167 unindexed reflections
 removing 387 reflections marked as centroid outliers
Traceback (most recent call last):
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/dials/command_line/integrate.py", line 576, in <module>
    halraiser(e)
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/dials/command_line/integrate.py", line 574, in <module>
    script.run()
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/dials/command_line/integrate.py", line 226, in run
    reference, rubbish = self.process_reference(reference)
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/dials/command_line/integrate.py", line 405, in process_reference
    raise RuntimeError('reflection table "panel" column does not match "shoebox" panel')
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: reflection table "panel" column does not match "shoebox" panel
```

**Comment by rjgildea** [comment]
It appears to work now, must have run spot-finding pre/mid-compilation so didn't have James' latest fixes...
