### ISSUE TITLE
dials.refine_bravais_settings errors from unhelpful errors 101

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#429]
ran:

```
dials.refine_bravais_settings 5_experiments.json  5_indexed.pickle

```

get the stdout:

```
DIALS 1.dev.1619-g75566d2
The following parameters have been modified:

input {
  experiments = 5_experiments.json
  reflections = 5_indexed.pickle
}

usr+sys time: 50.93 seconds, ticks: 14054214, micro-seconds/tick: 3.624
wall clock time: 97.37 seconds
```

and stderr:

```
Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/refine_bravais_settings.py", line 232, in <module>
    run(sys.argv[1:])
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/refine_bravais_settings.py", line 199, in run
    nproc=params.nproc, refiner_verbosity=params.verbosity)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/algorithms/indexing/symmetry.py", line 152, in refined_settings_factory_from_refined_triclinic
    preserve_exception_message=True)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/libtbx/easy_mp.py", line 623, in parallel_map
    result = res()
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/libtbx/scheduling/result.py", line 119, in __call__
    self.traceback( exception = self.exception() )
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 86, in __call__
    raise exception
RuntimeError: exit code = -9
```

gosh! we are getting close to #computersaysno :smile: 

is this "that thing" about multi processing and errors and stack traces which we discussed a while back?

**Comment by rjgildea** [comment]
Try running with nproc=1...

**Comment by graeme-winter** [comment]
Well yes, however the error above is still unhelpful 😉

**Comment by rjgildea** [comment]
Yes, but this is a long known and discussed "thing" with easy_mp - this is "issue" is not going to be fixed without fixing easy_mp (which is not trivial, I believe @Anthchirp spent some time on it a while back). More "helpful" would be to paste the actual error by running nproc=1

**Comment by graeme-winter** [comment]
Running now...

**Comment by graeme-winter** [comment]
Because this is broken in easy_mp...
