### ISSUE TITLE
dxtbx changes broke i19.screen

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#445]
running ```i19.screen``` on the X4_wide data in xia2_regression fails.

specifically:

```
$ dials.import /home/wra62962/local/dials/build/xia2_regression/test_data/X4_wide/X4_wide_M1S4_2_0001.cbf geometry.scan.image_range=1,90 geometry.scan.extrapolate_scan=True

DIALS 1.dev.1737-geb5b55f
The following parameters have been modified:

input {
  datablock = <image files>
}
geometry {
  scan {
    image_range = 1 90
    extrapolate_scan = True
  }
}


Applying input geometry in the following order:
  1. Manual geometry

Traceback (most recent call last):
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/dials_import.py", line 738, in <module>
    halraiser(e)
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/dials_import.py", line 736, in <module>
    script.run()
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/dials_import.py", line 629, in run
    datablocks = map(metadata_updater, datablock_importer())
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/dials_import.py", line 455, in __call__
    imageset = updater(imageset)
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/dials_import.py", line 323, in __call__
    imageset.set_scan(scan)
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dxtbx Internal Error: /scratch/wra62962/files/dials/modules/cctbx_project/dxtbx/imageset.h(348): DXTBX_ASSERT(index < scans_.size()) failure.
```

**Comment by rjgildea** [comment]
For some reason tst_extrapolate_scan() is commented out:
https://github.com/dials/dials/blob/master/test/command_line/tst_import.py#L21

Uncommenting this leads to:
```
$ dials.python /Users/rjgildea/software/cctbx/modules/dials/test/command_line/tst_import.py 
OK
OK
OK
OK
Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/dials_import.py", line 738, in <module>
    halraiser(e)
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/dials_import.py", line 736, in <module>
    script.run()
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/dials_import.py", line 629, in run
    datablocks = map(metadata_updater, datablock_importer())
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/dials_import.py", line 455, in __call__
    imageset = updater(imageset)
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/dials_import.py", line 323, in __call__
    imageset.set_scan(scan)
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dxtbx Internal Error: /Users/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/imageset.h(348): DXTBX_ASSERT(index < scans_.size()) failure.
dials.import /Users/rjgildea/software/cctbx/modules/dials_regression/centroid_test_data/centroid_0001.cbf output.datablock=import_extrapolate.json geometry.scan.image_range=1,900 geometry.scan.extrapolate_scan=True
Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/modules/dials/test/command_line/tst_import.py", line 237, in <module>
    test.run()
  File "/Users/rjgildea/software/cctbx/modules/dials/test/command_line/tst_import.py", line 21, in run
    self.tst_extrapolate_scan()
  File "/Users/rjgildea/software/cctbx/modules/dials/test/command_line/tst_import.py", line 226, in tst_extrapolate_scan
    assert(exists("import_extrapolate.json"))
AssertionError
```

**Comment by Anthchirp** [comment]
Was commented out as part of the dxtbx refactoring, so assume this was done by mistake.
https://github.com/dials/dials/commit/b65e955849523bd7cee81454d78eacbd087773a2

**Comment by jmp1985** [comment]
Yes,

I'm looking at fixing the issue now.

James

________________________________

**Comment by jmp1985** [comment]
This is now fixed....

**Comment by Anthchirp** [comment]
much obliged
