### ISSUE TITLE
dxtbx changes broke fast_dp

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#446]
```
Traceback (most recent call last):
  File "/home/gw56/svn/fast_dp/src/fast_dp.py", line 416, in main
    missing = fast_dp.set_start_image(image)
  File "/home/gw56/svn/fast_dp/src/fast_dp.py", line 154, in set_start_image
    self._metadata = read_image_metadata(self._start_image)
  File "/home/gw56/svn/fast_dp/lib/image_readers.py", line 292, in read_image_metadata
    return failover_hdf5(image)
  File "/home/gw56/svn/fast_dp/lib/image_readers.py", line 83, in failover_hdf5
    db = DataBlockFactory.from_filenames([hdf5_file])[0]
IndexError: list index out of range

```

DBF now returns empty list :sadface:

**Comment by graeme-winter** [comment]
Trivial reproducer:

```
from dxtbx.datablock import DataBlockFactory
import sys
db = DataBlockFactory.from_filenames([sys.argv[1]])
print db
```
prints:

```
 dials.python tst.py ~/svn/cctbx/build/xia2_regression/test_data/thaumatin_eiger/thaumatin28_w1_3_1_master.h5 
[]
```

**Comment by graeme-winter** [comment]
Ah, is numpy error which was silently ignored...

**Comment by graeme-winter** [comment]
ImportError: numpy.core.multiarray failed to import

did not stop things from working loudly, just meant it returned empty list...

**Comment by graeme-winter** [comment]
This is not a general problem.... seems broken not everywhere...
