### ISSUE TITLE
dials.create_profile_model: Zero pixels selected for estimation of profile parameters.

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#447]
any ideas?

```
$ dials.create_profile_model /dls/tmp/wra62962/directories/TXy4tvm7/49_refined_experiments.json /dls/tmp/wra62962/directories/TXy4tvm7/49_refined.pickle

The following parameters have been modified:

input {
  experiments = /dls/tmp/wra62962/directories/TXy4tvm7/49_refined_experiments.json
  reflections = /dls/tmp/wra62962/directories/TXy4tvm7/49_refined.pickle
}

Processing reference reflections
 read 687 strong spots
 removing 138 unindexed reflections
 removing 81 reflections marked as centroid outliers
 using 468 indexed reflections
 found 219 junk reflections
 time taken: 0.000628948
 masked neighbouring pixels in 468 shoeboxes

================================================================================

Predicting reflections

Prediction type: scan varying prediction
Predicted 781 reflections
Matching reference spots with predicted reflections
 468 observed reflections input
 781 reflections predicted
 468 reflections matched
 468 reflections accepted
Calculating E.S.D Beam Divergence.
Calculating E.S.D Reflecting Range.
Traceback (most recent call last):
  File "/dls/science/users/wra62962/dials/build/../modules/dials/command_line/create_profile_model.py", line 222, in <module>
    halraiser(e)
  File "/dls/science/users/wra62962/dials/build/../modules/dials/command_line/create_profile_model.py", line 220, in <module>
    script.run()
  File "/dls/science/users/wra62962/dials/build/../modules/dials/command_line/create_profile_model.py", line 127, in run
    experiments = ProfileModelFactory.create(params, experiments, reflections)
  File "/dls/science/users/wra62962/dials/modules/dials/algorithms/profile_model/factory.py", line 60, in create
    expr.scan)
  File "/dls/science/users/wra62962/dials/modules/dials/algorithms/profile_model/gaussian_rs/model.py", line 231, in create
    profile)
  File "/dls/science/users/wra62962/dials/modules/dials/algorithms/profile_model/gaussian_rs/model.py", line 386, in create_from_reflections
    algorithm=params.gaussian_rs.sigma_m_algorithm)
  File "/dls/science/users/wra62962/dials/modules/dials/algorithms/profile_model/gaussian_rs/calculator.py", line 538, in __init__
    algorithm=algorithm)
  File "/dls/science/users/wra62962/dials/modules/dials/algorithms/profile_model/gaussian_rs/calculator.py", line 478, in __init__
    crystal, beam, detector, goniometer, scan, reflections)
  File "/dls/science/users/wra62962/dials/modules/dials/algorithms/profile_model/gaussian_rs/calculator.py", line 321, in __init__
    raise RuntimeError("Something went wrong. Zero pixels selected for estimation of profile parameters.")
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: Something went wrong. Zero pixels selected for estimation of profile parameters.
```

**Comment by Anthchirp** [comment]
GW says JMP.

**Comment by graeme-winter** [comment]
Can sanity check by running dials.predict && extract showboxes, looking at
parameters

**Comment by jmp1985** [comment]
Should now be fixed - masking pixels had a bug for multi-axis goniometers
