### ISSUE TITLE
datablock.json broken for still images

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#449]
I have still images from EIGER, which I could process well before. However, today I noticed something is broken now. After `dials.import`, `dials.image_viewer` and `dials.generate_mask` fail to read the generated `datablock.json`.

```sh
$ dials.import ../data/test_master.h5 
DIALS 1.dev.1741-gc9bafde
The following parameters have been modified:
input {
  datablock = <image files>
}

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatHDFEigerNearlyNexus.FormatEigerNearlyNexus'>
  num images: 1000
  num sweeps: 0
  num stills: 1000
--------------------------------------------------------------------------------
Writing datablocks to datablock.json

$ dials.image_viewer datablock.json 
Sorry: Unable to handle the following arguments:
  datablock.json

Please check that your image data is accessible

$ dials.python
>>> from dxtbx.datablock import DataBlockFactory
>>> DataBlockFactory.from_json_file("datablock.json")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/dials/modules/cctbx_project/dxtbx/datablock.py", line 921, in from_json_file
    return DataBlockFactory.from_json(infile.read(), check_format)
  File "/app/dials/modules/cctbx_project/dxtbx/datablock.py", line 911, in from_json
    check_format)
  File "/app/dials/modules/cctbx_project/dxtbx/datablock.py", line 899, in from_dict
    importer = DataBlockDictImporter(obj, check_format)
  File "/app/dials/modules/cctbx_project/dxtbx/datablock.py", line 650, in __init__
    self.datablocks = self._load_datablocks(obj, check_format)
  File "/app/dials/modules/cctbx_project/dxtbx/datablock.py", line 664, in _load_datablocks
    return [self._load_datablocks(dd, check_format) for dd in obj]
  File "/app/dials/modules/cctbx_project/dxtbx/datablock.py", line 763, in _load_datablocks
    filenames, None, check_format, indices, format_kwargs=format_kwargs)
  File "/app/dials/modules/cctbx_project/dxtbx/imageset.py", line 869, in make_imageset
    check_format  = check_format)
  File "/app/dials/modules/cctbx_project/dxtbx/format/FormatMultiImage.py", line 160, in get_imageset
    reader = Class.get_reader()(filenames, **format_kwargs)
  File "/app/dials/modules/cctbx_project/dxtbx/format/FormatMultiImage.py", line 12, in __init__
    assert len(filenames) == 1
AssertionError
```

**Comment by biochem-fan** [comment]
Same happened for my SACLA MPCCD class. So this is not specific to EIGER.

You can reproduce this by
```
dials.import dials_regression/image_examples/SACLA_MPCCD_Cheetah/run266702-0-subset.h5 
```
and trying above commands.

At least DIALS 1.6.2-g7df89bd-release was fine.

**Comment by jmp1985** [comment]
Hi Takanori,

I tried this command using my development version of DIALS and I got the following output. There have been some large changes in dxtbx so it's possible that at some stage this was broken but I think updating it should work.

James


dials.import ~/Software/dials/modules/dials_regression/image_examples/SACLA_MPCCD_Cheetah/run266702-0-subset.h5
DIALS 1.dev.1747-g31e146f
The following parameters have been modified:

input {
  datablock = <image files>
}

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatHDF5SaclaMPCCD.FormatHDF5SaclaMPCCD'>
  num images: 4
  num sweeps: 0
  num stills: 4
--------------------------------------------------------------------------------
Writing datablocks to datablock.json



________________________________

**Comment by biochem-fan** [comment]
Hi James,

`dials.import` does work, but the output is wrong.
```
dials.image_viewer datablock.json
```
and
```
from dxtbx.datablock import DataBlockFactory
DataBlockFactory.from_json_file("datablock.json")
```
do not work.

**Comment by jmp1985** [comment]
Hi Takanori,

I've committed a fix - let me know if this works for you.

James

**Comment by biochem-fan** [comment]
Thank you very much. Now it is working fine.
