### ISSUE TITLE
dials generally broken for multi-image sets (i.e. Eiger)

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#454]
Commands:

```
dials.import `libtbx.find_under_build xia2_regression`/test_data/esrf-eiger-4m/thaumatin28_w1_3_1_master.h5
dials.find_spots datablock.json nproc=`libtbx.show_number_of_processors`
dials.index datablock.json strong.pickle
```

give

```
DIALS 1.dev.1752-g1b6f4fd
The following parameters have been modified:

input {
  datablock = datablock.json
  reflections = strong.pickle
}

Found max_cell: 208.5 Angstrom
Setting d_min: 4.07
FFT gridding: (256,256,256)
Number of centroids used: 16764
Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/index.py", line 186, in <module>
    run(sys.argv[1:])
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/index.py", line 158, in run
    idxr.index()
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/algorithms/indexing/indexer.py", line 768, in index
    experiments.extend(self.find_lattices())
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/algorithms/indexing/fft3d.py", line 55, in find_lattices
    self.candidate_crystal_models)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/algorithms/indexing/indexer.py", line 1393, in choose_best_orientation_matrix
    params = copy.deepcopy(self.all_params)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 351, in _reconstruct
    item = deepcopy(item, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/dls/science/users/gw56/svn/cctbx/base/lib/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
RuntimeError: dxtbx Internal Error: /dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/imageset.h(1120): DXTBX_ASSERT(indices.size() == scan->get_num_images()) failure.
```

Suspect this is related to dxtbx refactor @jmp1985

**Comment by graeme-winter** [comment]
Following commits from @jmp1985 is fixed
