### ISSUE TITLE
Windows: dials.index tries to do multiprocessing in run one refinement but this fails

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#464]
Data look fine, failure occurs anyhow:

```
Using max_cell: 119.8 Angstrom
Setting d_min: 2.34
FFT gridding: (256,256,256)
Number of centroids used: 102892
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\CCP4-7\python2.7\lib\multiprocessing\forking.py", line 381, in main
    self = load(from_parent)
  File "D:\CCP4-7\python2.7\lib\pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "D:\CCP4-7\python2.7\lib\pickle.py", line 858, in load
    dispatch[key](self)
  File "D:\CCP4-7\python2.7\lib\pickle.py", line 880, in load_eof
    raise EOFError
EOFError
Traceback (most recent call last):
  File "D:\CCP4-7\python2.7\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\CCP4-7\python2.7\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\CCP4-7\7.0\lib\py2\site-packages\dials\command_line\index.py", line 179, in <module>
    run(sys.argv[1:])
  File "D:\CCP4-7\7.0\lib\py2\site-packages\dials\command_line\index.py", line 156, in run
    idxr.index()
  File "D:\CCP4-7\7.0\lib\py2\site-packages\dials\algorithms\indexing\indexer.py", line 749, in index
    experiments.extend(self.find_lattices())
  File "D:\CCP4-7\7.0\lib\py2\site-packages\dials\algorithms\indexing\fft3d.py", line 55, in find_lattices
    self.candidate_crystal_models)
  File "D:\CCP4-7\7.0\lib\py2\site-packages\dials\algorithms\indexing\indexer.py", line 1459, in choose_best_orientation_matrix
    preserve_exception_message=True,
  File "D:\CCP4-7\7.0\lib\py2\site-packages\cctbx_project\libtbx\easy_mp.py", line 622, in parallel_map
    for ( calc, res ) in pfi:
  File "D:\CCP4-7\7.0\lib\py2\site-packages\cctbx_project\libtbx\scheduling\parallel_for.py", line 247, in next
    self.state.fillup( pfi = self )
  File "D:\CCP4-7\7.0\lib\py2\site-packages\cctbx_project\libtbx\scheduling\parallel_for.py", line 172, in fillup
    cls.iterate( pfi = pfi )
  File "D:\CCP4-7\7.0\lib\py2\site-packages\cctbx_project\libtbx\scheduling\parallel_for.py", line 161, in iterate
    manager = pfi.manager,
  File "D:\CCP4-7\7.0\lib\py2\site-packages\cctbx_project\libtbx\scheduling\parallel_for.py", line 15, in submit_one_job
    manager.submit( target = target, args = args, kwargs = kwargs ),
  File "D:\CCP4-7\7.0\lib\py2\site-packages\cctbx_project\libtbx\scheduling\job_scheduler.py", line 143, in submit
    self.poll()
  File "D:\CCP4-7\7.0\lib\py2\site-packages\cctbx_project\libtbx\scheduling\job_scheduler.py", line 221, in poll
    process.start()
  File "D:\CCP4-7\python2.7\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "D:\CCP4-7\python2.7\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "D:\CCP4-7\python2.7\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "D:\CCP4-7\python2.7\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "D:\CCP4-7\python2.7\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "D:\CCP4-7\python2.7\lib\pickle.py", line 419, in save_reduce
    save(state)
  File "D:\CCP4-7\python2.7\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\CCP4-7\python2.7\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "D:\CCP4-7\python2.7\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "D:\CCP4-7\python2.7\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\CCP4-7\python2.7\lib\pickle.py", line 562, in save_tuple
    save(element)
  File "D:\CCP4-7\python2.7\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\CCP4-7\python2.7\lib\pickle.py", line 748, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <function run_one_refinement at 0x00000000051059E8>: it's not found as dials.algorithms.indexing.indexer.run_one_refinement
# command line:
# dials.index.bat  '4_optimized_datablock.json' '2_SWEEP1_strong.pickle' 'indexing.method=fft3d' 'indexing.nproc=8' 'reflections_per_degree=100' 'close_to_spindle_cutoff=0.020000' 'outlier.algorithm=Auto' 'known_symmetry.space_group=75' 'known_symmetry.unit_cell="92.12,92.12,36.13,90.0,90.0,90.0"' 'output.experiments=5_experiments.json' 'output.reflections=5_indexed.pickle'
```

Reading the command-line this could be a xia2 bug - or a CCP4 bug - since nproc needs to be 1 on windows?

**Comment by dagewa** [comment]
This is almost certainly fixed
