### ISSUE TITLE
dials.index crash

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#47]
dials.import /dls/i19-1/data/2016/mt11238-5/2015NCS0616_dls3/dls3_05_0*cbf
dials.find_spots datablock.json
dials.index datablock.json strong.pickle

```
DIALS 1.0-57-ga692caf                                               
The following parameters have been modified:                        

input {
  datablock = ../datablock.json
  reflections = strong.pickle  
}                              

Found max_cell: 549.3 Angstrom
Setting d_min: 10.73          
FFT gridding: (256,256,256)   
Number of centroids used: 35  
Traceback (most recent call last):
  File "/dls_sw/apps/dials/latest/dials-dev20160115/build/../modules/dials/command_line/index.py", line 176, in <module>                                                                                                            
    run(sys.argv[1:])                                                                                             
  File "/dls_sw/apps/dials/latest/dials-dev20160115/build/../modules/dials/command_line/index.py", line 153, in run                                                                                                                 
    params=params)                                                                                                
  File "/dls_sw/apps/dials/latest/dials-dev20160115/modules/dials/algorithms/indexing/indexer.py", line 422, in from_parameters                                                                                                     
    idxr = indexer_fft3d(reflections, imagesets, params=params)                                                   
  File "/dls_sw/apps/dials/latest/dials-dev20160115/modules/dials/algorithms/indexing/fft3d.py", line 33, in __init__                                                                                                               
    super(indexer_fft3d, self).__init__(reflections, imagesets, params)                                           
  File "/dls_sw/apps/dials/latest/dials-dev20160115/modules/dials/algorithms/indexing/indexer.py", line 406, in __init__                                                                                                            
    self.index()                                                                                                  
  File "/dls_sw/apps/dials/latest/dials-dev20160115/modules/dials/algorithms/indexing/indexer.py", line 622, in index                                                                                                               
    experiments.extend(self.find_lattices())                                                                      
  File "/dls_sw/apps/dials/latest/dials-dev20160115/modules/dials/algorithms/indexing/fft3d.py", line 87, in find_lattices                                                                                                          
    self.candidate_crystal_models)                                                                                
  File "/dls_sw/apps/dials/latest/dials-dev20160115/modules/dials/algorithms/indexing/indexer.py", line 1192, in choose_best_orientation_matrix                                                                                     
    self.correct_non_primitive_basis(experiments, refl, threshold)                                                
  File "/dls_sw/apps/dials/latest/dials-dev20160115/modules/dials/algorithms/indexing/indexer.py", line 1263, in correct_non_primitive_basis                                                                                        
    reflections['miller_index'].select(sel), threshold=threshold)                                                 
  File "/dls_sw/apps/dials/latest/dials-dev20160115/modules/dials/algorithms/indexing/indexer.py", line 1721, in detect_non_primitive_basis                                                                                         
    if float(cum[counter])/miller_indices.size() > threshold and counter==0:                                      
ZeroDivisionError: float division by zero                                                                         
```

**Comment by graeme-winter** [comment]
Probably the error is in the max_cell identification => I will wager this
is a split xtal; rest of the problems probably derive from that - what if
max_cell set to sensible value, is error reproduced?

**Comment by graeme-winter** [comment]
Could we have a max_cell estimation which looks at the total # refl /
volume of RS to get an additional input to balance against the closest
separation (i.e. global as well as local estimate)

**Comment by Anthchirp** [comment]
max_cell=20 gives a different error. Don't know proper unit cell estimates, user has already left the building.

**Comment by graeme-winter** [comment]
fair enough - like I say there are better ways to solve this problem anyway
