### ISSUE TITLE
dials.reindex failing

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#490]
```
$ dials.reindex /dls/i19-1/data/2018/cm19671-1/processed/SAB090118/TCE_254K_screen2/1/DEFAULT/NATIVE/SWEEP1/integrate/12_integrated_experiments.json /dls/i19-1/data/2018/cm19671-1/processed/SAB090118/TCE_254K_screen2/1/DEFAULT/NATIVE/SWEEP1/integrate/12_integrated.pickle change_of_basis_op="-h,-k,1/2*h+1/2*l"
```

```
The following parameters have been modified:

change_of_basis_op = "-h,-k,1/2*h+1/2*l"
input {
  experiments = /dls/i19-1/data/2018/cm19671-1/processed/SAB090118/TCE_254K_screen2/1/DEFAULT/NATIVE/SWEEP1/integrate/12_integrated_experiments.json
  reflections = /dls/i19-1/data/2018/cm19671-1/processed/SAB090118/TCE_254K_screen2/1/DEFAULT/NATIVE/SWEEP1/integrate/12_integrated.pickle
}

Traceback (most recent call last):
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/reindex.py", line 244, in <module>
    run(sys.argv[1:])
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/reindex.py", line 198, in run
    cryst_reindexed = cryst_orig.change_basis(change_of_basis_op)
RuntimeError: cctbx Internal Error: /scratch/wra62962/files/dials/modules/cctbx_project/cctbx/sgtbx/rot_mx.cpp(19): Unsuitable value for rational rotation matrix.
```

Any ideas what's going on there?

**Comment by rjgildea** [comment]
As the error suggests it is not a valid rotation matrix?

**Comment by Anthchirp** [comment]
but ```-h,-k,1/2*h+1/2*l``` is a valid transformation? Bug in matrix creation or impossible to express transformation as rotation matrix?

**Comment by rjgildea** [comment]
Where did the matrix come from?

**Comment by Anthchirp** [comment]
actual problem is SCI-6476, this is red herring.
