### ISSUE TITLE
image viewer crash

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#493]
```
$ dials.image_viewer /dls/tmp/wra62962/directories/9rbmExxj/DEFAULT/NATIVE/SWEEP1/index/4_experiments.json
The following parameters have been modified:

input {
  experiments = /dls/tmp/wra62962/directories/9rbmExxj/DEFAULT/NATIVE/SWEEP1/index/4_experiments.json
}

Gtk-Message: Failed to load module "canberra-gtk-module"
Memory usage: 103.3 MB
Traceback (most recent call last):
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/command_line/image_viewer.py", line 202, in <module>
    runner()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/command_line/image_viewer.py", line 139, in __call__
    self.view()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/command_line/image_viewer.py", line 147, in view
    reflections=self.reflections)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/util/image_viewer/spotfinder_wrap.py", line 42, in display
    self.frame.load_image(chooser_wrapper(imagesets[0], 0))
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/util/image_viewer/spotfinder_frame.py", line 473, in load_image
    show_untrusted=show_untrusted)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/cctbx_project/rstbx/slip_viewer/frame.py", line 405, in load_image
    self.update_settings()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/util/image_viewer/spotfinder_frame.py", line 843, in update_settings
    spotfinder_data = self.get_spotfinder_data()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/util/image_viewer/spotfinder_frame.py", line 1251, in get_spotfinder_data
    xy = detector[0].get_ray_intersection(s1)
RuntimeError: dxtbx Internal Error: /dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/cctbx_project/dxtbx/model/virtual_panel.h(247): DXTBX_ASSERT(v[2] > 0) failure.
```

It works for the associated datablock.json:
```
$ dials.image_viewer /dls/tmp/wra62962/directories/9rbmExxj/DEFAULT/NATIVE/SWEEP1/index/1_SWEEP1_datablock.json
```

(files kept for 30 days at that location)

**Comment by Anthchirp** [comment]
```$ dials.show /dls/tmp/wra62962/directories/9rbmExxj/DEFAULT/NATIVE/SWEEP1/index/1_SWEEP1_datablock.json 
The following parameters have been modified:

input {
  datablock = /dls/tmp/wra62962/directories/9rbmExxj/DEFAULT/NATIVE/SWEEP1/index/1_SWEEP1_datablock.json
}

Format: <class 'dxtbx.format.Format.Format'>
/dls/i19-1/data/2018/mt15833-5/MFM-170_BA_drop_screen3_001/MFM-170_BA_drop_05_#####.cbf
Detector:
Panel:
  name: Panel
  type: SENSOR_PAD
  identifier: PILATUS 2M, S/N 24-0107 Diamond
  pixel_size:{0.172,0.172}
  image_size: {1475,1679}
  trusted_range: {-1,791927}
  thickness: 0.32
  material: Si
  mu: 1.41535
  gain: 1
  fast_axis: {0,1,0}
  slow_axis: {1,0,0}
  origin: {-148.95,-127.28,-160}
  pixel to millimeter strategy: ParallaxCorrectedPxMmStrategy
    mu: 1.41535
    t0: 0.32


Max resolution (at corners): 0.803762
Max resolution (inscribed):  1.049962

Beam:
    wavelength: 0.6889
    sample to source direction : {0,0,1}
    divergence: 0
    sigma divergence: 0
    polarization normal: {0,1,0}
    polarization fraction: 0.999
Beam centre (mm): (127.28,148.95)
Beam centre (px): (740.00,865.99)

Scan:
    image range:   {1,450}
    oscillation:   {0,0.2}
    exposure time: 0.1964

Goniometer:
    Rotation axis:   {0.5774,-0.8165,0}
    Fixed rotation:  {1,0,0,0,1,0,0,0,1}
    Setting rotation:{1,0,0,0,1,0,0,0,1}
    Axis #0 (GON_PHI):  {0.5774,-0.8165,0}
    Axis #1 (GON_OMEGA):  {1,0,0}
    Angles: 0,0
    scan axis: #0 (GON_PHI)
```

**Comment by Anthchirp** [comment]
and of the broken one:
```
$ dials.show /dls/tmp/wra62962/directories/9rbmExxj/DEFAULT/NATIVE/SWEEP1/index/4_experiments.json
The following parameters have been modified:

input {
  experiments = /dls/tmp/wra62962/directories/9rbmExxj/DEFAULT/NATIVE/SWEEP1/index/4_experiments.json
}

Experiment 0:
Detector:
Panel:
  name: Panel
  type: SENSOR_PAD
  identifier: PILATUS 2M, S/N 24-0107 Diamond
  pixel_size:{0.172,0.172}
  image_size: {1475,1679}
  trusted_range: {-1,791927}
  thickness: 0.32
  material: Si
  mu: 1.41535
  gain: 1
  fast_axis: {0.0014943,0.998071,0.062062}
  slow_axis: {0.99961,-0.00322142,0.0277382}
  origin: {-149.306,-126.029,-176.161}
  pixel to millimeter strategy: ParallaxCorrectedPxMmStrategy
    mu: 1.41535
    t0: 0.32


Max resolution (at corners): 0.800266
Max resolution (inscribed):  1.101417

Beam:
    wavelength: 0.6889
    sample to source direction : {0.00159224,-0.00225158,0.999996}
    divergence: 0
    sigma divergence: 0
    polarization normal: {0,1,0}
    polarization fraction: 0.999
Beam centre (mm): (127.12,148.91)
Beam centre (px): (739.07,865.76)

Scan:
    image range:   {1,450}
    oscillation:   {0,0.2}
    exposure time: 0.1964

Goniometer:
    Rotation axis:   {0.5774,-0.8165,0}
    Fixed rotation:  {1,0,0,0,1,0,0,0,1}
    Setting rotation:{1,0,0,0,1,0,0,0,1}
    Axis #0 (GON_PHI):  {0.5774,-0.8165,0}
    Axis #1 (GON_OMEGA):  {1,0,0}
    Angles: 0,0
    scan axis: #0 (GON_PHI)

Crystal:
    Unit cell: (5.839(17), 6.73(2), 7.257(18), 78.09(11), 80.60(9), 74.62(11))
    Space group: P 1
    U matrix:  {{-0.4079, -0.8139,  0.4137},
                { 0.2686, -0.5400, -0.7976},
                { 0.8726, -0.2142,  0.4389}}
    B matrix:  {{ 0.1713,  0.0000,  0.0000},
                {-0.0471,  0.1542,  0.0000},
                {-0.0206, -0.0268,  0.1418}}
    A = UB:    {{-0.0400, -0.1366,  0.0586},
                { 0.0879, -0.0619, -0.1131},
                { 0.1505, -0.0448,  0.0622}}

```

**Comment by Anthchirp** [comment]
I have my doubts regarding the quality of the input data, but it does not crash any more 👍 
![image](https://user-images.githubusercontent.com/2102431/35093845-69624c44-fc3b-11e7-90d8-6cff507c1e9c.png)
