### ISSUE TITLE
dials.find_spots max_spot_size=None crashes

### ISSUE THREAD

**Issue by dagewa** [dials/dials#516]
tested with i04 BAG training data.

```
dials.find_spots datablock.json nproc=8 max_spot_size=None
...
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/find_spots.py", line 199, in <module>
    halraiser(e)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/find_spots.py", line 197, in <module>
    script.run()
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/find_spots.py", line 146, in run
    datablocks[0], params)
  File "/home/fcx32934/sw/cctbx/modules/dials/array_family/flex.py", line 185, in from_observations
    return find_spots(datablock)
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 773, in __call__
    table, hot_mask = self._find_spots_in_imageset(imageset)
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 866, in _find_spots_in_imageset
    r, h = extract_spots(imageset[j0:j1])
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 477, in __call__
    return self._find_spots(imageset)
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 601, in _find_spots
    return converter(imageset, pixel_labeller)
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 414, in __call__
    imageset, pixel_labeller)
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/spot_finding/finder.py", line 319, in __call__
    self.write_hot_pixel_mask)
Boost.Python.ArgumentError: Please report this error to dials-support@lists.sourceforge.net: Python argument types in
    PixelListShoeboxCreator.__init__(PixelListShoeboxCreator, PixelListLabeller, int, int, bool, int, NoneType, bool)
did not match C++ signature:
    __init__(_object*, dials::model::PixelListLabeller pixel, unsigned long panel=0, unsigned long zstart=0, bool twod=False, unsigned long min_pixels=1, unsigned long max_pixels=20, bool find_hot_pixels=False)

```

**Comment by dagewa** [comment]
I see the PixelListShoeboxCreator really does need max_pixels set, so maybe he user-provided None should just be caught at the start and a suitably apologetic message given?

**Comment by rjgildea** [comment]
I've made a pull request (https://github.com/cctbx/cctbx_project/pull/147) that adds and allow_none attribute for int/float phil types, which would allow the following change:

```
$ git diff
diff --git a/algorithms/spot_finding/factory.py b/algorithms/spot_finding/factory.py
index 9420d6e..930fa38 100644
--- a/algorithms/spot_finding/factory.py
+++ b/algorithms/spot_finding/factory.py
@@ -73,7 +73,7 @@ def generate_phil_scope():
       max_spot_size = 100
         .help = "The maximum number of contiguous pixels for a spot"
                 "to be accepted by the filtering algorithm."
-        .type = int(value_min=1)
+        .type = int(value_min=1, allow_none=False)
 
       max_separation = 2
         .help = "The maximum peak-to-centroid separation (in pixels)"
```

```
$ dials.find_spots $(libtbx.find_in_repositories dials_regression)/centroid_test_data/centroid_0001.cbf max_spot_size=None
Traceback (most recent call last):
...
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: spotfinder.filter.max_spot_size cannot be None
```

**Comment by dagewa** [comment]
Yes, that sounds ideal, thanks

**Comment by ndevenish** [comment]
So, I put @rjgildea's patch in as https://github.com/dials/dials/commit/8c29320a19bcb8eaccb965f9aa040518c69bb5a4.

a) For this ticket, do we need to go through all the parameters to check if this should be applied to anything else, or is it just sufficient to have changed this

b)
```
$ dials.find_spots datablock.json max_spot_size=None
Traceback (most recent call last):
  File "/Users/nickd/dials/dist/build/../modules/dials/command_line/find_spots.py", line 199, in <module>
    halraiser(e)
  File "/Users/nickd/dials/dist/build/../modules/dials/command_line/find_spots.py", line 197, in <module>
    script.run()
  File "/Users/nickd/dials/dist/build/../modules/dials/command_line/find_spots.py", line 119, in run
    params, options = self.parser.parse_args(show_diff_phil=False)
  File "/Users/nickd/dials/dist/modules/dials/util/options.py", line 828, in parse_args
    quick_parse=quick_parse)
  File "/Users/nickd/dials/dist/modules/dials/util/options.py", line 505, in parse_args
    params = self._phil.extract()
  File "/Users/nickd/dials/dist/modules/cctbx_project/libtbx/phil/__init__.py", line 1778, in extract
    value = object.extract(parent=result)
  File "/Users/nickd/dials/dist/modules/cctbx_project/libtbx/phil/__init__.py", line 1778, in extract
    value = object.extract(parent=result)
  File "/Users/nickd/dials/dist/modules/cctbx_project/libtbx/phil/__init__.py", line 1778, in extract
    value = object.extract(parent=result)
  File "/Users/nickd/dials/dist/modules/cctbx_project/libtbx/phil/__init__.py", line 1143, in extract
    return self._type_from_words()(self.words, master=self)
  File "/Users/nickd/dials/dist/modules/cctbx_project/libtbx/phil/__init__.py", line 337, in from_words
    "%s cannot be None" % path)
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: spotfinder.filter.max_spot_size cannot be None
```

Since this is a user-error, should this be a `Sorry`, so we can know not show the traceback?

**Comment by dagewa** [comment]
Sorry for the late reply, I didn't see this as an email. Yes, I think this should be `Sorry`, but I think that would be sufficient to close this particular ticket. Perhaps a review of all parameters of each dials program would be a useful thing _someday_, but I don't see that happening imminently.

**Comment by dagewa** [comment]
I'm closing this now, because at least the error now gets trapped in the `OptionParser`. Perhaps all errors raised by that class should be `Sorry`s, perhaps not. Anyway that's out of scope for this issue.
