### ISSUE TITLE
dials.import_xds SPOT.XDS

### ISSUE THREAD

**Issue by dagewa** [dials/dials#517]
Does not work:

```
dials.import_xds SPOT.XDS 
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/import_xds.py", line 473, in <module>
    halraiser(e)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/import_xds.py", line 471, in <module>
    script.run()
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/import_xds.py", line 449, in run
    importer(params, options)
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/import_xds.py", line 197, in __call__
    raise RuntimeError('No XDS file found')
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: No XDS file found
```

Help suggests it should:

`Usage: dials.import_xds [options] (SPOT.XDS|INTEGRATE.HKL)`

Actually you need add **method=reflections**:

```
dials.import_xds SPOT.XDS method=reflections
The following parameters have been modified:

input {
  method = experiment *reflections
}

Read 772 spots from SPOT.XDS file..........................................0.00s
Created reflection list....................................................0.00s
Removed invalid reflections, 772 remaining.................................0.00s
Saved reflection table to spot_xds.pickle..................................0.00s
```

Is it just an improve-the-documentation thing, or is it worth making this smarter so the original works?

**Comment by rjgildea** [comment]
See also: https://github.com/dials/dials/issues/480
