### ISSUE TITLE
dials.import_xds writes incorrect template to experiments.json

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#529]
```
$ dials.import_xds  '/dls/mx-scratch/rjgildea/h5/3d_dials/DEFAULT/NATIVE/SWEEP1/refine/xds' 'xds_file=XPARM.XDS' 
$ grep template experiments.json 
      "template": "/dls/mx-scratch/gw56/Eiger/Soleil/transthyretin/h5/200Hz_0.1dpf_1_######.h5", 
```

**Comment by rjgildea** [comment]
I tried this change:
```
$ git diff
diff --git a/dxtbx/serialize/xds.py b/dxtbx/serialize/xds.py
index a414fb8..c08fb51 100644
--- a/dxtbx/serialize/xds.py
+++ b/dxtbx/serialize/xds.py
@@ -38,6 +38,9 @@ def to_imageset(input_filename, extra_filename=None):
 
   # Get the template
   template = handle.name_template_of_data_frames[0].replace('?', '#')
+  if template.endswith('h5'):
+    template = template.replace('#', 'master', 1)
+    template = template.replace('#', '')
   image_range = handle.data_range
   detector_name = handle.detector
```
But it then fails with:
```
$ dials.import_xds  '/dls/mx-scratch/rjgildea/h5/3d_dials/DEFAULT/NATIVE/SWEEP1/refine/xds' 'xds_file=XPARM.XDS' 
The following parameters have been modified:

input {
  xds_file = "XPARM.XDS"
}

Traceback (most recent call last):
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/dials/command_line/import_xds.py", line 473, in <module>
    halraiser(e)
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/dials/command_line/import_xds.py", line 471, in <module>
    script.run()
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/dials/command_line/import_xds.py", line 449, in run
    importer(params, options)
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/dials/command_line/import_xds.py", line 201, in __call__
    experiments = ExperimentListFactory.from_xds(xds_inp, xds_file)
  File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/model/experiment_list.py", line 706, in from_xds
    sweep = xds.to_imageset(xds_inp, xds_other)
  File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/serialize/xds.py", line 91, in to_imageset
    scan = scan)[0]
  File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/imageset.py", line 333, in from_template
    raise ValueError("Invalid template")
ValueError: Please report this error to dials-support@lists.sourceforge.net: Invalid template
```

**Comment by rjgildea** [comment]
See also: https://strucbio.biologie.uni-konstanz.de/xdswiki/index.php/Eiger#Script_for_generating_XDS.INP_from_master.h5

```
def create_XDS_INP(parameters, file_name):
    lines = []
    description = parameters["/entry/instrument/detector/description"].split()
    family = description[1].lower()
    sensor = float(parameters["/entry/instrument/detector/sensor_thickness"]) * 1000.0
    FAMILY = family.upper()
    det_name = description[2]
    file_template = re.sub("master\.h5", "??????.h5", file_name)
...
```
