### ISSUE TITLE
ZeroDivisionError with apparent one-pixel spot with intensity=1

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#549]
Just looked at this with @jmp1985. Data and script to process at ~~`/dls/tmp/mep23677/tmp.47hhIgqVJD/rad_dam_x11_1/dials.sh`~~ `/dls/science/users/mep23677/samples/rad_dam_x11_1/dials.sh`.

When spotfinding is run with `min_spot_size=1`, and integration is run:
```
Traceback (most recent call last):
  File "/dls/science/users/mep23677/dist/build/../modules/dials/command_line/integrate.py", line 615, in <module>
    halraiser(e)
  File "/dls/science/users/mep23677/dist/build/../modules/dials/command_line/integrate.py", line 613, in <module>
    script.run()
  File "/dls/science/users/mep23677/dist/build/../modules/dials/command_line/integrate.py", line 327, in run
    experiments = ProfileModelFactory.create(params, experiments, reference)
  File "/dls/science/users/mep23677/dist/modules/dials/algorithms/profile_model/factory.py", line 59, in create
    expr.scan)
  File "/dls/science/users/mep23677/dist/modules/dials/algorithms/profile_model/gaussian_rs/model.py", line 237, in create
    profile)
  File "/dls/science/users/mep23677/dist/modules/dials/algorithms/profile_model/gaussian_rs/model.py", line 392, in create_from_reflections
    algorithm=params.gaussian_rs.sigma_m_algorithm)
  File "/dls/science/users/mep23677/dist/modules/dials/algorithms/profile_model/gaussian_rs/calculator.py", line 509, in __init__
    beam_divergence = ComputeEsdBeamDivergence(detector, reflections)
  File "/dls/science/users/mep23677/dist/modules/dials/algorithms/profile_model/gaussian_rs/calculator.py", line 40, in __init__
    variance = self._beam_direction_variance_list(detector, reflections)
  File "/dls/science/users/mep23677/dist/modules/dials/algorithms/profile_model/gaussian_rs/calculator.py", line 82, in _beam_direction_variance_list
    variance.append(flex.sum(values * (angles**2)) / (flex.sum(values) - 1))
ZeroDivisionError: Please report this error to dials-support@lists.sourceforge.net: float division by zero
```

Appears to be a one-pixel spot with a count of one....

**Comment by graeme-winter** [comment]
To be clear: this has one one pixel spot with count one or more than one one count one pixel spot? Or more than one spot but one with one count on one pixel?

🙂

Did spot finding actually find a one pixel spot with one count on it’s one pixel?

**Comment by ndevenish** [comment]
It's apparently *143* one count spots with one pixel. Indexed.

```python
# coding: utf-8
import cPickle as pickle
from dials.array_family import flex

# Optional, repr for reftable
try:
  import tbxtools.repr
except ImportError:
  pass


with open("indexed.pickle") as f:
  ref = pickle.load(f)

# Spots that got indexed
indexed = ref.get_flags(ref.flags.indexed)
# Spots with intensity == 1
intensity_one = flex.bool([x["intensity.sum.value"] == 1 for x in ref])
# Spots with shoebox size (1,1,1)
size_one_shoebox = flex.bool([sum(x["shoebox"].size()) == 3 for x in ref])

reduced = ref.select(indexed & intensity_one & size_one_shoebox)

print("Number of entries: {}".format(len(reduced)))
print(reduced)
```
```
Number of entries: 143
<reflection_table
    bbox                   = <dials_array_family_flex_ext.int6 object at 0x7f115eb687d0>
    entering               = bool([ True, False,  True, ..., False,  True,  True])
    flags                  = size_t([131108, 131108, 131108, ..., 131108, 131108, 131108])
    id                     = int([0, 0, 0, ..., 0, 0, 0])
    imageset_id            = int([0, 0, 0, ..., 0, 0, 0])
    intensity.sum.value    = double([1., 1., 1., ..., 1., 1., 1.])
    intensity.sum.variance = double([1., 1., 1., ..., 1., 1., 1.])
    miller_index           = miller_index([(-13,   9, -15), ( 10, -20,  -5), (  1, -11, -15), (  ...
    panel                  = size_t([0, 0, 0, ..., 0, 0, 0])
    rlp                    = vec3_double([(-0.22162791723208972, 0.38079265210929547, 0.085580971...
    s1                     = vec3_double([(-0.22172194423042574, 0.3840727060671351, -1.382407845...
    shoebox                = <dials_array_family_flex_ext.shoebox object at 0x7f115eb68650>
    xyzcal.mm              = vec3_double([(129.347750042911, 50.81257221856427, -0.05205284482832...
    xyzcal.px              = vec3_double([(751.9734788728011, 295.33663331806025, -9.648166406245...
    xyzobs.mm.value        = vec3_double([(128.06299974975983, 49.29336909048389, -0.042324234360...
    xyzobs.mm.variance     = vec3_double([(0.002465333333333333, 0.002465333333333333, 6.34619624...
    xyzobs.px.value        = vec3_double([(744.5, 286.5, 1.5) (654.5, 1593.5, 3.5) (317.5, 924.5,...
    xyzobs.px.variance     = vec3_double([(0.08333333333333333, 0.08333333333333333, 0.0833333333...>
[143 rows x 18 columns]
```

**Comment by ndevenish** [comment]
Just tested and this is still a problem. Moved data to `/dls/science/users/mep23677/samples/rad_dam_x11_1`, as cleaning up temporary dirs.

**Comment by dagewa** [comment]
I have not checked, but am fairly sure this won't be a problem any more as it is caught in a conditional since 00522a4b04c91a28d5fb2fda4dacc5d2839d6af9

https://github.com/dials/dials/blob/4f6ccbafccc14d22b527b5410dea917a53cb71af/algorithms/profile_model/gaussian_rs/calculator.py#L84-L87
