### ISSUE TITLE
dials.export not happy when a dataset starts with image 0

### ISSUE THREAD

**Issue by dagewa** [dials/dials#569]
I have a dataset where image numbering starts from 0
```
dials.show integrated_experiments.json
...
Scan:
    image range:   {0,1060}
    oscillation:   {0,0.1025}
    exposure time: 0.096288
...
```
Everything processes fine, up to export but then fails:
```
dials.export integrated_experiments.json integrated.pickle

############################################################################
#                                                                          #
# The DIALS reference paper has now been published:                        #
#                                                                          #
# DIALS: implementation and evaluation of a new integration package (2018) #
# https://doi.org/10.1107/S2059798317017235        Acta Cryst. D74, 85-97. #
#                                                                          #
############################################################################


DIALS 1.dev.2610-g46cc83c
The following parameters have been modified:

input {
  experiments = integrated_experiments.json
  reflections = integrated.pickle
}

Read 14298 predicted reflections
Selected 13149 integrated reflections
Removing 0 reflections with I/Sig(I) < -5.0
Removing 0 profile reflections with I/Sig(I) < -5.0
Removing 192 incomplete reflections
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/export.py", line 713, in <module>
    exporter.export()
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/export.py", line 276, in export
    apply_scales=self.params.mtz.apply_scales)
  File "/home/fcx32934/sw/cctbx/modules/dials/util/export_mtz.py", line 740, in export_mtz
    force_static_model=force_static_model)
  File "/home/fcx32934/sw/cctbx/modules/dials/util/export_mtz.py", line 312, in _add_batch
    assert batch_number > 0
AssertionError

```

**Comment by jbeilstenedmands** [comment]
The recent email to dials-support (title Problem with Exporting MTZ file) also comes across this problem due to the image range starting at 0. However, after testing with the ccp4-dui version of dials (DIALS 1.11.2-g01fb9e997-release), v1.11.4 and the current version of master, this only fails on the dui version & 1.11.4; I think this is due to changes I recently made to batch handling in export (38dc2bb). Therefore I shall close this issue and recommend we include changes to export mtz in the next release (may require other export changes also).
