### ISSUE TITLE
dials.export crash

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#572]
```
$ module load dials # 1.10.1
$ dials.export_bitmaps /dls/i03/data/2018/cm19644-3/grid/lys/xtal_3/xtal_3_1_0001.cbf format=jpeg quality=95 binning=4 brightness=60

The following parameters have been modified:

binning = 4
brightness = 60
format = *jpeg png tiff
jpeg {
  quality = 95
}
input {
  datablock = <image files>
}

Exporting ./image0000.jpeg
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v1-10-1/build/../modules/dials/command_line/export_bitmaps.py", line 266, in <module>
    run(sys.argv[1:])
  File "/dls_sw/apps/dials/dials-v1-10-1/build/../modules/dials/command_line/export_bitmaps.py", line 102, in run
    imageset_as_bitmaps(imageset, params)
  File "/dls_sw/apps/dials/dials-v1-10-1/build/../modules/dials/command_line/export_bitmaps.py", line 137, in imageset_as_bitmaps
    image = imageset.get_raw_data(i_image-start)
RuntimeError: dxtbx Internal Error: /dls_sw/apps/dials/dials-v1-10-1/modules/cctbx_project/dxtbx/imageset.h(687): DXTBX_ASSERT(index < indices_.size()) failure.
```

A file ```image0000.jpeg``` is written to disk.

Bonus Q1: Why 0000 and not 0001 as is the normal case?

Bonus Q2: Can I set the default output filename?

**Comment by rjgildea** [comment]
There is a prefix= parameter you can use to modify the output filename.
