### ISSUE TITLE
Incompatibility between dials.cosym, dials.scale and data processed with cI lattice

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#574]
Cubic insulin data, 12 runs, processed with xia2/dials - is I213 (I23, cI) so indexing ambiguity. Chucked everything into cosym, worked fine, answers looked sensible, chucked results into dials.scale, failed:

```
dials.cosym \
../SAD/SWEEP1/integrate/12_integrated.pickle \
../SAD/SWEEP2/integrate/26_integrated.pickle \
../SAD/SWEEP3/integrate/40_integrated.pickle \
../SAD/SWEEP4/integrate/54_integrated.pickle \
../SAD/SWEEP5/integrate/68_integrated.pickle \
../SAD/SWEEP6/integrate/82_integrated.pickle \
../SAD/SWEEP7/integrate/96_integrated.pickle \
../SAD/SWEEP8/integrate/110_integrated.pickle \
../SAD/SWEEP9/integrate/124_integrated.pickle \
../SAD/SWEEP10/integrate/138_integrated.pickle \
../SAD/SWEEP11/integrate/152_integrated.pickle \
../SAD/SWEEP12/integrate/166_integrated.pickle \
../SAD/SWEEP1/integrate/12_integrated_experiments.json \
../SAD/SWEEP2/integrate/26_integrated_experiments.json \
../SAD/SWEEP3/integrate/40_integrated_experiments.json \
../SAD/SWEEP4/integrate/54_integrated_experiments.json \
../SAD/SWEEP5/integrate/68_integrated_experiments.json \
../SAD/SWEEP6/integrate/82_integrated_experiments.json \
../SAD/SWEEP7/integrate/96_integrated_experiments.json \
../SAD/SWEEP8/integrate/110_integrated_experiments.json \
../SAD/SWEEP9/integrate/124_integrated_experiments.json \
../SAD/SWEEP10/integrate/138_integrated_experiments.json \
../SAD/SWEEP11/integrate/152_integrated_experiments.json \
../SAD/SWEEP12/integrate/166_integrated_experiments.json
```

```
dials.scale space_group=I213 reindexed_experiments.json reindexed_reflections.pickle
```

=> 

```
Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/scale.py", line 428, in <module>
    halraiser(e)
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/scale.py", line 425, in <module>
    script.run()
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/scale.py", line 112, in run
    self.scale()
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/scale.py", line 216, in scale
    self.scaler = create_scaler(self.params, self.experiments, self.reflections)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/algorithms/scaling/scaler_factory.py", line 26, in create_scaler
    scaler = MultiScalerFactory.create(params, experiments, reflections)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/algorithms/scaling/scaler_factory.py", line 173, in create
    params, experiment, reflection, scaled_id=data_id, for_multi=True))
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/algorithms/scaling/scaler_factory.py", line 75, in create
    params)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/algorithms/scaling/scaler_factory.py", line 82, in filter_outliers
    reflections = quasi_normalisation(reflections, experiment)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/algorithms/scaling/scaling_utilities.py", line 210, in quasi_normalisation
    crystal_symmetry=experiment.crystal.get_crystal_symmetry(),
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/dxtbx/model/__init__.py", line 55, in get_crystal_symmetry
    assert_is_compatible_unit_cell=assert_is_compatible_unit_cell)
  File "/dls/science/users/gw56/svn/cctbx/modules/cctbx_project/cctbx/crystal/__init__.py", line 101, in __init__
    "Space group is incompatible with unit cell parameters."
AssertionError: Please report this error to dials-support@lists.sourceforge.net: Space group is incompatible with unit cell parameters.
```

**Comment by graeme-winter** [comment]
Set space_group for scaling to try to avoid this...

**Comment by rjgildea** [comment]
Where are these files on disk?

**Comment by graeme-winter** [comment]
Common-sense in fix above, which I think is the comparison we _mean_ to make
