### ISSUE TITLE
Disused test test/command_line/tst_compare.py

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#581]
One of a few non-pytest tests from #506 remaining, because added in 33d838bfe6095c971118334da1347e1738890174 (2014), but hasn't been run as part of the test suite... ever, as far as I can tell.

Test crashes with:
```
$ libtbx.python test/command_line/tst_compare.py
Traceback (most recent call last):
  File "test/command_line/tst_compare.py", line 28, in <module>
    test(dials_regression, tmpdir)
  File "test/command_line/tst_compare.py", line 15, in test
    join(path, 'sweep.json'),
  File "/Users/nickd/dials/dist/modules/cctbx_project/libtbx/easy_run.py", line 30, in raise_if_errors
    raise Error(msg)
RuntimeError: child process stderr output:
  command: ['dev.dials.compare_mosflm_dials', '/Users/nickd/dials/dist/modules/dials_regression/integration_test_data/i04-weak-data/integrate.mtz', '/Users/nickd/dials/dist/modules/dials_regression/integration_test_data/i04-weak-data/integrated.pickle', '/Users/nickd/dials/dist/modules/dials_regression/integration_test_data/i04-weak-data/crystal.json', '/Users/nickd/dials/dist/modules/dials_regression/integration_test_data/i04-weak-data/sweep.json']
  Traceback (most recent call last):
    File "/Users/nickd/dials/dist/build/../modules/dials/command_line/compare_mosflm_dials.py", line 313, in <module>
      compare_chunks(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
    File "/Users/nickd/dials/dist/build/../modules/dials/command_line/compare_mosflm_dials.py", line 153, in compare_chunks
      rdx = derive_reindex_matrix(crystal_json, sweep_json, integrate_mtz)
    File "/Users/nickd/dials/dist/build/../modules/dials/command_line/compare_mosflm_dials.py", line 296, in derive_reindex_matrix
      dA = get_dials_matrix(crystal_json)
    File "/Users/nickd/dials/dist/build/../modules/dials/command_line/compare_mosflm_dials.py", line 264, in get_dials_matrix
      crystal = load.crystal(crystal_json)
  AttributeError: 'module' object has no attribute 'crystal'
```

Worth fixing? Or just remove?

**Comment by rjgildea** [comment]
This is the actual command dev.dials.compare_mosflm_dials that is failing, so presumably that should be removed as well as the test (if not fixing).

**Comment by ndevenish** [comment]
@luisodls says fine to remove. The compare_x_y programs seem to be an intended set, but aren't covered in the tests. I've asked separately from this issue what we should do with them.
