### ISSUE TITLE
dials.spot_counts_per_image ZeroDivisionError

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#583]
run in ```/dls/mx/data/mx17352/mx17352-166/tmp/zocalo/VMXi-AB0608/well_4/images/image_6354.nxs/5ebfc8b1-37c8-456c-93bc-3cfb1b171c58/per-image-analysis```

```
| 595   | 1      | 1             | 9               |
| 596   | 1      | 1             | 12              |
| 597   | 0      | 0             | 0               |
| 598   | 0      | 0             | 0               |
| 599   | 1      | 1             | 11              |
| 600   | 0      | 0             | 0               |
----------------------------------------------------
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v1-10-1/build/../modules/dials/command_line/spot_counts_per_image.py", line 117, in <module>
    run(sys.argv[1:])
  File "/dls_sw/apps/dials/dials-v1-10-1/build/../modules/dials/command_line/spot_counts_per_image.py", line 89, in run
    imageset, reflections, resolution_analysis=params.resolution_analysis)
  File "/dls_sw/apps/dials/dials-v1-10-1/modules/dials/algorithms/spot_finding/per_image_analysis.py", line 688, in stats_single_image
    reflections_all, imageset, ice_sel, plot_filename=distl_method_2_filename)
  File "/dls_sw/apps/dials/dials-v1-10-1/modules/dials/algorithms/spot_finding/per_image_analysis.py", line 457, in estimate_resolution_limit_distl_method2
    binner = binner_d_star_cubed(d_spacings)
  File "/dls_sw/apps/dials/dials-v1-10-1/modules/dials/algorithms/spot_finding/per_image_analysis.py", line 57, in __init__
    math.ceil((d_star_cubed_sorted[-1] - d_star_cubed_sorted[0])/bin_step))
ZeroDivisionError: float division by zero
```

**Comment by Anthchirp** [comment]
command line is ```dials.spot_counts_per_image datablock.json strong.pickle json=pia.json joint_json=True split_json=True```

**Comment by Anthchirp** [comment]
This is with DIALS 1.10.1.

With master branch it's even worse :(
```
$ dials.spot_counts_per_image datablock.json strong.pickle json=pia.json joint_json=True split_json=True

Sorry: Unable to handle the following arguments:
  "datablock.json" failed during DataBlock processing:
    Traceback (most recent call last):
      File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/util/options.py", line 306, in try_read_datablocks
        self.datablocks.append(converter.from_string(argument))
      File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/util/phil.py", line 47, in from_string
        check_format=self._check_format))
      File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/cctbx_project/dxtbx/datablock.py", line 969, in from_json_file
        directory=directory)
      File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/cctbx_project/dxtbx/datablock.py", line 957, in from_json
        directory=directory)
      File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/cctbx_project/dxtbx/datablock.py", line 944, in from_dict
        importer = DataBlockDictImporter(obj, check_format, directory)
      File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/cctbx_project/dxtbx/datablock.py", line 651, in __init__
        self.datablocks = self._load_datablocks(obj, check_format, directory)
      File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/cctbx_project/dxtbx/datablock.py", line 664, in _load_datablocks
        return [self._load_datablocks(dd, check_format, directory) for dd in obj]
      File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/cctbx_project/dxtbx/datablock.py", line 762, in _load_datablocks
        format_kwargs = format_kwargs)
      File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/cctbx_project/dxtbx/imageset.py", line 611, in make_sweep
        single_file_indices = range(*array_range))
      File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/cctbx_project/dxtbx/format/FormatMultiImage.py", line 230, in get_imageset
        assert not (as_sweep and lazy), 'No lazy support for sweeps'
    AssertionError: No lazy support for sweeps
```

**Comment by rjgildea** [comment]
The problem in the master is this line here:
https://github.com/cctbx/cctbx_project/blob/master/dxtbx/format/FormatMultiImage.py#L193

If I comment out `lazy = True` then it loads and the error is as before.

**Comment by rjgildea** [comment]
Have reported as https://github.com/cctbx/cctbx_project/issues/215

**Comment by rjgildea** [comment]
I think this is a problem specific to this dataset:
There aren't many reflections, and most of them are at the same resolution, which fools the algorithm for determining the bin width:

reflection d_spacings:
[3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394275, 3.7655689437394266, 3.7655689437394266, 3.7655689437394266, 3.7655689437394266, 3.220656566008651, 3.220656566008651, 3.220656566008651, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 3.2206565660086506, 2.988934374943237, 2.988934374943237, 2.988934374943237, 2.988934374943237, 2.9443875966517394, 2.9443875966517394, 2.9443875966517394, 2.9443875966517394, 2.9443875966517394, 2.9443875966517394, 2.9443875966517394, 2.9443875966517394, 2.9443875966517394, 2.944387596651739, 2.944387596651739, 2.944387596651739, 2.452684417985707, 2.452684417985707, 2.452684417985707, 2.452684417985707, 2.452684417985707, 2.452684417985707, 2.452684417985707, 2.452684417985707, 2.452684417985707, 2.452684417985707, 2.452684417985707, 2.452684417985707, 2.452684417985707, 2.452684417985707, 2.149676680417901, 2.149676680417901, 2.149676680417901, 2.149676680417901, 2.149676680417901, 2.149676680417901, 2.149676680417901, 2.149676680417901, 2.149676680417901, 2.149676680417901, 2.149676680417901, 2.149676680417901, 2.149676680417901, 2.149676680417901, 2.149676680417901, 2.1496766804179006, 2.1496766804179006, 2.1496766804179006, 2.1496766804179006, 2.1496766804179006, 2.1496766804179006, 2.1496766804179006, 2.1496766804179006, 2.1496766804179006, 2.1496766804179006, 2.1496766804179006, 2.1496766804179006, 2.1496766804179006, 2.1496766804179006, 2.1496766804179006, 2.1496766804179006, 2.1496766804179006, 2.1496766804179006, 2.1496766804179006]
