### ISSUE TITLE
dials.import image_range= broken for multi image files

### ISSUE THREAD

**Issue by dagewa** [dials/dials#587]
Example data (a narrow wedge of 6 images, taken from https://zenodo.org/record/887440#.WzZLrnYzrCI, but other multi image files may do):
https://stfc365-my.sharepoint.com/:f:/g/personal/david_waterman_stfc_ac_uk/EguIH5vrMktLuUuhx-AmrPwBS86RrgT8f1XrME6okbzFyQ

`dials.import multi001_master.h5 image_range=2,6`

completes successfully, but

```
$ dials.show datablock.json 

############################################################################
#                                                                          #
# The DIALS reference paper has now been published:                        #
#                                                                          #
# DIALS: implementation and evaluation of a new integration package (2018) #
# https://doi.org/10.1107/S2059798317017235        Acta Cryst. D74, 85-97. #
#                                                                          #
############################################################################


Sorry: Unable to handle the following arguments:
  "datablock.json" failed during DataBlock processing:
    Traceback (most recent call last):
      File "/home/fcx32934/sw/cctbx/modules/dials/util/options.py", line 306, in try_read_datablocks
        self.datablocks.append(converter.from_string(argument))
      File "/home/fcx32934/sw/cctbx/modules/dials/util/phil.py", line 47, in from_string
        check_format=self._check_format))
      File "/home/fcx32934/sw/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 969, in from_json_file
        directory=directory)
      File "/home/fcx32934/sw/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 957, in from_json
        directory=directory)
      File "/home/fcx32934/sw/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 944, in from_dict
        importer = DataBlockDictImporter(obj, check_format, directory)
      File "/home/fcx32934/sw/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 651, in __init__
        self.datablocks = self._load_datablocks(obj, check_format, directory)
      File "/home/fcx32934/sw/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 664, in _load_datablocks
        return [self._load_datablocks(dd, check_format, directory) for dd in obj]
      File "/home/fcx32934/sw/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 748, in _load_datablocks
        assert min(indices) <= i0-1 and max(indices) >= i1-1
    AssertionError

```

**Comment by dagewa** [comment]
Trimming images from the end of a scan is fine, i.e. `dials.import multi001_master.h5 image_range=1,5` works. The problem is when the first value in the range is not 1.

**Comment by graeme-winter** [comment]
Under the hood I’ve used this before with massive Eiger data sets, splitting into chunks for processing for time reasons and then it worked. 

Using xia2. With image=nnn.h5:1:36000:3600 type syntax

I’d assume this works the same?

**Comment by dagewa** [comment]
It seems it does not work here. It is not limited to dials.show or the image viewer. Also find_spots bombs, so xia2 would not have avoided this. Do you have an Eiger dataset where the dials.import command works?

**Comment by dagewa** [comment]
Same issue with xia2_regression/test_data/thaumatin_eiger

**Comment by graeme-winter** [comment]
Ok I’ll check tonight

My money is on lazy loading changes...

**Comment by rjgildea** [comment]
Testing with older versions suggests that it has been broken since at least dials 1.8.

https://github.com/cctbx/cctbx_project/commit/1f875774d60a576141843461f8422a2474cec452

**Comment by graeme-winter** [comment]
🤔

Looks like something for Diamond Eiger... but if this is problem please assign to me

**Comment by graeme-winter** [comment]
Also I’m pretty sure it’s worked in xia2 since then for me...

**Comment by dagewa** [comment]
This also fails with other multi image files, such as EM image series files
from FEI, which made me wonder whether it is due to FormatMultiImage

**Comment by dagewa** [comment]
It looks to me like the assert is wrong
https://github.com/cctbx/cctbx_project/blob/master/dxtbx/datablock.py#L746-L748

As far as I can tell, `min(indices) == 0` always, while `max(indices) == len(indices) - 1`

**Comment by graeme-winter** [comment]
OK, looking at this:

```
xia2 image=/Users/graeme/svn/cctbx/build/xia2_regression/test_data/thaumatin_eiger/thaumatin28_w1_3_1_master.h5:1:100:50
```

seems to work as expected viz:

```
Environment configuration...
Python => /Users/graeme/svn/cctbx/build/../base/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
CCTBX => /Users/graeme/svn/cctbx/modules
CCP4 => /Applications/ccp4-7.0
CLIBD => /Applications/ccp4-7.0/lib/data
CCP4_SCR => /var/folders/hs/gvssfcd910s0jczjhjczj6h80000gn/T/tmpjW8aBh
Starting directory: /private/tmp/split
Working directory: /private/tmp/split
Free space:        28.21 GB
Contact: xia2.support@gmail.com
XIA2 0.5.626-g84b1b621
DIALS 1.dev.2665-g426fe0469
CCP4 7.0.048
Command line: xia2 image=/Users/graeme/svn/cctbx/build/xia2_regression/test_data/thaumatin_eiger/thaumatin28_w1_3_1_master.h5:1:100:50
-------------------- Spotfinding SWEEP1 --------------------
36931 spots found on 50 images (max 1361 / bin)
                                                 *
                                                 *
*                                                *
*                                 *              *
*                      *  **   *  *** ************
* *    ** *  ************************ ************
**************************************************
**************************************************
**************************************************
**************************************************
1                     image                     50
------------------- Autoindexing SWEEP1 --------------------
All possible indexing solutions:
tP  59.02  59.02 152.44  90.00  90.00  90.00
oC  83.14  83.50 152.39  90.00  90.00  90.00
oP  58.97  58.72 152.21  90.00  90.00  90.00
mC  83.28  82.86 151.98  90.00  90.08  90.00
mP  58.31 151.85  58.70  90.00  90.42  90.00
aP  58.65  58.34 151.81  89.91  90.00  90.43
Indexing solution:
tP  59.02  59.02 152.44  90.00  90.00  90.00
-------------------- Integrating SWEEP1 --------------------
Processed batches 1 to 50
Standard Deviation in pixel range: 0.29 0.34
Integration status per image:
oooooooooooooooooooooooooooooooooooooooooooooooooo
"o" => good        "%" => ok        "!" => bad rmsd
"O" => overloaded  "#" => many bad  "." => weak
"@" => abandoned
Mosaic spread: 1.316 < 1.316 < 1.316
-------------------- Spotfinding SWEEP2 --------------------
42886 spots found on 50 images (max 1534 / bin)
                                                 *
*                                                *
*                                                *
*                                                *
*          *   *   *  *  * *** ******  ***********
************ ************************ ************
**************************************************
**************************************************
**************************************************
**************************************************
51                    image                    100
------------------- Autoindexing SWEEP2 --------------------
All possible indexing solutions:
tP  58.47  58.47 151.06  90.00  90.00  90.00
oC  82.68  82.50 150.82  90.00  90.00  90.00
oP  58.26  58.36 150.81  90.00  90.00  90.00
mC  82.43  82.41 150.67  90.00  90.13  90.00
mP  58.23  58.20 150.44  90.00  89.90  90.00
aP  58.18  58.22 150.46  89.89  90.01  90.04
Indexing solution:
tP  58.47  58.47 151.06  90.00  90.00  90.00
-------------------- Integrating SWEEP2 --------------------
Processed batches 51 to 100
Standard Deviation in pixel range: 0.39 0.46
Integration status per image:
oooooooooooooooooooooooooooooooooooooooooooooooooo
"o" => good        "%" => ok        "!" => bad rmsd
"O" => overloaded  "#" => many bad  "." => weak
"@" => abandoned
Mosaic spread: 0.250 < 0.250 < 0.250
-------------------- Preparing DEFAULT ---------------------
Likely spacegroups:
P 4 21 2
Reindexing to first spacegroup setting: P 4 21 2 (h,k,l)
--------------------- Scaling DEFAULT ----------------------
Resolution for sweep NATIVE/SWEEP1: 1.96 (merged <I/sigI> > 1.0)
Resolution for sweep NATIVE/SWEEP2: 1.75 (merged <I/sigI> > 1.0)
--------------------- Scaling DEFAULT ----------------------
------------------- Unit cell refinement -------------------
NATIVE:  58.70  58.70 151.84  90.00  90.00  90.00
Overall twinning score: 4.23
Your data do not appear twinned
Project: AUTOMATIC
Crystal: DEFAULT
Sequence: 
Wavelength name: NATIVE
Wavelength 0.96770
Sweeps:
SWEEP SWEEP1 [WAVELENGTH NATIVE]
TEMPLATE thaumatin28_w1_3_1_master.h5
DIRECTORY /Users/graeme/svn/cctbx/build/xia2_regression/test_data/thaumatin_eiger
IMAGES (USER) 1 to 50
MTZ file: /private/tmp/split/DEFAULT/NATIVE/SWEEP1/integrate/dials_integrated.mtz

SWEEP SWEEP2 [WAVELENGTH NATIVE]
TEMPLATE thaumatin28_w1_3_1_master.h5
DIRECTORY /Users/graeme/svn/cctbx/build/xia2_regression/test_data/thaumatin_eiger
IMAGES (USER) 51 to 100
MTZ file: /private/tmp/split/DEFAULT/NATIVE/SWEEP2/integrate/dials_integrated.mtz
For AUTOMATIC/DEFAULT/NATIVE                 Overall    Low     High
High resolution limit                           1.75    4.74    1.75
Low resolution limit                           40.04   40.05    1.78
Completeness                                   99.5    99.9    96.7
Multiplicity                                    5.5     5.7     3.7
I/sigma                                         1.9     4.5     0.3
Rmerge(I)                                     0.513   0.440   0.478
Rmerge(I+/-)                                  0.496   0.416   0.405
Rmeas(I)                                      0.560   0.484   0.560
Rmeas(I+/-)                                   0.580   0.487   0.535
Rpim(I)                                       0.217   0.193   0.286
Rpim(I+/-)                                    0.292   0.245   0.345
CC half                                       0.780   0.609   0.812
Wilson B factor                              17.370
Anomalous completeness                         97.4    99.1    95.6
Anomalous multiplicity                          3.0     3.5     1.9
Anomalous correlation                        -0.222  -0.109   0.026
Anomalous slope                               0.309
Total observations                           151169    9119    4815
Total unique                                  27726    1590    1314
Assuming spacegroup: P 4 21 2
Unit cell (with estimated std devs):
58.697(2) 58.697(2) 151.835(6)
90.0      90.0       90.0     
mtz format:
Scaled reflections: /private/tmp/split/DataFiles/AUTOMATIC_DEFAULT_free.mtz
mtz_unmerged format:
Scaled reflections (NATIVE): /private/tmp/split/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged.mtz
sca format:
Scaled reflections (NATIVE): /private/tmp/split/DataFiles/AUTOMATIC_DEFAULT_scaled.sca
sca_unmerged format:
Scaled reflections (NATIVE): /private/tmp/split/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged.sca
Processing took 00h 11m 47s
```

etc. with spot finding from second sweep as:

```
Extracted 81078 spots
Removed 37890 spots with size < 3 pixels
Removed 84 spots with size > 100 pixels
Calculated 43104 spot centroids
Calculated 43104 spot intensities
Filtered 42886 of 43104 spots by peak-centroid distance
Found 60 possible hot pixel(s)

Histogram of per-image spot count for imageset 0:
42886 spots found on 50 images (max 1534 / bin)
                                                 *
*                                                *
*                                                *
*                                                *
*          *   *   *  *  * *** ******  ***********
************ ************************ ************
**************************************************
**************************************************
**************************************************
**************************************************
51                    image                    100
```

=> was not mad; this _can_ work, but presumably using a different mechanism to the dials import one.

**Comment by graeme-winter** [comment]
Oh, OK, the error is only appearing in dials.show 🤔have now reproduced original error

**Comment by dagewa** [comment]
How puzzling. Thanks for the fix though

**Comment by graeme-winter** [comment]
todo: add regression test... not closing until got to bottom of this

**Comment by graeme-winter** [comment]
Penny drops

Importing xia2 way probably sets the indices the way show etc expected

Import image range sets them to start from 0 which is maybe a bug? Should be the original indices? Discuss...

**Comment by graeme-winter** [comment]
OK - baseline testing

```
dials.import image_range=1,10 ~/svn/cctbx/build/xia2_regression/test_data/thaumatin_eiger/thaumatin28_w1_3_1_master.h5
=> find spots 
=>
Histogram of per-image spot count for imageset 0:
6488 spots found on 10 images (max 1092 / bin)
         *
*        *
*        *
*        *
**      **
** **** **
**********
**********
**********
**********
1 image 10

dials.import image_range=11,20 ~/svn/cctbx/build/xia2_regression/test_data/thaumatin_eiger/thaumatin28_w1_3_1_master.h5 
=> etc
=> 

Histogram of per-image spot count for imageset 0:
7244 spots found on 10 images (max 1226 / bin)
         *
         *
*        *
*        *
*     * **
** **** **
**********
**********
**********
**********
11      20
```

Current behaviour appears correct, modulo weirdness with use of indices (i.e. no user facing bug)

**Comment by dagewa** [comment]
> todo: add regression test... not closing until got to bottom of this

So close to the finish line....!

**Comment by dagewa** [comment]
The original example no longer causes a failure, so closing this.
