### ISSUE TITLE
dials.export_bitmaps: no binning for I23 images

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#588]
following from #575:
```
$ dials.export_bitmaps /dls/i23/data/2018/cm19648-3/20180619/scint/test_19_0001.cbf format=jpeg quality=95 binning=4 brightness=60
The following parameters have been modified:

binning = 4
brightness = 60
format = *jpeg png tiff
jpeg {
  quality = 95
}
input {
  datablock = <image files>
}

Traceback (most recent call last):
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/command_line/export_bitmaps.py", line 274, in <module>
    run(sys.argv[1:])
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/command_line/export_bitmaps.py", line 108, in run
    imageset_as_bitmaps(imageset, params)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/command_line/export_bitmaps.py", line 165, in imageset_as_bitmaps
    assert binning == 1
AssertionError
```
original issue: https://jira.diamond.ac.uk/browse/SCI-7471

**Comment by rjgildea** [comment]
Assert exists because _get_flex_image_multipanel() doesn't support the parameter binning [c.f. _get_flex_image()]:
https://github.com/cctbx/cctbx_project/blob/master/rstbx/slip_viewer/tile_generation.py#L50
called from:
https://github.com/dials/dials/blob/master/command_line/export_bitmaps.py#L166

**Comment by rjgildea** [comment]
Fixed: https://github.com/cctbx/cctbx_project/commit/0ad4f68e7fefaa98f15baffd87fc0d87e433cb0c
