### ISSUE TITLE
How do I export 1 image from stills set?

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#589]
I have a ```.nxs``` file, specifically ```/dls/mx/data/mx19458/mx19458-6/VMXi-AB0592/well_145/images/image_6043.nxs```, and want to ```dials.export_bitmap``` exactly one (preferably the first) image. How can I do that?

```$ dials.export_bitmap this.nxs``` exports all images.

```
$ dials.import this.nxs
--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatNexus.FormatNexus'>
  num images: 7242
  num sweeps: 0
  num stills: 7242
--------------------------------------------------------------------------------
Writing datablocks to datablock.json
$ dials.export_bitmap datablock.json
```
is (expectedly) the same.

```
$ dials.import this.nxs image_range=1,1
Applying input geometry in the following order:
  1. Manual geometry

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatNexus.FormatNexus'>
  num images: 1
  num sweeps: 0
  num stills: 7242
--------------------------------------------------------------------------------
Writing datablocks to datablock.json
$ dials.export_bitmap datablock.json
```
still exports all images.

**Comment by rjgildea** [comment]
dials.show seems to be broken on this example:
```
$ dials.import /dls/mx/data/mx19458/mx19458-6/VMXi-AB0592/well_145/images/image_6043.nxs image_range=1,1
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 1.dev.2658-g571374c
The following parameters have been modified:

input {
  datablock = <image files>
}
geometry {
  scan {
    image_range = 1 1
  }
}


Applying input geometry in the following order:
  1. Manual geometry

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatNexus.FormatNexus'>
  num images: 1
  num sweeps: 0
  num stills: 7242
--------------------------------------------------------------------------------
Writing datablocks to datablock.json
$ dials.show datablock.json 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
Sorry: Unable to handle the following arguments:
  "datablock.json" failed during DataBlock processing:
    Traceback (most recent call last):
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/dials/util/options.py", line 306, in try_read_datablocks
        self.datablocks.append(converter.from_string(argument))
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/dials/util/phil.py", line 47, in from_string
        check_format=self._check_format))
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 969, in from_json_file
        directory=directory)
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 957, in from_json
        directory=directory)
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 944, in from_dict
        importer = DataBlockDictImporter(obj, check_format, directory)
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 651, in __init__
        self.datablocks = self._load_datablocks(obj, check_format, directory)
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 664, in _load_datablocks
        return [self._load_datablocks(dd, check_format, directory) for dd in obj]
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 798, in _load_datablocks
        filenames, None, check_format, indices, format_kwargs=format_kwargs)
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/imageset.py", line 536, in make_imageset
        check_format  = check_format)
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/format/FormatMultiImage.py", line 270, in get_imageset
        for i in range(format_instance.get_num_images()):
    AttributeError: 'NoneType' object has no attribute 'get_num_images'

```

**Comment by rjgildea** [comment]
Might have just been an issue with out-of-date sources... after updating dials.show works fine.

**Comment by rjgildea** [comment]
```
$ dials.python
Python 2.7.8 (default_cci, Mar  1 2017, 15:32:48) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from dxtbx.serialize import load
>>> db = load.datablock('datablock.json')
>>> imageset = db[0].extract_imagesets()[0]
>>> len(imageset)
7242
```
Why is the length of the imageset 7242 and not 0?

**Comment by ndevenish** [comment]
> Why is the length of the imageset 7242 and not 1? @jmp1985 ?

This is by design? As far as I could derived from my unmerged [datablock-refactor](https://github.com/ndevenish/cctbx_project/blob/fasterimport/dxtbx/datablock.py#L900-L906), the rules for building datablocks out of a list of images are:
- Each change in format goes into it's own Datablock
- FormatMultiImage files each have their own ImageSet
- Every set of images forming a scan goes into it's own ImageSweep
- Any consecutive still frames that share **any** metadata with the previous still frame get collected into one ImageSet

**Comment by Anthchirp** [comment]
some resolution for this is required for https://jira.diamond.ac.uk/browse/SCI-7495

**Comment by ndevenish** [comment]
Is https://github.com/dials/dials/commit/9699db3ef4a1fb739ad709b15d6d0ad2c620fc5b what you need for this?

**Comment by Anthchirp** [comment]
```dials.export_bitmaps /dls/mx/data/mx19458/mx19458-6/VMXi-AB0592/well_145/images/image_6043.nxs imageset_index=1```
Perfect. Thank you.
