### ISSUE TITLE
dials.scale not working in CCP4

### ISSUE THREAD

**Issue by dagewa** [dials/dials#631]
Missing `mock`
```
$ dials.scale 
Traceback (most recent call last):
  File "/home/david/ccp4/ccp4-7.0/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/david/ccp4/ccp4-7.0/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/david/ccp4/ccp4-7.0/lib/py2/site-packages/dials/command_line/scale.py", line 57, in <module>
    from dials.algorithms.scaling.scaling_library import create_scaling_model,\
  File "/home/david/ccp4/ccp4-7.0/lib/py2/site-packages/dials/algorithms/scaling/scaling_library.py", line 15, in <module>
    from mock import Mock
ImportError: No module named mock
david@brno:~$ 
```

**Comment by dagewa** [comment]
Required in production, not just testing. Resolution therefore awaits CCP4 adding `mock`

**Comment by jbeilstenedmands** [comment]
Is it obvious which bit of the code is requiring the funcsigs module? I tried looking at the funcsigs documentation but I don't really understand in what situations this would be needed.

**Comment by dagewa** [comment]
it is pulled in by `mock` apparently

**Comment by dagewa** [comment]
Full traceback as follows:
```
$ dials.scale
Traceback (most recent call last):
  File "/home/david/ccp4/ccp4-7.0/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/david/ccp4/ccp4-7.0/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/david/ccp4/ccp4-7.0/lib/py2/site-packages/dials/command_line/scale.py", line 57, in <module>
    from dials.algorithms.scaling.scaling_library import create_scaling_model,\
  File "/home/david/ccp4/ccp4-7.0/lib/py2/site-packages/dials/algorithms/scaling/scaling_library.py", line 15, in <module>
    from mock import Mock
  File "/home/david/ccp4/ccp4-7.0/lib/python2.7/site-packages/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/home/david/ccp4/ccp4-7.0/lib/python2.7/site-packages/mock/mock.py", line 80, in <module>
    import funcsigs
ImportError: No module named funcsigs
```
This isn't your problem though, back over to CCP4...
