### ISSUE TITLE
In dials.integrate track down and prevent (ideally) cause of exit code = -9

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#659]
Believed to be memory allocation in second step of integration i.e. once the reference profiles are constructed, when gets to integration it falls over. This is probably the most widely reported real bug.

**Comment by graeme-winter** [comment]
Multiple possible solutions for this - using threaded integration in preference to multiprocessing is one, better prediction of memory usage would be a second. Really needs a test case to throw the problem however.

**Comment by dagewa** [comment]
Possible solution 1 is in the works #833

**Comment by dagewa** [comment]
This is still one of the most commonly-reported bugs, and in my eyes the most serious.

We struggle to process "normal" data on a "normal" computer. For example, I have a dataset from a CCP4 workshop that is nothing particularly special: P3 cell with a=84.5 Å, c=107.0 Å, P6M detector, 360° at 0.1°/image and a moderately large mosaicity of 0.5°. I can't process this beyond 2.0 Å on my laptop with 16 GB RAM, even using just a single process! Ronan ran it on one of the CCP4 servers with nproc=1 and noted it required 31 GB of memory and took 7.5 hours to complete.

XDS has no such problem. We are keeping all integrated data in RAM for no good reason. Once a spot is integrated, it is integrated. Dump it somewhere. Or at least dump its shoebox

**Comment by graeme-winter** [comment]
Excellent to see some diagnostic here, keeping all shoeboxes around is unnecessary and a very poor idea

Do you have pointers where the issues are centred?

**Comment by dagewa** [comment]
I don't have any such pointers, just coming at it from a user perspective at the moment. Tried to process data, it failed. I did notice it failed during integration though, so after profile modelling. It integrated a couple of hundred images then died. I no longer have the logs for that run here though.

**Comment by graeme-winter** [comment]
If the offending images are somewhere public would help a lot! 👍

**Comment by dagewa** [comment]
I can't do for this case. I think a 3600 image fine-sliced dataset of thaumatin would do though. We can set the mosaicity to 0.5° manually

**Comment by graeme-winter** [comment]
Reproduced:

/dls/i04/data/2020/cm26459-1/20200220/TestInsulin/ins_10/ins_10_1_master.h5

```
# disable virtual memory
ulimit -v 0

dials.import ../insulin-vanilla/ins_10_1_master.h5
dials.find_spots imported.expt nproc=8
dials.index imported.expt strong.refl
dials.refine indexed.expt indexed.refl
# proper values are 0.03 / 0.11
dials.integrate refined.expt refined.refl nproc=8 sigma_m=0.5 sigma_b=0.1
```

...

```
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/integrate.py", line 665, in <module>
    script.run()
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/integrate.py", line 353, in run
    reflections = integrator.integrate()
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/integration/integrator.py", line 1192, in integrate
    self.reflections, _, time_info = processor.process()
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/integration/processor.py", line 259, in process
    self.manager.initialize()
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/integration/processor.py", line 601, in initialize
    self.compute_processors()
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/integration/processor.py", line 826, in compute_processors
    max_memory / 1e9,
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: 
        Not enough memory to run integration jobs.  This could be caused by a
        highly mosaic crystal model.  Possible solutions include increasing the
        percentage of memory allowed for shoeboxes or decreasing the block size.
        The average shoebox size is 121 x 123 pixels x 42 images - is your crystal
        really this mosaic?
            Total system memory: 17.2 GB
            Shoebox memory limit: 12.9 GB
            Required shoebox memory: 44.4 GB
```

**Comment by graeme-winter** [comment]
This was on my MacBook Pro with 16 GB RAM

**Comment by dagewa** [comment]
Thanks, ideal test case :+1:

**Comment by dagewa** [comment]
It bombed during integration with `nproc=1` by setting a 12 GB limit on Linux:
```
ulimit -v 12000000
dials.integrate refined.expt refined.refl sigma_m=0.5 sigma_b=0.1
```
finally failing here:
```
 1795 [3882]: *******************************************************
 1796 [3800]: *****************************************************
 1797 [3684]: ****************************************************
 1798 [3584]: **************************************************
 1799 [3487]: *************************************************
 1800 [3394]: ************************************************

Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/integrate.py", line 665, in <module>
    script.run()
  File "/home/fcx32934/sw/cctbx/build/../modules/dials/command_line/integrate.py", line 353, in run
    reflections = integrator.integrate()
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/integration/integrator.py", line 1192, in integrate
    self.reflections, _, time_info = processor.process()
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/integration/processor.py", line 305, in process
    self.manager.accumulate(task())
  File "/home/fcx32934/sw/cctbx/modules/dials/algorithms/integration/processor.py", line 491, in __call__
    sbox_memory / 1e9,
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: 
        There was a problem allocating memory for shoeboxes.  This could be caused
        by a highly mosaic crystal model.  Possible solutions include increasing the
        percentage of memory allowed for shoeboxes or decreasing the block size.
        The average shoebox size is 122 x 124 pixels x 44 images - is your crystal
        really this mosaic?
        Total system memory: 16.7 GB
        Shoebox memory limit: 12.5 GB
        Required shoebox memory: 51.1 GB

```

**Comment by graeme-winter** [comment]
Disabling checks in debugging-integrate-memory-use branch to see where this actually fails, rather than computes something && says no

**Comment by graeme-winter** [comment]
Oh, not very helpful

```
/dls_sw/cluster/GE/UGE8.6.7/TEST/spool/cs04r-sc-com99-09/job_scripts/1178132: line 9: 865167 Segmentation fault      dials.integrate refined.expt refined.refl sigma_m=0.5 sigma_b=0.1
```

no useful stack trace 🤔 last console output

```
 1800 [3394]: ************************************************

 Memory usage:
  Total system memory: 134.845 GB
  Limit shoebox memory: 101.134 GB
  Required shoebox memory: 51.0777 GB
```

**Comment by dagewa** [comment]
What are the options for inspecting memory use at a breakpoint in processing? I suspect it's shoeboxes that tip the balance, but it would be good to know for sure.

**Comment by ndevenish** [comment]
A memory profiler might help - valgrind? VTune also has a memory profiler that looks promising, started running things before I left for leave but didn’t get to dig in.

**Comment by graeme-winter** [comment]
Another option could be https://docs.python.org/3/library/faulthandler.html - just taking a look at this now, may try hacking in on my branch above

**Comment by graeme-winter** [comment]
```
Fatal Python error: Segmentation fault

Current thread 0x00007f999f926740 (most recent call first):
  File "/dls/science/users/gw56/git/modules/dials/algorithms/integration/processor.py", line 520 in __call__
  File "/dls/science/users/gw56/git/modules/dials/algorithms/integration/processor.py", line 305 in process
  File "/dls/science/users/gw56/git/modules/dials/algorithms/integration/integrator.py", line 1192 in integrate
  File "/dls/science/users/gw56/git/build/../modules/dials/command_line/integrate.py", line 353 in run
  File "/dls/science/users/gw56/git/build/../modules/dials/command_line/integrate.py", line 665 in <module>
```

Useful 🙂

**Comment by dagewa** [comment]
Would [guppy](https://www.pluralsight.com/guides/profiling-memory-usage-in-python) help, or crippled by boost.python?

**Comment by graeme-winter** [comment]
Digging a bit here I think the solution will be in processor to pass the option not to save the shoeboxes down the stack so we don't allocate / fill them outside the minimum scope where they are needed. Looking more at this now.

**Comment by dagewa** [comment]
Thanks for looking at it. I was wondering about moving shoeboxes out of the reflection table and into a map structure, leaving only keys into the map in the reflection table. Shoeboxes can then be consumed and deleted after use. But I wasn't 100% sure it _is_ the shoeboxes at fault (though, say >95%)

**Comment by graeme-winter** [comment]
![maxrss](https://user-images.githubusercontent.com/1241716/76841036-177cdf80-6830-11ea-87a0-e90a911c4f67.png)

Looking at maximum resident size in memory it climbs fairly slowly then jumps as we go into the actual integration phase - this is I think where things go bad usually. This was "sensible" processing on a small molecule example so probably not representative - waiting on the smoking gnu above to finish running...

**Comment by graeme-winter** [comment]
OK, troublesome task above (with slightly silly mosaic parameters) has finished and illustrates the issue well - 

![boom](https://user-images.githubusercontent.com/1241716/76843695-0d5ce000-6834-11ea-93bb-7caa2594df0f.png)

From the output - 

```
 Memory usage:
  Total system memory: 134.845 GB
  Limit shoebox memory: 101.134 GB
  Required shoebox memory: 51.0777 GB
```

This shoebox memory estimate is sound, and the problem...

**Comment by graeme-winter** [comment]
Coming up for some air... it looks like the shoeboxes are kinda deallocated at the C++ level - there are still references to `reflections["shoebox"]` lurking around - the `sys.getrefcount()` says 2 which means 1, so there are some odd things happening

**Comment by graeme-winter** [comment]
General synopsis at 13:15 hrs: looks like the shoeboxes _are_ bring freed in the C++ code - if we are not writing them out - and deleting the "shoebox" column from the reflection table makes very little difference, as this is just 6 numbers or so and a couple of pointers per reflection.

**Comment by graeme-winter** [comment]
Though... the memory estimate above seems spot on which makes me like 🤔

I checked the reference counts and I _think_ the shoeboxes are bring freed... before being unlinked from the shoebox structure the `data` member had one `use_count()` reference

**Comment by graeme-winter** [comment]
![memory](https://user-images.githubusercontent.com/1241716/76931955-bd3c5700-68e1-11ea-89d5-8be732defa8a.png)

Testing with small molecule set with deliberately large profile model parameters - the memory does not go up constantly, so something is being freed somewhere. I am coming around to the idea that what is causing us problems is the steep rise in memory use between 0 and 50 frames at the start of actual integration. I am not sure we can avoid this whilst keeping the pixel data in memory. 

However: this is not a matter of us doing something dumb, this is a real problem.

**Comment by graeme-winter** [comment]
Looking at another thread - are our processing / profile parameters sensible? Compare what XDS reports and DIALS, considering that in theory they have the same underlying model - 

```
For reference - XDS says

 ***** SUGGESTED VALUES FOR INPUT PARAMETERS *****
 BEAM_DIVERGENCE=   0.36785  BEAM_DIVERGENCE_E.S.D.=   0.03679
 REFLECTING_RANGE=  0.53704  REFLECTING_RANGE_E.S.D.=  0.07672

DIALS says

Using 10678 / 10679 reflections for sigma calculation
Calculating E.S.D Beam Divergence.
Calculating E.S.D Reflecting Range (mosaicity).
 sigma b: 0.052859 degrees
 sigma m: 0.106186 degrees
```

perform integration with both - manually setting the profile parameters to "simulate" the XDS job and write a little jiffy to get the differences for matched reflections. If our profile parameters were too large we would see simply added noise, and the average intensity would be the same. If the XDS parameters are too small the integrated intensity should be systematically lower. 

Script:

```
from dials.array_family import flex

def filter_tukey(data):
    from scitbx.math import five_number_summary

    outliers = flex.bool(len(data), False)
    min_x, q1_x, med_x, q3_x, max_x = five_number_summary(data)
    iqr_x = q3_x - q1_x
    cut_x = 1.5 * iqr_x
    outliers.set_selected(data > q3_x + cut_x, True)
    outliers.set_selected(data < q1_x - cut_x, True)
    
    return data.select(~outliers)

def compare(a, b):
    '''Effectively compute b - a'''
    data_a = flex.reflection_table.from_file(a)
    data_a = data_a.select(data_a.get_flags(data_a.flags.integrated_prf))

    data_b = flex.reflection_table.from_file(b)
    data_b = data_b.select(data_b.get_flags(data_b.flags.integrated_prf))

    matches = data_a.match(data_b)

    i_a = data_a["intensity.prf.value"].select(matches[0])
    i_b = data_b["intensity.prf.value"].select(matches[1])

    b_a = flex.double(sorted(i_b - i_a))

    # chuck outliers - use Tukey's fences

    b_a = filter_tukey(b_a)
    
    hist = flex.histogram(b_a)

    for c, v in zip(hist.slot_centers(), hist.slots()):
        print(c, v)
    
if __name__ == '__main__':
    import sys

    compare(sys.argv[1], sys.argv[2])

```

Result:

![profile-parameters](https://user-images.githubusercontent.com/1241716/76947760-013d5500-68fe-11ea-8e96-bb0f9005e6c8.png)

Yes, there is a systematic difference in favour of the DIALS profile parameters being ~ right (at least, using smaller profile parameters makes for a systematic reduction in intensities which I interpret as missing the tails of the peak)

**Comment by graeme-winter** [comment]
Shoeboxes useful because:
![Screenshot 2020-03-18 at 07 06 07](https://user-images.githubusercontent.com/1241716/76953544-c8ee4480-6906-11ea-9ce9-4f686b58920c.png)

**Comment by rjgildea** [comment]
> Reproduced:
> 
> /dls/i04/data/2020/cm26459-1/20200220/TestInsulin/ins_10/ins_10_1_master.h5
> 
> ```
> # disable virtual memory
> ulimit -v 0
> 
> dials.import ../insulin-vanilla/ins_10_1_master.h5
> dials.find_spots imported.expt nproc=8
> dials.index imported.expt strong.refl
> dials.refine indexed.expt indexed.refl
> # proper values are 0.03 / 0.11
> dials.integrate refined.expt refined.refl nproc=8 sigma_m=0.5 sigma_b=0.1
> ```
> 
> ...
> 
> ```
> Traceback (most recent call last):
>   File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/integrate.py", line 665, in <module>
>     script.run()
>   File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/integrate.py", line 353, in run
>     reflections = integrator.integrate()
>   File "/Users/graeme/svn/cctbx/modules/dials/algorithms/integration/integrator.py", line 1192, in integrate
>     self.reflections, _, time_info = processor.process()
>   File "/Users/graeme/svn/cctbx/modules/dials/algorithms/integration/processor.py", line 259, in process
>     self.manager.initialize()
>   File "/Users/graeme/svn/cctbx/modules/dials/algorithms/integration/processor.py", line 601, in initialize
>     self.compute_processors()
>   File "/Users/graeme/svn/cctbx/modules/dials/algorithms/integration/processor.py", line 826, in compute_processors
>     max_memory / 1e9,
> RuntimeError: Please report this error to dials-support@lists.sourceforge.net: 
>         Not enough memory to run integration jobs.  This could be caused by a
>         highly mosaic crystal model.  Possible solutions include increasing the
>         percentage of memory allowed for shoeboxes or decreasing the block size.
>         The average shoebox size is 121 x 123 pixels x 42 images - is your crystal
>         really this mosaic?
>             Total system memory: 17.2 GB
>             Shoebox memory limit: 12.9 GB
>             Required shoebox memory: 44.4 GB
> ```

**Comment by Anthchirp** [comment]
Just for the record: In DIALS 2.1.3 (which is the version included in CCP4 7.1) a related issue shows up as
```
Modelling reflection profiles

Traceback (most recent call last):
  File "/usr/local/dials-v2-1-3/build/../modules/dials/command_line/integrate.py", line 669, in <module>
    script.run()
  File "/usr/local/dials-v2-1-3/base/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/dials-v2-1-3/modules/dials/util/__init__.py", line 124, in show_mail_on_error
    e.args = (text + " " + str(e.args[0]),)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd7' in position 281: ordinal not in range(128)
```
and this should be fixed in DIALS 2.2.3 via #1221

**Comment by graeme-winter** [comment]
100% _not at all stale_ - still an issue 😞

**Comment by dagewa** [comment]
Ok, we've had quite a bit of work on this noted above, and these days we are reducing `nproc` when it looks like we are going to exceed memory limits. However, one thing I've seen a few times is that it reduces `nproc` to something, then bombs anyway. Are we still being too optimistic when we reduce `nproc`?

**Comment by dagewa** [comment]
We are having a significant number of these failures at the DLS workshop. I think perhaps the reason for that is because the machines have a fairly large number of cores (28) for the amount of RAM (32 or 16 GB). I suspect this calculation is flawed:
```
WARN: Memory situation report:
  Available system memory                           :  33.1 GB
  Maximum memory for processing                     :  29.8 GB
  Memory required per process                       :   2.4 GB
Reducing number of processes from 28 to 12 due to memory constraints.
```
I would bet the memory required per process is greater than 2.4 GB because this calculation is not including some overhead taken by each process. Indeed, it looks like it only takes into account the memory required for shoeboxes, not including _any_ overhead.

```python
        # Get the maximum shoebox memory to estimate memory use for one process
        memory_required_per_process = flex.max(
            self.jobs.shoebox_memory(self.reflections, self.params.shoebox.flatten)
        )
```

We should be able to figure out a better value for the memory required per process empirically by running jobs of various sizes, recording the peak memory usage, and dividing that by `nproc`. With enough runs we should be able to form a predictive model for the true `memory_required_per_process`.
