### ISSUE TITLE
dials.scale model=auto fails

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#668]
model=auto is apparently the default, but explicitly setting model=auto on the command line fails:
```
$ dials.scale integrated_experiments.json integrated.pickle model=auto
...
Traceback (most recent call last):
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/dials/command_line/scale.py", line 586, in <module>
    halraiser(e)
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/dials/command_line/scale.py", line 583, in <module>
    script.run()
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/dials/command_line/scale.py", line 144, in run
    self.scale()
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/dials/command_line/scale.py", line 219, in scale
    self.reflections)
  File "/dls/mx-scratch/rjgildea/software/cctbx/modules/dials/algorithms/scaling/scaling_library.py", line 231, in create_scaling_model
    raise Sorry('Unable to create scaling model of type %s' % params.model)
Sorry: Unable to create scaling model of type Auto
```

**Comment by rjgildea** [comment]
There's a slight quirk of phil for a 'choice' phil type such that if you do:
```
  model = physical array KB *auto
      .type = choice
```
then the default value will get interpreted as the string 'auto', whereas when you pass 'auto' on the command line it will get interpreted as a libtbx.Auto type. I suggest that you remove the '*auto' from the phil definition, and leave none selected:
```
  model = physical array KB
      .type = choice
```
and then in your code do:
```
    if self.params.model in (None, libtbx.Auto):
      self.experiments = create_auto_scaling_model(self.params, self.experiments,
        self.reflections)
    else:
      self.experiments = create_scaling_model(self.params, self.experiments,
        self.reflections)
```
which should work for both the default behaviour, and if 'auto is explicitly passed on the command line.

**Comment by jbeilstenedmands** [comment]
Thanks for the suggestion, this passes my tests and works as expected so I've commited the code, this issue should now be solved.
