### ISSUE TITLE
Incorrect behaviour when given .h5 data files as input

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#693]
Users may inadvertently provide a data .h5 file instead of master.h5 as input, however for some programs this leads to ambiguous behaviour/errors:
```
$ dials.show /dls/i04/data/2019/cm23004-1/20190116/Eiger/E-change/1/Se_Thaum_5_1_000001.h5 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  datablock = <image files>
}

Format: <class 'dxtbx.format.FormatHDF5RawData.FormatRawData'>
```
```
$ dials.image_viewer /dls/i04/data/2019/cm23004-1/20190116/Eiger/E-change/1/Se_Thaum_5_1_000001.h5 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  datablock = <image files>
}

Gtk-Message: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/command_line/image_viewer.py", line 206, in <module>
    runner()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/command_line/image_viewer.py", line 139, in __call__
    self.view()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/command_line/image_viewer.py", line 147, in view
    reflections=self.reflections)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/util/image_viewer/spotfinder_wrap.py", line 55, in display
    self.frame.load_image(chooser_wrapper(imagesets[0], 0))
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/util/image_viewer/spotfinder_frame.py", line 563, in load_image
    show_untrusted=show_untrusted)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/util/image_viewer/slip_viewer/frame.py", line 326, in load_image
    img = rv_image(file_name_or_data)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/cctbx_project/rstbx/viewer/__init__.py", line 247, in __init__
    if len(detector) == 1:
TypeError: object of type 'NoneType' has no len()
```

**Comment by rjgildea** [comment]
The data file is "understood" by the FormatRawData class:
https://github.com/cctbx/cctbx_project/blob/master/dxtbx/format/FormatHDF5RawData.py
```$ dxtbx.print_header /dls/i04/data/2019/cm23004-1/20190116/Eiger/E-change/1/Se_Thaum_5_1_000001.h5 
=== /dls/i04/data/2019/cm23004-1/20190116/Eiger/E-change/1/Se_Thaum_5_1_000001.h5 ===
Using header reader: FormatRawData
No beam model found
No detector model found
No goniometer model found
No scan model found
```

**Comment by rjgildea** [comment]
Should dials option parser explicitly check for presence of detector and beam objects in read_datablocks_from_images? Without those two objects we can't do any meaningful processing...
https://github.com/dials/dials/blob/master/util/options.py#L286

**Comment by graeme-winter** [comment]
Cleaned up user facing behaviour:

```
Grey-Area crc :( $ dials.import ~/data/i04-eiger-small/Therm_6_2_000001.h5 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.300-gb0816c723
The following parameters have been modified:

input {
  experiments = <image files>
}

Sorry: 
          Imageset contains no beam or detector model. This means you will be
          unable to process your data.

          Possible causes of this error are:
             - A problem reading the images with one of the dxtbx format classes
             - A lack of header information in the file itself.

          You can override this by specifying the metadata as geometry parameters
        
Grey-Area crc :( $ dials.show ~/data/i04-eiger-small/Therm_6_2_000001.h5 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = <image files>
}

Error: experiment has no detector
Grey-Area crc :( $ dials.image_viewer ~/data/i04-eiger-small/Therm_6_2_000001.h5 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = <image files>
}

Error: experiment has no detector
```
