### ISSUE TITLE
reciprocal lattice viewer broken for imported_experiments.json

### ISSUE THREAD

**Issue by dagewa** [dials/dials#723]
```bash
dials.import ~/xray/mosflm_exam_hg_images/*.mar1600
dials.find_spots imported_experiments.json
dials.reciprocal_lattice_viewer imported_experiments.json strong.pickle
```
produces
```
AttributeError: 'NoneType' object has no attribute 'get_A'
Traceback (most recent call last):
  File "/home/david/sw/cctbx/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 1013, in <module>
    run(sys.argv[1:])
  File "/home/david/sw/cctbx/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 1003, in run
    f.load_models(imagesets, reflections, crystals)
  File "/home/david/sw/cctbx/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 362, in load_models
    render_3d.load_models(self, imagesets, reflections, crystals)
  File "/home/david/sw/cctbx/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 134, in load_models
    matrix.sqr(c.get_A()).transpose().as_list_of_lists() for c in crystals
AttributeError: 'NoneType' object has no attribute 'get_A'

```

**Comment by dagewa** [comment]
Not sure about the immediate fix in this case. `crystals = experiments.crystals()` gives `[None]` rather than `None`, but setting it to `None` instead causes the viewer to hang so there is something deeper to fix.

**Comment by dagewa** [comment]
I don't know what has changed, but as of today this appears to be fixed. So, closing.
