### ISSUE TITLE
dials.convert_to_cbf doesn't

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#745]
```
Grey-Area manual :( $ dials.convert_to_cbf ~/data/i04-8558/data_200/ge1_200mm_1_master.h5 
The following parameters have been modified:

input {
  experiments = <image files>
}

Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/convert_to_cbf.py", line 91, in <module>
    run()
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/convert_to_cbf.py", line 84, in run
    assert len(imagesets) == 1
AssertionError
```

**Comment by graeme-winter** [comment]
Wait, what? Added a print to get the len() out and

```
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/convert_to_cbf.py", line 91, in <module>
    run()
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/convert_to_cbf.py", line 84, in run
    assert len(imagesets) == 1, len(imagesets)
AssertionError: 1800
```

on master

this is not a good thing

**Comment by graeme-winter** [comment]
@ndevenish points out 

```
     else:
-        imagesets = experiments[0].imageset
-        assert len(imagesets) == 1
+        imagesets = experiments.imagesets()
+        assert len(imagesets) == 1, len(imagesets)
         imageset = imagesets[0]
```

**Comment by graeme-winter** [comment]
https://github.com/dials/dials/commit/5efd0000ba42038271565ea2a20726c57806b6ab

**Comment by ndevenish** [comment]
Fixed by https://github.com/dials/dials/commit/5efd0000ba42038271565ea2a20726c57806b6ab
