### ISSUE TITLE
dials.integrate broken on i23 images

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#759]
Original xia2 command:
`xia2 anomalous=True read_all_image_headers=False dials.find_spots.phil_file=find_spots.phil image=/dls/i23/data/2019/nr23017-1/20190302/germ_9keV/data_1_0001.cbf`
```
$ pwd
/dls/mx-scratch/rjgildea/dials_758b/i23_germ_9keV/kernel_3/DEFAULT/SAD/SWEEP1/integrate
$ dials.integrate  'input.experiments=/dls/mx-scratch/rjgildea/dials_758b/i23_germ_9keV/kernel_3/DEFAULT/SAD/SWEEP1/refine/11_refined_experiments.json' 'nproc=20' 'input.reflections=/dls/mx-scratch/rjgildea/dials_758b/i23_germ_9keV/kernel_3/DEFAULT/SAD/SWEEP1/refine/11_refined.pickle' 'output.include_bad_reference=True' 'debug.reference.output=True' 'profile.fitting=True' 'outlier.algorithm=null' 'background.algorithm=glm' 'prediction.d_max=21.859971' 'prediction.d_min=0.911777'
...
Modelling reflection profiles

Traceback (most recent call last):
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/dials/command_line/integrate.py", line 700, in <module>
    halraiser(e)
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/dials/command_line/integrate.py", line 698, in <module>
    script.run()
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/dials/command_line/integrate.py", line 370, in run
    reflections = integrator.integrate()
  File "/dls/mx-scratch/rjgildea/software/cctbx/modules/dials/algorithms/integration/integrator.py", line 1129, in integrate
    profile_fitter_single.add(expr.profile.fitting_class()(expr))
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dials Internal Error: /dls/mx-scratch/rjgildea/software/cctbx/modules/dials/algorithms/profile_model/modeller/multi_experiment_modeller.h(41): DIALS_ASSERT(modeller != __null) failure.
```
This regression appears to have been introduced in the last week (it ran successfully with dials/latest generated on 10th April). As far as I can tell it was caused by this commit in dxtbx: https://github.com/dials/dxtbx/commit/e7fc84863a9cc35aabd0c3f603aa334810a1a642

**Comment by ndevenish** [comment]
Did your tests confirm it was this and not the previous one? In any case, this looks like related to one of my commits so will poke in the morning.
