### ISSUE TITLE
Profile xia2/dials on NP high res ProtK dataset:

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#767]
- https://ispyb.diamond.ac.uk/dc/visit/cm23003-2/id/3474639
- /dls/i03/data/2019/cm23003-2/proteinasek/protk_1/protk_1_1_master.h5
- ProtK, 3600 images @ 0.1 deg, 0.99 Å at corners

**Comment by rjgildea** [comment]
Using dials/latest dials.integrate fails with the following error:

/dls/mx-scratch/rjgildea/dials_13/protk_1_1_/001/DEFAULT/SAD/SWEEP1/integrate/13_dials.integrate_INTEGRATE.log

```
 Using multiprocessing with 20 parallel job(s)

easy_mp crash detected; subprocess trace: ----
Stacktrace:
exit code = -9
----------------------------------------------

Traceback (most recent call last):
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190426/build/../modules/dials/command_line/integrate.py", line 700, in <module>
    halraiser(e)
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190426/build/../modules/dials/command_line/integrate.py", line 698, in <module>
    script.run()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190426/build/../modules/dials/command_line/integrate.py", line 370, in run
    reflections = integrator.integrate()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190426/modules/dials/algorithms/integration/integrator.py", line 1254, in integrate
    self.reflections, _, time_info = processor.process()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190426/modules/dials/algorithms/integration/processor.py", line 295, in process
    preserve_exception_message=True,
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190426/modules/dials/util/mp.py", line 172, in multi_node_parallel_map
    preserve_exception_message=preserve_exception_message,
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190426/modules/dials/util/mp.py", line 45, in parallel_map
    preserve_exception_message=preserve_exception_message,
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190426/modules/cctbx_project/libtbx/easy_mp.py", line 628, in parallel_map
    result = res()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190426/modules/cctbx_project/libtbx/scheduling/result.py", line 119, in __call__
    self.traceback( exception = self.exception() )
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190426/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 117, in __call__
    self.raise_handler( exception = exception )
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190426/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 134, in raise_with_traceback
    raise_(type(exception), exception, self.traceback)
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190426/modules/cctbx_project/libtbx/scheduling/mainthread.py", line 100, in poll
    value = target( *args, **kwargs )
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190426/modules/dials/util/mp.py", line 88, in __call__
    preserve_exception_message=self.preserve_exception_message,
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190426/modules/cctbx_project/libtbx/easy_mp.py", line 628, in parallel_map
    result = res()
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190426/modules/cctbx_project/libtbx/scheduling/result.py", line 119, in __call__
    self.traceback( exception = self.exception() )
  File "/dls/science/groups/scisoft/DIALS/CD/latest/dials-dev20190426/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 88, in __call__
    raise exception
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: exit code = -9
# command line:
# dials.integrate  'input.experiments=/dls/mx-scratch/rjgildea/dials_13/protk_1_1_/001/DEFAULT/SAD/SWEEP1/refine/11_refined_experiments.json' 'nproc=20' 'input.reflections=/dls/mx-scratch/rjgildea/dials_13/protk_1_1_/001/DEFAULT/SAD/SWEEP1/refine/11_refined.mpack' 'output.experiments=13_integrated_experiments.json' 'output.reflections=13_integrated.mpack' 'output.report=13_integration_report.json' 'output.include_bad_reference=True' 'debug.reference.output=True' 'profile.fitting=True' 'outlier.algorithm=null' 'background.algorithm=glm' 'prediction.d_max=45.571596' 'prediction.d_min=0.788858'
```

**Comment by ndevenish** [comment]
\o/ for swallowed stacktraces.

I thought we had a monkeypatch in dials that fixed this?

**Comment by Anthchirp** [comment]
Yes we do pass on stack traces through easy_mp. But a subprocess -9 exit doesn't leave a stack trace to be passed through.
