### ISSUE TITLE
dials.import on grid scan setting grid scan parameters fails

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#773]
```
Grey-Area run :( $ dials.import ../xrc_37_master.h5 as_grid_scan=1 grid_size=19,5
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.288-gbdbe68fc1
The following parameters have been modified:

input {
  as_grid_scan = True
  grid_size = 19 5
  experiments = <image files>
}

Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 909, in <module>
    halraiser(e)
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 907, in <module>
    script.run()
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 781, in run
    experiments = metadata_updater(imageset_importer())
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 506, in __call__
    imageset_list = self.convert_to_grid_scan(imageset_list, self.params)
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 701, in convert_to_grid_scan
    ImageGrid.from_imageset(imageset.as_imageset(), params.input.grid_size)
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dxtbx Internal Error: /Users/graeme/svn/cctbx/modules/dxtbx/imageset.h(1195): DXTBX_ASSERT(grid_size[0] * grid_size[1] == size()) failure.
```

the grid is of size 95 = 19 x 5 - this is correct - however now the grid scan is interpreted as a list of 95 1 image things so it all fails horribly

expect this closely related to the datablock to experiment switch over

**Comment by graeme-winter** [comment]
Probably worth holding fire on any fixes for this - possible we could resolve this another way...
