### ISSUE TITLE
dxtbx/dials.import errors with compressed images

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#79]
```
$ bzip2 insulin_1_001.img 
$ dials.import insulin_1_001.img.bz2 
Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/import.py", line 505, in <module>
    halraiser(e)
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/import.py", line 503, in <module>
    script.run()
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/import.py", line 247, in run
    params, options = self.parser.parse_args(show_diff_phil=False)
  File "/Users/rjgildea/software/cctbx/modules/dials/util/options.py", line 699, in parse_args
    return_unhandled=return_unhandled)
  File "/Users/rjgildea/software/cctbx/modules/dials/util/options.py", line 375, in parse_args
    scan_tolerance=scan_tolerance)
  File "/Users/rjgildea/software/cctbx/modules/dials/util/options.py", line 100, in __init__
    scan_tolerance)
  File "/Users/rjgildea/software/cctbx/modules/dials/util/options.py", line 142, in try_read_datablocks_from_images
    scan_tolerance=scan_tolerance)
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/datablock.py", line 814, in from_filenames
    scan_tolerance=None)
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/datablock.py", line 451, in __init__
    scan_tolerance)
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/datablock.py", line 494, in _extract_file_metadata
    fmt = format_class(filename)
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/format/FormatSMVADSCSN.py", line 30, in __init__
    FormatSMVADSC.__init__(self, image_file)
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/format/FormatSMVADSC.py", line 53, in __init__
    FormatSMV.__init__(self, image_file)
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/format/FormatSMV.py", line 70, in __init__
    Format.__init__(self, image_file)
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/format/Format.py", line 115, in __init__
    self.setup()
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/format/Format.py", line 126, in setup
    self._start()
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/format/FormatSMVADSCSN.py", line 38, in _start
    self.detectorbase.readHeader()
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/iotbx/detectors/adsc.py", line 19, in readHeader
    assert stream.read(len(MAGIC_NUMBER)) == MAGIC_NUMBER
AssertionError: Please report this error to dials-support@lists.sourceforge.net:
```

The self.understand() method uses the Format.open_file() method, which handles bz2 and gzip compressed files, however the self._start() method calls self.detectorbase.readHeader() - iotbx.detectors.adsc.ADSCImage.readHeader() - which doesn't handle compressed files, leading to the above error.

**Comment by Anthchirp** [comment]
Would it make sense to rewrite iotbx to pass file handles instead of file names? This way iotbx could work with compressed files and also make use of the existing dxtbx caching logic.

**Comment by rjgildea** [comment]
An even nastier one:

```
$ cp $(libtbx.find_in_repositories dials_regression)/image_examples/RAXIS-HTC/test1_lysozyme_0111060001.osc .
$ gzip test1_lysozyme_0111060001.osc -9
$ dials.import test1_lysozyme_0111060001.osc.gz 
show_stack(1): /Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/iotbx/detectors/raxisbase.py(88) readHeader
show_stack(2): /Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/iotbx/detectors/raxis.py(14) readHeader
show_stack(3): /Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/format/FormatRAXIS.py(114) _start
show_stack(4): /Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/format/Format.py(126) setup
show_stack(5): /Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/format/Format.py(115) __init__
show_stack(6): /Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/format/FormatRAXIS.py(98) __init__
show_stack(7): /Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/datablock.py(494) _extract_file_metadata
show_stack(8): /Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/datablock.py(451) __init__
show_stack(9): /Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/datablock.py(814) from_filenames
show_stack(10): /Users/rjgildea/software/cctbx/modules/dials/util/options.py(142) try_read_datablocks_from_images
show_stack(11): /Users/rjgildea/software/cctbx/modules/dials/util/options.py(100) __init__
show_stack(12): /Users/rjgildea/software/cctbx/modules/dials/util/options.py(375) parse_args
show_stack(13): /Users/rjgildea/software/cctbx/modules/dials/util/options.py(699) parse_args
show_stack(14): /Users/rjgildea/software/cctbx/build/../modules/dials/command_line/import.py(247) run
show_stack(15): /Users/rjgildea/software/cctbx/build/../modules/dials/command_line/import.py(503) <module>
libc backtrace (82 frames, most recent call last):
  83  ???                                 0x0000000000000004 0x0 + 4
  82  Python                              0x0000000100000d71 Python + 3441
  81  Python                              0x0000000100000e58 Python + 3672
  80  Python                              0x00000001000edd84 Py_Main + 3076
  79  Python                              0x00000001000d64e7 PyRun_SimpleFileExFlags + 711
  78  Python                              0x00000001000d69c4 PyRun_FileExFlags + 164
  77  Python                              0x00000001000ad5d6 PyEval_EvalCode + 54
  76  Python                              0x00000001000adc62 PyEval_EvalCodeEx + 1666
  75  Python                              0x00000001000b17df PyEval_EvalFrameEx + 14111
  74  Python                              0x00000001000b5596 fast_function + 118
  73  Python                              0x00000001000adc62 PyEval_EvalCodeEx + 1666
  72  Python                              0x00000001000b17df PyEval_EvalFrameEx + 14111
  71  Python                              0x00000001000b5596 fast_function + 118
  70  Python                              0x00000001000adc62 PyEval_EvalCodeEx + 1666
  69  Python                              0x00000001000b17df PyEval_EvalFrameEx + 14111
  68  Python                              0x00000001000b5596 fast_function + 118
  67  Python                              0x00000001000adc62 PyEval_EvalCodeEx + 1666
  66  Python                              0x00000001000b299b PyEval_EvalFrameEx + 18651
  65  Python                              0x0000000100010d43 PyObject_Call + 99
  64  Python                              0x0000000100069e63 type_call + 339
  63  Python                              0x000000010006fd0d slot_tp_init + 141
  62  Python                              0x0000000100010d43 PyObject_Call + 99
  61  Python                              0x000000010001e247 instancemethod_call + 247
  60  Python                              0x0000000100010d43 PyObject_Call + 99
  59  Python                              0x0000000100036aac function_call + 364
  58  Python                              0x00000001000adc62 PyEval_EvalCodeEx + 1666
  57  Python                              0x00000001000b17df PyEval_EvalFrameEx + 14111
  56  Python                              0x00000001000b5596 fast_function + 118
  55  Python                              0x00000001000adc62 PyEval_EvalCodeEx + 1666
  54  Python                              0x00000001000b17df PyEval_EvalFrameEx + 14111
  53  Python                              0x00000001000b5596 fast_function + 118
  52  Python                              0x00000001000adc62 PyEval_EvalCodeEx + 1666
  51  Python                              0x00000001000b299b PyEval_EvalFrameEx + 18651
  50  Python                              0x0000000100010d43 PyObject_Call + 99
  49  Python                              0x0000000100069e63 type_call + 339
  48  Python                              0x000000010006fd0d slot_tp_init + 141
  47  Python                              0x0000000100010d43 PyObject_Call + 99
  46  Python                              0x000000010001e247 instancemethod_call + 247
  45  Python                              0x0000000100010d43 PyObject_Call + 99
  44  Python                              0x0000000100036aac function_call + 364
  43  Python                              0x00000001000adc62 PyEval_EvalCodeEx + 1666
  42  Python                              0x00000001000b17df PyEval_EvalFrameEx + 14111
  41  Python                              0x00000001000b5596 fast_function + 118
  40  Python                              0x00000001000adc62 PyEval_EvalCodeEx + 1666
  39  Python                              0x00000001000b299b PyEval_EvalFrameEx + 18651
  38  Python                              0x0000000100010d43 PyObject_Call + 99
  37  Python                              0x0000000100069e63 type_call + 339
  36  Python                              0x000000010006fd0d slot_tp_init + 141
  35  Python                              0x0000000100010d43 PyObject_Call + 99
  34  Python                              0x000000010001e247 instancemethod_call + 247
  33  Python                              0x0000000100010d43 PyObject_Call + 99
  32  Python                              0x0000000100036aac function_call + 364
  31  Python                              0x00000001000adc62 PyEval_EvalCodeEx + 1666
  30  Python                              0x00000001000b299b PyEval_EvalFrameEx + 18651
  29  Python                              0x0000000100010d43 PyObject_Call + 99
  28  Python                              0x000000010001e247 instancemethod_call + 247
  27  Python                              0x0000000100010d43 PyObject_Call + 99
  26  Python                              0x0000000100036aac function_call + 364
  25  Python                              0x00000001000adc62 PyEval_EvalCodeEx + 1666
  24  Python                              0x00000001000b17df PyEval_EvalFrameEx + 14111
  23  Python                              0x00000001000b5596 fast_function + 118
  22  Python                              0x00000001000adc62 PyEval_EvalCodeEx + 1666
  21  Python                              0x00000001000b17df PyEval_EvalFrameEx + 14111
  20  Python                              0x00000001000b5596 fast_function + 118
  19  Python                              0x00000001000adc62 PyEval_EvalCodeEx + 1666
  18  Python                              0x00000001000b17df PyEval_EvalFrameEx + 14111
  17  Python                              0x00000001000b5596 fast_function + 118
  16  Python                              0x00000001000adc62 PyEval_EvalCodeEx + 1666
  15  Python                              0x00000001000b299b PyEval_EvalFrameEx + 18651
  14  Python                              0x0000000100010d43 PyObject_Call + 99
  13  Python                              0x000000010001e247 instancemethod_call + 247
  12  Python                              0x0000000100010d43 PyObject_Call + 99
  11  Python                              0x0000000100036aac function_call + 364
  10  Python                              0x00000001000adc62 PyEval_EvalCodeEx + 1666
  9   Python                              0x00000001000b2da1 PyEval_EvalFrameEx + 19681
  8   _struct.so                          0x00000001002f5606 unpack + 86
  7   _struct.so                          0x00000001002f4f2c s_unpack + 60
  6   _struct.so                          0x00000001002f5173 s_unpack_internal + 163
  5   _struct.so                          0x00000001002f358f bu_float + 15
  4   _struct.so                          0x00000001002f5ea4 cache_struct + 1972
  3   libsystem_platform.dylib            0x00007fff8fd5beaa _sigtramp + 26
  2   boost_python_meta_ext.so            0x00000001007be830 initboost_python_meta_ext + 0
Floating-point error (Python and libc call stacks above)
                This crash may be due to a problem in any imported
                Python module, including modules which are not part
                of the cctbx project. To disable the traps leading
                to this message, define these environment variables
                (e.g. assign the value 1):
                    BOOST_ADAPTBX_FPE_DEFAULT
                    BOOST_ADAPTBX_SIGNALS_DEFAULT
                This will NOT solve the problem, just mask it, but
                may allow you to proceed in case it is not critical.
```

Strangely, dials.import apparently works on the default (-6) compression level, but then dials.find_spots fails:

```
$ gzip test1_lysozyme_0111060001.osc 
$ dials.import test1_lysozyme_0111060001.osc.gz 
DIALS 1.0-211-g3c29133
The following parameters have been modified:

input {
  datablock = <image files>
}

--------------------------------------------------------------------------------
DataBlock 0
  format: <class 'dxtbx.format.FormatRAXIS.FormatRAXIS'>
  num images: 1
  num sweeps: 1
  num stills: 0
--------------------------------------------------------------------------------
Writing datablocks to datablock.json
$ dials.find_spots datablock.json 
DIALS 1.0-211-g3c29133
The following parameters have been modified:

input {
  datablock = datablock.json
}

Setting spotfinder.filter.min_spot_size=6
Configuring spot finder from input parameters
--------------------------------------------------------------------------------
Finding strong spots in imageset 0
--------------------------------------------------------------------------------

Finding spots in image 111060001 to 111060001...
Extracting strong pixels from images
 Using multiprocessing with 1 parallel job(s)

Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/find_spots.py", line 196, in <module>
    halraiser(e)
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/find_spots.py", line 194, in <module>
    script.run()
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/find_spots.py", line 143, in run
    datablocks[0], params)
  File "/Users/rjgildea/software/cctbx/modules/dials/array_family/flex.py", line 174, in from_observations
    return find_spots(datablock)
  File "/Users/rjgildea/software/cctbx/modules/dials/algorithms/peak_finding/spot_finder.py", line 389, in __call__
    table, hot_mask = self._find_in_imageset(imageset)
  File "/Users/rjgildea/software/cctbx/modules/dials/algorithms/peak_finding/spot_finder.py", line 451, in _find_in_imageset
    spots_all.extend(self.find_spots(imageset[j0:j1]))
  File "/Users/rjgildea/software/cctbx/modules/dials/algorithms/peak_finding/spot_finder.py", line 323, in __call__
    result = function(task)
  File "/Users/rjgildea/software/cctbx/modules/dials/algorithms/peak_finding/spot_finder.py", line 90, in __call__
    image = self.imageset.get_corrected_data(index)
  File "/Users/rjgildea/Dropbox/cctbx/sources/cctbx_project/dxtbx/imageset.py", line 527, in get_corrected_data
    r = d.as_double()
AttributeError: Please report this error to dials-support@lists.sourceforge.net: 'NoneType' object has no attribute 'as_double'
```

**Comment by rjgildea** [comment]
```
Revision: 23841
          http://sourceforge.net/p/cctbx/code/23841
Author:   rjgildea
Date:     2016-02-19 10:07:28 +0000 (Fri, 19 Feb 2016)
Log Message:
-----------
code to test reading gz or bz2 compressed files in dxtbx: it doesn't work, not currently exercised

Modified Paths:
--------------
    trunk/dxtbx/tests/tst_dxtbx.py

Modified: trunk/dxtbx/tests/tst_dxtbx.py
===================================================================
--- trunk/dxtbx/tests/tst_dxtbx.py      2016-02-19 10:07:24 UTC (rev 23840)
+++ trunk/dxtbx/tests/tst_dxtbx.py      2016-02-19 10:07:28 UTC (rev 23841)
@@ -33,6 +33,60 @@

   print 'OK'

+
+def tst_dxtbx_compressed():
+  import libtbx.load_env
+  try:
+    dials_regression = libtbx.env.dist_path('dials_regression')
+  except KeyError, e:
+    print 'FAIL: dials_regression not configured'
+    return
+
+  import os
+  from dxtbx.format.Registry import Registry
+
+  from dials_regression.image_examples.get_all_working_images import \
+      get_all_working_images
+
+  # test that reading gz or bz2 compressed files works: it doesn't!
+
+  from libtbx import smart_open
+  from libtbx.test_utils import open_tmp_directory
+  import shutil
+
+  tmp_dir = open_tmp_directory()
+  print tmp_dir
+
+  for directory, image in get_all_working_images():
+    file_path = os.path.join(dials_regression, 'image_examples',
+                             directory, image)
+    for ext in ('.gz', '.bz2')[:]:
+      compressed_path = os.path.join(tmp_dir, os.path.basename(file_path)) + ext
+      with open(file_path, 'rb') as f_in, smart_open.for_writing(compressed_path) as f_out:
+        shutil.copyfileobj(f_in, f_out)
+      print file_path, compressed_path
+      format = Registry.find(compressed_path)
+      try:
+        i = format(compressed_path)
+      except Exception, e:
+        print 'Error reading compressed file: %s' %compressed_path
+        import traceback
+        traceback.print_exc()
+      else:
+        print 'Successfully read compressed file: %s' %compressed_path
+        det = i.get_detector()
+        if det is not None:
+          size = det[0].get_image_size()
+        b = i.get_beam()
+        g = i.get_goniometer()
+        s = i.get_scan()
+        try:
+          d = i.get_raw_data()
+        except IOError:
+          pass
+
+  print 'OK'
+
 def tst_dxtbx_models():

   from dxtbx.tests.test_beam import test_beam
@@ -71,3 +125,4 @@
 if __name__ == '__main__':
   tst_dxtbx()
   tst_dxtbx_models()  # these tests are failing in the misc_build.  Disable them until they can be debugged.
+  #tst_dxtbx_compressed()
```

**Comment by Anthchirp** [comment]
dxtbx file cache should now be able to cope with compressed files
https://sourceforge.net/p/cctbx/code/23876/
https://sourceforge.net/p/cctbx/code/23875/

**Comment by graeme-winter** [comment]
Is this still an open bug or has the problem largely gone away?

**Comment by Anthchirp** [comment]
Specific case works now. 
DIALS 1.dev.355-ged46252
