### ISSUE TITLE
dials.compute_delta_cchalf broken with mtz input

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#852]
I spy an opportunity for improved test coverage:
```
$ dials.compute_delta_cchalf mtzfile=scaled_unmerged.mtz 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/compute_delta_cchalf.py", line 568, in <module>
    run()
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/compute_delta_cchalf.py", line 561, in run
    script.run()
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/compute_delta_cchalf.py", line 162, in run
    data = self.prepare_data()
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/compute_delta_cchalf.py", line 154, in prepare_data
    data = self.read_mtzfile(self.params.input.mtzfile)
  File "/Users/rjgildea/software/cctbx/build/../modules/dials/command_line/compute_delta_cchalf.py", line 331, in read_mtzfile
    variance=variance,
TypeError: Please report this error to dials-support@lists.sourceforge.net: __new__() takes exactly 9 arguments (7 given)
```

**Comment by dagewa** [comment]
Are experimental identifiers really needed for `PerImageCChalfStatistics`? It seems they are used to construct a selection based on equality to `reflection_table['id']`, but as I understand it we still don't really know what to put inside the experimental identifiers (#507), so there could be circumstances where that would not work. Relying on high-level metadata like experimental identifiers limits the generality of the method, making cases like MTZ input more difficult to implement. Perhaps all that is needed is an ordered set of the elements of `reflection_table['id']` to make the selection, ignoring experimental identifiers, which might not exist.
