### ISSUE TITLE
Cosym crash on many stills

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#877]
Running on a whole load of still data crashes with following (doesn't take long to crash):
```
$ dials.cosym $(cat /dls/science/users/mep23677/cosym_ticket877_fail.list) space_group=P3221 nproc=20
...
...
Resolution estimate from <I>/<sigI> > 4.0 : 5.65
Resolution estimate from CC1/2 > 0.60: 1.64
High resolution limit set to: 1.64
Selecting 238635 reflections with d > 1.64
Using 2 dimensions for analysis
Traceback (most recent call last):
  File "/dls/science/users/mep23677/dist/build/../modules/dials/command_line/cosym.py", line 357, in <module>
    run(sys.argv[1:])
  File "/dls/science/users/mep23677/dist/build/../modules/dials/command_line/cosym.py", line 351, in run
    cosym_instance.run()
  File "/dls/science/users/mep23677/dist/modules/dials/util/observer.py", line 45, in notify
    r = method(self, *args, **kwargs)
  File "/dls/science/users/mep23677/dist/build/../modules/dials/command_line/cosym.py", line 125, in run
    self.cosym_analysis.run()
  File "/dls/science/users/mep23677/dist/modules/dials/algorithms/symmetry/cosym/__init__.py", line 268, in run
    self._optimise()
  File "/dls/science/users/mep23677/dist/modules/dials/util/observer.py", line 45, in notify
    r = method(self, *args, **kwargs)
  File "/dls/science/users/mep23677/dist/modules/dials/algorithms/symmetry/cosym/__init__.py", line 299, in _optimise
    termination_params=termination_params,
  File "/dls/science/users/mep23677/dist/modules/dials/algorithms/symmetry/cosym/engine.py", line 43, in __init__
    target_evaluator=self, termination_params=termination_params
  File "/dls/science/users/mep23677/dist/modules/cctbx_project/scitbx/lbfgs/__init__.py", line 278, in run
    line_search)
  File "/dls/science/users/mep23677/dist/modules/cctbx_project/scitbx/lbfgs/__init__.py", line 134, in run_c_plus_plus
    f, g, d = target_evaluator.compute_functional_gradients_diag()
  File "/dls/science/users/mep23677/dist/modules/dials/algorithms/symmetry/cosym/engine.py", line 54, in compute_functional_gradients_diag
    f, g, curvs = self.compute_functional_gradients_and_curvatures()
  File "/dls/science/users/mep23677/dist/modules/dials/algorithms/symmetry/cosym/engine.py", line 72, in compute_functional_gradients_and_curvatures
    self.f, self.g = self.target.compute_functional_and_gradients(self.x)
  File "/dls/science/users/mep23677/dist/modules/dials/algorithms/symmetry/cosym/target.py", line 376, in compute_functional_and_gradients
    f = self.compute_functional(x)
  File "/dls/science/users/mep23677/dist/modules/dials/algorithms/symmetry/cosym/target.py", line 322, in compute_functional
    assert (x.size() // self.dim) == (self._lattices.size() * len(self._sym_ops))
AssertionError: Please report this error to dials-support@lists.sourceforge.net:
```

**Comment by rjgildea** [comment]
I can get it to fail more quickly with:
`$ dials.cosym $(head -n 1000 /dls/science/users/mep23677/cosym_ticket877_fail.list | tail -n 250) space_group=P3221 nproc=20`

I suspect it is in some way related to having multiple lattices in the input.

**Comment by rjgildea** [comment]
The problem is that there are some datasets with barely any reflections. In particular, the 134th experiment (using the above subset) has only 2 reflections, both of which are removed because they have epsilon > 1 in the Patterson group.
https://github.com/dials/dials/blob/382d4d274ca64135525ccf9e9c7067e0c4c3a377/algorithms/symmetry/__init__.py#L113-L115
This results in a mismatch between the number of miller arrays in self.input_intensities and the number of unique values in self.dataset_ids, which results in the error seen above.
```
$ grep "Selected [0-9] " dials.cosym.log
Selected 4 summation integrated reflections
Selected 7 summation integrated reflections
Selected 9 summation integrated reflections
Selected 2 summation integrated reflections
Selected 9 summation integrated reflections
Selected 4 summation integrated reflections
Selected 6 summation integrated reflections
Selected 8 summation integrated reflections
Selected 9 summation integrated reflections
Selected 3 summation integrated reflections
```
