### ISSUE TITLE
Refine Bravais settings broken by recent commit

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#892]
```
Grey-Area run :( $ dials.refine_bravais_settings indexed.* nproc=1
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.708-ga2f9aec4f
The following parameters have been modified:

nproc = 1
input {
  experiments = indexed.expt
  reflections = indexed.refl
}

Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/refine_bravais_settings.py", line 254, in <module>
    run()
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/refine_bravais_settings.py", line 227, in run
    nproc=params.nproc,
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/indexing/symmetry.py", line 189, in refined_settings_factory_from_refined_triclinic
    preserve_exception_message=True,
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/libtbx/easy_mp.py", line 628, in parallel_map
    result = res()
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/libtbx/scheduling/result.py", line 119, in __call__
    self.traceback( exception = self.exception() )
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 117, in __call__
    self.raise_handler( exception = exception )
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/libtbx/scheduling/stacktrace.py", line 134, in raise_with_traceback
    raise_(type(exception), exception, self.traceback)
  File "/Users/graeme/svn/cctbx/modules/cctbx_project/libtbx/scheduling/mainthread.py", line 100, in poll
    value = target( *args, **kwargs )
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/indexing/symmetry.py", line 218, in refine_subgroup
    assert len(args) == 5
AssertionError
```

**Comment by graeme-winter** [comment]
Much thanks @rjgildea - however how did this one slip through? Guessing non-CI-working at the moment root issue...
