### ISSUE TITLE
dials.reciprocal_lattice_viewer fails with data from split_experiments

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#905]
```
cd /dls/mx-scratch/xia2/issue-323/example01/NFF
mkdir work
cd work
mkdir 1 2 
cd 1
dials.import ../../NFF_01_00*cbf
dials.find_spots imported.expt nproc=20
cd ../2
dials.import ../../NFF_02_00*cbf
dials.find_spots imported.expt nproc=20
cd ../
dials.index 1/strong.refl 1/imported.expt 2/strong.refl 2/imported.expt 
dials.split_experiments indexed.*
```

gives `split_(0,1).(expt,refl)` - 

 - the _0 ones will load and show only indexed reflections
 - the _1 ones fail to load with this error:

```
Grey-Area work :( $ dials.reciprocal_lattice_viewer split_1.*
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = split_1.expt
  reflections = split_1.refl
}

RuntimeError: min() argument is an empty array
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 79, in <module>
    run(sys.argv[1:])
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/reciprocal_lattice_viewer.py", line 71, in run
    f.load_models(experiments, reflections)
  File "/Users/graeme/svn/cctbx/modules/dials/util/reciprocal_lattice/viewer.py", line 85, in load_models
    Render3d.load_models(self, experiments, reflections)
  File "/Users/graeme/svn/cctbx/modules/dials/util/reciprocal_lattice/__init__.py", line 91, in load_models
    self.set_points()
  File "/Users/graeme/svn/cctbx/modules/dials/util/reciprocal_lattice/viewer.py", line 147, in set_points
    Render3d.set_points(self)
  File "/Users/graeme/svn/cctbx/modules/dials/util/reciprocal_lattice/__init__.py", line 178, in set_points
    self.settings.d_min = flex.min(d_spacings)
RuntimeError: min() argument is an empty array
```

on master

**Comment by graeme-winter** [comment]
FWIW the `split_1.*` file pair refine just fine but reciprocal lattice viewer on the `refined.*` output also explodes...

**Comment by graeme-winter** [comment]
Reverted fix in commit above as the treatment of integrated data now excludes unindexed reflections by default, as they do not have a matching image set. 

Need to revisit this but I think that falls under the purview of #907
