### ISSUE TITLE
detector.get_panel_intersection sometimes fails for I23 detector

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#95]
The comment for this function implies that it should return -1 if the beam intersects with no panel, however the following traceback suggests otherwise:

```
Traceback (most recent call last):
  File "/home/hko55533/software/cctbx/build/../modules/dials/command_line/show.py", line 288, in <module>
    run(sys.argv[1:])
  File "/home/hko55533/software/cctbx/build/../modules/dials/command_line/show.py", line 89, in run
    panel_id = expt.detector.get_panel_intersection(expt.beam.get_s0())
RuntimeError: dxtbx Internal Error: /home/hko55533/software/cctbx/modules/cctbx_project/dxtbx/model/virtual_panel.h(242): DXTBX_ASSERT(v[2] > 0) failure.
```

**Comment by jmp1985** [comment]
This function fails all the time unless the vector intersects with the first panel. Now fixed
