### ISSUE TITLE
Bare commands that return non-zero exit code

### ISSUE THREAD

**Issue by dagewa** [dials/dials#961]
Most `dials.` commands print useful help when run without any arguments. However, some raise errors and write to stderr. This dumb script prints the names and stderr output for commands that don't exit cleanly with a user-friendly message:
```bash
for prog in $(compgen -c dials. | sort)
do
  if [ $prog == "dials.python" ]; then
    continue
  fi
  output=$($prog 2>&1)
  if [ $? -ne 0 ]; then
    echo $prog
    echo $output
    echo
  fi
done
```
results:
```
dials.augment_spots
Sorry: Exactly one reflection file needed

dials.background
Usage: dials.background [options] image_*.cbf Options: -h, --help show this help message and exit -c, --show-config Show the configuration parameters. -a ATTRIBUTES_LEVEL, --attributes-level=ATTRIBUTES_LEVEL Set the attributes level for showing configuration parameters -e EXPERT_LEVEL, --expert-level=EXPERT_LEVEL Set the expert level for showing configuration parameters -v Increase verbosity --phil=FILE PHIL files to read. Pass '-' for STDIN. Can be specified multiple times, but duplicates ignored. Examples: dials.background image_*.cbf Please pass an experiment list

dials.compute_delta_cchalf
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235 Traceback (most recent call last): File "/home/david/sw/cctbx/build/../modules/dials/command_line/compute_delta_cchalf.py", line 562, in <module> run() File "/home/david/sw/cctbx/build/../modules/dials/command_line/compute_delta_cchalf.py", line 555, in run script.run() File "/home/david/sw/cctbx/build/../modules/dials/command_line/compute_delta_cchalf.py", line 149, in run data.miller_index, AttributeError: Please report this error to dials-support@lists.sourceforge.net: type object 'exceptions.SystemExit' has no attribute 'miller_index'

dials.filter_reflections
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235 Usage: dials.filter_reflections [options] experiment.expt Options: -h, --help show this help message and exit -c, --show-config Show the configuration parameters. -a ATTRIBUTES_LEVEL, --attributes-level=ATTRIBUTES_LEVEL Set the attributes level for showing configuration parameters -e EXPERT_LEVEL, --expert-level=EXPERT_LEVEL Set the expert level for showing configuration parameters -v Increase verbosity --phil=FILE PHIL files to read. Pass '-' for STDIN. Can be specified multiple times, but duplicates ignored. This program takes reflection files as input and filters them based on user- specified criteria, to write out a subset of the original file. Filtering is first done by evaluating the optional boolean 'flag_expression' using reflection flag values. The operators allowed are '&' for 'and', '|' for 'or', and '~' for 'not'. Expressions may contain nested sub-expressions using parentheses. Following this, optional additional filters are applied according to values in the reflection table, such as by resolution or user-defined masks. If a reflection file is passed in to the program but no filtering parameters are set, a table will be printed, giving the flag values present in the reflection file. Examples: dials.filter_reflections refined.refl flag_expression=used_in_refinement dials.filter_reflections integrated.refl flag_expression="integrated & ~reference_spot" dials.filter_reflections integrated.refl flag_expression="indexed & (failed_during_summation | failed_during_profile_fitting)" dials.filter_reflections indexed.refl indexed.expt d_max=20 d_min=2.5 Sorry: No valid reflection file given

dials.generate_mask
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235 Usage: dials.generate_mask [options] models.expt Options: -h, --help show this help message and exit -c, --show-config Show the configuration parameters. -a ATTRIBUTES_LEVEL, --attributes-level=ATTRIBUTES_LEVEL Set the attributes level for showing configuration parameters -e EXPERT_LEVEL, --expert-level=EXPERT_LEVEL Set the expert level for showing configuration parameters -v Increase verbosity --phil=FILE PHIL files to read. Pass '-' for STDIN. Can be specified multiple times, but duplicates ignored. Mask images to remove unwanted pixels. This program is used to generate mask to specify which pixels should be considered "invalid" during spot finding and integration. It provides a few options to create simple masks using the detector trusted range, or from simple shapes or by setting different resolution ranges. Examples: dials.generate_mask models.expt border=5 dials.generate_mask models.expt \ untrusted.rectangle=50,100,50,100 \ untrusted.circle=200,200,100 dials.generate_mask models.expt resolution.d_max=2.00

dials.goniometer_calibration
Either space_group must be specified or set the parameter use_space_group_from_experiments=True

dials.import_stream
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235 DIALS 2.dev.956-g40f6b98 Traceback (most recent call last): File "/home/david/sw/cctbx/build/../modules/dials/command_line/import_stream.py", line 174, in <module> script.run() File "/home/david/sw/cctbx/build/../modules/dials/command_line/import_stream.py", line 118, in run stream = ZMQStream(params.input.host, params.input.port) File "/home/david/sw/cctbx/modules/dials/util/stream.py", line 21, in __init__ self.connect() File "/home/david/sw/cctbx/modules/dials/util/stream.py", line 29, in connect import zmq ImportError: Please report this error to dials-support@lists.sourceforge.net: No module named zmq

dials.plot_scan_varying_model
Usage: dials.plot_scan_varying_model [options] refined.expt Options: -h, --help show this help message and exit -c, --show-config Show the configuration parameters. -a ATTRIBUTES_LEVEL, --attributes-level=ATTRIBUTES_LEVEL Set the attributes level for showing configuration parameters -e EXPERT_LEVEL, --expert-level=EXPERT_LEVEL Set the expert level for showing configuration parameters -v Increase verbosity --phil=FILE PHIL files to read. Pass '-' for STDIN. Can be specified multiple times, but duplicates ignored. Generate plots of scan-varying models, including crystal orientation, unit cell and beam centre, from the input refined.expt Examples: dials.plot_scan_varying_model refined.expt Sorry: No experiments found in the input

dials.potato
Traceback (most recent call last): File "/home/david/sw/cctbx/build/../modules/dials_scratch/command_line/potato.py", line 21, in <module> from dials_scratch.jmp.potato.potato import Integrator File "/home/david/sw/cctbx/modules/dials_scratch/jmp/potato/potato.py", line 20, in <module> from dials.algorithms.refinement.refinement_helpers import corrgram ImportError: cannot import name corrgram

dials.refine
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235 No Experiments found in the input

dials.stills_process_mpi
Traceback (most recent call last): File "/home/david/sw/cctbx/build/../modules/dials/command_line/stills_process_mpi.py", line 163, in <module> from mpi4py import MPI ImportError: No module named mpi4py

dials.sweep_to_stills
No Experiments found in the input usage: dials.sweep_to_stills [options] [param.phil] models.expt reflections.refl

```

**Comment by dagewa** [comment]
I suggest that these be modified to be more user-friendly when run without arguments (where appropriate)

- [ ] dials.augment_spots
- [ ] dials.background
- [ ] dials.compute_delta_cchalf
- [ ] dials.filter_reflections
- [ ] dials.generate_mask
- [ ] dials.goniometer_calibration
- [ ] dials.import_stream
- [ ] dials.plot_scan_varying_model
- [ ] dials.potato
- [ ] dials.refine
- [ ] dials.stills_process_mpi
- [ ] dials.sweep_to_stills
