### ISSUE TITLE
dials.import template=nonsense

### ISSUE THREAD

**Issue by dagewa** [dials/dials#97]
This crashes with an error. It would be better to fail gracefully

DIALS 1.0-0-g66ac5d4
The following parameters have been modified:

input {
  template = "nonsense"
}

Traceback (most recent call last):
  File "C:\CCP4-7\python2.7\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\CCP4-7\python2.7\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dials\command_line\import.py", line
482, in <module>
    halraiser(e)
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dials\command_line\import.py", line
480, in <module>
    script.run()
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dials\command_line\import.py", line
284, in run
    options.verbose)
  File "C:\CCP4-7\7.0\lib\py2\site-packages\cctbx_project\dxtbx\datablock.py", l
ine 352, in __init__
    fmt = find_format(paths[0])
IndexError: Please report this error to dials-support@lists.sourceforge.net: lis
t index out of range

**Comment by jmp1985** [comment]
Fixed in 24346.
