### ISSUE TITLE
HDF5 representation of reflection data does not read

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#982]
Based on user report, verified with:

```
Silver-Surfer index :) $ dials.python
Python 2.7.15 (default, Oct 10 2018, 09:01:12) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from dials.array_family import flex
>>> data = flex.reflection_table.from_file("5_indexed.refl")
>>> data.as_h5("5_indexed.h5")
>>> reloaded = flex.reflection_table.from_h5("5_indexed.h5")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/graeme/svn/cctbx/modules/dials/array_family/flex.py", line 250, in from_h5
    self = handle.get_reflections()
  File "/Users/graeme/svn/cctbx/modules/dials/util/nexus_old.py", line 145, in get_reflections
    return self.get_data(ReflectionListDecoder())
  File "/Users/graeme/svn/cctbx/modules/dials/util/nexus_old.py", line 137, in get_data
    return decoder.decode(self._handle)
  File "/Users/graeme/svn/cctbx/modules/dials/util/nexus_old.py", line 81, in decode
    col[i].data = flex.double(data["%d" % i].value)
Boost.Python.ArgumentError: Python argument types in
    None.None(Shoebox, double)
did not match C++ signature:
    None(dials::model::Shoebox<float> {lvalue}, scitbx::af::versa<float, scitbx::af::flex_grid<scitbx::af::small<long, 10ul> > > {lvalue})
```

**Comment by graeme-winter** [comment]
Task 0: decide if HDF5 format reflection data is a thing we want, given the move to messagepack which is in progress.

**Comment by dagewa** [comment]
I can see how HDF5 would make exploratory data analysis in third party packages like R a little easier. Not that msgpack is a huge barrier, but HDF5 has more universal support.

**Comment by phyy-nx** [comment]
Is this different from NXreflections?

http://download.nexusformat.org/sphinx/classes/base_classes/NXreflections.html

Also, it's been my thought that massive parallel merging of xfel datasets
could greatly benefit from data serialized as hdf5.  Seems it would be more
amenable to parallel reads.

**Comment by dagewa** [comment]
I think it _should_ be NXreflections, and I think it is worth keeping, not least because much of NXreflections appears to be based on DIALS definitions!
