### ISSUE TITLE
Scan-varying refinement with a fixed cell does not work

### ISSUE THREAD

**Issue by dagewa** [dials/dials#999]
I think this used to work...? Anyway should not bomb like this.

```
dials.refine $(dials.data get -q x4wide_processed)/AUTOMATIC_DEFAULT_scaled.{expt,refl}\
  scan_varying=true crystal.fix=cell
```
\<skip to the end\>

```
RMSDs by experiment:
---------------------------------------------
| Exp | Nref  | RMSD_X  | RMSD_Y | RMSD_Z   |
| id  |       | (px)    | (px)   | (images) |
---------------------------------------------
| 0   | 79093 | 0.55327 | 0.7036 | 0.22402  |
---------------------------------------------
Traceback (most recent call last):
  File "/home/david/sw/cctbx/build/../modules/dials/command_line/refine.py", line 476, in <module>
    run()
  File "/home/david/sw/cctbx/build/../modules/dials/command_line/refine.py", line 388, in run
    experiments, reflections, params
  File "/home/david/sw/cctbx/build/../modules/dials/command_line/refine.py", line 283, in run_dials_refine
    refiner, reflections, history = run_macrocycle(params, reflections, experiments)
  File "/home/david/sw/cctbx/build/../modules/dials/command_line/refine.py", line 198, in run_macrocycle
    history = refiner.run()
  File "/home/david/sw/cctbx/modules/dials/algorithms/refinement/refiner.py", line 987, in run
    self._update_models()
  File "/home/david/sw/cctbx/modules/dials/algorithms/refinement/refiner.py", line 1078, in _update_models
    A_list = self._pred_param.get_varying_UB(obs_image_numbers, iexp)
  File "/home/david/sw/cctbx/modules/dials/algorithms/refinement/parameterisation/scan_varying_prediction_parameters.py", line 455, in get_varying_UB
    UB_list.append(U * B)
  File "/home/david/sw/cctbx/modules/cctbx_project/scitbx/matrix/__init__.py", line 85, in __mul__
    return rec([x * other for x in self.elems], self.n)
```
Failure is _after_ refinement occurs

**Comment by dagewa** [comment]
Reminder to self:

- [ ] Make it work
- [ ] Add test
